# Generated by Django 5.2 on 2026-08-09 07:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr_staff', '0011_hrexportjob_hrstaffnumbersequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrCredentialCatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('category', models.CharField(choices=[('TEACHER_QUALIFICATION', 'Teacher Qualification'), ('VOCATIONAL_QUALIFICATION', 'Vocational Qualification'), ('VOCATIONAL_SKILL_LEVEL', 'Vocational Skill Level'), ('NON_TEACHER_PROFESSIONAL_TITLE', 'Non-Teacher Professional Title'), ('PROFESSIONAL_LICENSE', 'Professional License'), ('INDUSTRY_CERTIFICATION', 'Industry Certification'), ('TRAINING_CERTIFICATE', 'Training Certificate'), ('OTHER', 'Other')], db_index=True, max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('issuer_type', models.CharField(choices=[('EDUCATION_AUTHORITY', 'Education Authority'), ('MOHRSS', 'MOHRSS'), ('ASSESSMENT_AGENCY', 'Assessment Agency'), ('TITLE_APPROVAL_AUTHORITY', 'Title Approval Authority'), ('INDUSTRY_ORG', 'Industry Organization'), ('TRAINING_INSTITUTION', 'Training Institution'), ('OTHER_ISSUER', 'Other')], default='OTHER_ISSUER', max_length=32)),
                ('issuer_catalog_ref', models.CharField(blank=True, default='', max_length=64)),
                ('level_schema', models.JSONField(blank=True, null=True)),
                ('validity_policy', models.JSONField(blank=True, null=True)),
                ('requires_document', models.BooleanField(default=False)),
                ('requires_external_verification', models.BooleanField(default=False)),
                ('applicable_professions', models.JSONField(blank=True, null=True)),
                ('skill_mappings_json', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DEPRECATED', 'Deprecated')], default='ACTIVE', max_length=16)),
                ('version', models.BigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HR Credential Catalog Item',
                'verbose_name_plural': 'HR Credential Catalog Items',
                'indexes': [models.Index(fields=['tenant_id', 'category'], name='hr_qualific_tenant__76d9f4_idx'), models.Index(fields=['code'], name='hr_qualific_code_c8e9f9_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'code'), name='uniq_catalog_tenant_code')],
            },
        ),
        migrations.CreateModel(
            name='HrPersonCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('external_engagement_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('credential_name_snapshot', models.CharField(max_length=200)),
                ('level_code', models.CharField(blank=True, default='', max_length=64)),
                ('certificate_no_cipher', models.BinaryField(blank=True, null=True)),
                ('certificate_no_hash', models.CharField(blank=True, default='', max_length=128)),
                ('issuer_name', models.CharField(max_length=200)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_VERIFICATION', 'Under Verification'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended'), ('REVOKED', 'Revoked'), ('INVALID', 'Invalid'), ('SUPERSEDED', 'Superseded'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=24)),
                ('source', models.CharField(choices=[('SELF_REPORTED', 'Self Reported'), ('HR_ENTERED', 'HR Entered'), ('MIGRATED', 'Migrated'), ('VERIFIED_EXTERNAL', 'Verified External'), ('BUSINESS_PROCESS', 'Business Process')], default='HR_ENTERED', max_length=24)),
                ('self_reported', models.BooleanField(default=False)),
                ('current_verification_status', models.CharField(blank=True, default='', max_length=24)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.BigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_item_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_credentials', to='hr_qualification.hrcredentialcatalogitem')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qualification_credentials', to='hr_staff.hrperson')),
                ('staff_master_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qualification_credentials', to='hr_staff.hrstaffmaster')),
            ],
            options={
                'verbose_name': 'HR Person Credential',
                'verbose_name_plural': 'HR Person Credentials',
            },
        ),
        migrations.CreateModel(
            name='HrCredentialVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_type', models.CharField(choices=[('MANUAL_ORIGINAL_REVIEW', 'Manual Original Review'), ('OFFICIAL_DATABASE', 'Official Database'), ('THIRD_PARTY_PROVIDER', 'Third Party Provider'), ('ISSUER_CONFIRMATION', 'Issuer Confirmation'), ('IMPORT_TRUSTED_SOURCE', 'Import Trusted Source'), ('MIGRATION_VERIFIED', 'Migration Verified')], default='MANUAL_ORIGINAL_REVIEW', max_length=32)),
                ('provider', models.CharField(blank=True, default='', max_length=100)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=200)),
                ('result', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('VERIFIED', 'Verified'), ('NOT_FOUND', 'Not Found'), ('MISMATCH', 'Mismatch'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked'), ('NEEDS_MANUAL_REVIEW', 'Needs Manual Review'), ('PROVIDER_UNAVAILABLE', 'Provider Unavailable')], default='PENDING', max_length=32)),
                ('verified_by', models.BigIntegerField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_valid_until', models.DateTimeField(blank=True, null=True)),
                ('raw_result_document_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('version', models.BigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to='hr_qualification.hrpersoncredential')),
            ],
            options={
                'verbose_name': 'HR Credential Verification',
                'verbose_name_plural': 'HR Credential Verifications',
            },
        ),
        migrations.CreateModel(
            name='HrCredentialStatusEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, default='', max_length=24)),
                ('to_status', models.CharField(max_length=24)),
                ('reason', models.TextField(blank=True, default='')),
                ('actor_id', models.BigIntegerField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('evidence_event_id', models.UUIDField(blank=True, null=True)),
                ('credential_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_events', to='hr_qualification.hrpersoncredential')),
            ],
            options={
                'verbose_name': 'HR Credential Status Event',
                'verbose_name_plural': 'HR Credential Status Events',
                'ordering': ['occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='HrCredentialRenewal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('renewal_type', models.CharField(choices=[('SAME_LEVEL', 'Same Level'), ('UPGRADE', 'Upgrade'), ('CORRECTION', 'Correction')], default='SAME_LEVEL', max_length=24)),
                ('reason', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('new_credential_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renewals_as_new', to='hr_qualification.hrpersoncredential')),
                ('original_credential_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renewals_as_original', to='hr_qualification.hrpersoncredential')),
            ],
            options={
                'verbose_name': 'HR Credential Renewal',
                'verbose_name_plural': 'HR Credential Renewals',
            },
        ),
        migrations.CreateModel(
            name='HrCredentialDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('CERTIFICATE_SCAN', 'Certificate Scan'), ('OFFICIAL_VERIFICATION', 'Official Verification Document'), ('RENEWAL_DOCUMENT', 'Renewal Document'), ('REVOCATION_NOTICE', 'Revocation Notice'), ('OTHER_DOC', 'Other')], default='CERTIFICATE_SCAN', max_length=32)),
                ('file_id', models.CharField(max_length=200)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('checksum', models.CharField(blank=True, default='', max_length=128)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('verified', models.BooleanField(default=False)),
                ('sensitivity', models.CharField(blank=True, default='RESTRICTED_HR', max_length=32)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('credential_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='hr_qualification.hrpersoncredential')),
            ],
            options={
                'verbose_name': 'HR Credential Document',
                'verbose_name_plural': 'HR Credential Documents',
            },
        ),
        migrations.CreateModel(
            name='HrQualificationRiskCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('credential_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('recognition_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('risk_type', models.CharField(choices=[('REQUIRED_CREDENTIAL_MISSING', 'Required Credential Missing'), ('CREDENTIAL_UNVERIFIED', 'Credential Unverified'), ('CREDENTIAL_EXPIRING', 'Credential Expiring'), ('CREDENTIAL_EXPIRED', 'Credential Expired'), ('CREDENTIAL_REVOKED', 'Credential Revoked'), ('CERTIFICATE_DOCUMENT_MISSING', 'Certificate Document Missing'), ('VERIFICATION_PROVIDER_ERROR', 'Verification Provider Error'), ('DOUBLE_TEACHER_EVIDENCE_INVALIDATED', 'Double Teacher Evidence Invalidated')], max_length=48)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=16)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.CharField(blank=True, default='', max_length=200)),
                ('due_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=24)),
                ('resolution', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.BigIntegerField(blank=True, null=True)),
                ('version', models.BigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qualification_risks', to='hr_staff.hrperson')),
            ],
            options={
                'verbose_name': 'HR Qualification Risk Case',
                'verbose_name_plural': 'HR Qualification Risk Cases',
            },
        ),
        migrations.CreateModel(
            name='HrCredentialRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('target_type', models.CharField(choices=[('HR02_POST', 'HR02 Post'), ('HR08_EXTERNAL_CATEGORY', 'HR08 External Category'), ('HR09_DOUBLE_TEACHER_LEVEL', 'HR09 Double Teacher Level'), ('OTHER_TARGET', 'Other')], default='OTHER_TARGET', max_length=32)),
                ('target_ref', models.CharField(blank=True, default='', max_length=200)),
                ('credential_category', models.CharField(blank=True, choices=[('TEACHER_QUALIFICATION', 'Teacher Qualification'), ('VOCATIONAL_QUALIFICATION', 'Vocational Qualification'), ('VOCATIONAL_SKILL_LEVEL', 'Vocational Skill Level'), ('NON_TEACHER_PROFESSIONAL_TITLE', 'Non-Teacher Professional Title'), ('PROFESSIONAL_LICENSE', 'Professional License'), ('INDUSTRY_CERTIFICATION', 'Industry Certification'), ('TRAINING_CERTIFICATE', 'Training Certificate'), ('OTHER', 'Other')], default='', max_length=32)),
                ('minimum_level', models.CharField(blank=True, default='', max_length=64)),
                ('verification_required', models.BooleanField(default=False)),
                ('valid_on_date_required', models.BooleanField(default=False)),
                ('hard_or_soft', models.CharField(choices=[('HARD', 'Hard Requirement'), ('SOFT', 'Soft / Preferred')], default='HARD', max_length=8)),
                ('version', models.BigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_item_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='hr_qualification.hrcredentialcatalogitem')),
            ],
            options={
                'verbose_name': 'HR Credential Requirement',
                'verbose_name_plural': 'HR Credential Requirements',
                'indexes': [models.Index(fields=['tenant_id', 'target_type'], name='hr_qualific_tenant__dba1b3_idx'), models.Index(fields=['tenant_id', 'credential_category'], name='hr_qualific_tenant__619060_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='hrpersoncredential',
            index=models.Index(fields=['tenant_id', 'person_id', 'catalog_item_id'], name='hr_qualific_tenant__a7993b_idx'),
        ),
        migrations.AddIndex(
            model_name='hrpersoncredential',
            index=models.Index(fields=['tenant_id', 'status', 'valid_to'], name='hr_qualific_tenant__a8c256_idx'),
        ),
        migrations.AddIndex(
            model_name='hrpersoncredential',
            index=models.Index(fields=['tenant_id', 'current_verification_status'], name='hr_qualific_tenant__4af107_idx'),
        ),
        migrations.AddIndex(
            model_name='hrpersoncredential',
            index=models.Index(fields=['staff_master_id'], name='hr_qualific_staff_m_167652_idx'),
        ),
        migrations.AddIndex(
            model_name='hrcredentialverification',
            index=models.Index(fields=['credential_id'], name='hr_qualific_credent_62da58_idx'),
        ),
        migrations.AddIndex(
            model_name='hrcredentialverification',
            index=models.Index(fields=['result'], name='hr_qualific_result_c29683_idx'),
        ),
        migrations.AddIndex(
            model_name='hrcredentialstatusevent',
            index=models.Index(fields=['credential_id'], name='hr_qualific_credent_56f0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='hrcredentialrenewal',
            index=models.Index(fields=['original_credential_id'], name='hr_qualific_origina_e9f382_idx'),
        ),
        migrations.AddIndex(
            model_name='hrcredentialdocument',
            index=models.Index(fields=['credential_id'], name='hr_qualific_credent_2566c3_idx'),
        ),
        migrations.AddIndex(
            model_name='hrqualificationriskcase',
            index=models.Index(fields=['tenant_id', 'risk_type', 'severity', 'status'], name='hr_qualific_tenant__3a7d26_idx'),
        ),
        migrations.AddIndex(
            model_name='hrqualificationriskcase',
            index=models.Index(fields=['credential_id'], name='hr_qualific_credent_3c072f_idx'),
        ),
        migrations.AddIndex(
            model_name='hrqualificationriskcase',
            index=models.Index(fields=['recognition_id'], name='hr_qualific_recogni_6bf6bd_idx'),
        ),
    ]
