# Generated by Django 5.2 on 2026-08-09 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_qualification', '0002_hrdoubleteacherrecognitionbatch_hrdoubleteacherrule_and_more'),
        ('hr_staff', '0011_hrexportjob_hrstaffnumbersequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrdoubleteacherevidenceitem',
            name='package_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='hr_qualification.hrdoubleteacherevidencepackage'),
        ),
        migrations.AlterField(
            model_name='hrdoubleteacherrulepack',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=16),
        ),
        migrations.AddIndex(
            model_name='hrpersoncredential',
            index=models.Index(fields=['tenant_id', 'certificate_no_hash'], name='hr_qualific_tenant__3f2db3_idx'),
        ),
    ]
