# Generated by Django 5.2 on 2026-08-30 10:06

import hashlib
import json

import django.db.models.deletion
import uuid
from django.db import migrations, models


def _canonical(value):
    if hasattr(value, "isoformat"):
        return value.isoformat()
    if isinstance(value, uuid.UUID):
        return str(value)
    return value


def seal_legacy_final_decisions(apps, schema_editor):
    Decision = apps.get_model("hr_qualification", "HrDoubleTeacherFinalDecision")
    alias = schema_editor.connection.alias
    fields = (
        "id",
        "application_id_id",
        "decision",
        "recognized_level",
        "effective_from",
        "effective_to",
        "decision_authority",
        "meeting_ref",
        "published_at",
        "version",
        "authority_receipt_json",
        "sealed_at",
        "published_by",
    )
    for row in Decision.objects.using(alias).all().iterator():
        if row.published_at is None:
            continue
        row.sealed_at = row.published_at or row.created_at
        row.published_by = 0
        row.authority_receipt_json = {
            "permissionCode": "hr.qualification.review.finalize",
            "authorityRef": row.meeting_ref or row.decision_authority or "LEGACY-MIGRATION-0006",
            "actorUserId": 0,
            "actorType": "MIGRATION",
        }
        payload = {field: _canonical(getattr(row, field)) for field in fields}
        row.content_hash = hashlib.sha256(
            json.dumps(
                payload,
                ensure_ascii=False,
                sort_keys=True,
                separators=(",", ":"),
                default=str,
            ).encode("utf-8")
        ).hexdigest()
        row.save(
            using=alias,
            update_fields=[
                "sealed_at",
                "published_by",
                "authority_receipt_json",
                "content_hash",
            ],
        )


def create_mysql_authority_triggers(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    statements = (
        """
        CREATE TRIGGER hr09_final_decision_no_update
        BEFORE UPDATE ON hr_qualification_hrdoubleteacherfinaldecision
        FOR EACH ROW
        BEGIN
            IF OLD.sealed_at IS NOT NULL THEN
                SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'HR09_FINAL_DECISION_APPEND_ONLY_UPDATE';
            END IF;
        END
        """,
        """
        CREATE TRIGGER hr09_final_decision_no_delete
        BEFORE DELETE ON hr_qualification_hrdoubleteacherfinaldecision
        FOR EACH ROW
        BEGIN
            IF OLD.sealed_at IS NOT NULL THEN
                SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'HR09_FINAL_DECISION_APPEND_ONLY_DELETE';
            END IF;
        END
        """,
        """
        CREATE TRIGGER hr09_decision_amendment_no_update
        BEFORE UPDATE ON hr_qualification_hrdoubleteacherfinaldecisionamendment
        FOR EACH ROW
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'HR09_FINAL_DECISION_AMENDMENT_APPEND_ONLY_UPDATE'
        """,
        """
        CREATE TRIGGER hr09_decision_amendment_no_delete
        BEFORE DELETE ON hr_qualification_hrdoubleteacherfinaldecisionamendment
        FOR EACH ROW
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'HR09_FINAL_DECISION_AMENDMENT_APPEND_ONLY_DELETE'
        """,
        """
        CREATE TRIGGER hr09_evidence_package_no_frozen_update
        BEFORE UPDATE ON hr_qualification_hrdoubleteacherevidencepackage
        FOR EACH ROW
        BEGIN
            IF OLD.status = 'FROZEN' THEN
                SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'HR09_EVIDENCE_PACKAGE_FROZEN_UPDATE';
            END IF;
        END
        """,
        """
        CREATE TRIGGER hr09_evidence_package_no_frozen_delete
        BEFORE DELETE ON hr_qualification_hrdoubleteacherevidencepackage
        FOR EACH ROW
        BEGIN
            IF OLD.status = 'FROZEN' THEN
                SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'HR09_EVIDENCE_PACKAGE_FROZEN_DELETE';
            END IF;
        END
        """,
        """
        CREATE TRIGGER hr09_evidence_item_no_frozen_insert
        BEFORE INSERT ON hr_qualification_hrdoubleteacherevidenceitem
        FOR EACH ROW
        BEGIN
            IF (SELECT COUNT(*) FROM hr_qualification_hrdoubleteacherevidencepackage
                WHERE id = NEW.package_id_id AND status = 'FROZEN') > 0 THEN
                SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'HR09_EVIDENCE_ITEM_FROZEN_INSERT';
            END IF;
        END
        """,
        """
        CREATE TRIGGER hr09_evidence_item_no_frozen_update
        BEFORE UPDATE ON hr_qualification_hrdoubleteacherevidenceitem
        FOR EACH ROW
        BEGIN
            IF (SELECT COUNT(*) FROM hr_qualification_hrdoubleteacherevidencepackage
                WHERE id = OLD.package_id_id AND status = 'FROZEN') > 0 THEN
                SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'HR09_EVIDENCE_ITEM_FROZEN_UPDATE';
            END IF;
        END
        """,
        """
        CREATE TRIGGER hr09_evidence_item_no_frozen_delete
        BEFORE DELETE ON hr_qualification_hrdoubleteacherevidenceitem
        FOR EACH ROW
        BEGIN
            IF (SELECT COUNT(*) FROM hr_qualification_hrdoubleteacherevidencepackage
                WHERE id = OLD.package_id_id AND status = 'FROZEN') > 0 THEN
                SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'HR09_EVIDENCE_ITEM_FROZEN_DELETE';
            END IF;
        END
        """,
    )
    with schema_editor.connection.cursor() as cursor:
        for statement in statements:
            cursor.execute(statement)


def drop_mysql_authority_triggers(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    names = (
        "hr09_final_decision_no_update",
        "hr09_final_decision_no_delete",
        "hr09_decision_amendment_no_update",
        "hr09_decision_amendment_no_delete",
        "hr09_evidence_package_no_frozen_update",
        "hr09_evidence_package_no_frozen_delete",
        "hr09_evidence_item_no_frozen_insert",
        "hr09_evidence_item_no_frozen_update",
        "hr09_evidence_item_no_frozen_delete",
    )
    with schema_editor.connection.cursor() as cursor:
        for name in names:
            cursor.execute(f"DROP TRIGGER IF EXISTS {name}")


class Migration(migrations.Migration):

    # MySQL trigger DDL is non-transactional (implicit commit).
    atomic = False

    dependencies = [
        ('hr_qualification', '0005_hrdoubleteacherevidencepackage_frozen_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrDoubleTeacherFinalDecisionAmendment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('kind', models.CharField(choices=[('CORRECTION', 'Correction'), ('REVOCATION', 'Revocation')], db_index=True, max_length=16)),
                ('replacement_payload_json', models.JSONField(blank=True, default=dict)),
                ('effect_receipt_json', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField()),
                ('authority_ref', models.CharField(max_length=200)),
                ('authority_receipt_json', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('content_hash', models.CharField(max_length=64)),
                ('sealed_at', models.DateTimeField(db_index=True)),
                ('published_by', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'HR Double Teacher Final Decision Amendment',
                'verbose_name_plural': 'HR Double Teacher Final Decision Amendments',
            },
        ),
        migrations.AlterModelOptions(
            name='hrdoubleteacherfinaldecision',
            options={'permissions': [('hr.qualification.review.final_decision.correct', 'Append HR09 final-decision correction'), ('hr.qualification.review.final_decision.revoke', 'Append HR09 final-decision revocation')], 'verbose_name': 'HR Double Teacher Final Decision', 'verbose_name_plural': 'HR Double Teacher Final Decisions'},
        ),
        migrations.AddField(
            model_name='hrdoubleteacherfinaldecision',
            name='authority_receipt_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='hrdoubleteacherfinaldecision',
            name='content_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='hrdoubleteacherfinaldecision',
            name='published_by',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hrdoubleteacherfinaldecision',
            name='sealed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(
            seal_legacy_final_decisions,
            migrations.RunPython.noop,
            atomic=True,
        ),
        migrations.AddConstraint(
            model_name='hrdoubleteacherfinaldecision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('content_hash', ''), ('published_at__isnull', True), ('sealed_at__isnull', True)), models.Q(('published_at__isnull', False), ('sealed_at__isnull', False), models.Q(('content_hash', ''), _negated=True), ('published_by__isnull', False)), _connector='OR'), name='ck_hr09_final_decision_seal'),
        ),
        migrations.AddField(
            model_name='hrdoubleteacherfinaldecisionamendment',
            name='source_decision_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authority_amendments', to='hr_qualification.hrdoubleteacherfinaldecision'),
        ),
        migrations.AddField(
            model_name='hrdoubleteacherfinaldecisionamendment',
            name='supersedes_amendment_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor_amendment', to='hr_qualification.hrdoubleteacherfinaldecisionamendment'),
        ),
        migrations.AddIndex(
            model_name='hrdoubleteacherfinaldecisionamendment',
            index=models.Index(fields=['tenant_id', 'source_decision_id', 'created_at'], name='idx_hr09_decision_amendment'),
        ),
        migrations.AddConstraint(
            model_name='hrdoubleteacherfinaldecisionamendment',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'idempotency_key'), name='uq_hr09_decision_amendment_key'),
        ),
        migrations.AddConstraint(
            model_name='hrdoubleteacherfinaldecisionamendment',
            constraint=models.CheckConstraint(condition=models.Q(('content_hash', ''), _negated=True), name='ck_hr09_decision_amendment_hash'),
        ),
        migrations.RunPython(
            create_mysql_authority_triggers,
            drop_mysql_authority_triggers,
            atomic=False,
        ),
    ]
