# Generated by Django 5.2 on 2026-08-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_qualification", "0006_hrdoubleteacherfinaldecisionamendment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HrQualificationPermissionMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("hr.qualification.credential.view", "查看本校教师资格与职业资格事实"),
                    ("hr.qualification.credential.create", "登记教师资格与职业资格"),
                    ("hr.qualification.credential.verify", "核验教师资格与职业资格证据"),
                    ("hr.qualification.credential.revoke", "暂停或撤销教师资格事实"),
                    ("hr.qualification.credential.sensitive_view", "查看资格证号等受限字段"),
                    ("hr.qualification.credential.export", "导出资格受控数据"),
                    ("hr.qualification.rule.view", "查看双师型规则版本"),
                    ("hr.qualification.rule.manage", "维护双师型规则草稿"),
                    ("hr.qualification.rule.publish", "发布双师型正式规则版本"),
                    ("hr.qualification.application.self", "本人发起和查看双师型申请"),
                    ("hr.qualification.application.view", "查看本校双师型申请"),
                    ("hr.qualification.application.formal_review", "执行双师型形式审查"),
                    ("hr.qualification.review.score", "提交双师型评审评分"),
                    ("hr.qualification.review.panel_manage", "管理双师型评审组"),
                    ("hr.qualification.review.finalize", "作出双师型最终决定"),
                    ("hr.qualification.recognition.view", "查看双师型正式认定"),
                    ("hr.qualification.recognition.manage", "维护双师型认定有效期"),
                    ("hr.qualification.recognition.recheck", "发起和处理双师型复核"),
                    ("hr.qualification.recognition.revoke", "撤销双师型正式认定"),
                    ("hr.qualification.risk.view", "查看资格与双师型风险"),
                    ("hr.qualification.risk.manage", "处置资格与双师型风险"),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
