# HR15 benefit + occupational pension Authority.

import uuid
from django.db import migrations, models


def base_fields():
    return [("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("tenant_id", models.PositiveBigIntegerField(db_index=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("created_by", models.PositiveBigIntegerField(blank=True, null=True)), ("updated_by", models.PositiveBigIntegerField(blank=True, null=True))]


class Migration(migrations.Migration):
    dependencies = [("hr_payroll", "0003_payroll_adjust_permission")]
    operations = [
        migrations.CreateModel(name="BenefitPlan", fields=base_fields()+[("plan_code",models.CharField(max_length=64)),("version_no",models.PositiveIntegerField(default=1)),("name",models.CharField(max_length=200)),("benefit_type",models.CharField(max_length=64)),("provider_name",models.CharField(blank=True,default="",max_length=200)),("currency_code",models.CharField(default="CNY",max_length=3)),("employer_rate",models.DecimalField(decimal_places=6,default=0,max_digits=10)),("employee_rate",models.DecimalField(decimal_places=6,default=0,max_digits=10)),("fixed_amount",models.DecimalField(decimal_places=2,default=0,max_digits=18)),("effective_from",models.DateField()),("effective_to",models.DateField(blank=True,null=True)),("rule_snapshot_json",models.JSONField(default=dict)),("content_hash",models.CharField(blank=True,default="",max_length=64)),("status",models.CharField(choices=[("DRAFT","Draft"),("PUBLISHED","Published"),("INACTIVE","Inactive")],db_index=True,default="DRAFT",max_length=16))], options={"db_table":"hr15_benefit_plan","constraints":[models.UniqueConstraint(fields=("tenant_id","plan_code","version_no"),name="uq_hr15_benefit_plan_ver"),models.CheckConstraint(condition=models.Q(effective_to__isnull=True)|models.Q(effective_to__gt=models.F("effective_from")),name="ck_hr15_benefit_date")],"indexes":[models.Index(fields=["tenant_id","plan_code","status"],name="idx_hr15_benefit_plan")]}),
        migrations.CreateModel(name="BenefitEnrollmentFact", fields=base_fields()+[("enrollment_no",models.CharField(max_length=64)),("benefit_plan_id",models.UUIDField()),("staff_id",models.UUIDField()),("effective_from",models.DateField()),("effective_to",models.DateField(blank=True,null=True)),("employer_amount",models.DecimalField(decimal_places=2,default=0,max_digits=18)),("employee_amount",models.DecimalField(decimal_places=2,default=0,max_digits=18)),("snapshot_json",models.JSONField(default=dict)),("supersedes_enrollment_id",models.UUIDField(blank=True,null=True))], options={"db_table":"hr15_benefit_enrollment_fact","constraints":[models.UniqueConstraint(fields=("tenant_id","enrollment_no"),name="uq_hr15_benefit_enroll_no"),models.UniqueConstraint(fields=("tenant_id","supersedes_enrollment_id"),name="uq_hr15_benefit_supersede"),models.CheckConstraint(condition=models.Q(effective_to__isnull=True)|models.Q(effective_to__gt=models.F("effective_from")),name="ck_hr15_benefit_enroll_date")],"indexes":[models.Index(fields=["tenant_id","staff_id","benefit_plan_id"],name="idx_hr15_benefit_staff")]}),
        migrations.CreateModel(name="OccupationalPensionPlan", fields=base_fields()+[("plan_code",models.CharField(max_length=64)),("version_no",models.PositiveIntegerField(default=1)),("name",models.CharField(max_length=200)),("employer_rate",models.DecimalField(decimal_places=6,max_digits=10)),("employee_rate",models.DecimalField(decimal_places=6,max_digits=10)),("contribution_basis_rule_json",models.JSONField(default=dict)),("effective_from",models.DateField()),("effective_to",models.DateField(blank=True,null=True)),("content_hash",models.CharField(blank=True,default="",max_length=64)),("status",models.CharField(choices=[("DRAFT","Draft"),("PUBLISHED","Published"),("INACTIVE","Inactive")],db_index=True,default="DRAFT",max_length=16))], options={"db_table":"hr15_pension_plan","constraints":[models.UniqueConstraint(fields=("tenant_id","plan_code","version_no"),name="uq_hr15_pension_plan_ver"),models.CheckConstraint(condition=models.Q(employer_rate__gte=0)&models.Q(employee_rate__gte=0),name="ck_hr15_pension_rates"),models.CheckConstraint(condition=models.Q(effective_to__isnull=True)|models.Q(effective_to__gt=models.F("effective_from")),name="ck_hr15_pension_plan_date")]}),
        migrations.CreateModel(name="OccupationalPensionPeriod", fields=base_fields()+[("plan_id",models.UUIDField()),("period_code",models.CharField(max_length=32)),("start_date",models.DateField()),("end_date",models.DateField()),("status",models.CharField(choices=[("OPEN","Open"),("CLOSED","Closed")],db_index=True,default="OPEN",max_length=16)),("closed_at",models.DateTimeField(blank=True,null=True))], options={"db_table":"hr15_pension_period","constraints":[models.UniqueConstraint(fields=("tenant_id","plan_id","period_code"),name="uq_hr15_pension_period"),models.CheckConstraint(condition=models.Q(end_date__gt=models.F("start_date")),name="ck_hr15_pension_period_date")],"indexes":[models.Index(fields=["tenant_id","status","period_code"],name="idx_hr15_pension_period")]}),
        migrations.CreateModel(name="OccupationalPensionContributionFact", fields=base_fields()+[("contribution_no",models.CharField(max_length=64)),("pension_period_id",models.UUIDField()),("pension_plan_id",models.UUIDField()),("staff_id",models.UUIDField()),("sequence_no",models.PositiveIntegerField(default=1)),("basis_amount",models.DecimalField(decimal_places=2,max_digits=18)),("employer_amount",models.DecimalField(decimal_places=2,max_digits=18)),("employee_amount",models.DecimalField(decimal_places=2,max_digits=18)),("total_amount",models.DecimalField(decimal_places=2,max_digits=18)),("supersedes_contribution_id",models.UUIDField(blank=True,null=True)),("snapshot_json",models.JSONField(default=dict))], options={"db_table":"hr15_pension_contribution_fact","constraints":[models.UniqueConstraint(fields=("tenant_id","contribution_no"),name="uq_hr15_pension_contrib_no"),models.UniqueConstraint(fields=("tenant_id","pension_period_id","staff_id","sequence_no"),name="uq_hr15_pension_staff_seq"),models.UniqueConstraint(fields=("tenant_id","supersedes_contribution_id"),name="uq_hr15_pension_supersede"),models.CheckConstraint(condition=models.Q(basis_amount__gte=0)&models.Q(employer_amount__gte=0)&models.Q(employee_amount__gte=0)&models.Q(total_amount__gte=0),name="ck_hr15_pension_amounts")],"indexes":[models.Index(fields=["tenant_id","pension_period_id","staff_id"],name="idx_hr15_pension_contrib")]}),
        migrations.CreateModel(name="OccupationalPensionSettlementFact", fields=base_fields()+[("settlement_no",models.CharField(max_length=64)),("pension_period_id",models.UUIDField()),("pension_plan_id",models.UUIDField()),("contribution_count",models.PositiveIntegerField(default=0)),("staff_count",models.PositiveIntegerField(default=0)),("employer_total",models.DecimalField(decimal_places=2,default=0,max_digits=20)),("employee_total",models.DecimalField(decimal_places=2,default=0,max_digits=20)),("grand_total",models.DecimalField(decimal_places=2,default=0,max_digits=20)),("snapshot_json",models.JSONField(default=dict)),("closed_at",models.DateTimeField())], options={"db_table":"hr15_pension_settlement_fact","constraints":[models.UniqueConstraint(fields=("tenant_id","settlement_no"),name="uq_hr15_pension_settle_no"),models.UniqueConstraint(fields=("tenant_id","pension_period_id"),name="uq_hr15_pension_period_settle")]}),
        migrations.CreateModel(name="HrPayrollAuthorityPermissionMeta", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID"))], options={"managed":False,"permissions":(("hr.payroll.benefit.view","HR15: View Benefit Authority"),("hr.payroll.benefit.manage","HR15: Manage Benefit Authority"),("hr.payroll.pension.view","HR15: View Occupational Pension"),("hr.payroll.pension.manage","HR15: Manage Occupational Pension"),("hr.payroll.pension.close","HR15: Close Occupational Pension Period"))}),
    ]
