# Generated by Django 5.2 on 2026-08-30 08:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_payroll', '0007_payroll_workflow_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrPayrollStatutoryPermissionMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('hr.payroll.statutory.view', 'HR15: View social insurance and housing fund'), ('hr.payroll.statutory.manage', 'HR15: Manage statutory contribution rules')),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatutoryContributionFact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('payroll_period_id', models.UUIDField()),
                ('payroll_result_id', models.UUIDField()),
                ('calculation_batch_id', models.UUIDField()),
                ('staff_id', models.UUIDField()),
                ('rule_version_id', models.UUIDField()),
                ('contribution_group', models.CharField(choices=[('SOCIAL_INSURANCE', 'Social insurance'), ('HOUSING_FUND', 'Housing fund')], max_length=32)),
                ('contribution_code', models.CharField(max_length=32)),
                ('requested_base', models.DecimalField(decimal_places=2, max_digits=18)),
                ('contribution_base', models.DecimalField(decimal_places=2, max_digits=18)),
                ('employee_rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('employer_rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('employee_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('employer_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('employee_item_code', models.CharField(max_length=64)),
                ('employer_item_code', models.CharField(max_length=64)),
                ('input_snapshot_id', models.UUIDField()),
                ('input_content_hash', models.CharField(max_length=64)),
                ('rule_content_hash', models.CharField(max_length=64)),
                ('evidence_hash', models.CharField(max_length=64)),
                ('review_evidence_hash', models.CharField(blank=True, default='', max_length=64)),
                ('reviewed_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('sealed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CALCULATED', 'Calculated'), ('REVIEWED', 'Reviewed'), ('SEALED', 'Sealed')], db_index=True, default='CALCULATED', max_length=16)),
            ],
            options={
                'db_table': 'hr15_statutory_contribution_fact',
                'indexes': [models.Index(fields=['tenant_id', 'payroll_period_id', 'status'], name='idx_hr15_stat_period_status'), models.Index(fields=['tenant_id', 'staff_id', 'payroll_period_id'], name='idx_hr15_stat_staff_period')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'payroll_result_id', 'rule_version_id'), name='uq_hr15_stat_result_rule'), models.CheckConstraint(condition=models.Q(('requested_base__gte', 0), ('contribution_base__gte', 0), ('employee_amount__gte', 0), ('employer_amount__gte', 0)), name='ck_hr15_stat_fact_amounts')],
            },
        ),
        migrations.CreateModel(
            name='StatutoryContributionRuleVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('rule_code', models.CharField(max_length=64)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('contribution_group', models.CharField(choices=[('SOCIAL_INSURANCE', 'Social insurance'), ('HOUSING_FUND', 'Housing fund')], max_length=32)),
                ('contribution_code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('jurisdiction_code', models.CharField(max_length=32)),
                ('base_variable_key', models.CharField(max_length=64)),
                ('base_floor', models.DecimalField(decimal_places=2, max_digits=18)),
                ('base_ceiling', models.DecimalField(decimal_places=2, max_digits=18)),
                ('employee_rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('employer_rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('employee_item_code', models.CharField(max_length=64)),
                ('employer_item_code', models.CharField(max_length=64)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('policy_evidence_json', models.JSONField(default=dict)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('RETIRED', 'Retired')], db_index=True, default='DRAFT', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hr15_statutory_contribution_rule',
                'indexes': [models.Index(fields=['tenant_id', 'status', 'effective_from'], name='idx_hr15_stat_effective')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'rule_code', 'version_no'), name='uq_hr15_stat_rule_ver'), models.UniqueConstraint(fields=('tenant_id', 'employee_item_code', 'version_no'), name='uq_hr15_stat_employee_item_ver'), models.UniqueConstraint(fields=('tenant_id', 'employer_item_code', 'version_no'), name='uq_hr15_stat_employer_item_ver'), models.CheckConstraint(condition=models.Q(('base_floor__gte', 0), ('base_ceiling__gte', models.F('base_floor'))), name='ck_hr15_stat_base_range'), models.CheckConstraint(condition=models.Q(('employee_rate__gte', 0), ('employee_rate__lte', 1), ('employer_rate__gte', 0), ('employer_rate__lte', 1)), name='ck_hr15_stat_rates'), models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='ck_hr15_stat_effective_range')],
            },
        ),
    ]
