# Generated by Django 5.2 on 2026-08-30 09:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_payroll', '0008_hrpayrollstatutorypermissionmeta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrPayrollLegacyTakeoverPermissionMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('hr.payroll.legacy_takeover.view', 'HR15: View legacy payroll takeover evidence'), ('hr.payroll.legacy_takeover.manage', 'HR15: Verify and activate legacy payroll takeover')),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegacyPayrollAssetInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('inventory_no', models.CharField(max_length=96)),
                ('status', models.CharField(choices=[('COMPLETE', 'Complete'), ('UNAVAILABLE', 'Unavailable')], db_index=True, max_length=16)),
                ('legacy_row_count', models.PositiveIntegerField(default=0)),
                ('matched_row_count', models.PositiveIntegerField(default=0)),
                ('unavailable_row_count', models.PositiveIntegerField(default=0)),
                ('snapshot_hash', models.CharField(max_length=64)),
                ('reason_codes_json', models.JSONField(blank=True, default=list)),
                ('captured_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'hr15_legacy_payroll_inventory',
                'indexes': [models.Index(fields=['tenant_id', 'status', 'captured_at'], name='idx_hr15_leg_inv_state')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'inventory_no'), name='uq_hr15_legacy_inventory_no')],
            },
        ),
        migrations.CreateModel(
            name='LegacyPayrollCutoverControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('INVENTORIED', 'Inventoried'), ('VERIFIED', 'Verified'), ('UNAVAILABLE', 'Unavailable'), ('ACTIVE', 'Active')], db_index=True, default='INVENTORIED', max_length=16)),
                ('latest_inventory_id', models.UUIDField(blank=True, null=True)),
                ('latest_snapshot_hash', models.CharField(blank=True, default='', max_length=64)),
                ('activation_key', models.CharField(blank=True, default='', max_length=96)),
                ('activation_evidence_hash', models.CharField(blank=True, default='', max_length=64)),
                ('activation_evidence_json', models.JSONField(blank=True, default=dict)),
                ('write_block_enabled', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('activated_by', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hr15_legacy_payroll_cutover',
                'constraints': [models.UniqueConstraint(fields=('tenant_id',), name='uq_hr15_legacy_cutover_tenant')],
            },
        ),
        migrations.CreateModel(
            name='LegacyPayrollMappingFact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('inventory_id', models.UUIDField()),
                ('legacy_payslip_id', models.PositiveBigIntegerField()),
                ('legacy_employee_ref_hash', models.CharField(max_length=64)),
                ('staff_id', models.UUIDField(blank=True, null=True)),
                ('payroll_period_id', models.UUIDField(blank=True, null=True)),
                ('payroll_result_id', models.UUIDField(blank=True, null=True)),
                ('payroll_payslip_id', models.UUIDField(blank=True, null=True)),
                ('finance_reconciliation_id', models.UUIDField(blank=True, null=True)),
                ('reconciliation_status', models.CharField(db_index=True, max_length=48)),
                ('legacy_amount_hash', models.CharField(blank=True, default='', max_length=64)),
                ('authority_amount_hash', models.CharField(blank=True, default='', max_length=64)),
                ('evidence_hash', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'hr15_legacy_payroll_mapping_fact',
                'indexes': [models.Index(fields=['tenant_id', 'inventory_id', 'reconciliation_status'], name='idx_hr15_legacy_mapping_state')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'inventory_id', 'legacy_payslip_id'), name='uq_hr15_legacy_mapping_row')],
            },
        ),
        migrations.CreateModel(
            name='LegacyPayrollWriteBlockAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('cutover_id', models.UUIDField()),
                ('operation', models.CharField(max_length=24)),
                ('object_ref_hash', models.CharField(blank=True, default='', max_length=64)),
                ('actor_user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('reason_code', models.CharField(max_length=64)),
                ('blocked_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'hr15_legacy_payroll_write_block_audit',
                'indexes': [models.Index(fields=['tenant_id', 'blocked_at'], name='idx_hr15_legacy_write_block')],
            },
        ),
    ]
