# Generated by hand for HR05-S6（provisioning payload）
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_onboarding", "0002_hronboardingoutboxevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="hrprovisioningrequest",
            name="payload_json",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
