# Generated by hand for HR05-S2 补强（material 幂等唯一约束）
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_onboarding", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="hronboardingmaterial",
            constraint=models.UniqueConstraint(
                fields=("case", "requirement"), name="uniq_hr_ob_mat_case_requirement"
            ),
        ),
    ]
