# Generated by Django 5.2 on 2026-08-09 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_onboarding', '0008_hronboardingcase_actual_report_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='hronboardingcase',
            new_name='hr_onboardi_tenant__6b7ff7_idx',
            old_name='hr_ob_case_tenant_actual_report_idx',
        ),
    ]
