# Generated by Django 5.2 on 2026-08-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_onboarding', '0013_alter_hronboardingpermissionmeta_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hronboardingoutboxevent',
            name='external_ref',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='hronboardingoutboxevent',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hronboardingoutboxevent',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='hronboardingoutboxevent',
            name='lease_owner',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='hronboardingoutboxevent',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='hronboardingoutboxevent',
            index=models.Index(fields=['tenant_id', 'status', 'next_attempt_at'], name='hr05_outbox_due_idx'),
        ),
    ]
