# Generated by Django 5.2 on 2026-08-30 13:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_onboarding', '0014_hronboardingoutboxevent_external_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrOnboardingIdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('operation', models.CharField(max_length=64)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('SUCCEEDED', 'Succeeded'), ('FAILED_RETRYABLE', 'Failed, retryable'), ('FAILED_TERMINAL', 'Failed, terminal')], db_index=True, default='IN_PROGRESS', max_length=24)),
                ('authority_type', models.CharField(blank=True, default='', max_length=64)),
                ('authority_id', models.CharField(blank=True, default='', max_length=64)),
                ('response_summary', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('attempt_count', models.PositiveIntegerField(default=1)),
                ('lease_owner', models.CharField(blank=True, default='', max_length=64)),
                ('lease_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HR Onboarding Idempotency Record',
                'verbose_name_plural': 'HR Onboarding Idempotency Records',
            },
        ),
        migrations.AlterField(
            model_name='hrprovisioningrequest',
            name='idempotency_key',
            field=models.CharField(max_length=128),
        ),
        migrations.AddConstraint(
            model_name='hrprovisioningrequest',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'idempotency_key'), name='uniq_hr05_provision_tenant_idem'),
        ),
        migrations.AddIndex(
            model_name='hronboardingidempotencyrecord',
            index=models.Index(fields=['tenant_id', 'status', 'lease_expires_at'], name='hr05_idem_lease_idx'),
        ),
        migrations.AddConstraint(
            model_name='hronboardingidempotencyrecord',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'operation', 'idempotency_key'), name='uniq_hr05_idem_tenant_op_key'),
        ),
    ]
