# Generated by Django 5.2.17 on 2026-09-19 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_onboarding', '0017_durable_excel_import_ledger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hronboardingpermissionmeta',
            options={'managed': False, 'permissions': (('hr05.template.manage', 'Hr05 Template Manage'), ('hr05.template.publish', 'Hr05 Template Publish'), ('hr05.case.view', 'Hr05 Case View'), ('hr05.case.create', 'Hr05 Case Create'), ('hr05.case.cancel', 'Hr05 Case Cancel'), ('hr05.case.activate', 'Hr05 Case Activate'), ('hr05.activation_fact.correct', 'Hr05 Activation_Fact Correct'), ('hr05.activation_fact.revoke', 'Hr05 Activation_Fact Revoke'), ('hr05.report.checkin', 'Hr05 Report Checkin'), ('hr05.material.review', 'Hr05 Material Review'), ('hr05.material.sensitive_view', 'Hr05 Material Sensitive_View'), ('hr05.task.manage', 'Hr05 Task Manage'), ('hr05.task.complete', 'Hr05 Task Complete'), ('hr05.task.waive', 'Hr05 Task Waive'), ('hr05.identity.provision', 'Hr05 Identity Provision'), ('hr05.position.commit', 'Hr05 Position Commit'), ('hr05.probation.manage', 'Hr05 Probation Manage'), ('hr05.probation.finalize', 'Hr05 Probation Finalize'), ('hr05.export', 'Hr05 Export'), ('hr05.sensitive_export', 'Hr05 Sensitive_Export'))},
        ),
    ]
