from django.urls import path

from . import (
    api,
    asof_api,
    exchange_api,
    evaluation_api,
    legacy_api,
    metric_api,
    metric_evaluation_api,
    quality_api,
    quality_finding_api,
    submission_api,
)

app_name = "hr_data_api"

urlpatterns = [
    path("dashboard/", api.dashboard, name="dashboard"),
    path(
        "legacy/report-assets/",
        legacy_api.legacy_report_assets,
        name="legacy-report-assets",
    ),
    path(
        "legacy/report-takeover/inventory/",
        legacy_api.inventory,
        name="legacy-report-takeover-inventory",
    ),
    path(
        "legacy/report-takeover/assets/<uuid:asset_id>/mapping/",
        legacy_api.map_asset,
        name="legacy-report-takeover-asset-mapping",
    ),
    path(
        "legacy/report-takeover/assets/<uuid:asset_id>/reconcile/",
        legacy_api.reconcile_asset,
        name="legacy-report-takeover-asset-reconcile",
    ),
    path(
        "legacy/report-takeover/cutovers/<str:cutover_code>/advance/",
        legacy_api.advance_cutover,
        name="legacy-report-takeover-advance",
    ),
    path(
        "definitions/populations/",
        api.create_population_definition,
        name="population-definition-create",
    ),
    path(
        "definitions/dimensions/",
        api.create_dimension_definition,
        name="dimension-definition-create",
    ),
    path(
        "definitions/metrics/",
        metric_api.create_metric_definition,
        name="metric-definition-create",
    ),
    path(
        "metrics/evaluate/",
        metric_evaluation_api.evaluate_metric,
        name="metric-evaluation-create",
    ),
    path(
        "as-of/evidence/",
        asof_api.reconstruct_evidence,
        name="asof-evidence-reconstruct",
    ),
    path(
        "as-of/evaluate/",
        evaluation_api.evaluate,
        name="asof-evaluate",
    ),
    path(
        "quality/rules/",
        quality_api.create_rule,
        name="quality-rule-create",
    ),
    path(
        "quality/runs/",
        quality_api.execute_run,
        name="quality-run-execute",
    ),
    path(
        "quality/findings/<uuid:finding_id>/acknowledge/",
        quality_finding_api.acknowledge,
        name="quality-finding-acknowledge",
    ),
    path(
        "quality/findings/<uuid:finding_id>/verify-fixed/",
        quality_finding_api.verify_fixed,
        name="quality-finding-verify-fixed",
    ),
    path("exchange/datasets/", exchange_api.create_dataset, name="exchange-dataset-create"),
    path(
        "exchange/targets/",
        exchange_api.create_target_mapping,
        name="exchange-target-create",
    ),
    path("exchange/jobs/", exchange_api.queue_job, name="exchange-job-queue"),
    path(
        "exchange/jobs/<uuid:job_id>/receipt/",
        exchange_api.record_receipt,
        name="exchange-job-receipt",
    ),
    path(
        "exchange/jobs/<uuid:job_id>/reconcile/",
        exchange_api.reconcile_job,
        name="exchange-job-reconcile",
    ),
    path(
        "exchange/dead-letters/",
        exchange_api.dead_letters,
        name="exchange-dead-letters",
    ),
    path("submissions/", submission_api.create_submission, name="submission-create"),
    path(
        "submissions/<uuid:submission_id>/validate/",
        submission_api.validate_submission,
        name="submission-validate",
    ),
    path(
        "submissions/<uuid:submission_id>/corrections/",
        submission_api.create_correction,
        name="submission-correction-create",
    ),
    path(
        "submissions/<uuid:submission_id>/approve/",
        submission_api.approve_submission,
        name="submission-approve",
    ),
    path(
        "submissions/<uuid:submission_id>/submit/",
        submission_api.submit_submission,
        name="submission-submit",
    ),
    path(
        "submissions/<uuid:submission_id>/receipt/",
        submission_api.record_receipt,
        name="submission-receipt",
    ),
]
