"""HR07 canonical API routes."""

from django.urls import path

from hr_contracts.api import agreements, documents, lifecycle
from hr_contracts import setup_api

app_name = "hr_contracts_api"

urlpatterns = [
    path(
        "api/v1/hr/contracts/setup/workbench",
        setup_api.setup_workbench,
        name="hr07-setup-workbench",
    ),
    path(
        "api/v1/hr/contracts/setup/templates/publish",
        setup_api.publish_template,
        name="hr07-template-publish",
    ),
    path(
        "api/v1/hr/contracts/setup/expiry-policies/publish",
        setup_api.publish_expiry_policy,
        name="hr07-expiry-policy-publish",
    ),
    path(
        "api/v1/hr/contracts/setup/expiry-scan",
        setup_api.scan_expiry,
        name="hr07-expiry-scan",
    ),
    path(
        "api/v1/hr/contracts/agreements",
        agreements.agreement_collection,
        name="hr07-agreement-collection",
    ),
    path(
        "api/v1/hr/contracts/agreements/<uuid:agreement_id>",
        agreements.agreement_detail,
        name="hr07-agreement-detail",
    ),
    path(
        "api/v1/hr/contracts/agreements/<uuid:agreement_id>/documents",
        documents.document_collection,
        name="hr07-document-collection",
    ),
    path(
        "api/v1/hr/contracts/documents/<uuid:document_id>/ticket",
        documents.generate_ticket,
        name="hr07-document-ticket",
    ),
    path(
        "api/v1/hr/contracts/documents/download",
        documents.download_via_ticket,
        name="hr07-document-download",
    ),
    path(
        "api/v1/hr/contracts/agreements/<uuid:agreement_id>/versions/sign",
        agreements.sign_initial_version,
        name="hr07-agreement-sign",
    ),
    path(
        "api/v1/hr/contracts/agreements/<uuid:agreement_id>/versions/<uuid:version_id>/activate",
        agreements.activate_initial_version,
        name="hr07-agreement-activate",
    ),
    path(
        "api/v1/hr/contracts/agreements/<uuid:agreement_id>/versions/<uuid:version_id>/correct",
        agreements.correct_version,
        name="hr07-agreement-version-correct",
    ),
    path(
        "api/v1/hr/contracts/agreements/<uuid:agreement_id>/versions/<uuid:version_id>/void",
        agreements.void_version,
        name="hr07-agreement-version-void",
    ),
    path(
        "api/v1/hr/contracts/cases",
        lifecycle.case_collection,
        name="hr07-case-collection",
    ),
    path(
        "api/v1/hr/contracts/cases/<uuid:case_id>",
        lifecycle.case_detail,
        name="hr07-case-detail",
    ),
    path(
        "api/v1/hr/contracts/cases/<uuid:case_id>/submit",
        lifecycle.case_submit,
        name="hr07-case-submit",
    ),
    path(
        "api/v1/hr/contracts/cases/<uuid:case_id>/approve",
        lifecycle.case_approve,
        name="hr07-case-approve",
    ),
    path(
        "api/v1/hr/contracts/cases/<uuid:case_id>/versions/sign",
        lifecycle.case_sign_successor,
        name="hr07-case-sign-successor",
    ),
    path(
        "api/v1/hr/contracts/cases/<uuid:case_id>/versions/<uuid:version_id>/activate",
        lifecycle.case_activate_successor,
        name="hr07-case-activate-successor",
    ),
    path(
        "api/v1/hr/contracts/cases/<uuid:case_id>/termination/effect",
        lifecycle.case_effect_termination,
        name="hr07-case-effect-termination",
    ),
]
