# Generated by Django 5.2 on 2026-08-30 13:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


APPEND_ONLY_TABLES = (
    "hr18_submission_dispatch_attempt",
    "hr18_submission_trusted_receipt",
    "hr18_submission_dispatch_event",
)


def install_mysql_submission_dispatch_seals(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    for table in APPEND_ONLY_TABLES:
        schema_editor.execute(f"DROP TRIGGER IF EXISTS {table}_no_update")
        schema_editor.execute(f"DROP TRIGGER IF EXISTS {table}_no_delete")
        schema_editor.execute(
            f"""
            CREATE TRIGGER {table}_no_update
            BEFORE UPDATE ON {table}
            FOR EACH ROW
            SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'HR18_SUBMISSION_DISPATCH_EVIDENCE_IMMUTABLE'
            """
        )
        schema_editor.execute(
            f"""
            CREATE TRIGGER {table}_no_delete
            BEFORE DELETE ON {table}
            FOR EACH ROW
            SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'HR18_SUBMISSION_DISPATCH_EVIDENCE_IMMUTABLE'
            """
        )

    schema_editor.execute("DROP TRIGGER IF EXISTS hr18_submission_dispatch_job_guard")
    schema_editor.execute("DROP TRIGGER IF EXISTS hr18_submission_dispatch_job_no_delete")
    schema_editor.execute("DROP TRIGGER IF EXISTS hr18_submission_dispatch_job_guard_insert")
    schema_editor.execute("DROP TRIGGER IF EXISTS hr18_submission_attempt_guard_insert")
    schema_editor.execute("DROP TRIGGER IF EXISTS hr18_submission_event_guard_insert")
    schema_editor.execute("DROP TRIGGER IF EXISTS hr18_submission_receipt_guard_insert")
    schema_editor.execute(
        """
        CREATE TRIGGER hr18_submission_dispatch_job_guard_insert
        BEFORE INSERT ON hr18_submission_dispatch_job
        FOR EACH ROW
        BEGIN
            IF NEW.status <> 'QUEUED'
               OR NEW.payload_hash NOT REGEXP '^[0-9a-f]{64}$'
               OR NEW.request_hash NOT REGEXP '^[0-9a-f]{64}$'
               OR NOT EXISTS (
                    SELECT 1 FROM hr18_submission_snapshot s
                    WHERE s.id = NEW.submission_id
                      AND s.tenant_id = NEW.tenant_id
                      AND s.definition_version = NEW.definition_version
                      AND s.payload_hash = NEW.payload_hash
               ) THEN
                SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'HR18_SUBMISSION_DISPATCH_PARENT_MISMATCH';
            END IF;
        END
        """
    )
    schema_editor.execute(
        """
        CREATE TRIGGER hr18_submission_dispatch_job_guard
        BEFORE UPDATE ON hr18_submission_dispatch_job
        FOR EACH ROW
        BEGIN
            IF NOT (OLD.tenant_id <=> NEW.tenant_id)
               OR NOT (OLD.submission_id <=> NEW.submission_id)
               OR NOT (OLD.provider_key <=> NEW.provider_key)
               OR NOT (OLD.schema_version <=> NEW.schema_version)
               OR NOT (OLD.definition_version <=> NEW.definition_version)
               OR NOT (OLD.payload_hash <=> NEW.payload_hash)
               OR NOT (OLD.request_hash <=> NEW.request_hash)
               OR NOT (OLD.idempotency_key <=> NEW.idempotency_key)
               OR NOT (OLD.max_attempts <=> NEW.max_attempts)
               OR NOT (OLD.created_at <=> NEW.created_at)
               OR NOT (OLD.created_by <=> NEW.created_by) THEN
                SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'HR18_SUBMISSION_DISPATCH_IDENTITY_IMMUTABLE';
            END IF;
            IF NOT (
                (OLD.status IN ('QUEUED', 'RETRY_WAIT', 'LEASED') AND NEW.status = 'LEASED')
                OR (OLD.status = 'LEASED' AND NEW.status IN ('RETRY_WAIT', 'SUBMITTED', 'DEAD'))
                OR (OLD.status = 'SUBMITTED' AND NEW.status IN ('ACCEPTED', 'REJECTED'))
            ) THEN
                SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'HR18_SUBMISSION_DISPATCH_STATE_INVALID';
            END IF;
        END
        """
    )
    schema_editor.execute(
        """
        CREATE TRIGGER hr18_submission_attempt_guard_insert
        BEFORE INSERT ON hr18_submission_dispatch_attempt
        FOR EACH ROW
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM hr18_submission_dispatch_job j
                WHERE j.id = NEW.job_id
                  AND j.tenant_id = NEW.tenant_id
                  AND j.idempotency_key = NEW.idempotency_key
                  AND j.attempt_count = NEW.attempt_no
            ) THEN
                SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'HR18_SUBMISSION_DISPATCH_ATTEMPT_PARENT_MISMATCH';
            END IF;
        END
        """
    )
    schema_editor.execute(
        """
        CREATE TRIGGER hr18_submission_event_guard_insert
        BEFORE INSERT ON hr18_submission_dispatch_event
        FOR EACH ROW
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM hr18_submission_dispatch_job j
                JOIN hr18_submission_snapshot s ON s.id = j.submission_id
                WHERE j.id = NEW.job_id
                  AND s.id = NEW.submission_id
                  AND j.tenant_id = NEW.tenant_id
                  AND s.tenant_id = NEW.tenant_id
            ) THEN
                SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'HR18_SUBMISSION_EVENT_PARENT_MISMATCH';
            END IF;
        END
        """
    )
    schema_editor.execute(
        """
        CREATE TRIGGER hr18_submission_dispatch_job_no_delete
        BEFORE DELETE ON hr18_submission_dispatch_job
        FOR EACH ROW
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'HR18_SUBMISSION_DISPATCH_IMMUTABLE'
        """
    )
    schema_editor.execute(
        """
        CREATE TRIGGER hr18_submission_receipt_guard_insert
        BEFORE INSERT ON hr18_submission_trusted_receipt
        FOR EACH ROW
        BEGIN
            IF NEW.outcome NOT IN ('ACCEPTED', 'REJECTED')
               OR NEW.receipt_hash NOT REGEXP '^[0-9a-f]{64}$'
               OR NEW.payload_hash NOT REGEXP '^[0-9a-f]{64}$'
               OR NEW.signature_key_id = ''
               OR NOT EXISTS (
                    SELECT 1
                    FROM hr18_submission_dispatch_job j
                    JOIN hr18_submission_snapshot s ON s.id = j.submission_id
                    WHERE j.id = NEW.job_id
                      AND s.id = NEW.submission_id
                      AND j.tenant_id = NEW.tenant_id
                      AND s.tenant_id = NEW.tenant_id
                      AND j.status = 'SUBMITTED'
                      AND s.status = 'SUBMITTED'
                      AND j.provider_key = NEW.provider_key
                      AND j.schema_version = NEW.schema_version
                      AND j.definition_version = NEW.definition_version
                      AND j.payload_hash = NEW.payload_hash
                      AND j.dispatch_ref = NEW.dispatch_ref
               ) THEN
                SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'HR18_SUBMISSION_RECEIPT_UNTRUSTED_OR_MISMATCH';
            END IF;
        END
        """
    )


def remove_mysql_submission_dispatch_seals(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    for table in APPEND_ONLY_TABLES:
        schema_editor.execute(f"DROP TRIGGER IF EXISTS {table}_no_update")
        schema_editor.execute(f"DROP TRIGGER IF EXISTS {table}_no_delete")
    schema_editor.execute("DROP TRIGGER IF EXISTS hr18_submission_dispatch_job_guard")
    schema_editor.execute("DROP TRIGGER IF EXISTS hr18_submission_dispatch_job_no_delete")
    schema_editor.execute("DROP TRIGGER IF EXISTS hr18_submission_dispatch_job_guard_insert")
    schema_editor.execute("DROP TRIGGER IF EXISTS hr18_submission_attempt_guard_insert")
    schema_editor.execute("DROP TRIGGER IF EXISTS hr18_submission_event_guard_insert")
    schema_editor.execute("DROP TRIGGER IF EXISTS hr18_submission_receipt_guard_insert")


class Migration(migrations.Migration):

    # MySQL trigger DDL commits implicitly.
    atomic = False

    dependencies = [
        ('hr_data', '0014_evidence_database_seals'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionDispatchJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('provider_key', models.CharField(max_length=64)),
                ('schema_version', models.CharField(max_length=32)),
                ('definition_version', models.PositiveIntegerField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('request_hash', models.CharField(max_length=64)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('LEASED', 'Leased'), ('RETRY_WAIT', 'Waiting to retry'), ('SUBMITTED', 'Provider confirmed dispatch'), ('ACCEPTED', 'Trusted receipt accepted'), ('REJECTED', 'Trusted receipt rejected'), ('DEAD', 'Terminal dispatch failure')], db_index=True, default='QUEUED', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('dispatch_ref', models.CharField(blank=True, default='', max_length=255)),
                ('provider_version', models.CharField(blank=True, default='', max_length=64)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_job', to='hr_data.submissionsnapshot')),
            ],
            options={
                'db_table': 'hr18_submission_dispatch_job',
            },
        ),
        migrations.CreateModel(
            name='SubmissionDispatchEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('event_type', models.CharField(max_length=64)),
                ('event_key', models.CharField(max_length=160)),
                ('event_hash', models.CharField(max_length=64)),
                ('occurred_at', models.DateTimeField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_events', to='hr_data.submissionsnapshot')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='hr_data.submissiondispatchjob')),
            ],
            options={
                'db_table': 'hr18_submission_dispatch_event',
            },
        ),
        migrations.CreateModel(
            name='SubmissionDispatchAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('attempt_no', models.PositiveIntegerField()),
                ('idempotency_key', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('DISPATCHED', 'Trusted adapter dispatched'), ('RETRYABLE_FAILURE', 'Retryable failure'), ('TERMINAL_FAILURE', 'Terminal failure')], max_length=24)),
                ('provider_version', models.CharField(blank=True, default='', max_length=64)),
                ('dispatch_ref', models.CharField(blank=True, default='', max_length=255)),
                ('response_hash', models.CharField(blank=True, default='', max_length=64)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='hr_data.submissiondispatchjob')),
            ],
            options={
                'db_table': 'hr18_submission_dispatch_attempt',
            },
        ),
        migrations.CreateModel(
            name='SubmissionTrustedReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('provider_key', models.CharField(max_length=64)),
                ('provider_version', models.CharField(max_length=64)),
                ('schema_version', models.CharField(max_length=32)),
                ('definition_version', models.PositiveIntegerField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('dispatch_ref', models.CharField(max_length=255)),
                ('receipt_ref', models.CharField(max_length=255)),
                ('outcome', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], max_length=16)),
                ('receipt_hash', models.CharField(max_length=64)),
                ('signature_key_id', models.CharField(blank=True, default='', max_length=128)),
                ('received_at', models.DateTimeField()),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='trusted_receipt', to='hr_data.submissiondispatchjob')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='trusted_receipt', to='hr_data.submissionsnapshot')),
            ],
            options={
                'db_table': 'hr18_submission_trusted_receipt',
            },
        ),
        migrations.AddIndex(
            model_name='submissiondispatchjob',
            index=models.Index(fields=['tenant_id', 'status', 'next_attempt_at'], name='idx_hr18_sub_dispatch_due'),
        ),
        migrations.AddConstraint(
            model_name='submissiondispatchjob',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'submission_id'), name='uq_hr18_submission_dispatch_submission'),
        ),
        migrations.AddConstraint(
            model_name='submissiondispatchjob',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'idempotency_key'), name='uq_hr18_submission_dispatch_idem'),
        ),
        migrations.AddConstraint(
            model_name='submissiondispatchevent',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'event_key'), name='uq_hr18_submission_event_key'),
        ),
        migrations.AddConstraint(
            model_name='submissiondispatchattempt',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'job_id', 'attempt_no'), name='uq_hr18_submission_dispatch_attempt'),
        ),
        migrations.AddConstraint(
            model_name='submissiontrustedreceipt',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'receipt_ref'), name='uq_hr18_submission_receipt_ref'),
        ),
        migrations.RunPython(
            install_mysql_submission_dispatch_seals,
            remove_mysql_submission_dispatch_seals,
        ),
    ]
