# Generated by Django 5.2 on 2026-08-09 (HR08-S6 hand-written, model-aligned)

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_external", "0004_industry"),
    ]

    operations = [
        migrations.CreateModel(
            name="HrExternalAcademicIdentity",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.BigIntegerField(db_index=True)),
                ("external_teacher_no", models.CharField(max_length=32)),
                ("academic_teacher_id", models.CharField(blank=True, default="", max_length=64)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("ACTIVE", "Active"), ("SUSPENDED", "Suspended"), ("EXPIRED", "Expired"), ("REVOKED", "Revoked")], db_index=True, default="PENDING", max_length=16)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("drift_note", models.CharField(blank=True, default="", max_length=512)),
                ("version", models.BigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("engagement_id", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="academic_identities", to="hr_external.hrexternalengagement")),
            ],
            options={
                "verbose_name": "HR External Academic Identity",
                "verbose_name_plural": "HR External Academic Identities",
            },
        ),
        migrations.AddConstraint(
            model_name="hrexternalacademicidentity",
            constraint=models.UniqueConstraint(fields=("tenant_id", "engagement_id"), name="uniq_hr_external_academic_eng"),
        ),
        migrations.AddConstraint(
            model_name="hrexternalacademicidentity",
            constraint=models.CheckConstraint(condition=models.Q(("version__gte", 1)), name="hr_external_academic_version_gte_1"),
        ),
        migrations.AddIndex(
            model_name="hrexternalacademicidentity",
            index=models.Index(fields=["tenant_id", "status"], name="hr_external_academic_status_idx"),
        ),
        migrations.AddIndex(
            model_name="hrexternalacademicidentity",
            index=models.Index(fields=["tenant_id", "academic_teacher_id"], name="hr_external_academic_teacher_idx"),
        ),
    ]
