# Generated by Django 5.2 on 2026-08-09 (HR08-S7 hand-written, model-aligned)

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_external", "0005_academic_identity"),
    ]

    operations = [
        migrations.CreateModel(
            name="HrExternalTaskPlan",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.BigIntegerField(db_index=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField(blank=True, null=True)),
                ("plan_version", models.PositiveIntegerField(default=1)),
                ("status", models.CharField(default="DRAFT", max_length=16)),
                ("approved_by", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("engagement_id", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="task_plans", to="hr_external.hrexternalengagement")),
            ],
            options={
                "verbose_name": "HR External Task Plan",
                "verbose_name_plural": "HR External Task Plans",
            },
        ),
        migrations.CreateModel(
            name="HrExternalServiceTask",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.BigIntegerField(db_index=True)),
                ("task_type", models.CharField(max_length=40)),
                ("source_domain", models.CharField(choices=[("ACADEMIC", "Academic"), ("HR08", "HR08"), ("LEGACY_IMPORT", "Legacy Import"), ("OTHER", "Other")], default="HR08", max_length=24)),
                ("source_object_type", models.CharField(blank=True, choices=[("TEACHING_ASSIGNMENT", "Teaching Assignment"), ("COURSE_DELIVERY", "Course Delivery"), ("TEACHING_EVALUATION", "Teaching Evaluation"), ("SERVICE_TASK", "Service Task"), ("OTHER", "Other")], default="", max_length=32)),
                ("source_object_id", models.CharField(blank=True, default="", max_length=64)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, default="")),
                ("planned_quantity", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("planned_unit", models.CharField(blank=True, default="", max_length=32)),
                ("planned_start", models.DateField()),
                ("planned_end", models.DateField(blank=True, null=True)),
                ("owner_org_id", models.BigIntegerField(db_index=True)),
                ("reviewer_id", models.BigIntegerField(blank=True, null=True)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("ASSIGNED", "Assigned"), ("ACCEPTED", "Accepted"), ("IN_PROGRESS", "In Progress"), ("SUBMITTED", "Submitted"), ("UNDER_REVIEW", "Under Review"), ("COMPLETED", "Completed"), ("REJECTED_FOR_CORRECTION", "Rejected For Correction"), ("CANCELLED", "Cancelled")], db_index=True, default="DRAFT", max_length=24)),
                ("acceptance", models.CharField(choices=[("PENDING", "Pending"), ("ACCEPTED", "Accepted"), ("REQUEST_CLARIFICATION", "Request Clarification"), ("DECLINED_WITH_REASON", "Declined With Reason")], default="PENDING", max_length=24)),
                ("settlement_eligible", models.BooleanField(default=False)),
                ("version", models.BigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assignment_id", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="service_tasks", to="hr_external.hrexternalengagementassignment")),
                ("engagement_id", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="service_tasks", to="hr_external.hrexternalengagement")),
            ],
            options={
                "verbose_name": "HR External Service Task",
                "verbose_name_plural": "HR External Service Tasks",
            },
        ),
        migrations.CreateModel(
            name="HrExternalTaskEvidence",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.BigIntegerField(db_index=True)),
                ("evidence_type", models.CharField(max_length=40)),
                ("document_id", models.CharField(blank=True, default="", max_length=64)),
                ("submitted_by", models.BigIntegerField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("verified_by", models.BigIntegerField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="UPLOADED", max_length=24)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("task_id", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="evidences", to="hr_external.hrexternalservicetask")),
            ],
            options={
                "verbose_name": "HR External Task Evidence",
                "verbose_name_plural": "HR External Task Evidences",
            },
        ),
        migrations.CreateModel(
            name="HrExternalWorkloadRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.BigIntegerField(db_index=True)),
                ("source", models.CharField(choices=[("ACADEMIC_VERIFIED", "Academic Verified"), ("SYSTEM_CALCULATED", "System Calculated"), ("MANUAL_WITH_EVIDENCE", "Manual With Evidence"), ("IMPORT_VERIFIED", "Import Verified")], default="SYSTEM_CALCULATED", max_length=32)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("unit", models.CharField(blank=True, default="", max_length=32)),
                ("service_date", models.DateField()),
                ("verification_status", models.CharField(choices=[("UNVERIFIED", "Unverified"), ("PENDING", "Pending"), ("VERIFIED", "Verified"), ("REJECTED", "Rejected")], default="UNVERIFIED", max_length=16)),
                ("settlement_status", models.CharField(choices=[("NOT_ELIGIBLE", "Not Eligible"), ("PENDING", "Pending"), ("READY", "Ready"), ("VERIFIED", "Verified"), ("LOCKED", "Locked")], default="NOT_ELIGIBLE", max_length=16)),
                ("verified_by", models.BigIntegerField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.BigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("engagement_id", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="workload_records", to="hr_external.hrexternalengagement")),
                ("task_id", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="workload_records", to="hr_external.hrexternalservicetask")),
            ],
            options={
                "verbose_name": "HR External Workload Record",
                "verbose_name_plural": "HR External Workload Records",
            },
        ),
        migrations.CreateModel(
            name="HrExternalSettlementBasis",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.BigIntegerField(db_index=True)),
                ("period", models.CharField(max_length=64)),
                ("verified_workload", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("eligible_items", models.JSONField(blank=True, default=list)),
                ("policy_ref", models.CharField(blank=True, default="", max_length=64)),
                ("status", models.CharField(choices=[("NOT_ELIGIBLE", "Not Eligible"), ("PENDING", "Pending"), ("READY", "Ready"), ("VERIFIED", "Verified"), ("LOCKED", "Locked")], default="PENDING", max_length=16)),
                ("version", models.BigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("engagement_id", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="settlement_bases", to="hr_external.hrexternalengagement")),
            ],
            options={
                "verbose_name": "HR External Settlement Basis",
                "verbose_name_plural": "HR External Settlement Bases",
            },
        ),
        migrations.AddConstraint(
            model_name="hrexternaltaskplan",
            constraint=models.UniqueConstraint(fields=("engagement_id", "plan_version"), name="uniq_hr_external_task_plan_version"),
        ),
        migrations.AddIndex(
            model_name="hrexternaltaskplan",
            index=models.Index(fields=["tenant_id", "engagement_id"], name="hr_external_task_plan_eng_idx"),
        ),
        migrations.AddConstraint(
            model_name="hrexternalservicetask",
            constraint=models.CheckConstraint(condition=models.Q(("planned_end__isnull", True), models.Q(("planned_start__lt", models.F("planned_end"))), _connector="OR"), name="hr_external_task_dates_valid"),
        ),
        migrations.AddConstraint(
            model_name="hrexternalservicetask",
            constraint=models.CheckConstraint(condition=models.Q(("version__gte", 1)), name="hr_external_task_version_gte_1"),
        ),
        migrations.AddIndex(
            model_name="hrexternalservicetask",
            index=models.Index(fields=["tenant_id", "engagement_id", "task_type", "status"], name="hr_external_task_eng_type_status_idx"),
        ),
        migrations.AddIndex(
            model_name="hrexternalservicetask",
            index=models.Index(fields=["tenant_id", "owner_org_id", "status"], name="hr_external_task_org_status_idx"),
        ),
        migrations.AddIndex(
            model_name="hrexternaltaskevidence",
            index=models.Index(fields=["tenant_id", "task_id"], name="hr_external_evidence_task_idx"),
        ),
        migrations.AddConstraint(
            model_name="hrexternalworkloadrecord",
            constraint=models.CheckConstraint(condition=models.Q(("version__gte", 1)), name="hr_external_workload_version_gte_1"),
        ),
        migrations.AddIndex(
            model_name="hrexternalworkloadrecord",
            index=models.Index(fields=["tenant_id", "engagement_id", "service_date"], name="hr_external_workload_eng_date_idx"),
        ),
        migrations.AddIndex(
            model_name="hrexternalworkloadrecord",
            index=models.Index(fields=["tenant_id", "verification_status"], name="hr_external_workload_ver_idx"),
        ),
        migrations.AddConstraint(
            model_name="hrexternalsettlementbasis",
            constraint=models.UniqueConstraint(fields=("tenant_id", "engagement_id", "period"), name="uniq_hr_external_settlement_period"),
        ),
        migrations.AddConstraint(
            model_name="hrexternalsettlementbasis",
            constraint=models.CheckConstraint(condition=models.Q(("version__gte", 1)), name="hr_external_settlement_version_gte_1"),
        ),
    ]
