# Generated by Django 5.2 on 2026-08-09 (HR08-S9 hand-written, model-aligned)

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_external", "0007_renewal_exit"),
    ]

    operations = [
        migrations.CreateModel(
            name="HrExternalProjectionState",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.BigIntegerField(db_index=True)),
                ("worker_kind", models.CharField(default="EXTERNAL", max_length=16)),
                ("regular_employee", models.BooleanField(default=False)),
                ("benefits_eligible", models.BooleanField(default=False)),
                ("payroll_regular", models.BooleanField(default=False)),
                ("attendance_regular", models.BooleanField(default=False)),
                ("legacy_employee_id", models.BigIntegerField(blank=True, db_index=True, null=True)),
                ("legacy_badge_id", models.CharField(blank=True, default="", max_length=64)),
                ("projection_hash", models.CharField(blank=True, default="", max_length=64)),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("LEGACY_EMPLOYEE_MISSING", "Legacy Employee Missing"), ("DRIFT", "Drift"), ("SUPERSEDED", "Superseded")], default="ACTIVE", max_length=32)),
                ("last_projected_at", models.DateTimeField(blank=True, null=True)),
                ("last_reconciled_at", models.DateTimeField(blank=True, null=True)),
                ("mismatch_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_profile_id", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="projection_states", to="hr_external.hrexternalteacherprofile")),
            ],
            options={
                "verbose_name": "HR External Projection State",
                "verbose_name_plural": "HR External Projection States",
            },
        ),
        migrations.AddConstraint(
            model_name="hrexternalprojectionstate",
            constraint=models.UniqueConstraint(fields=("tenant_id", "external_profile_id"), name="uniq_hr_external_projection_profile"),
        ),
        migrations.AddIndex(
            model_name="hrexternalprojectionstate",
            index=models.Index(fields=["tenant_id", "status"], name="hr_external_projection_status_idx"),
        ),
        migrations.AddIndex(
            model_name="hrexternalprojectionstate",
            index=models.Index(fields=["tenant_id", "legacy_employee_id"], name="hr_external_projection_legacy_idx"),
        ),
    ]
