# Generated by Django 5.2 on 2026-08-09 (HR08-B6 hand-written, model-aligned)

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_external", "0010_materials"),
    ]

    operations = [
        migrations.CreateModel(
            name="HrExternalPortalToken",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.BigIntegerField(db_index=True)),
                ("token_hash", models.CharField(db_index=True, max_length=64, unique=True)),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("EXPIRED", "Expired"), ("REVOKED", "Revoked")], default="ACTIVE", max_length=16)),
                ("expires_at", models.DateTimeField()),
                ("issued_by", models.BigIntegerField(blank=True, null=True)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("external_profile_id", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="portal_tokens", to="hr_external.hrexternalteacherprofile")),
            ],
            options={
                "verbose_name": "HR External Portal Token",
                "verbose_name_plural": "HR External Portal Tokens",
            },
        ),
        migrations.AddIndex(
            model_name="hrexternalportaltoken",
            index=models.Index(fields=["tenant_id", "external_profile_id", "status"], name="hr_external_portal_token_profile_idx"),
        ),
    ]
