# Generated by Django 5.2 on 2026-08-09 (HR08-复审 hand-written, model-aligned)
# 补：HrExternalMaterial 增加 version 字段与 version>=1 CheckConstraint（§118 一致性）

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_external", "0012_task_evidence_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="hrexternalmaterial",
            name="version",
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name="hrexternalmaterial",
            constraint=models.CheckConstraint(condition=models.Q(("version__gte", 1)), name="hr_external_material_version_gte_1"),
        ),
    ]
