# Generated by Django 5.2 on 2026-08-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_qualification', '0003_alter_hrdoubleteacherevidenceitem_package_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrdoubleteacherrule',
            name='dimension_code',
            field=models.CharField(choices=[('ETHICS_AND_CONDUCT', 'Ethics and Conduct'), ('TEACHING_ABILITY', 'Teaching Ability'), ('PRACTICAL_TEACHING', 'Practical Teaching'), ('TEACHING_RESEARCH', 'Teaching Research'), ('PROGRAM_DEVELOPMENT', 'Program Development'), ('ENTERPRISE_EXPERIENCE', 'Enterprise Experience'), ('INDUSTRY_PRACTICE', 'Industry Practice'), ('PROFESSIONAL_SKILL', 'Professional Skill'), ('VOCATIONAL_CERTIFICATE', 'Vocational Certificate'), ('NON_TEACHER_PROFESSIONAL_TITLE', 'Non-Teacher Professional Title'), ('TECHNICAL_INNOVATION', 'Technical Innovation'), ('RESULT_TRANSFORMATION', 'Result Transformation'), ('TEACHING_AWARD', 'Teaching Award'), ('SKILL_COMPETITION', 'Skill Competition'), ('STUDENT_COMPETITION_GUIDANCE', 'Student Competition Guidance'), ('TEAM_LEADERSHIP', 'Team Leadership'), ('TEACHER_DEVELOPMENT_CONTRIBUTION', 'Teacher Development Contribution'), ('INDUSTRY_IMPACT', 'Industry Impact'), ('OTHER_EQUIVALENT_CAPABILITY', 'Other Equivalent Capability'), ('PROFESSIONAL_KNOWLEDGE', 'Professional Knowledge'), ('VOCATIONAL_CERTIFICATE_OR_EQUIV', 'Vocational Certificate or Equivalent'), ('INTERMEDIATE_SKILL_OR_EQUIV', 'Intermediate Skill or Equivalent'), ('SENIOR_SKILL_OR_EQUIV', 'Senior Skill or Equivalent')], default='TEACHING_ABILITY', max_length=48),
        ),
    ]
