# Generated by Django 5.2 on 2026-08-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_structure', '0002_hrpositionreservation_uniq_hr_reservation_position_biz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hr02AuthorityCutover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(unique=True)),
                ('mode', models.CharField(choices=[('LEGACY_STRUCTURE_ONLY', 'Legacy Structure Only'), ('DUAL_READ_COMPARE', 'Dual Read Compare'), ('HR02_AUTHORITY', 'HR02 Authority')], default='LEGACY_STRUCTURE_ONLY', max_length=32)),
                ('cutover_at', models.DateTimeField(auto_now=True)),
                ('operator', models.CharField(blank=True, default='', max_length=128)),
                ('old_mode', models.CharField(blank=True, default='', max_length=32)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('reconcile_report_id', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'verbose_name': 'HR02 Authority Cutover',
                'verbose_name_plural': 'HR02 Authority Cutovers',
            },
        ),
    ]
