# Generated by Django 5.2 on 2026-08-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_structure', '0004_alter_hrpositionreservation_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hrpostcatalogversion',
            constraint=models.UniqueConstraint(fields=('catalog_id', 'version_no'), name='uniq_hr_catalog_version_no'),
        ),
    ]
