# Generated by Django 5.2 on 2026-08-09 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_structure', '0005_hrpostcatalogversion_uniq_hr_catalog_version_no'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hrorganizationversion',
            constraint=models.UniqueConstraint(fields=('organization_id', 'version_no'), name='uniq_hr_org_version_no'),
        ),
    ]
