# Generated by Django 5.2 on 2026-09-03 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_alter_timesheet_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timesheet",
            options={
                "ordering": ("-id",),
                "verbose_name": "Timesheet",
                "verbose_name_plural": "Timesheets",
            },
        ),
    ]
