# Generated by Django 5.2 on 2026-08-08 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HrAlertInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('alert_key', models.CharField(max_length=64)),
                ('source_domain', models.CharField(max_length=64)),
                ('source_object_type', models.CharField(blank=True, default='', max_length=64)),
                ('source_object_id', models.CharField(blank=True, default='', max_length=64)),
                ('dedupe_key', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Info')], default='MEDIUM', max_length=16)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('SNOOZED', 'Snoozed'), ('RESOLVED', 'Resolved'), ('EXPIRED', 'Expired')], db_index=True, default='OPEN', max_length=16)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('owner_role', models.CharField(blank=True, default='', max_length=64)),
                ('owner_user_id', models.BigIntegerField(blank=True, null=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'HR Alert Instance',
                'verbose_name_plural': 'HR Alert Instances',
                'indexes': [models.Index(fields=['tenant_id', 'status', 'severity'], name='hr_control__tenant__a587da_idx'), models.Index(fields=['tenant_id', 'due_at'], name='hr_control__tenant__07d135_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['OPEN', 'ACKNOWLEDGED', 'SNOOZED'])), fields=('tenant_id', 'dedupe_key', 'status'), name='uniq_hr_alert_open_dedupe')],
            },
        ),
        migrations.CreateModel(
            name='HrAuthorityCutover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('domain', models.CharField(choices=[('ORGANIZATION', 'Organization'), ('STAFF', 'Staff')], max_length=32)),
                ('mode', models.CharField(choices=[('LEGACY_ONLY', 'Legacy Only'), ('DUAL_READ_COMPARE', 'Dual Read Compare'), ('AUTHORITY_ONLY', 'Authority Only')], default='LEGACY_ONLY', max_length=32)),
                ('cutover_at', models.DateTimeField(auto_now=True)),
                ('cutover_by', models.CharField(blank=True, default='', max_length=128)),
                ('reason', models.CharField(max_length=255)),
                ('source_snapshot_hash', models.CharField(blank=True, default='', max_length=64)),
                ('mapping_version', models.CharField(blank=True, default='DRAFT_V1', max_length=32)),
                ('verification_report_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'HR Authority Cutover',
                'verbose_name_plural': 'HR Authority Cutovers',
                'unique_together': {('tenant_id', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='HrDashboardPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('user_id', models.BigIntegerField()),
                ('pinned_metric_keys', models.JSONField(blank=True, default=list)),
                ('quick_action_keys', models.JSONField(blank=True, default=list)),
                ('default_period', models.CharField(blank=True, default='month', max_length=16)),
                ('layout_version', models.CharField(default='1', max_length=8)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'HR Dashboard Preference',
                'verbose_name_plural': 'HR Dashboard Preferences',
                'unique_together': {('tenant_id', 'user_id')},
            },
        ),
    ]
