# Generated by Django 5.2 on 2026-08-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_control_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrControlCenterPermissionMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('hr.dashboard.view', 'HR Dashboard: View'), ('hr.dashboard.overview.view', 'HR Dashboard: View Overview'), ('hr.dashboard.todo.view', 'HR Dashboard: View Todos'), ('hr.dashboard.todo.supervise', 'HR Dashboard: Supervise Todos'), ('hr.dashboard.alert.view', 'HR Dashboard: View Alerts'), ('hr.dashboard.alert.manage', 'HR Dashboard: Manage Alerts'), ('hr.dashboard.workforce.view', 'HR Dashboard: View Workforce'), ('hr.dashboard.workforce.drilldown', 'HR Dashboard: Workforce Drilldown'), ('hr.dashboard.quick_action.use', 'HR Dashboard: Use Quick Actions'), ('hr.dashboard.export', 'HR Dashboard: Export'), ('hr.dashboard.sensitive_metrics.view', 'HR Dashboard: View Sensitive Metrics')),
                'managed': False,
            },
        ),
    ]
