# Generated by Django 5.2 on 2026-09-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_control_center', '0003_active_alert_unique_backstop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrauthoritycutover',
            name='domain',
            field=models.CharField(choices=[('ORGANIZATION', 'Organization'), ('STAFF', 'Staff'), ('ASSESSMENT', 'Assessment')], max_length=32),
        ),
    ]
