# Generated by Django 5.2 on 2026-08-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_staff', '0002_hremploymentrelationship_hrstaffassignment_and_more'),
        ('hr_structure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hrstaffassignment',
            name='chk_hr_assignment_effective_to_gt_from',
        ),
        migrations.AddConstraint(
            model_name='hrstaffassignment',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), ('status', 'CANCELLED'), _connector='OR'), name='chk_hr_assignment_effective_to_gt_from'),
        ),
    ]
