# Generated by Django 5.2 on 2026-08-08 16:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_staff', '0004_hrcredential_hrdegreerecord_hreducationexperience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrStaffMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('category_code', models.CharField(choices=[('IDENTITY', 'Identity'), ('EDUCATION', 'Education'), ('DEGREE', 'Degree'), ('TEACHER_QUALIFICATION', 'Teacher Qualification'), ('PROFESSIONAL_CERTIFICATE', 'Professional Certificate'), ('SKILL_CERTIFICATE', 'Skill Certificate'), ('EMPLOYMENT', 'Employment'), ('APPOINTMENT', 'Appointment'), ('CONTRACT_REFERENCE', 'Contract Reference'), ('HONOR', 'Honor'), ('CORRECTION_EVIDENCE', 'Correction Evidence'), ('OTHER_HR', 'Other HR')], default='OTHER_HR', max_length=32)),
                ('title', models.CharField(max_length=250)),
                ('sensitivity_level', models.CharField(choices=[('PUBLIC_HR', 'Public HR'), ('RESTRICTED_HR', 'Restricted HR'), ('SENSITIVE', 'Sensitive'), ('HIGH_SENSITIVE', 'High Sensitive')], default='RESTRICTED_HR', max_length=16)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='UNVERIFIED', max_length=16)),
                ('current_version_id', models.UUIDField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='', max_length=32)),
                ('related_fact_type', models.CharField(blank=True, default='', max_length=32)),
                ('related_fact_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='hr_staff.hrstaffmaster')),
            ],
            options={
                'verbose_name': 'HR Staff Material',
                'verbose_name_plural': 'HR Staff Materials',
            },
        ),
        migrations.CreateModel(
            name='HrStaffMaterialVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('storage_file_id', models.CharField(blank=True, default='', max_length=255)),
                ('legacy_document_id', models.BigIntegerField(blank=True, null=True)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=64)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('uploaded_by', models.BigIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by', models.BigIntegerField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('replaced_by_version_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CURRENT', 'Current'), ('REPLACED', 'Replaced'), ('VOID', 'Void'), ('RETIRED', 'Retired')], default='CURRENT', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='hr_staff.hrstaffmaterial')),
            ],
            options={
                'verbose_name': 'HR Staff Material Version',
                'verbose_name_plural': 'HR Staff Material Versions',
            },
        ),
        migrations.CreateModel(
            name='HrMaterialRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('request_type', models.CharField(blank=True, default='', max_length=32)),
                ('required_category_code', models.CharField(blank=True, choices=[('IDENTITY', 'Identity'), ('EDUCATION', 'Education'), ('DEGREE', 'Degree'), ('TEACHER_QUALIFICATION', 'Teacher Qualification'), ('PROFESSIONAL_CERTIFICATE', 'Professional Certificate'), ('SKILL_CERTIFICATE', 'Skill Certificate'), ('EMPLOYMENT', 'Employment'), ('APPOINTMENT', 'Appointment'), ('CONTRACT_REFERENCE', 'Contract Reference'), ('HONOR', 'Honor'), ('CORRECTION_EVIDENCE', 'Correction Evidence'), ('OTHER_HR', 'Other HR')], default='', max_length=32)),
                ('due_at', models.DateField(blank=True, null=True)),
                ('instruction', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=16)),
                ('requested_by', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_staff_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_requests', to='hr_staff.hrstaffmaster')),
            ],
            options={
                'verbose_name': 'HR Material Request',
                'verbose_name_plural': 'HR Material Requests',
                'indexes': [models.Index(fields=['tenant_id', 'target_staff_id', 'status'], name='hr_staff_hr_tenant__1286a9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='hrstaffmaterial',
            index=models.Index(fields=['tenant_id', 'staff_id', 'category_code'], name='hr_staff_hr_tenant__5d4e76_idx'),
        ),
        migrations.AddIndex(
            model_name='hrstaffmaterial',
            index=models.Index(fields=['tenant_id', 'verification_status'], name='hr_staff_hr_tenant__01d6ca_idx'),
        ),
        migrations.AddIndex(
            model_name='hrstaffmaterialversion',
            index=models.Index(fields=['tenant_id', 'material_id', 'version_no'], name='hr_staff_hr_tenant__41e0e3_idx'),
        ),
        migrations.AddIndex(
            model_name='hrstaffmaterialversion',
            index=models.Index(fields=['tenant_id', 'sha256'], name='hr_staff_hr_tenant__fadb0e_idx'),
        ),
        migrations.AddIndex(
            model_name='hrstaffmaterialversion',
            index=models.Index(fields=['tenant_id', 'expiry_date'], name='hr_staff_hr_tenant__4203c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='hrstaffmaterialversion',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'material_id', 'version_no'), name='uniq_hr_material_version_no'),
        ),
    ]
