# Generated by Django 5.2 on 2026-08-08 17:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_staff', '0006_hrcorrectioncase_hrcorrectionitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrBusinessEventInbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('event_type', models.CharField(max_length=64)),
                ('source_business_type', models.CharField(max_length=64)),
                ('source_business_id', models.CharField(max_length=64)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSING', 'Processing'), ('CONSUMED', 'Consumed'), ('FAILED', 'Failed')], default='RECEIVED', max_length=16)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, default='', max_length=512)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'HR Business Event Inbox',
                'verbose_name_plural': 'HR Business Event Inboxes',
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='hr_staff_hr_tenant__5f0d2d_idx'), models.Index(fields=['tenant_id', 'source_business_type', 'source_business_id'], name='hr_staff_hr_tenant__d95cbd_idx')],
            },
        ),
        migrations.CreateModel(
            name='HrOutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed'), ('DEAD', 'Dead')], db_index=True, default='PENDING', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, default='', max_length=512)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'HR Outbox Event',
                'verbose_name_plural': 'HR Outbox Events',
                'indexes': [models.Index(fields=['tenant_id', 'status', 'created_at'], name='hr_staff_hr_tenant__2eeebc_idx'), models.Index(fields=['tenant_id', 'event_type', 'correlation_id'], name='hr_staff_hr_tenant__1464c8_idx')],
            },
        ),
    ]
