# Generated by Django 5.2 on 2026-08-08 23:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_staff', '0008_hrstaffpermissionmeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('template_key', models.CharField(max_length=64)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VALIDATING', 'Validating'), ('VALIDATION_FAILED', 'Validation Failed'), ('READY_TO_COMMIT', 'Ready to Commit'), ('COMMITTING', 'Committing'), ('COMPLETED', 'Completed'), ('PARTIAL_FAILED', 'Partial Failed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=24)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('error_workbook_path', models.CharField(blank=True, default='', max_length=255)),
                ('committed_by', models.BigIntegerField(blank=True, null=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('checkpoint', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HR Import Job',
                'verbose_name_plural': 'HR Import Jobs',
                'indexes': [models.Index(fields=['tenant_id', 'status', 'created_at'], name='hr_staff_hr_tenant__a49860_idx')],
            },
        ),
        migrations.CreateModel(
            name='HrImportRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('row_no', models.PositiveIntegerField()),
                ('data_json', models.JSONField(blank=True, default=dict)),
                ('is_valid', models.BooleanField(default=True)),
                ('error_summary', models.CharField(blank=True, default='', max_length=512)),
                ('commit_status', models.CharField(default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='hr_staff.hrimportjob')),
            ],
            options={
                'verbose_name': 'HR Import Row',
                'verbose_name_plural': 'HR Import Rows',
            },
        ),
        migrations.CreateModel(
            name='HrImportIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('row_no', models.PositiveIntegerField(default=0)),
                ('field_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_code', models.CharField(max_length=64)),
                ('message', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='hr_staff.hrimportjob')),
                ('row_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='hr_staff.hrimportrow')),
            ],
            options={
                'verbose_name': 'HR Import Issue',
                'verbose_name_plural': 'HR Import Issues',
            },
        ),
        migrations.AddConstraint(
            model_name='hrimportrow',
            constraint=models.UniqueConstraint(fields=('job_id', 'row_no'), name='uniq_hr_import_row_no'),
        ),
    ]
