# Generated by Django 5.2 on 2026-08-08 23:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_staff', '0009_hrimportjob_hrimportrow_hrimportissue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrMaterialDownloadTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('purpose', models.CharField(blank=True, default='', max_length=512)),
                ('issued_by', models.BigIntegerField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('uses', models.PositiveIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'HR Material Download Ticket',
                'verbose_name_plural': 'HR Material Download Tickets',
            },
        ),
        migrations.AlterField(
            model_name='hrcorrectioncase',
            name='case_no',
            field=models.CharField(max_length=32),
        ),
        migrations.AddConstraint(
            model_name='hrcorrectioncase',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'case_no'), name='uniq_hr_correction_tenant_case_no'),
        ),
        migrations.AddField(
            model_name='hrmaterialdownloadticket',
            name='material_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='hr_staff.hrstaffmaterial'),
        ),
        migrations.AddField(
            model_name='hrmaterialdownloadticket',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_tickets', to='hr_staff.hrstaffmaster'),
        ),
        migrations.AddField(
            model_name='hrmaterialdownloadticket',
            name='version_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='hr_staff.hrstaffmaterialversion'),
        ),
        migrations.AddIndex(
            model_name='hrmaterialdownloadticket',
            index=models.Index(fields=['tenant_id', 'expires_at'], name='hr_staff_hr_tenant__d718de_idx'),
        ),
    ]
