# Generated by Django 5.2 on 2026-08-09 12:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_staff', '0011_hrexportjob_hrstaffnumbersequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrPersonMergeCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('case_no', models.CharField(max_length=32)),
                ('reason', models.CharField(max_length=512)),
                ('evidence_material_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('APPLIED', 'Applied'), ('REVERSED', 'Reversed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=16)),
                ('approved_by', models.BigIntegerField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.BigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_person_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merge_source_cases', to='hr_staff.hrperson')),
                ('target_person_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merge_target_cases', to='hr_staff.hrperson')),
            ],
            options={
                'verbose_name': 'HR Person Merge Case',
                'verbose_name_plural': 'HR Person Merge Cases',
            },
        ),
        migrations.CreateModel(
            name='HrPersonMergeAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('source_person_id', models.UUIDField(db_index=True)),
                ('target_person_id', models.UUIDField(db_index=True)),
                ('alias_status', models.CharField(default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merge_case_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='hr_staff.hrpersonmergecase')),
            ],
            options={
                'verbose_name': 'HR Person Merge Alias',
                'verbose_name_plural': 'HR Person Merge Aliases',
            },
        ),
        migrations.AddIndex(
            model_name='hrpersonmergecase',
            index=models.Index(fields=['tenant_id', 'source_person_id'], name='hr_staff_hr_tenant__de21e0_idx'),
        ),
        migrations.AddIndex(
            model_name='hrpersonmergecase',
            index=models.Index(fields=['tenant_id', 'status'], name='hr_staff_hr_tenant__d09c39_idx'),
        ),
        migrations.AddConstraint(
            model_name='hrpersonmergecase',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'case_no'), name='uniq_hr_person_merge_tenant_case_no'),
        ),
        migrations.AddIndex(
            model_name='hrpersonmergealias',
            index=models.Index(fields=['tenant_id', 'source_person_id'], name='hr_staff_hr_tenant__99d991_idx'),
        ),
    ]
