# Generated by Django 5.2 on 2026-08-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_payroll', '0006_payroll_calculation_payment_chain'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrPayrollWorkflowPermissionMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('hr.payroll.rule.manage', 'HR15: Manage salary rule versions'), ('hr.payroll.input.manage', 'HR15: Freeze payroll input snapshots'), ('hr.payroll.calculate', 'HR15: Run payroll calculations'), ('hr.payroll.review', 'HR15: Review payroll calculations'), ('hr.payroll.finalize', 'HR15: Finalize reviewed payroll'), ('hr.payroll.payment', 'HR15: Issue and receive payroll payments'), ('hr.payroll.payslip.view_sensitive', 'HR15: View sensitive payslips'), ('hr.payroll.reconcile', 'HR15: Reconcile payroll with finance')),
                'managed': False,
            },
        ),
    ]
