# Generated by Django 5.2.17 on 2026-09-18 16:49

import uuid
from django.db import migrations, models


def protect_reverse_with_business_data(apps, schema_editor):
    """A rollback cannot silently erase newly accepted payroll/tax facts.

    Empty-schema rehearsal may reverse. Once this feature has data, restore a
    verified backup or use a forward repair, with the school's finance sign-off.
    """
    alias = schema_editor.connection.alias
    names = ("PayrollPolicyVersion", "PayrollStandardVersion", "PayrollBasisVersion",
             "PayrollWorkloadFact", "PayrollTrial", "PayrollTrialApproval",
             "PayrollTaxAccount", "PayrollTaxReservation", "PayrollTaxReceiptSupplement",
             "PayrollRetroApplication", "PayrollImportStage")
    if any(apps.get_model("hr_payroll", name).objects.using(alias).exists() for name in names):
        raise RuntimeError("HR15_V8_ROLLBACK_BLOCKED: new payroll/policy/tax data exists; use verified backup or forward repair")
    if apps.get_model("hr_payroll", "PayrollPeriod").objects.using(alias).exclude(engine_version="LEGACY_V2").exists():
        raise RuntimeError("HR15_V8_ROLLBACK_BLOCKED: a policy-engine period exists")
    if apps.get_model("hr_payroll", "SalaryRuleVersion").objects.using(alias).exclude(pay_group_code="").exists():
        raise RuntimeError("HR15_V8_ROLLBACK_BLOCKED: grouped salary rules exist")


class Migration(migrations.Migration):

    dependencies = [
        ('hr_payroll', '0013_seal_payroll_result_authority'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollBasisVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('evidence_ref', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('DRAFT', '待复核'), ('PUBLISHED', '已生效配置'), ('RETIRED', '已被替代')], db_index=True, default='DRAFT', max_length=16)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('published_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('supersedes_id', models.UUIDField(blank=True, null=True)),
                ('payroll_profile_id', models.UUIDField()),
                ('staff_id', models.UUIDField()),
                ('selectors_json', models.JSONField(blank=True, default=dict)),
                ('variables_json', models.JSONField(blank=True, default=dict)),
                ('tax_deductions_json', models.JSONField(blank=True, default=dict)),
                ('cost_shares_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'hr15_basis_version',
            },
        ),
        migrations.CreateModel(
            name='PayrollImportStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('kind', models.CharField(default='STANDARD', max_length=16)),
                ('file_hash', models.CharField(max_length=64)),
                ('stage_hash', models.CharField(max_length=64)),
                ('rows_json', models.JSONField(blank=True, default=list)),
                ('errors_json', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='PREVIEW', max_length=16)),
                ('applied_ids_json', models.JSONField(blank=True, default=list)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'hr15_policy_import_stage',
            },
        ),
        migrations.CreateModel(
            name='PayrollPolicyScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('scope_key', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'hr15_policy_scope_lock',
            },
        ),
        migrations.CreateModel(
            name='PayrollPolicyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('evidence_ref', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('DRAFT', '待复核'), ('PUBLISHED', '已生效配置'), ('RETIRED', '已被替代')], db_index=True, default='DRAFT', max_length=16)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('published_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('supersedes_id', models.UUIDField(blank=True, null=True)),
                ('pay_group_code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('configuration_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'hr15_policy_version',
            },
        ),
        migrations.CreateModel(
            name='PayrollRetroApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('source_result_id', models.UUIDField()),
                ('trial_id', models.UUIDField()),
                ('adjustment_result_id', models.UUIDField()),
                ('prior_chain_hash', models.CharField(max_length=64)),
                ('delta_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'hr15_retro_application',
            },
        ),
        migrations.CreateModel(
            name='PayrollStandardVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('evidence_ref', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('DRAFT', '待复核'), ('PUBLISHED', '已生效配置'), ('RETIRED', '已被替代')], db_index=True, default='DRAFT', max_length=16)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('published_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('supersedes_id', models.UUIDField(blank=True, null=True)),
                ('pay_group_code', models.CharField(max_length=64)),
                ('table_code', models.CharField(max_length=64)),
                ('level_code', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency_code', models.CharField(default='CNY', max_length=3)),
            ],
            options={
                'db_table': 'hr15_standard_version',
            },
        ),
        migrations.CreateModel(
            name='PayrollTaxAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('withholding_agent_code', models.CharField(max_length=64)),
                ('person_id', models.UUIDField()),
                ('tax_year', models.PositiveIntegerField()),
                ('version_no', models.PositiveIntegerField(default=0)),
                ('totals_json', models.JSONField(blank=True, default=dict)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('pending_result_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hr15_tax_account',
            },
        ),
        migrations.CreateModel(
            name='PayrollTaxReceiptSupplement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('tax_reservation_id', models.UUIDField()),
                ('receipt_json', models.JSONField(default=dict)),
                ('content_hash', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'hr15_tax_receipt_supplement',
            },
        ),
        migrations.CreateModel(
            name='PayrollTaxReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('payroll_result_id', models.UUIDField()),
                ('tax_account_id', models.UUIDField()),
                ('staff_id', models.UUIDField()),
                ('input_json', models.JSONField(blank=True, default=dict)),
                ('quote_json', models.JSONField(blank=True, default=dict)),
                ('content_hash', models.CharField(max_length=64)),
                ('status', models.CharField(default='RESERVED', max_length=16)),
                ('receipt_ref', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'db_table': 'hr15_tax_reservation',
            },
        ),
        migrations.CreateModel(
            name='PayrollTrial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('payroll_period_id', models.UUIDField()),
                ('staff_id', models.UUIDField()),
                ('revision_no', models.PositiveIntegerField()),
                ('idempotency_key', models.CharField(max_length=128)),
                ('purpose', models.CharField(default='NORMAL', max_length=16)),
                ('source_result_id', models.UUIDField(blank=True, null=True)),
                ('input_payload_json', models.JSONField(blank=True, default=dict)),
                ('output_json', models.JSONField(blank=True, default=dict)),
                ('content_hash', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'hr15_trial_revision',
            },
        ),
        migrations.CreateModel(
            name='PayrollTrialApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('trial_id', models.UUIDField()),
                ('trial_hash', models.CharField(max_length=64)),
                ('decision', models.CharField(max_length=16)),
                ('note', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'hr15_trial_approval',
            },
        ),
        migrations.CreateModel(
            name='PayrollWorkloadFact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('evidence_ref', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('DRAFT', '待复核'), ('PUBLISHED', '已生效配置'), ('RETIRED', '已被替代')], db_index=True, default='DRAFT', max_length=16)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('published_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('supersedes_id', models.UUIDField(blank=True, null=True)),
                ('payroll_period_id', models.UUIDField()),
                ('staff_id', models.UUIDField()),
                ('workload_key', models.CharField(max_length=128)),
                ('variable_key', models.CharField(max_length=64)),
                ('units', models.DecimalField(decimal_places=4, max_digits=14)),
                ('share', models.DecimalField(decimal_places=6, max_digits=9)),
                ('coefficient', models.DecimalField(decimal_places=6, max_digits=12)),
            ],
            options={
                'db_table': 'hr15_verified_workload',
            },
        ),
        migrations.RemoveConstraint(
            model_name='payrollinputsnapshot',
            name='uq_hr15_input_period_staff',
        ),
        migrations.RemoveConstraint(
            model_name='salaryruleversion',
            name='uq_hr15_salary_rule_ver',
        ),
        migrations.RemoveConstraint(
            model_name='salaryruleversion',
            name='uq_hr15_salary_item_ver',
        ),
        migrations.AddField(
            model_name='payrollinputsnapshot',
            name='revision_no',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='engine_version',
            field=models.CharField(default='LEGACY_V2', max_length=24),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='payroll_purpose',
            field=models.CharField(default='REGULAR', max_length=16),
        ),
        migrations.AddField(
            model_name='salaryruleversion',
            name='allocation_mode',
            field=models.CharField(default='FULL_PERIOD', max_length=24),
        ),
        migrations.AddField(
            model_name='salaryruleversion',
            name='pay_group_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='payrollcalculationline',
            name='rule_version_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='payrollinputsnapshot',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'payroll_period_id', 'staff_id', 'revision_no'), name='uq_hr15_input_period_staff'),
        ),
        migrations.AddConstraint(
            model_name='salaryruleversion',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'pay_group_code', 'rule_code', 'version_no'), name='uq_hr15_salary_rule_ver'),
        ),
        migrations.AddConstraint(
            model_name='salaryruleversion',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'pay_group_code', 'item_code', 'version_no'), name='uq_hr15_salary_item_ver'),
        ),
        migrations.AddConstraint(
            model_name='payrollbasisversion',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'payroll_profile_id', 'version_no'), name='uq_hr15_basis_version'),
        ),
        migrations.AddConstraint(
            model_name='payrollbasisversion',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='ck_hr15_basis_dates'),
        ),
        migrations.AddConstraint(
            model_name='payrollpolicyscope',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'scope_key'), name='uq_hr15_policy_scope'),
        ),
        migrations.AddConstraint(
            model_name='payrollpolicyversion',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'pay_group_code', 'version_no'), name='uq_hr15_policy_group_version'),
        ),
        migrations.AddConstraint(
            model_name='payrollpolicyversion',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='ck_hr15_policy_dates'),
        ),
        migrations.AddConstraint(
            model_name='payrollretroapplication',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'trial_id'), name='uq_hr15_retro_trial'),
        ),
        migrations.AddConstraint(
            model_name='payrollstandardversion',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'pay_group_code', 'table_code', 'level_code', 'version_no'), name='uq_hr15_standard_version'),
        ),
        migrations.AddConstraint(
            model_name='payrollstandardversion',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='ck_hr15_standard_amount'),
        ),
        migrations.AddConstraint(
            model_name='payrollstandardversion',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='ck_hr15_standard_dates'),
        ),
        migrations.AddConstraint(
            model_name='payrolltaxaccount',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'withholding_agent_code', 'person_id', 'tax_year'), name='uq_hr15_tax_person_year'),
        ),
        migrations.AddConstraint(
            model_name='payrolltaxreceiptsupplement',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'tax_reservation_id'), name='uq_hr15_tax_receipt_supplement'),
        ),
        migrations.AddConstraint(
            model_name='payrolltaxreservation',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'payroll_result_id'), name='uq_hr15_tax_result'),
        ),
        migrations.AddConstraint(
            model_name='payrolltrial',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'payroll_period_id', 'staff_id', 'revision_no'), name='uq_hr15_trial_revision'),
        ),
        migrations.AddConstraint(
            model_name='payrolltrial',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'idempotency_key'), name='uq_hr15_trial_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='payrolltrialapproval',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'trial_id'), name='uq_hr15_trial_approval'),
        ),
        migrations.AddConstraint(
            model_name='payrollworkloadfact',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'payroll_period_id', 'workload_key', 'staff_id', 'version_no'), name='uq_hr15_workload_source'),
        ),
        migrations.AddConstraint(
            model_name='payrollworkloadfact',
            constraint=models.CheckConstraint(condition=models.Q(('units__gte', 0), ('share__gt', 0), ('share__lte', 1), ('coefficient__gte', 0)), name='ck_hr15_workload_values'),
        ),
        migrations.RunPython(migrations.RunPython.noop, reverse_code=protect_reverse_with_business_data),
    ]
