# Generated by Django 5.2 on 2026-08-09 04:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_changes', '0003_hrtemporaryassignmentextension'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrChangeOutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('event_id', models.CharField(max_length=64, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('event_version', models.PositiveIntegerField(default=1)),
                ('aggregate_type', models.CharField(blank=True, default='', max_length=32)),
                ('aggregate_id', models.CharField(blank=True, default='', max_length=64)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('DROPPED', 'Dropped')], db_index=True, default='PENDING', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'HR Change Outbox Event',
                'verbose_name_plural': 'HR Change Outbox Events',
                'indexes': [models.Index(fields=['tenant_id', 'status', 'occurred_at'], name='hr_changes__tenant__e57127_idx')],
            },
        ),
    ]
