# Generated by Django 5.2 on 2026-08-09 05:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_changes', '0004_hrchangeoutboxevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrChangeAuthorityMode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True, unique=True)),
                ('mode', models.CharField(choices=[('LEGACY_ACTIVE', 'Legacy Active'), ('DUAL_READ_COMPARE', 'Dual Read Compare'), ('HR06_AUTHORITY', 'HR06 Authority'), ('LEGACY_READONLY_PROJECTION', 'Legacy Readonly Projection')], default='LEGACY_ACTIVE', max_length=32)),
                ('switched_by', models.BigIntegerField(blank=True, null=True)),
                ('switched_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'HR Change Authority Mode',
                'verbose_name_plural': 'HR Change Authority Modes',
            },
        ),
    ]
