# Generated by Django 5.2 on 2026-08-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_structure', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hrpositionreservation',
            constraint=models.UniqueConstraint(fields=('position_id', 'source_business_id'), name='uniq_hr_reservation_position_biz'),
        ),
        migrations.AddConstraint(
            model_name='hrpositionreservation',
            constraint=models.UniqueConstraint(fields=('position_pool_id', 'source_business_id'), name='uniq_hr_reservation_pool_biz'),
        ),
    ]
