# Generated by Django 5.2 on 2026-08-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_structure', '0003_hr02authoritycutover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrpositionreservation',
            name='idempotency_key',
            field=models.CharField(max_length=128),
        ),
        migrations.AddConstraint(
            model_name='hrpositionreservation',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'idempotency_key'), name='uniq_hr_reservation_tenant_idem'),
        ),
    ]
