# Generated by Django 5.2 on 2026-08-30 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_structure', '0007_hrstructurepermissionmeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrPositionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('position_type', models.CharField(choices=[('REGULAR', 'Regular'), ('TEMP', 'Temp'), ('SPECIAL', 'Special')], default='REGULAR', max_length=16)),
                ('planned_fte', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('max_incumbents', models.PositiveIntegerField(default=1)),
                ('allow_multiple_incumbents', models.BooleanField(default=False)),
                ('lifecycle_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('ACTIVE', 'Active'), ('FROZEN', 'Frozen'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('validity_from', models.DateField()),
                ('validity_to', models.DateField(blank=True, null=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('change_case_id', models.CharField(blank=True, default='', max_length=64)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=128)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position_versions', to='hr_structure.hrorganization')),
                ('position_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_versions', to='hr_structure.hrposition')),
                ('post_catalog_version_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr_structure.hrpostcatalogversion')),
                ('post_grade_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hr_structure.hrpostgrade')),
            ],
            options={
                'verbose_name': 'HR Position Version',
                'verbose_name_plural': 'HR Position Versions',
                'indexes': [models.Index(fields=['tenant_id', 'position_id', 'validity_from'], name='hr_structur_tenant__2d2d5e_idx'), models.Index(fields=['tenant_id', 'organization_id', 'lifecycle_status'], name='hr_structur_tenant__0aac4d_idx')],
                'constraints': [models.UniqueConstraint(fields=('position_id', 'version_no'), name='uniq_hr_position_version_no')],
            },
        ),
    ]
