# Generated by Django 5.2 on 2026-08-30 10:04

import hashlib
import json
import uuid
from django.db import migrations, models


TERMINAL_ARCHIVE_STATUSES = {"RECEIVED", "RETURNED", "CANCELLED"}


def _digest(payload):
    return hashlib.sha256(
        json.dumps(
            payload, ensure_ascii=False, sort_keys=True, separators=(",", ":")
        ).encode("utf-8")
    ).hexdigest()


def seal_existing_authorities(apps, schema_editor):
    RetirementFact = apps.get_model("hr_exit", "RetirementFact")
    ArchiveReceipt = apps.get_model("hr_exit", "ArchiveTransferReceipt")

    retirement_batch = []
    for row in RetirementFact.objects.all().iterator(chunk_size=500):
        row.evidence_ref = row.evidence_ref or f"exitfact://{row.exit_fact_id}"
        row.sealed_at = row.sealed_at or row.created_at
        row.content_hash = _digest(
            {
                "tenantId": int(row.tenant_id),
                "factNo": row.fact_no,
                "personId": str(row.person_id),
                "exitFactId": str(row.exit_fact_id),
                "retirementType": row.retirement_type,
                "statutoryDate": row.statutory_date.isoformat() if row.statutory_date else None,
                "effectiveDate": row.effective_date.isoformat(),
                "status": row.status,
                "supersedesFactId": str(row.supersedes_fact_id) if row.supersedes_fact_id else None,
                "evidenceRef": row.evidence_ref,
                "sealedAt": row.sealed_at.isoformat(),
                "createdBy": row.created_by,
            }
        )
        retirement_batch.append(row)
        if len(retirement_batch) >= 500:
            RetirementFact.objects.bulk_update(
                retirement_batch, ["evidence_ref", "sealed_at", "content_hash"]
            )
            retirement_batch = []
    if retirement_batch:
        RetirementFact.objects.bulk_update(
            retirement_batch, ["evidence_ref", "sealed_at", "content_hash"]
        )

    archive_batch = []
    for row in ArchiveReceipt.objects.all().iterator(chunk_size=500):
        if row.status not in TERMINAL_ARCHIVE_STATUSES:
            row.evidence_ref = ""
            row.sealed_at = None
            row.content_hash = ""
        else:
            row.evidence_ref = (
                row.evidence_ref
                or row.receipt_attachment_ref
                or row.archive_attachment_ref
                or f"archive-transfer://{row.id}"
            )
            row.sealed_at = row.sealed_at or row.received_at or row.updated_at or row.created_at
            row.content_hash = _digest(
                {
                    "tenantId": int(row.tenant_id),
                    "transferNo": row.transfer_no,
                    "caseId": str(row.case_id),
                    "personId": str(row.person_id),
                    "destinationType": row.destination_type,
                    "destinationName": row.destination_name,
                    "destinationAddress": row.destination_address,
                    "transferMethod": row.transfer_method,
                    "trackingNo": row.tracking_no,
                    "archiveAttachmentRef": row.archive_attachment_ref,
                    "receiptAttachmentRef": row.receipt_attachment_ref,
                    "operatorUserId": row.operator_user_id,
                    "sentAt": row.sent_at.isoformat() if row.sent_at else None,
                    "receivedAt": row.received_at.isoformat() if row.received_at else None,
                    "receivedBy": row.received_by,
                    "returnReason": row.return_reason,
                    "status": row.status,
                    "supersedesReceiptId": str(row.supersedes_receipt_id) if row.supersedes_receipt_id else None,
                    "evidenceRef": row.evidence_ref,
                    "sealedAt": row.sealed_at.isoformat(),
                    "createdBy": row.created_by,
                    "updatedBy": row.updated_by,
                }
            )
        archive_batch.append(row)
        if len(archive_batch) >= 500:
            ArchiveReceipt.objects.bulk_update(
                archive_batch, ["evidence_ref", "sealed_at", "content_hash"]
            )
            archive_batch = []
    if archive_batch:
        ArchiveReceipt.objects.bulk_update(
            archive_batch, ["evidence_ref", "sealed_at", "content_hash"]
        )


def install_mysql_write_seals(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    for trigger in (
        "hr16_retirement_fact_no_delete",
        "hr16_retirement_fact_guard_update",
        "hr16_archive_receipt_no_update",
        "hr16_archive_receipt_no_delete",
        "hr16_pension_transition_no_update",
        "hr16_pension_transition_no_delete",
    ):
        schema_editor.execute(f"DROP TRIGGER IF EXISTS {trigger}")
    schema_editor.execute(
        """
        CREATE TRIGGER hr16_retirement_fact_guard_update
        BEFORE UPDATE ON hr16_retirement_fact
        FOR EACH ROW
        BEGIN
            IF OLD.sealed_at IS NOT NULL AND (
                NOT (NEW.tenant_id <=> OLD.tenant_id) OR
                NOT (NEW.fact_no <=> OLD.fact_no) OR
                NOT (NEW.person_id <=> OLD.person_id) OR
                NOT (NEW.exit_fact_id <=> OLD.exit_fact_id) OR
                NOT (NEW.retirement_type <=> OLD.retirement_type) OR
                NOT (NEW.statutory_date <=> OLD.statutory_date) OR
                NOT (NEW.effective_date <=> OLD.effective_date) OR
                NOT (NEW.status <=> OLD.status) OR
                NOT (NEW.supersedes_fact_id <=> OLD.supersedes_fact_id) OR
                NOT (NEW.evidence_ref <=> OLD.evidence_ref) OR
                NOT (NEW.content_hash <=> OLD.content_hash) OR
                NOT (NEW.sealed_at <=> OLD.sealed_at) OR
                NOT (NEW.created_by <=> OLD.created_by)
            ) THEN
                SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'RETIREMENT_FACT_IMMUTABLE: formal fields are sealed';
            END IF;
            IF (OLD.pension_processing_status = 'NOT_STARTED' AND
                NEW.pension_processing_status NOT IN ('NOT_STARTED', 'IN_PROGRESS')) OR
               (OLD.pension_processing_status = 'IN_PROGRESS' AND
                NEW.pension_processing_status NOT IN ('IN_PROGRESS', 'COMPLETED')) OR
               (OLD.pension_processing_status = 'COMPLETED' AND
                NEW.pension_processing_status <> 'COMPLETED') THEN
                SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'RETIREMENT_PENSION_STATUS_INVALID_TRANSITION';
            END IF;
        END
        """
    )
    schema_editor.execute(
        """
        CREATE TRIGGER hr16_retirement_fact_no_delete
        BEFORE DELETE ON hr16_retirement_fact
        FOR EACH ROW
        BEGIN
            IF OLD.sealed_at IS NOT NULL THEN
                SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'RETIREMENT_FACT_IMMUTABLE: formal facts cannot be deleted';
            END IF;
        END
        """
    )
    schema_editor.execute(
        """
        CREATE TRIGGER hr16_archive_receipt_no_update
        BEFORE UPDATE ON hr16_archive_transfer_receipt
        FOR EACH ROW
        BEGIN
            IF OLD.sealed_at IS NOT NULL THEN
                SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'ARCHIVE_TRANSFER_RECEIPT_IMMUTABLE: terminal receipt';
            END IF;
        END
        """
    )
    schema_editor.execute(
        """
        CREATE TRIGGER hr16_archive_receipt_no_delete
        BEFORE DELETE ON hr16_archive_transfer_receipt
        FOR EACH ROW
        BEGIN
            IF OLD.sealed_at IS NOT NULL THEN
                SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'ARCHIVE_TRANSFER_RECEIPT_IMMUTABLE: terminal receipt';
            END IF;
        END
        """
    )
    schema_editor.execute(
        """
        CREATE TRIGGER hr16_pension_transition_no_update
        BEFORE UPDATE ON hr16_retirement_pension_transition
        FOR EACH ROW
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'RETIREMENT_PENSION_TRANSITION_IMMUTABLE'
        """
    )
    schema_editor.execute(
        """
        CREATE TRIGGER hr16_pension_transition_no_delete
        BEFORE DELETE ON hr16_retirement_pension_transition
        FOR EACH ROW
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'RETIREMENT_PENSION_TRANSITION_IMMUTABLE'
        """
    )


def remove_mysql_write_seals(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    for trigger in (
        "hr16_retirement_fact_no_delete",
        "hr16_retirement_fact_guard_update",
        "hr16_archive_receipt_no_update",
        "hr16_archive_receipt_no_delete",
        "hr16_pension_transition_no_update",
        "hr16_pension_transition_no_delete",
    ):
        schema_editor.execute(f"DROP TRIGGER IF EXISTS {trigger}")


class Migration(migrations.Migration):

    dependencies = [
        ('hr_exit', '0010_exit_fact_integrity'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetirementPensionTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('retirement_fact_id', models.UUIDField(db_index=True)),
                ('from_status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], max_length=16)),
                ('to_status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], max_length=16)),
                ('evidence_ref', models.CharField(max_length=256)),
                ('content_hash', models.CharField(max_length=64)),
                ('sealed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'hr16_retirement_pension_transition',
                'base_manager_name': 'objects',
            },
        ),
        migrations.AlterModelOptions(
            name='archivetransferreceipt',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='retirementfact',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='exitcase',
            options={
                'permissions': [
                    ('hr.exit.view', '查看 HR16 退休与离校工作区'),
                    ('hr.exit.manage', '办理 HR16 退休与离校流程'),
                    ('hr.exit.handover', '维护 HR16 离校交接清单'),
                    ('hr.exit.effect', '执行 HR16 正式离校就业关系生效'),
                    ('hr.exit.fact.correct', '更正 HR16 已封板离校正式事实'),
                    ('hr.exit.fact.revoke', '撤销 HR16 已封板离校正式事实'),
                    ('hr.exit.retirement_policy.manage', '维护 HR16 版本化退休政策'),
                    ('hr.exit.retirement_precheck.execute', '执行 HR16 退休日期预审'),
                    ('hr.exit.retirement.pension.manage', '推进 HR16 养老金办理进度并提交证据'),
                ]
            },
        ),
        migrations.AddField(
            model_name='archivetransferreceipt',
            name='content_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='archivetransferreceipt',
            name='evidence_ref',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='archivetransferreceipt',
            name='sealed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retirementfact',
            name='content_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='retirementfact',
            name='evidence_ref',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='retirementfact',
            name='sealed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(seal_existing_authorities, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='archivetransferreceipt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('content_hash', ''), ('sealed_at__isnull', True), ('status__in', ('DRAFT', 'SENT'))), models.Q(('content_hash__regex', '^[0-9a-f]{64}$'), ('evidence_ref__gt', ''), ('sealed_at__isnull', False), ('status__in', ('RECEIVED', 'RETURNED', 'CANCELLED'))), _connector='OR'), name='ck_hr16_archive_receipt_seal'),
        ),
        migrations.AddConstraint(
            model_name='retirementfact',
            constraint=models.CheckConstraint(condition=models.Q(('content_hash__regex', '^[0-9a-f]{64}$'), ('evidence_ref__gt', ''), ('sealed_at__isnull', False)), name='ck_hr16_retire_fact_seal'),
        ),
        migrations.AddConstraint(
            model_name='retirementfact',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'exit_fact_id'), name='uq_hr16_retire_exit_fact'),
        ),
        migrations.AddConstraint(
            model_name='retirementfact',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'supersedes_fact_id'), name='uq_hr16_retire_successor'),
        ),
        migrations.AddConstraint(
            model_name='retirementpensiontransition',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'retirement_fact_id', 'to_status'), name='uq_hr16_retire_pension_step'),
        ),
        migrations.AddConstraint(
            model_name='retirementpensiontransition',
            constraint=models.CheckConstraint(condition=models.Q(('content_hash__regex', '^[0-9a-f]{64}$'), ('evidence_ref__gt', '')), name='ck_hr16_retire_pension_evidence'),
        ),
        migrations.RunPython(install_mysql_write_seals, remove_mysql_write_seals),
    ]
