# Generated by Django 5.2 on 2026-08-08 16:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HrPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('person_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('legal_name', models.CharField(max_length=200)),
                ('preferred_name', models.CharField(blank=True, default='', max_length=200)),
                ('gender_code', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unspecified')], max_length=1, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('nationality_code', models.CharField(blank=True, default='', max_length=16)),
                ('status', models.CharField(choices=[('PENDING_ENTRY', 'Pending Entry'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('DEPARTURE_PENDING', 'Departure Pending'), ('DEPARTED', 'Departed'), ('RETIRED', 'Retired'), ('RETIRED_REHIRED', 'Retired and Rehired')], db_index=True, default='PENDING_ENTRY', max_length=24)),
                ('version', models.BigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HR Person',
                'verbose_name_plural': 'HR Persons',
                'indexes': [models.Index(fields=['tenant_id', 'legal_name'], name='hr_staff_hr_tenant__822eeb_idx'), models.Index(fields=['tenant_id', 'status'], name='hr_staff_hr_tenant__38c3cb_idx')],
            },
        ),
        migrations.CreateModel(
            name='HrSensitiveAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('staff_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('field_code', models.CharField(max_length=64)),
                ('actor_user_id', models.BigIntegerField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, default='', max_length=512)),
                ('action', models.CharField(default='REVEAL', max_length=32)),
                ('access_token_ref', models.CharField(blank=True, default='', max_length=128)),
                ('revealed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
            ],
            options={
                'verbose_name': 'HR Sensitive Access Log',
                'verbose_name_plural': 'HR Sensitive Access Logs',
                'indexes': [models.Index(fields=['tenant_id', 'staff_id', 'revealed_at'], name='hr_staff_hr_tenant__4ec068_idx'), models.Index(fields=['tenant_id', 'field_code'], name='hr_staff_hr_tenant__0aeb08_idx')],
            },
        ),
        migrations.CreateModel(
            name='HrStaffAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('staff_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('person_id', models.UUIDField(blank=True, null=True)),
                ('actor_user_id', models.BigIntegerField(blank=True, null=True)),
                ('actor_staff_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('business_type', models.CharField(blank=True, default='', max_length=64)),
                ('business_id', models.CharField(blank=True, default='', max_length=64)),
                ('before_snapshot_ref', models.CharField(blank=True, default='', max_length=128)),
                ('after_snapshot_ref', models.CharField(blank=True, default='', max_length=128)),
                ('reason', models.CharField(blank=True, default='', max_length=512)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('approval_instance_id', models.CharField(blank=True, default='', max_length=64)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'HR Staff Audit Event',
                'verbose_name_plural': 'HR Staff Audit Events',
                'indexes': [models.Index(fields=['tenant_id', 'staff_id', 'occurred_at'], name='hr_staff_hr_tenant__efbd56_idx'), models.Index(fields=['tenant_id', 'action'], name='hr_staff_hr_tenant__ae4065_idx'), models.Index(fields=['tenant_id', 'business_type', 'business_id'], name='hr_staff_hr_tenant__fde93d_idx')],
            },
        ),
        migrations.CreateModel(
            name='HrStaffMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('staff_no', models.CharField(max_length=64)),
                ('staff_category_code', models.CharField(choices=[('TEACHER', 'Teacher'), ('ADMIN', 'Administrative'), ('ENGINEERING_TECHNICAL', 'Engineering Technical'), ('EXPERIMENTAL', 'Experimental'), ('LIBRARY_ARCHIVES', 'Library/Archives'), ('LOGISTICS', 'Logistics'), ('OTHER', 'Other')], default='TEACHER', max_length=32)),
                ('current_employment_status', models.CharField(blank=True, db_index=True, default='', max_length=24)),
                ('primary_assignment_id', models.UUIDField(blank=True, null=True)),
                ('legacy_employee_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('source', models.CharField(choices=[('SELF_REPORTED', 'Self Reported'), ('HR_ENTERED', 'HR Entered'), ('MIGRATED', 'Migrated'), ('VERIFIED_EXTERNAL', 'Verified External'), ('BUSINESS_PROCESS', 'Business Process')], default='HR_ENTERED', max_length=24)),
                ('version', models.BigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_masters', to='hr_staff.hrperson')),
            ],
            options={
                'verbose_name': 'HR Staff Master',
                'verbose_name_plural': 'HR Staff Masters',
            },
        ),
        migrations.CreateModel(
            name='HrLegacyProjectionState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('legacy_employee_id', models.BigIntegerField(db_index=True)),
                ('last_projected_at', models.DateTimeField(blank=True, null=True)),
                ('projection_hash', models.CharField(blank=True, default='', max_length=64)),
                ('last_reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('mismatch_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legacy_projection_states', to='hr_staff.hrstaffmaster')),
            ],
            options={
                'verbose_name': 'HR Legacy Projection State',
                'verbose_name_plural': 'HR Legacy Projection States',
            },
        ),
        migrations.CreateModel(
            name='HrExternalIdentityMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('system_code', models.CharField(max_length=64)),
                ('external_subject', models.CharField(max_length=254)),
                ('mapping_status', models.CharField(default='ACTIVE', max_length=16)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_identities', to='hr_staff.hrstaffmaster')),
            ],
            options={
                'verbose_name': 'HR External Identity Mapping',
                'verbose_name_plural': 'HR External Identity Mappings',
            },
        ),
        migrations.CreateModel(
            name='HrAccountLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('auth_user_id', models.BigIntegerField(blank=True, null=True)),
                ('auth_identifier', models.CharField(blank=True, default='', max_length=254)),
                ('link_status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('UNLINKED', 'Unlinked')], default='ACTIVE', max_length=16)),
                ('linked_at', models.DateTimeField(blank=True, null=True)),
                ('unlinked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_links', to='hr_staff.hrstaffmaster')),
            ],
            options={
                'verbose_name': 'HR Account Link',
                'verbose_name_plural': 'HR Account Links',
            },
        ),
        migrations.CreateModel(
            name='HrEmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('name', models.CharField(max_length=120)),
                ('relation', models.CharField(blank=True, default='', max_length=40)),
                ('phone', models.CharField(blank=True, default='', max_length=25)),
                ('masked_phone', models.CharField(blank=True, default='', max_length=25)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emergency_contacts', to='hr_staff.hrperson')),
            ],
            options={
                'verbose_name': 'HR Emergency Contact',
                'verbose_name_plural': 'HR Emergency Contacts',
                'indexes': [models.Index(fields=['tenant_id', 'person_id'], name='hr_staff_hr_tenant__fc77dd_idx')],
            },
        ),
        migrations.CreateModel(
            name='HrPersonContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('contact_kind', models.CharField(choices=[('PERSONAL_MOBILE', 'Personal Mobile'), ('PERSONAL_EMAIL', 'Personal Email'), ('WORK_MOBILE', 'Work Mobile'), ('WORK_EMAIL', 'Work Email'), ('HOME_ADDRESS', 'Home Address'), ('OTHER', 'Other')], max_length=24)),
                ('contact_value', models.CharField(max_length=512)),
                ('masked_display', models.CharField(blank=True, default='', max_length=512)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='hr_staff.hrperson')),
            ],
            options={
                'verbose_name': 'HR Person Contact',
                'verbose_name_plural': 'HR Person Contacts',
                'indexes': [models.Index(fields=['tenant_id', 'person_id', 'contact_kind'], name='hr_staff_hr_tenant__257c2d_idx'), models.Index(fields=['tenant_id', 'is_primary'], name='hr_staff_hr_tenant__9c901c_idx')],
            },
        ),
        migrations.CreateModel(
            name='HrPersonIdentityDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('document_type', models.CharField(choices=[('NATIONAL_ID', 'National ID'), ('PASSPORT', 'Passport'), ('HK_MACAO_TW', 'HK/Macao/TW Permit'), ('FOREIGN_RESIDENT', 'Foreign Resident Permit'), ('OTHER', 'Other')], default='NATIONAL_ID', max_length=24)),
                ('document_number_ciphertext', models.TextField(blank=True, default='')),
                ('document_number_fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('masked_display', models.CharField(blank=True, default='', max_length=64)),
                ('issuing_country', models.CharField(blank=True, default='CN', max_length=8)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='UNVERIFIED', max_length=16)),
                ('verified_by', models.BigIntegerField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.BigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identity_documents', to='hr_staff.hrperson')),
            ],
            options={
                'verbose_name': 'HR Person Identity Document',
                'verbose_name_plural': 'HR Person Identity Documents',
                'indexes': [models.Index(fields=['tenant_id', 'person_id', 'document_type'], name='hr_staff_hr_tenant__5580e7_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('document_number_fingerprint__isnull', False), models.Q(('document_number_fingerprint', ''), _negated=True)), fields=('tenant_id', 'document_number_fingerprint'), name='uniq_hr_identity_fingerprint_tenant')],
            },
        ),
        migrations.AddIndex(
            model_name='hrstaffmaster',
            index=models.Index(fields=['tenant_id', 'current_employment_status'], name='hr_staff_hr_tenant__7fab0b_idx'),
        ),
        migrations.AddIndex(
            model_name='hrstaffmaster',
            index=models.Index(fields=['tenant_id', 'legacy_employee_id'], name='hr_staff_hr_tenant__3c208b_idx'),
        ),
        migrations.AddConstraint(
            model_name='hrstaffmaster',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'staff_no'), name='uniq_hr_staff_tenant_staff_no'),
        ),
        migrations.AddConstraint(
            model_name='hrstaffmaster',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'person_id'), name='uniq_hr_staff_tenant_person_canonical'),
        ),
        migrations.AddConstraint(
            model_name='hrlegacyprojectionstate',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'legacy_employee_id'), name='uniq_hr_legacy_projection_tenant_emp'),
        ),
        migrations.AddConstraint(
            model_name='hrexternalidentitymapping',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'system_code', 'external_subject'), name='uniq_hr_external_identity_scope'),
        ),
        migrations.AddIndex(
            model_name='hraccountlink',
            index=models.Index(fields=['tenant_id', 'staff_id', 'link_status'], name='hr_staff_hr_tenant__78cf19_idx'),
        ),
        migrations.AddIndex(
            model_name='hraccountlink',
            index=models.Index(fields=['tenant_id', 'auth_identifier'], name='hr_staff_hr_tenant__171b19_idx'),
        ),
    ]
