# Generated by Django 5.2 on 2026-08-08 16:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_staff', '0001_initial'),
        ('hr_structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrEmploymentRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('relationship_type', models.CharField(choices=[('REGULAR_EMPLOYMENT', 'Regular Employment'), ('CONTRACT', 'Contract'), ('LABOR_DISPATCH', 'Labor Dispatch'), ('EXTERNAL_PART_TIME', 'External Part-time'), ('SECONDMENT', 'Secondment'), ('RETIRED_REHIRE', 'Retired Rehire'), ('REHIRE', 'Rehire'), ('OTHER', 'Other')], default='REGULAR_EMPLOYMENT', max_length=32)),
                ('employment_type', models.CharField(blank=True, default='', max_length=32)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ENDED', 'Ended'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=16)),
                ('source_business_type', models.CharField(blank=True, default='', max_length=64)),
                ('source_business_id', models.CharField(blank=True, default='', max_length=64)),
                ('reason_code', models.CharField(blank=True, default='', max_length=64)),
                ('version', models.BigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employment_relationships', to='hr_staff.hrstaffmaster')),
            ],
            options={
                'verbose_name': 'HR Employment Relationship',
                'verbose_name_plural': 'HR Employment Relationships',
            },
        ),
        migrations.CreateModel(
            name='HrStaffAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('legacy_department_id', models.BigIntegerField(blank=True, null=True)),
                ('legacy_job_position_id', models.BigIntegerField(blank=True, null=True)),
                ('assignment_type', models.CharField(choices=[('PRIMARY', 'Primary'), ('CONCURRENT', 'Concurrent'), ('TEMPORARY', 'Temporary'), ('SECONDMENT', 'Secondment')], default='PRIMARY', max_length=16)),
                ('assignment_role_code', models.CharField(blank=True, default='', max_length=64)),
                ('fte', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('source_business_type', models.CharField(blank=True, default='', max_length=64)),
                ('source_business_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ENDING_SOON', 'Ending Soon'), ('ENDED', 'Ended'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=16)),
                ('version', models.BigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employment_relationship_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='hr_staff.hremploymentrelationship')),
                ('organization_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hr03_assignments', to='hr_structure.hrorganization')),
                ('position_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hr03_assignments', to='hr_structure.hrposition')),
                ('post_catalog_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hr03_assignments', to='hr_structure.hrpostcatalogversion')),
                ('reporting_staff_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports_to_assignments', to='hr_staff.hrstaffmaster')),
            ],
            options={
                'verbose_name': 'HR Staff Assignment',
                'verbose_name_plural': 'HR Staff Assignments',
            },
        ),
        migrations.CreateModel(
            name='HrStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('status_code', models.CharField(choices=[('PENDING_ENTRY', 'Pending Entry'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('DEPARTURE_PENDING', 'Departure Pending'), ('DEPARTED', 'Departed'), ('RETIRED', 'Retired'), ('RETIRED_REHIRED', 'Retired and Rehired')], max_length=24)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('reason_code', models.CharField(blank=True, default='', max_length=64)),
                ('source_business_type', models.CharField(blank=True, default='', max_length=64)),
                ('source_business_id', models.CharField(blank=True, default='', max_length=64)),
                ('version', models.BigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='hr_staff.hrstaffmaster')),
            ],
            options={
                'verbose_name': 'HR Status History',
                'verbose_name_plural': 'HR Status Histories',
            },
        ),
        migrations.AddIndex(
            model_name='hremploymentrelationship',
            index=models.Index(fields=['tenant_id', 'staff_id', 'effective_from'], name='hr_staff_hr_tenant__59f86d_idx'),
        ),
        migrations.AddIndex(
            model_name='hremploymentrelationship',
            index=models.Index(fields=['tenant_id', 'status'], name='hr_staff_hr_tenant__bc04fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='hremploymentrelationship',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='chk_hr_rel_effective_to_gt_from'),
        ),
        migrations.AddIndex(
            model_name='hrstaffassignment',
            index=models.Index(fields=['tenant_id', 'employment_relationship_id', 'effective_from'], name='hr_staff_hr_tenant__fd9aed_idx'),
        ),
        migrations.AddIndex(
            model_name='hrstaffassignment',
            index=models.Index(fields=['tenant_id', 'organization_id', 'effective_from', 'effective_to'], name='hr_staff_hr_tenant__701e90_idx'),
        ),
        migrations.AddIndex(
            model_name='hrstaffassignment',
            index=models.Index(fields=['tenant_id', 'position_id', 'effective_from', 'effective_to'], name='hr_staff_hr_tenant__345582_idx'),
        ),
        migrations.AddIndex(
            model_name='hrstaffassignment',
            index=models.Index(fields=['tenant_id', 'status'], name='hr_staff_hr_tenant__ebe781_idx'),
        ),
        migrations.AddConstraint(
            model_name='hrstaffassignment',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='chk_hr_assignment_effective_to_gt_from'),
        ),
        migrations.AddConstraint(
            model_name='hrstaffassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('assignment_type', 'PRIMARY'), ('effective_to__isnull', True)), fields=('tenant_id', 'employment_relationship_id'), name='uniq_hr_assignment_open_primary_per_rel'),
        ),
        migrations.AddIndex(
            model_name='hrstatushistory',
            index=models.Index(fields=['tenant_id', 'staff_id', 'effective_from'], name='hr_staff_hr_tenant__4d9260_idx'),
        ),
        migrations.AddConstraint(
            model_name='hrstatushistory',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='chk_hr_status_effective_to_gt_from'),
        ),
    ]
