# Generated by Django 5.2 on 2026-08-08 17:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_staff', '0005_hrstaffmaterial_hrstaffmaterialversion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrCorrectionCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_no', models.CharField(max_length=32, unique=True)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('RETURNED', 'Returned'), ('RESUBMITTED', 'Resubmitted'), ('APPROVED', 'Approved'), ('APPLYING', 'Applying'), ('APPLIED', 'Applied'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=16)),
                ('reason', models.CharField(max_length=512)),
                ('evidence_material_id', models.UUIDField(blank=True, null=True)),
                ('impact_level', models.CharField(choices=[('NO_DOWNSTREAM_IMPACT', 'No Downstream Impact'), ('REQUIRES_REINDEX', 'Requires Reindex'), ('REQUIRES_DASHBOARD_RECALC', 'Requires Dashboard Recalc'), ('AFFECTS_CLOSED_PAYROLL', 'Affects Closed Payroll'), ('AFFECTS_ARCHIVED_ASSESSMENT', 'Affects Archived Assessment'), ('AFFECTS_REPORTED_DATA', 'Affects Reported Data'), ('HIGH_RISK_RETROACTIVE', 'High Risk Retroactive')], default='NO_DOWNSTREAM_IMPACT', max_length=32)),
                ('submitted_by', models.BigIntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.BigIntegerField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.BigIntegerField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('apply_error', models.CharField(blank=True, default='', max_length=512)),
                ('return_reason', models.CharField(blank=True, default='', max_length=512)),
                ('reject_reason', models.CharField(blank=True, default='', max_length=512)),
                ('version', models.BigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_cases', to='hr_staff.hrstaffmaster')),
            ],
            options={
                'verbose_name': 'HR Correction Case',
                'verbose_name_plural': 'HR Correction Cases',
            },
        ),
        migrations.CreateModel(
            name='HrCorrectionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('fact_type', models.CharField(blank=True, default='', max_length=32)),
                ('fact_id', models.UUIDField(blank=True, null=True)),
                ('field_code', models.CharField(max_length=64)),
                ('old_value_masked', models.CharField(blank=True, default='', max_length=512)),
                ('new_value_masked', models.CharField(blank=True, default='', max_length=512)),
                ('old_value_ref', models.CharField(blank=True, default='', max_length=128)),
                ('new_value_ref', models.CharField(blank=True, default='', max_length=128)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('impact_level', models.CharField(choices=[('NO_DOWNSTREAM_IMPACT', 'No Downstream Impact'), ('REQUIRES_REINDEX', 'Requires Reindex'), ('REQUIRES_DASHBOARD_RECALC', 'Requires Dashboard Recalc'), ('AFFECTS_CLOSED_PAYROLL', 'Affects Closed Payroll'), ('AFFECTS_ARCHIVED_ASSESSMENT', 'Affects Archived Assessment'), ('AFFECTS_REPORTED_DATA', 'Affects Reported Data'), ('HIGH_RISK_RETROACTIVE', 'High Risk Retroactive')], default='NO_DOWNSTREAM_IMPACT', max_length=32)),
                ('applied', models.BooleanField(default=False)),
                ('apply_result', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='hr_staff.hrcorrectioncase')),
            ],
            options={
                'verbose_name': 'HR Correction Item',
                'verbose_name_plural': 'HR Correction Items',
            },
        ),
        migrations.CreateModel(
            name='HrFieldGovernancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('field_code', models.CharField(max_length=64)),
                ('edit_mode', models.CharField(choices=[('SELF_DIRECT', 'Self Direct'), ('SELF_REQUEST', 'Self Request'), ('HR_DIRECT', 'HR Direct'), ('HR_APPROVAL', 'HR Approval'), ('BUSINESS_PROCESS_ONLY', 'Business Process Only'), ('LOCKED', 'Locked')], max_length=32)),
                ('required_permission', models.CharField(blank=True, default='', max_length=64)),
                ('required_evidence', models.BooleanField(default=False)),
                ('approval_policy', models.CharField(blank=True, default='', max_length=32)),
                ('sensitivity_level', models.CharField(choices=[('PUBLIC_HR', 'Public HR'), ('RESTRICTED_HR', 'Restricted HR'), ('SENSITIVE', 'Sensitive'), ('HIGH_SENSITIVE', 'High Sensitive')], default='PUBLIC_HR', max_length=16)),
                ('retroactive_allowed', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HR Field Governance Policy',
                'verbose_name_plural': 'HR Field Governance Policies',
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'field_code'), name='uniq_hr_field_policy_tenant_code')],
            },
        ),
        migrations.AddIndex(
            model_name='hrcorrectioncase',
            index=models.Index(fields=['tenant_id', 'staff_id', 'status'], name='hr_staff_hr_tenant__36ea9d_idx'),
        ),
        migrations.AddIndex(
            model_name='hrcorrectioncase',
            index=models.Index(fields=['tenant_id', 'status', 'created_at'], name='hr_staff_hr_tenant__27b4ab_idx'),
        ),
        migrations.AddIndex(
            model_name='hrcorrectionitem',
            index=models.Index(fields=['tenant_id', 'case_id'], name='hr_staff_hr_tenant__31c966_idx'),
        ),
    ]
