# Generated by Django 5.2 on 2026-08-09 00:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_staff', '0010_hrmaterialdownloadticket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('requested_by', models.BigIntegerField(blank=True, null=True)),
                ('purpose', models.CharField(max_length=512)),
                ('fields_json', models.JSONField(blank=True, default=list)),
                ('scope_info_json', models.JSONField(blank=True, default=dict)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=16)),
                ('file_ref', models.CharField(blank=True, default='', max_length=255)),
                ('download_token', models.CharField(blank=True, default='', max_length=64)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'HR Export Job',
                'verbose_name_plural': 'HR Export Jobs',
                'indexes': [models.Index(fields=['tenant_id', 'status', 'created_at'], name='hr_staff_hr_tenant__c8bf6e_idx'), models.Index(fields=['tenant_id', 'download_token'], name='hr_staff_hr_tenant__39336c_idx')],
            },
        ),
        migrations.CreateModel(
            name='HrStaffNumberSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('prefix', models.CharField(max_length=16)),
                ('next_value', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HR Staff Number Sequence',
                'verbose_name_plural': 'HR Staff Number Sequences',
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'prefix'), name='uniq_hr_staff_number_sequence')],
            },
        ),
    ]
