# Generated by Django 5.2 on 2026-08-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_staff', '0015_personnel_decision_authority_seal'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrdegreerecord',
            name='source_business_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='hrdegreerecord',
            name='source_domain',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='hreducationexperience',
            name='source_business_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='hreducationexperience',
            name='source_domain',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='hrdegreerecord',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'source_domain', 'source_business_id'), name='uniq_hr03_degree_source_fact'),
        ),
        migrations.AddConstraint(
            model_name='hreducationexperience',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'source_domain', 'source_business_id'), name='uniq_hr03_education_source_fact'),
        ),
    ]
