# Generated by Django 5.2 on 2026-09-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("hr_staff", "0016_hrdegreerecord_source_business_id_and_more")]

    operations = [
        migrations.AddField(
            model_name="hrstaffassignment",
            name="location_code",
            field=models.CharField(blank=True, default="", max_length=128),
        )
    ]
