import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [('hr_assessment', '0002_state_convergence_01')]
    operations = [
        migrations.AlterField(model_name='hrassessmentpolicypack', name='code', field=models.CharField(max_length=50, verbose_name='政策编码')),
        migrations.AlterField(model_name='hrassessmentpolicypack', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrassessmentpolicypack', name='name', field=models.CharField(max_length=200, verbose_name='政策名称')),
        migrations.AlterField(model_name='hrassessmentpolicypack', name='owner_org_id', field=models.UUIDField(blank=True, null=True, verbose_name='归属组织 ID')),
        migrations.AlterField(model_name='hrassessmentpolicypack', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrassessmentpolicypack', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrassessmentpolicyversion', name='content_hash', field=models.CharField(blank=True, default='', max_length=64, verbose_name='内容哈希 (SHA-256)')),
        migrations.AlterField(model_name='hrassessmentpolicyversion', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrassessmentpolicyversion', name='effective_from', field=models.DateField(verbose_name='生效日期')),
        migrations.AlterField(model_name='hrassessmentpolicyversion', name='policy_pack', field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='hr_assessment.hrassessmentpolicypack', verbose_name='所属政策包')),
        migrations.AlterField(model_name='hrassessmentpolicyversion', name='status', field=models.CharField(db_index=True, default='DRAFT', max_length=30, verbose_name='状态')),
        migrations.AlterField(model_name='hrassessmentpolicyversion', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrassessmentpolicyversion', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrassessmentpolicyversion', name='version_no', field=models.PositiveIntegerField(default=1, verbose_name='版本号')),
        migrations.AlterField(model_name='hrassessmentpopulationsnapshot', name='classification_profile_json', field=models.JSONField(default=dict, verbose_name='分类评价 profile')),
        migrations.AlterField(model_name='hrassessmentpopulationsnapshot', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrassessmentpopulationsnapshot', name='cycle', field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='population', to='hr_assessment.hrassessmentcycle', verbose_name='所属周期')),
        migrations.AlterField(model_name='hrassessmentpopulationsnapshot', name='eligibility_reason_codes', field=models.JSONField(default=list, verbose_name='资格判定原因码')),
        migrations.AlterField(model_name='hrassessmentpopulationsnapshot', name='employment_relationship_id', field=models.UUIDField(null=True, verbose_name='聘用关系 ID')),
        migrations.AlterField(model_name='hrassessmentpopulationsnapshot', name='excluded', field=models.BooleanField(default=False, verbose_name='是否排除')),
        migrations.AlterField(model_name='hrassessmentpopulationsnapshot', name='included', field=models.BooleanField(default=True, verbose_name='是否包含')),
        migrations.AlterField(model_name='hrassessmentpopulationsnapshot', name='org_id', field=models.UUIDField(null=True, verbose_name='当时组织 ID')),
        migrations.AlterField(model_name='hrassessmentpopulationsnapshot', name='policy_version_id', field=models.UUIDField(null=True, verbose_name='适用政策版本 ID')),
        migrations.AlterField(model_name='hrassessmentpopulationsnapshot', name='position_id', field=models.UUIDField(null=True, verbose_name='当时岗位 ID')),
        migrations.AlterField(model_name='hrassessmentpopulationsnapshot', name='primary_assignment_id', field=models.UUIDField(null=True, verbose_name='主岗任职 ID')),
        migrations.AlterField(model_name='hrassessmentpopulationsnapshot', name='snapshot_at', field=models.DateTimeField(verbose_name='快照时间')),
        migrations.AlterField(model_name='hrassessmentpopulationsnapshot', name='special_case', field=models.CharField(default='', max_length=50, verbose_name='特殊情形')),
        migrations.AlterField(model_name='hrassessmentpopulationsnapshot', name='staff_id', field=models.UUIDField(verbose_name='人员 ID')),
        migrations.AlterField(model_name='hrassessmentpopulationsnapshot', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrassessmentpopulationsnapshot', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrassessmentpopulationsnapshot', name='worker_category', field=models.CharField(default='', max_length=50, verbose_name='人员类别')),
        migrations.AlterField(model_name='hrassessmentpublicitycase', name='announcement_ref', field=models.UUIDField(null=True, verbose_name='公示文引用')),
        migrations.AlterField(model_name='hrassessmentpublicitycase', name='candidate_result_refs_json', field=models.JSONField(default=list, verbose_name='候选结果引用')),
        migrations.AlterField(model_name='hrassessmentpublicitycase', name='completed_at', field=models.DateTimeField(null=True, verbose_name='完成时间')),
        migrations.AlterField(model_name='hrassessmentpublicitycase', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrassessmentpublicitycase', name='cycle', field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publicity_cases', to='hr_assessment.hrassessmentcycle', verbose_name='所属周期')),
        migrations.AlterField(model_name='hrassessmentpublicitycase', name='end_at', field=models.DateTimeField(verbose_name='公示结束')),
        migrations.AlterField(model_name='hrassessmentpublicitycase', name='minimum_duration_hours', field=models.PositiveIntegerField(default=120, verbose_name='最短时长(小时)')),
        migrations.AlterField(model_name='hrassessmentpublicitycase', name='scope_json', field=models.JSONField(default=dict, verbose_name='公示范围')),
        migrations.AlterField(model_name='hrassessmentpublicitycase', name='start_at', field=models.DateTimeField(verbose_name='公示开始')),
        migrations.AlterField(model_name='hrassessmentpublicitycase', name='status', field=models.CharField(default='DRAFT', max_length=30, verbose_name='公示状态')),
        migrations.AlterField(model_name='hrassessmentpublicitycase', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrassessmentpublicitycase', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrassessmentworkflowversion', name='content_hash', field=models.CharField(blank=True, default='', max_length=64, verbose_name='内容哈希 (SHA-256)')),
        migrations.AlterField(model_name='hrassessmentworkflowversion', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrassessmentworkflowversion', name='status', field=models.CharField(db_index=True, default='DRAFT', max_length=30, verbose_name='状态')),
        migrations.AlterField(model_name='hrassessmentworkflowversion', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrassessmentworkflowversion', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrassessmentworkflowversion', name='version_no', field=models.PositiveIntegerField(default=1, verbose_name='版本号')),
        migrations.AlterField(model_name='hrcalibrationrevision', name='after_grade_recommendation', field=models.CharField(default='', max_length=30, verbose_name='校准后建议档次')),
        migrations.AlterField(model_name='hrcalibrationrevision', name='after_rating_json', field=models.JSONField(default=dict, verbose_name='校准后评分')),
        migrations.AlterField(model_name='hrcalibrationrevision', name='approved_by', field=models.UUIDField(null=True, verbose_name='批准人')),
        migrations.AlterField(model_name='hrcalibrationrevision', name='before_grade_recommendation', field=models.CharField(default='', max_length=30, verbose_name='校准前建议档次')),
        migrations.AlterField(model_name='hrcalibrationrevision', name='before_rating_json', field=models.JSONField(default=dict, verbose_name='校准前评分')),
        migrations.AlterField(model_name='hrcalibrationrevision', name='case_id', field=models.UUIDField(verbose_name='Case ID')),
        migrations.AlterField(model_name='hrcalibrationrevision', name='proposed_by', field=models.UUIDField(null=True, verbose_name='提议人')),
        migrations.AlterField(model_name='hrcalibrationrevision', name='reason_code', field=models.CharField(default='', max_length=50, verbose_name='原因码')),
        migrations.AlterField(model_name='hrcalibrationrevision', name='reason_text', field=models.TextField(default='', verbose_name='原因说明')),
        migrations.AlterField(model_name='hrcalibrationrevision', name='session', field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='hr_assessment.hrcalibrationsession', verbose_name='所属会话')),
        migrations.AlterField(model_name='hrcalibrationrevision', name='timestamp', field=models.DateTimeField(auto_now_add=True, verbose_name='时间戳')),
        migrations.AlterField(model_name='hrcalibrationsession', name='classification_profile_json', field=models.JSONField(default=dict, verbose_name='分类 profile')),
        migrations.AlterField(model_name='hrcalibrationsession', name='closed_at', field=models.DateTimeField(null=True, verbose_name='关闭时间')),
        migrations.AlterField(model_name='hrcalibrationsession', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrcalibrationsession', name='cycle_id', field=models.UUIDField(verbose_name='所属周期 ID')),
        migrations.AlterField(model_name='hrcalibrationsession', name='facilitator_staff_id', field=models.UUIDField(null=True, verbose_name='主持人')),
        migrations.AlterField(model_name='hrcalibrationsession', name='opened_at', field=models.DateTimeField(null=True, verbose_name='打开时间')),
        migrations.AlterField(model_name='hrcalibrationsession', name='participants_json', field=models.JSONField(default=list, verbose_name='参与者')),
        migrations.AlterField(model_name='hrcalibrationsession', name='policy_version_id', field=models.UUIDField(null=True, verbose_name='政策版本 ID')),
        migrations.AlterField(model_name='hrcalibrationsession', name='scope_org_ids_json', field=models.JSONField(default=list, verbose_name='范围组织')),
        migrations.AlterField(model_name='hrcalibrationsession', name='session_status', field=models.CharField(default='OPEN', max_length=30, verbose_name='会话状态')),
        migrations.AlterField(model_name='hrcalibrationsession', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrcalibrationsession', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrcyclesnapshot', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrcyclesnapshot', name='cycle', field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='snapshot', to='hr_assessment.hrassessmentcycle', verbose_name='所属周期')),
        migrations.AlterField(model_name='hrcyclesnapshot', name='frozen_at', field=models.DateTimeField(auto_now_add=True, verbose_name='冻结时间')),
        migrations.AlterField(model_name='hrcyclesnapshot', name='frozen_deadlines_json', field=models.JSONField(default=dict, verbose_name='冻结的截止日期')),
        migrations.AlterField(model_name='hrcyclesnapshot', name='frozen_indicator_set_json', field=models.JSONField(default=dict, verbose_name='冻结的指标集')),
        migrations.AlterField(model_name='hrcyclesnapshot', name='frozen_org_scope_json', field=models.JSONField(default=dict, verbose_name='冻结的组织范围')),
        migrations.AlterField(model_name='hrcyclesnapshot', name='frozen_policy_json', field=models.JSONField(default=dict, verbose_name='冻结的政策版本')),
        migrations.AlterField(model_name='hrcyclesnapshot', name='frozen_population_query_definition', field=models.JSONField(default=dict, verbose_name='冻结的人群查询定义')),
        migrations.AlterField(model_name='hrcyclesnapshot', name='frozen_publicity_rule_json', field=models.JSONField(default=dict, verbose_name='冻结的公示规则')),
        migrations.AlterField(model_name='hrcyclesnapshot', name='frozen_rating_scale_json', field=models.JSONField(default=dict, verbose_name='冻结的评分尺度')),
        migrations.AlterField(model_name='hrcyclesnapshot', name='frozen_result_notice_rule_json', field=models.JSONField(default=dict, verbose_name='冻结的通知规则')),
        migrations.AlterField(model_name='hrcyclesnapshot', name='frozen_reviewer_rules_json', field=models.JSONField(default=dict, verbose_name='冻结的评议人规则')),
        migrations.AlterField(model_name='hrcyclesnapshot', name='frozen_workflow_json', field=models.JSONField(default=dict, verbose_name='冻结的工作流')),
        migrations.AlterField(model_name='hrcyclesnapshot', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrcyclesnapshot', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrethicsassessmentcase', name='decided_at', field=models.DateTimeField(null=True, verbose_name='确定时间')),
        migrations.AlterField(model_name='hrethicsassessmentcase', name='decided_by', field=models.UUIDField(null=True, verbose_name='确定人')),
        migrations.AlterField(model_name='hrethicsassessmentcase', name='ethics_policy_version_id', field=models.UUIDField(null=True, verbose_name='师德政策版本 ID')),
        migrations.AlterField(model_name='hrethicsassessmentcase', name='gate_reason_code', field=models.CharField(default='', max_length=50, verbose_name='Gate 原因码')),
        migrations.AlterField(model_name='hrethicsassessmentcase', name='gate_status', field=models.CharField(default='REVIEW_REQUIRED', max_length=30, verbose_name='Gate 状态')),
        migrations.AlterField(model_name='hrethicsassessmentcase', name='source_refs_json', field=models.JSONField(default=list, verbose_name='师德事实引用')),
        migrations.AlterField(model_name='hrexcellentquotapolicy', name='content_hash', field=models.CharField(blank=True, default='', max_length=64, verbose_name='内容哈希 (SHA-256)')),
        migrations.AlterField(model_name='hrexcellentquotapolicy', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrexcellentquotapolicy', name='status', field=models.CharField(db_index=True, default='DRAFT', max_length=30, verbose_name='状态')),
        migrations.AlterField(model_name='hrexcellentquotapolicy', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrexcellentquotapolicy', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrexcellentquotapolicy', name='version_no', field=models.PositiveIntegerField(default=1, verbose_name='版本号')),
        migrations.AlterField(model_name='hrfinalassessmentresult', name='assessment_type', field=models.CharField(max_length=30, verbose_name='考核类型')),
        migrations.AlterField(model_name='hrfinalassessmentresult', name='calculated_score', field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='计算分')),
        migrations.AlterField(model_name='hrfinalassessmentresult', name='case_id', field=models.UUIDField(unique=True, verbose_name='考核 Case ID')),
        migrations.AlterField(model_name='hrfinalassessmentresult', name='content_hash', field=models.CharField(default='', max_length=64, verbose_name='内容哈希')),
        migrations.AlterField(model_name='hrfinalassessmentresult', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrfinalassessmentresult', name='cycle_id', field=models.UUIDField(null=True, verbose_name='周期 ID')),
        migrations.AlterField(model_name='hrfinalassessmentresult', name='decision_reason', field=models.TextField(default='', verbose_name='审定理由')),
        migrations.AlterField(model_name='hrfinalassessmentresult', name='decision_session_id', field=models.UUIDField(null=True, verbose_name='审定会话 ID')),
        migrations.AlterField(model_name='hrfinalassessmentresult', name='display_grade_snapshot_json', field=models.JSONField(default=dict, verbose_name='档次显示快照')),
        migrations.AlterField(model_name='hrfinalassessmentresult', name='finalized_at', field=models.DateTimeField(null=True, verbose_name='审定时间')),
        migrations.AlterField(model_name='hrfinalassessmentresult', name='finalized_by', field=models.UUIDField(null=True, verbose_name='审定人')),
        migrations.AlterField(model_name='hrfinalassessmentresult', name='grade_code', field=models.CharField(max_length=30, verbose_name='档次代码')),
        migrations.AlterField(model_name='hrfinalassessmentresult', name='policy_version_id', field=models.UUIDField(null=True, verbose_name='政策版本 ID')),
    ]
