# Generated by Django 5.2 on 2026-08-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_assessment", "0012_result_fact_seals"),
    ]

    operations = [
        migrations.CreateModel(
            name="HrAssessmentPermissionMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("hr.assessment.policy.admin", "考核政策管理"),
                    ("hr.assessment.cycle.admin", "考核周期管理"),
                    ("hr.assessment.hr_reviewer", "校级人事评审"),
                    ("hr.assessment.college_reviewer", "学院评审"),
                    ("hr.assessment.manager_reviewer", "主管评审"),
                    ("hr.assessment.panel_member", "评审委员会成员"),
                    ("hr.assessment.calibration_manager", "校准管理"),
                    ("hr.assessment.final_decider", "审定决策"),
                    ("hr.assessment.result.correct", "追加更正或撤销已封板考核结果"),
                    ("hr.assessment.ethics_reviewer", "师德评审"),
                    ("hr.assessment.special_reviewer", "专项评审"),
                    ("hr.assessment.archive_manager", "档案管理"),
                    ("hr.assessment.auditor", "审计"),
                    ("hr.assessment.employee_self", "本人自助"),
                    ("hr.assessment.analytics_view", "统计分析"),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
