# Generated by Django 5.2 on 2026-08-30 10:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def classify_existing_versions(apps, schema_editor):
    Version = apps.get_model("hr_contracts", "HrContractVersion")
    alias = schema_editor.connection.alias
    Version.objects.using(alias).filter(source_business_type="RENEW").update(
        version_type="RENEWAL"
    )
    Version.objects.using(alias).filter(source_business_type="CHANGE").update(
        version_type="AMENDMENT"
    )


def install_mysql_authority_seals(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    trigger_names = (
        "hr07_agreement_guard_update",
        "hr07_agreement_guard_delete",
        "hr07_version_guard_update",
        "hr07_version_guard_delete",
        "hr07_version_action_no_update",
        "hr07_version_action_no_delete",
    )
    for trigger_name in trigger_names:
        schema_editor.execute(f"DROP TRIGGER IF EXISTS {trigger_name}")
    schema_editor.execute(
        """
        CREATE TRIGGER hr07_agreement_guard_update
        BEFORE UPDATE ON hr07_contract_agreement
        FOR EACH ROW
        BEGIN
            IF OLD.current_version_no > 0 AND (
                NOT (OLD.tenant_id <=> NEW.tenant_id) OR
                NOT (OLD.agreement_no <=> NEW.agreement_no) OR
                NOT (OLD.subject_type <=> NEW.subject_type) OR
                NOT (OLD.staff_id <=> NEW.staff_id) OR
                NOT (OLD.employment_relationship_id <=> NEW.employment_relationship_id) OR
                NOT (OLD.subject_person_id <=> NEW.subject_person_id) OR
                NOT (OLD.subject_reference_type <=> NEW.subject_reference_type) OR
                NOT (OLD.subject_reference_id <=> NEW.subject_reference_id) OR
                NOT (OLD.agreement_title <=> NEW.agreement_title) OR
                NOT (OLD.agreement_type <=> NEW.agreement_type) OR
                NOT (OLD.legacy_contract_id <=> NEW.legacy_contract_id)
            ) THEN
                SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'HR07_FORMAL_AGREEMENT_IDENTITY_IMMUTABLE';
            END IF;
        END
        """
    )
    schema_editor.execute(
        """
        CREATE TRIGGER hr07_agreement_guard_delete
        BEFORE DELETE ON hr07_contract_agreement
        FOR EACH ROW
        BEGIN
            IF OLD.status <> 'DRAFT' OR OLD.current_version_no > 0 THEN
                SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'HR07_FORMAL_AGREEMENT_NO_DELETE';
            END IF;
        END
        """
    )
    schema_editor.execute(
        """
        CREATE TRIGGER hr07_version_guard_update
        BEFORE UPDATE ON hr07_contract_version
        FOR EACH ROW
        BEGIN
            IF OLD.status <> 'DRAFT' AND (
                NOT (OLD.tenant_id <=> NEW.tenant_id) OR
                NOT (OLD.agreement_id <=> NEW.agreement_id) OR
                NOT (OLD.version_no <=> NEW.version_no) OR
                NOT (OLD.version_type <=> NEW.version_type) OR
                NOT (OLD.effective_from <=> NEW.effective_from) OR
                NOT (OLD.signed_at <=> NEW.signed_at) OR
                NOT (OLD.signed_document_ref <=> NEW.signed_document_ref) OR
                NOT (OLD.content_snapshot_json <=> NEW.content_snapshot_json) OR
                NOT (OLD.content_hash <=> NEW.content_hash) OR
                NOT (OLD.supersedes_version_id <=> NEW.supersedes_version_id) OR
                NOT (OLD.source_business_type <=> NEW.source_business_type) OR
                NOT (OLD.source_business_id <=> NEW.source_business_id) OR
                NOT (OLD.created_at <=> NEW.created_at) OR
                NOT (OLD.created_by <=> NEW.created_by)
            ) THEN
                SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'HR07_SIGNED_VERSION_CONTENT_IMMUTABLE';
            END IF;
            IF NOT (OLD.effective_to <=> NEW.effective_to) AND NOT (
                OLD.status = 'EFFECTIVE' AND NEW.status IN ('SUPERSEDED', 'TERMINATED')
            ) THEN
                SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'HR07_SIGNED_VERSION_DATE_IMMUTABLE';
            END IF;
            IF NOT (OLD.status <=> NEW.status) AND NOT (
                (OLD.status = 'DRAFT' AND NEW.status = 'SIGNED') OR
                (OLD.status = 'SIGNED' AND NEW.status IN ('EFFECTIVE', 'VOID')) OR
                (OLD.status = 'EFFECTIVE' AND NEW.status IN ('SUPERSEDED', 'TERMINATED', 'EXPIRED', 'VOID'))
            ) THEN
                SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'HR07_VERSION_STATUS_TRANSITION_INVALID';
            END IF;
        END
        """
    )
    schema_editor.execute(
        """
        CREATE TRIGGER hr07_version_guard_delete
        BEFORE DELETE ON hr07_contract_version
        FOR EACH ROW
        BEGIN
            IF OLD.status <> 'DRAFT' THEN
                SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'HR07_SIGNED_VERSION_NO_DELETE';
            END IF;
        END
        """
    )
    schema_editor.execute(
        """
        CREATE TRIGGER hr07_version_action_no_update
        BEFORE UPDATE ON hr07_contract_version_action
        FOR EACH ROW
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'HR07_VERSION_ACTION_APPEND_ONLY_UPDATE'
        """
    )
    schema_editor.execute(
        """
        CREATE TRIGGER hr07_version_action_no_delete
        BEFORE DELETE ON hr07_contract_version_action
        FOR EACH ROW
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'HR07_VERSION_ACTION_APPEND_ONLY_DELETE'
        """
    )


def remove_mysql_authority_seals(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    for trigger_name in (
        "hr07_agreement_guard_update",
        "hr07_agreement_guard_delete",
        "hr07_version_guard_update",
        "hr07_version_guard_delete",
        "hr07_version_action_no_update",
        "hr07_version_action_no_delete",
    ):
        schema_editor.execute(f"DROP TRIGGER IF EXISTS {trigger_name}")


class Migration(migrations.Migration):

    # MySQL CREATE/DROP TRIGGER causes an implicit commit and must never run
    # inside Django's migration transaction boundary.
    atomic = False

    dependencies = [
        ('hr_contracts', '0002_external_workforce_agreement_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrContractVersionAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('CORRECTION', 'Correction'), ('VOID', 'Void')], db_index=True, max_length=16)),
                ('reason', models.TextField()),
                ('evidence_ref', models.CharField(max_length=255)),
                ('authority_ref', models.CharField(max_length=200)),
                ('authority_receipt_json', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('sealed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'hr07_contract_version_action',
            },
        ),
        migrations.AddField(
            model_name='hrcontractversion',
            name='version_type',
            field=models.CharField(choices=[('INITIAL', 'Initial'), ('RENEWAL', 'Renewal'), ('AMENDMENT', 'Amendment'), ('CORRECTION', 'Correction'), ('MIGRATION', 'Migration')], db_index=True, default='INITIAL', max_length=16),
        ),
        migrations.AlterField(
            model_name='hrcontractversion',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SIGNED', 'Signed'), ('EFFECTIVE', 'Effective'), ('SUPERSEDED', 'Superseded'), ('TERMINATED', 'Terminated'), ('EXPIRED', 'Expired'), ('VOID', 'Void')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.RunPython(
            classify_existing_versions,
            migrations.RunPython.noop,
            atomic=True,
        ),
        migrations.AddConstraint(
            model_name='hrcontractversion',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'supersedes_version_id'), name='uq_hr07_ver_successor'),
        ),
        migrations.AddField(
            model_name='hrcontractversionaction',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='version_actions', to='hr_contracts.hrcontractagreement'),
        ),
        migrations.AddField(
            model_name='hrcontractversionaction',
            name='source_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authority_actions', to='hr_contracts.hrcontractversion'),
        ),
        migrations.AddField(
            model_name='hrcontractversionaction',
            name='successor_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_authority_action', to='hr_contracts.hrcontractversion'),
        ),
        migrations.AddIndex(
            model_name='hrcontractversionaction',
            index=models.Index(fields=['tenant_id', 'agreement', 'created_at'], name='idx_hr07_ver_action_agree'),
        ),
        migrations.AddConstraint(
            model_name='hrcontractversionaction',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'idempotency_key'), name='uq_hr07_ver_action_key'),
        ),
        migrations.AddConstraint(
            model_name='hrcontractversionaction',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'source_version', 'kind'), name='uq_hr07_ver_action_source_kind'),
        ),
        migrations.AddConstraint(
            model_name='hrcontractversionaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'CORRECTION'), ('successor_version__isnull', False)), models.Q(('kind', 'VOID'), ('successor_version__isnull', True)), _connector='OR'), name='ck_hr07_ver_action_shape'),
        ),
        migrations.RunPython(
            install_mysql_authority_seals,
            remove_mysql_authority_seals,
            atomic=False,
        ),
    ]
