# Generated by Django 5.2 on 2026-08-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_contracts", "0003_hrcontractversionaction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HrContractsPermissionMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("hr.contracts.agreement.view", "查看学校合同主档及正式版本"),
                    ("hr.contracts.agreement.create", "创建合同主档"),
                    ("hr.contracts.agreement.sign", "冻结首个签署版本"),
                    ("hr.contracts.agreement.activate", "使已签署版本正式生效"),
                    ("hr.contracts.case.create", "发起合同续签、变更或解除业务单"),
                    ("hr.contracts.case.submit", "提交合同续签、变更或解除业务单"),
                    ("hr.contracts.case.approve", "审批合同续签、变更或解除业务单"),
                    ("hr.contracts.case.sign", "冻结续签或变更后的新合同版本"),
                    ("hr.contracts.case.activate", "使续签或变更后的新合同版本生效"),
                    ("hr.contracts.case.terminate", "执行已批准合同解除生效"),
                    ("hr.contracts.version.correct", "更正已签署合同并追加正式后继版本"),
                    ("hr.contracts.version.void", "作废错误、重复或法律上未成立的签署版本"),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
