# Generated by Django 5.2 on 2026-08-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrrecruitmentposition',
            name='reservation_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='hrrecruitmentposition',
            name='reservation_no',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
