# Generated by Django 5.2 on 2026-08-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_recruitment', '0002_hrrecruitmentposition_reservation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrrecruitmentcampaign',
            name='public_token',
            field=models.CharField(blank=True, default='', max_length=64, unique=True),
        ),
    ]
