# Generated by Django 5.2 on 2026-08-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_recruitment', '0003_hrrecruitmentcampaign_public_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrproposedhire',
            name='reservation_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='hrrecruitmenthandoff',
            name='reservation_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
    ]
