# Generated by Django 5.2 on 2026-08-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_recruitment', '0005_alter_hrrecruitmentpermissionmeta_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hrrecruitmentposition',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'campaign_id', 'public_slug'), name='uniq_hr_position_slug_per_campaign'),
        ),
    ]
