# Generated by Django 5.2 on 2026-08-09 12:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_recruitment', '0008_remove_hrselectionresultsnapshot_uniq_hr_selection_rank_per_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrAssessmentParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_participations', to='hr_recruitment.hrjobapplication', verbose_name='Application')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='hr_recruitment.hrassessmentevent', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Assessment Participant',
                'verbose_name_plural': 'Assessment Participants',
                'indexes': [models.Index(fields=['tenant_id', 'event_id'], name='hr_recruitm_tenant__9200c3_idx'), models.Index(fields=['tenant_id', 'application_id'], name='hr_recruitm_tenant__4b6fca_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'event_id', 'application_id'), name='uniq_hr_assessment_participant_event_app')],
            },
        ),
    ]
