# Generated by Django 5.2 on 2026-08-30 10:30

import hashlib
import json

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


SEALED_TABLES = (
    ("hr04_hiring_decision_fact", "HR04_HIRING_FACT_IMMUTABLE"),
    ("hr04_hiring_decision_revision", "HR04_HIRING_REVISION_IMMUTABLE"),
)


def _hash(payload):
    encoded = json.dumps(
        payload,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
        default=str,
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def backfill_accepted_hiring_facts(apps, schema_editor):
    Offer = apps.get_model("hr_recruitment", "HrRecruitmentOffer")
    Fact = apps.get_model("hr_recruitment", "HrHiringDecisionFact")
    for offer in Offer.objects.filter(status="ACCEPTED").select_related(
        "proposed_hire_id__application_id__candidate_id",
        "proposed_hire_id__application_id__recruitment_position_id",
    ).iterator(chunk_size=500):
        proposed = offer.proposed_hire_id
        application = proposed.application_id
        candidate = application.candidate_id
        position = application.recruitment_position_id
        tenants = {
            int(offer.tenant_id),
            int(proposed.tenant_id),
            int(application.tenant_id),
            int(candidate.tenant_id),
            int(position.tenant_id),
        }
        if (
            len(tenants) != 1
            or proposed.recruitment_position_id_id
            != application.recruitment_position_id_id
            or proposed.approval_status != "APPROVE"
        ):
            continue
        accepted_at = offer.accepted_at or offer.updated_at or offer.created_at
        payload = {
            "tenantId": int(offer.tenant_id),
            "offerId": str(offer.id),
            "proposedHireId": str(proposed.id),
            "applicationId": str(application.id),
            "candidateId": str(candidate.id),
            "recruitmentPositionId": str(position.id),
            "offerNo": offer.offer_no,
            "rank": int(proposed.rank),
            "finalScore": str(proposed.final_score),
            "employmentType": offer.employment_type or "",
            "expectedReportDate": (
                offer.expected_report_date.isoformat()
                if offer.expected_report_date
                else None
            ),
            "acceptedAt": accepted_at.isoformat(),
            "approvedAt": (
                proposed.approved_at.isoformat() if proposed.approved_at else None
            ),
            "approvedBy": proposed.approved_by or "",
            "status": "EFFECTIVE",
            "version": 1,
        }
        Fact.objects.create(
            id=uuid.uuid4(),
            tenant_id=offer.tenant_id,
            offer_id=offer.id,
            proposed_hire_id=proposed.id,
            application_id=application.id,
            candidate_id=candidate.id,
            recruitment_position_id=position.id,
            offer_no=offer.offer_no,
            rank=proposed.rank,
            final_score=proposed.final_score,
            employment_type=offer.employment_type or "",
            expected_report_date=offer.expected_report_date,
            accepted_at=accepted_at,
            approved_at=proposed.approved_at,
            approved_by=proposed.approved_by or "",
            content_hash=_hash(payload),
            sealed_at=accepted_at,
            created_by=offer.created_by or "MIGRATION",
        )


def install_mysql_hiring_seals(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    for table, code in SEALED_TABLES:
        schema_editor.execute(f"DROP TRIGGER IF EXISTS {table}_seal_insert")
        schema_editor.execute(f"DROP TRIGGER IF EXISTS {table}_no_update")
        schema_editor.execute(f"DROP TRIGGER IF EXISTS {table}_no_delete")
        schema_editor.execute(
            f"""
            CREATE TRIGGER {table}_no_update
            BEFORE UPDATE ON {table}
            FOR EACH ROW
            SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = '{code}: append a correction fact'
            """
        )
        schema_editor.execute(
            f"""
            CREATE TRIGGER {table}_no_delete
            BEFORE DELETE ON {table}
            FOR EACH ROW
            SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = '{code}: formal facts cannot be deleted'
            """
        )
    schema_editor.execute(
        """
        CREATE TRIGGER hr04_hiring_decision_fact_seal_insert
        BEFORE INSERT ON hr04_hiring_decision_fact
        FOR EACH ROW
        BEGIN
            IF NEW.sealed_at IS NULL
               OR NEW.content_hash NOT REGEXP '^[0-9a-f]{64}$' THEN
                SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'HR04_HIRING_FACT_SEAL_REQUIRED';
            END IF;
            IF (
                SELECT COUNT(*)
                FROM hr_recruitment_hrrecruitmentoffer o
                JOIN hr_recruitment_hrproposedhire p
                  ON p.id = o.proposed_hire_id_id
                JOIN hr_recruitment_hrjobapplication a
                  ON a.id = p.application_id_id
                JOIN hr_recruitment_hrrecruitmentcandidate c
                  ON c.id = a.candidate_id_id
                JOIN hr_recruitment_hrrecruitmentposition rp
                  ON rp.id = a.recruitment_position_id_id
                WHERE o.id = NEW.offer_id
                  AND p.id = NEW.proposed_hire_id
                  AND a.id = NEW.application_id
                  AND c.id = NEW.candidate_id
                  AND rp.id = NEW.recruitment_position_id
                  AND o.tenant_id = NEW.tenant_id
                  AND p.tenant_id = NEW.tenant_id
                  AND a.tenant_id = NEW.tenant_id
                  AND c.tenant_id = NEW.tenant_id
                  AND rp.tenant_id = NEW.tenant_id
                  AND p.recruitment_position_id_id = a.recruitment_position_id_id
                  AND o.status = 'ACCEPTED'
                  AND p.approval_status = 'APPROVE'
                  AND NEW.offer_no = o.offer_no
                  AND NEW.rank = p.rank
                  AND NEW.final_score = p.final_score
                  AND NEW.employment_type = COALESCE(o.employment_type, '')
                  AND (NEW.expected_report_date <=> o.expected_report_date)
                  AND NEW.accepted_at = o.accepted_at
                  AND (NEW.approved_at <=> p.approved_at)
                  AND NEW.approved_by = COALESCE(p.approved_by, '')
            ) <> 1 THEN
                SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'HR04_HIRING_PARENT_LINEAGE_INVALID';
            END IF;
        END
        """
    )
    schema_editor.execute(
        """
        CREATE TRIGGER hr04_hiring_decision_revision_seal_insert
        BEFORE INSERT ON hr04_hiring_decision_revision
        FOR EACH ROW
        BEGIN
            IF NEW.sealed_at IS NULL
               OR NEW.content_hash NOT REGEXP '^[0-9a-f]{64}$' THEN
                SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'HR04_HIRING_REVISION_SEAL_REQUIRED';
            END IF;
            IF NEW.revision_type NOT IN ('CORRECTION', 'REVOCATION')
               OR NEW.new_version <> NEW.previous_version + 1 THEN
                SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'HR04_HIRING_REVISION_STATE_INVALID';
            END IF;
            IF (SELECT COUNT(*) FROM hr04_hiring_decision_fact f
                WHERE f.id = NEW.fact_id AND f.tenant_id = NEW.tenant_id) <> 1 THEN
                SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'HR04_HIRING_REVISION_PARENT_INVALID';
            END IF;
            IF NEW.previous_version <> (
                SELECT COALESCE(MAX(r.new_version), 1)
                FROM hr04_hiring_decision_revision r
                WHERE r.fact_id = NEW.fact_id
            ) THEN
                SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'HR04_HIRING_REVISION_VERSION_CONFLICT';
            END IF;
            IF EXISTS (
                SELECT 1 FROM hr04_hiring_decision_revision r
                WHERE r.fact_id = NEW.fact_id AND r.revision_type = 'REVOCATION'
            ) THEN
                SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'HR04_HIRING_FACT_ALREADY_REVOKED';
            END IF;
        END
        """
    )


def remove_mysql_hiring_seals(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    for table, _code in SEALED_TABLES:
        schema_editor.execute(f"DROP TRIGGER IF EXISTS {table}_seal_insert")
        schema_editor.execute(f"DROP TRIGGER IF EXISTS {table}_no_update")
        schema_editor.execute(f"DROP TRIGGER IF EXISTS {table}_no_delete")


class Migration(migrations.Migration):

    dependencies = [
        ('hr_recruitment', '0011_alter_hrrecruitmentpermissionmeta_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hrrecruitmentpermissionmeta',
            options={'managed': False, 'permissions': (('hr04.plan.view', 'Hr04 Plan View'), ('hr04.plan.create', 'Hr04 Plan Create'), ('hr04.plan.approve', 'Hr04 Plan Approve'), ('hr04.campaign.view', 'Hr04 Campaign View'), ('hr04.campaign.manage', 'Hr04 Campaign Manage'), ('hr04.campaign.publish', 'Hr04 Campaign Publish'), ('hr04.application.view', 'Hr04 Application View'), ('hr04.application.manage', 'Hr04 Application Manage'), ('hr04.application.sensitive_view', 'Hr04 Application Sensitive_View'), ('hr04.application.export', 'Hr04 Application Export'), ('hr04.qualification.review', 'Hr04 Qualification Review'), ('hr04.qualification.finalize', 'Hr04 Qualification Finalize'), ('hr04.assessment.manage', 'Hr04 Assessment Manage'), ('hr04.assessment.score', 'Hr04 Assessment Score'), ('hr04.assessment.score_override', 'Hr04 Assessment Score_Override'), ('hr04.assessment.unlock_score', 'Hr04 Assessment Unlock_Score'), ('hr04.proposed_hire.manage', 'Hr04 Proposed_Hire Manage'), ('hr04.public_notice.publish', 'Hr04 Public_Notice Publish'), ('hr04.offer.manage', 'Hr04 Offer Manage'), ('hr04.hiring_decision.correct', 'Hr04 Hiring_Decision Correct'), ('hr04.hiring_decision.revoke', 'Hr04 Hiring_Decision Revoke'), ('hr04.handoff_hr05', 'Hr04 Handoff_Hr05'))},
        ),
        migrations.CreateModel(
            name='HrHiringDecisionFact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('offer_no', models.CharField(max_length=64)),
                ('rank', models.PositiveIntegerField()),
                ('final_score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('employment_type', models.CharField(blank=True, default='', max_length=64)),
                ('expected_report_date', models.DateField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, default='', max_length=128)),
                ('content_hash', models.CharField(max_length=64)),
                ('sealed_at', models.DateTimeField()),
                ('created_by', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hiring_decision_facts', to='hr_recruitment.hrjobapplication')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hiring_decision_facts', to='hr_recruitment.hrrecruitmentcandidate')),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hiring_decision_fact', to='hr_recruitment.hrrecruitmentoffer')),
                ('proposed_hire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hiring_decision_facts', to='hr_recruitment.hrproposedhire')),
                ('recruitment_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hiring_decision_facts', to='hr_recruitment.hrrecruitmentposition')),
            ],
            options={
                'db_table': 'hr04_hiring_decision_fact',
            },
        ),
        migrations.CreateModel(
            name='HrHiringDecisionRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('correction_no', models.CharField(max_length=80)),
                ('previous_version', models.PositiveIntegerField()),
                ('new_version', models.PositiveIntegerField()),
                ('revision_type', models.CharField(choices=[('CORRECTION', 'Correction'), ('REVOCATION', 'Revocation')], max_length=16)),
                ('reason', models.TextField()),
                ('authority_actor_id', models.CharField(max_length=128)),
                ('evidence_ref', models.CharField(blank=True, default='', max_length=255)),
                ('before_snapshot_json', models.JSONField(default=dict)),
                ('after_snapshot_json', models.JSONField(default=dict)),
                ('effective_at', models.DateTimeField()),
                ('content_hash', models.CharField(max_length=64)),
                ('sealed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='hr_recruitment.hrhiringdecisionfact')),
            ],
            options={
                'db_table': 'hr04_hiring_decision_revision',
            },
        ),
        migrations.AddIndex(
            model_name='hrhiringdecisionfact',
            index=models.Index(fields=['tenant_id', 'candidate', 'accepted_at'], name='idx_hr04_hire_candidate'),
        ),
        migrations.AddIndex(
            model_name='hrhiringdecisionfact',
            index=models.Index(fields=['tenant_id', 'recruitment_position', 'accepted_at'], name='idx_hr04_hire_position'),
        ),
        migrations.AddIndex(
            model_name='hrhiringdecisionrevision',
            index=models.Index(fields=['tenant_id', 'fact', 'new_version'], name='idx_hr04_hire_revision'),
        ),
        migrations.AddConstraint(
            model_name='hrhiringdecisionrevision',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'correction_no'), name='uq_hr04_hire_revision_key'),
        ),
        migrations.AddConstraint(
            model_name='hrhiringdecisionrevision',
            constraint=models.UniqueConstraint(fields=('fact', 'new_version'), name='uq_hr04_hire_revision_ver'),
        ),
        migrations.AddConstraint(
            model_name='hrhiringdecisionrevision',
            constraint=models.CheckConstraint(condition=models.Q(('new_version', django.db.models.expressions.CombinedExpression(models.F('previous_version'), '+', models.Value(1)))), name='ck_hr04_hire_revision_next'),
        ),
        migrations.RunPython(
            backfill_accepted_hiring_facts,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            install_mysql_hiring_seals,
            remove_mysql_hiring_seals,
        ),
    ]
