"""
hr_qualification/api/urls.py —— HR09 REST API 路由（总册 §107-111）。

前缀：/api/v1/hr/qualifications/
"""

from django.urls import path

from hr_qualification.api import views_credential, views_rule, views_application, views_review

urlpatterns = [
    # ---- Credential（总册 §107）----
    path(
        "api/v1/hr/qualifications/credentials",
        views_credential.credential_list,
        name="api-qualification-credential-list",
    ),
    path(
        "api/v1/hr/qualifications/credentials/create",
        views_credential.credential_create,
        name="api-qualification-credential-create",
    ),
    path(
        "api/v1/hr/qualifications/credentials/exact-match",
        views_credential.credential_exact_match,
        name="api-qualification-credential-exact-match",
    ),
    path(
        "api/v1/hr/qualifications/credentials/<str:credential_id>",
        views_credential.credential_detail,
        name="api-qualification-credential-detail",
    ),
    path(
        "api/v1/hr/qualifications/credentials/<str:credential_id>/patch",
        views_credential.credential_update,
        name="api-qualification-credential-update",
    ),
    path(
        "api/v1/hr/qualifications/credentials/<str:credential_id>/submit-verification",
        views_credential.credential_submit_verification,
        name="api-qualification-credential-submit-verification",
    ),
    path(
        "api/v1/hr/qualifications/credentials/<str:credential_id>/verify",
        views_credential.credential_verify,
        name="api-qualification-credential-verify",
    ),
    path(
        "api/v1/hr/qualifications/credentials/<str:credential_id>/renew",
        views_credential.credential_renew,
        name="api-qualification-credential-renew",
    ),
    path(
        "api/v1/hr/qualifications/credentials/<str:credential_id>/suspend",
        views_credential.credential_suspend,
        name="api-qualification-credential-suspend",
    ),
    path(
        "api/v1/hr/qualifications/credentials/<str:credential_id>/revoke",
        views_credential.credential_revoke,
        name="api-qualification-credential-revoke",
    ),
    path(
        "api/v1/hr/qualifications/credentials/<str:credential_id>/verifications",
        views_credential.credential_verification_history,
        name="api-qualification-credential-verifications",
    ),
    # ---- Credential Catalog + Advanced ----
    path(
        "api/v1/hr/qualifications/catalog",
        views_credential.catalog_list,
        name="api-qualification-catalog-list",
    ),
    path(
        "api/v1/hr/qualifications/credentials/<str:credential_id>/requirement-match",
        views_credential.requirement_match,
        name="api-qualification-credential-requirement-match",
    ),
    path(
        "api/v1/hr/qualifications/credentials/<str:credential_id>/status-history",
        views_credential.credential_status_history,
        name="api-qualification-credential-status-history",
    ),
    path(
        "api/v1/hr/qualifications/credentials/<str:credential_id>/risk-scan",
        views_credential.credential_risk_scan,
        name="api-qualification-credential-risk-scan",
    ),
    path(
        "api/v1/hr/qualifications/credentials/<str:credential_id>/documents",
        views_credential.credential_documents,
        name="api-qualification-credential-documents",
    ),

    # ---- Rule Pack（总册 §108）----
    path(
        "api/v1/hr/qualifications/double-teacher/rule-packs",
        views_rule.rule_pack_list,
        name="api-qualification-rule-pack-list",
    ),
    path(
        "api/v1/hr/qualifications/double-teacher/rule-packs/create",
        views_rule.rule_pack_create,
        name="api-qualification-rule-pack-create",
    ),
    path(
        "api/v1/hr/qualifications/double-teacher/rule-packs/<str:pack_id>",
        views_rule.rule_pack_detail,
        name="api-qualification-rule-pack-detail",
    ),
    path(
        "api/v1/hr/qualifications/double-teacher/rule-packs/<str:pack_id>/versions",
        views_rule.rule_version_create,
        name="api-qualification-rule-version-create",
    ),
    path(
        "api/v1/hr/qualifications/double-teacher/rule-versions/<str:version_id>",
        views_rule.rule_version_detail,
        name="api-qualification-rule-version-detail",
    ),
    path(
        "api/v1/hr/qualifications/double-teacher/rule-versions/<str:version_id>/validate",
        views_rule.rule_version_validate,
        name="api-qualification-rule-version-validate",
    ),
    path(
        "api/v1/hr/qualifications/double-teacher/rule-versions/<str:version_id>/publish",
        views_rule.rule_version_publish,
        name="api-qualification-rule-version-publish",
    ),
    path(
        "api/v1/hr/qualifications/double-teacher/rule-versions/<str:version_id>/diff",
        views_rule.rule_version_diff,
        name="api-qualification-rule-version-diff",
    ),
    path(
        "api/v1/hr/qualifications/double-teacher/rule-versions/<str:version_id>/rules",
        views_rule.rule_create,
        name="api-qualification-rule-create",
    ),

    # ---- Batch + Application（总册 §109）----
    path(
        "api/v1/hr/qualifications/double-teacher/batches",
        views_application.batch_list,
        name="api-qualification-batch-list",
    ),
    path(
        "api/v1/hr/qualifications/double-teacher/batches/create",
        views_application.batch_create,
        name="api-qualification-batch-create",
    ),
    path(
        "api/v1/hr/qualifications/double-teacher/batches/<str:batch_id>",
        views_application.batch_detail,
        name="api-qualification-batch-detail",
    ),
    path(
        "api/v1/hr/qualifications/double-teacher/batches/<str:batch_id>/advance",
        views_application.batch_advance,
        name="api-qualification-batch-advance",
    ),
    path(
        "api/v1/hr/qualifications/double-teacher/applications",
        views_application.application_create,
        name="api-qualification-application-create",
    ),
    path(
        "api/v1/hr/qualifications/double-teacher/applications/mine",
        views_application.my_applications,
        name="api-qualification-application-mine",
    ),
    path(
        "api/v1/hr/qualifications/double-teacher/applications/<str:app_id>",
        views_application.application_detail,
        name="api-qualification-application-detail",
    ),
    path(
        "api/v1/hr/qualifications/double-teacher/applications/<str:app_id>/precheck",
        views_application.application_precheck,
        name="api-qualification-application-precheck",
    ),
    path(
        "api/v1/hr/qualifications/double-teacher/applications/<str:app_id>/submit",
        views_application.application_submit,
        name="api-qualification-application-submit",
    ),
    path(
        "api/v1/hr/qualifications/double-teacher/applications/<str:app_id>/withdraw",
        views_application.application_withdraw,
        name="api-qualification-application-withdraw",
    ),
    path(
        "api/v1/hr/qualifications/double-teacher/applications/<str:app_id>/resubmit",
        views_application.application_resubmit,
        name="api-qualification-application-resubmit",
    ),

    # ---- Review（总册 §110）----
    path(
        "api/v1/hr/qualifications/double-teacher/applications/<str:app_id>/formal-review",
        views_review.application_formal_review,
        name="api-qualification-application-formal-review",
    ),
    path(
        "api/v1/hr/qualifications/double-teacher/applications/<str:app_id>/return",
        views_review.application_return,
        name="api-qualification-application-return",
    ),
    path(
        "api/v1/hr/qualifications/double-teacher/applications/<str:app_id>/mark-eligible",
        views_review.application_mark_eligible,
        name="api-qualification-application-mark-eligible",
    ),
    path(
        "api/v1/hr/qualifications/double-teacher/score-sheets/<str:sheet_id>/submit",
        views_review.score_sheet_submit,
        name="api-qualification-score-sheet-submit",
    ),
    path(
        "api/v1/hr/qualifications/double-teacher/panel-decisions",
        views_review.panel_decision_create,
        name="api-qualification-panel-decision-create",
    ),
    path(
        "api/v1/hr/qualifications/double-teacher/final-decisions",
        views_review.final_decision_create,
        name="api-qualification-final-decision-create",
    ),

    # ---- Recognition / Recheck / Risk（总册 §111）----
    path(
        "api/v1/hr/qualifications/double-teacher/recognitions",
        views_review.recognition_list,
        name="api-qualification-recognition-list",
    ),
    path(
        "api/v1/hr/qualifications/double-teacher/recognitions/<str:recognition_id>",
        views_review.recognition_detail,
        name="api-qualification-recognition-detail",
    ),
    path(
        "api/v1/hr/qualifications/double-teacher/recognitions/<str:recognition_id>/recheck",
        views_review.recognition_recheck,
        name="api-qualification-recognition-recheck",
    ),
    path(
        "api/v1/hr/qualifications/double-teacher/rechecks/<str:recheck_id>/decide",
        views_review.recheck_decide,
        name="api-qualification-recheck-decide",
    ),
    path(
        "api/v1/hr/qualifications/risks",
        views_review.risk_list,
        name="api-qualification-risk-list",
    ),
    path(
        "api/v1/hr/qualifications/risks/<str:risk_id>/acknowledge",
        views_review.risk_acknowledge,
        name="api-qualification-risk-acknowledge",
    ),
    path(
        "api/v1/hr/qualifications/risks/<str:risk_id>/resolve",
        views_review.risk_resolve,
        name="api-qualification-risk-resolve",
    ),
]
