# Generated by Django 5.2 on 2026-08-09 (HR08-S1 hand-written, model-aligned)

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HrExternalCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('is_system_builtin', models.BooleanField(default=False)),
                ('requires_open_selection', models.BooleanField(default=False)),
                ('requires_ethics_review', models.BooleanField(default=True)),
                ('requires_teacher_qualification', models.BooleanField(default=False)),
                ('requires_industry_experience', models.BooleanField(default=False)),
                ('default_engagement_months', models.PositiveIntegerField(blank=True, null=True)),
                ('allow_multiple_assignments', models.BooleanField(default=True)),
                ('allow_teaching', models.BooleanField(default=False)),
                ('allow_research', models.BooleanField(default=False)),
                ('agreement_requirement', models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('REQUIRED_BEFORE_ACTIVATION', 'Required Before Activation'), ('REQUIRED_AFTER_ACTIVATION_GRACE', 'Required After Activation Grace')], default='REQUIRED_BEFORE_ACTIVATION', max_length=32)),
                ('agreement_type_code', models.CharField(blank=True, default='', max_length=64)),
                ('access_policy_code', models.CharField(blank=True, default='', max_length=64)),
                ('settlement_policy_code', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.BigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HR External Category',
                'verbose_name_plural': 'HR External Categories',
                'ordering': ['code'],
                'indexes': [
                    models.Index(fields=['tenant_id', 'is_active'], name='hr_external_cat_tenant_active_idx'),
                    models.Index(fields=['tenant_id', 'code'], name='hr_external_cat_tenant_code_idx'),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name='hrexternalcategory',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'code'), name='uniq_hr_external_category_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='hrexternalcategory',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='hr_external_category_version_gte_1'),
        ),
    ]
