# Generated by Django 5.2 on 2026-08-09 (HR08-S3 hand-written, model-aligned)

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_external", "0002_authority_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="HrExternalImportJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.BigIntegerField(db_index=True)),
                ("job_type", models.CharField(choices=[("PROFILE", "External Teacher Profile"), ("ENGAGEMENT", "Engagement"), ("TASK", "Service Task"), ("WORKLOAD", "Workload")], max_length=24)),
                ("template_version", models.CharField(blank=True, default="", max_length=32)),
                ("status", models.CharField(choices=[("UPLOADED", "Uploaded"), ("VALIDATING", "Validating"), ("VALIDATION_FAILED", "Validation Failed"), ("READY_TO_COMMIT", "Ready To Commit"), ("COMMITTING", "Committing"), ("COMPLETED", "Completed"), ("PARTIAL_FAILED", "Partial Failed"), ("FAILED", "Failed")], db_index=True, default="UPLOADED", max_length=24)),
                ("file_name", models.CharField(blank=True, default="", max_length=255)),
                ("file_ref", models.CharField(blank=True, default="", max_length=255)),
                ("error_workbook_ref", models.CharField(blank=True, default="", max_length=255)),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("success_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("error_summary_json", models.JSONField(blank=True, default=dict)),
                ("created_by", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "HR External Import Job",
                "verbose_name_plural": "HR External Import Jobs",
            },
        ),
        migrations.CreateModel(
            name="HrExternalImportRow",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.BigIntegerField(db_index=True)),
                ("row_no", models.PositiveIntegerField()),
                ("raw_json", models.JSONField(blank=True, default=dict)),
                ("validation_issues", models.JSONField(blank=True, default=list)),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("VALID", "Valid"), ("INVALID", "Invalid"), ("PREVIEW", "Preview"), ("COMMITTED", "Committed"), ("FAILED", "Failed"), ("SKIPPED", "Skipped")], default="PENDING", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("job_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="rows", to="hr_external.hrexternalimportjob")),
            ],
            options={
                "verbose_name": "HR External Import Row",
                "verbose_name_plural": "HR External Import Rows",
            },
        ),
        migrations.AddIndex(
            model_name="hrexternalimportjob",
            index=models.Index(fields=["tenant_id", "status"], name="hr_external_import_status_idx"),
        ),
        migrations.AddIndex(
            model_name="hrexternalimportjob",
            index=models.Index(fields=["tenant_id", "job_type", "created_at"], name="hr_external_import_type_time_idx"),
        ),
        migrations.AddConstraint(
            model_name="hrexternalimportrow",
            constraint=models.UniqueConstraint(fields=("job_id", "row_no"), name="uniq_hr_external_import_row_no"),
        ),
    ]
