# Generated by Django 5.2 on 2026-08-09 (HR08-S4 hand-written, model-aligned)

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_external", "0003_import_staging"),
    ]

    operations = [
        migrations.CreateModel(
            name="HrExternalIndustryProfile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.BigIntegerField(db_index=True)),
                ("industry_experience_years", models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ("current_employer", models.CharField(blank=True, default="", max_length=200)),
                ("current_industry_role", models.CharField(blank=True, default="", max_length=200)),
                ("major_projects", models.JSONField(blank=True, default=list)),
                ("patents_products", models.JSONField(blank=True, default=list)),
                ("technical_awards", models.JSONField(blank=True, default=list)),
                ("enterprise_training_experience", models.JSONField(blank=True, default=list)),
                ("industry_association_roles", models.JSONField(blank=True, default=list)),
                ("industry_domains", models.JSONField(blank=True, default=list)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("version", models.BigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("profile_id", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="industry_profile", to="hr_external.hrexternalteacherprofile")),
            ],
            options={
                "verbose_name": "HR External Industry Profile",
                "verbose_name_plural": "HR External Industry Profiles",
            },
        ),
        migrations.CreateModel(
            name="HrExternalContribution",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.BigIntegerField(db_index=True)),
                ("contribution_type", models.CharField(choices=[("COURSE_CO_BUILD", "Course Co-build"), ("TRAINING_PROJECT", "Training Project"), ("PROGRAM_DEVELOPMENT", "Program Development"), ("TALENT_TRAINING_CONSULT", "Talent Training Consult"), ("INDUSTRY_ACADEMIC_COOP", "Industry-academic Cooperation"), ("TECH_ATTACK", "Technical Breakthrough"), ("STUDENT_PROJECT_GUIDANCE", "Student Project Guidance"), ("TEACHER_PRACTICE_GUIDANCE", "Teacher Practice Guidance"), ("SKILL_COMPETITION_GUIDANCE", "Skill Competition Guidance"), ("APPRENTICESHIP_GUIDANCE", "Apprenticeship Guidance"), ("FACULTY_TRAINING", "Faculty Training"), ("INDUSTRY_RESOURCE_IMPORT", "Industry Resource Import"), ("OTHER", "Other")], default="OTHER", max_length=40)),
                ("title", models.CharField(max_length=300)),
                ("period", models.CharField(blank=True, default="", max_length=64)),
                ("evidence_ids", models.JSONField(blank=True, default=list)),
                ("verification_status", models.CharField(choices=[("UPLOADED", "Uploaded"), ("PENDING_VERIFICATION", "Pending Verification"), ("VERIFIED", "Verified"), ("REJECTED", "Rejected")], default="UPLOADED", max_length=24)),
                ("related_task_ids", models.JSONField(blank=True, default=list)),
                ("quantitative_value", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("qualitative_summary", models.TextField(blank=True, default="")),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("SUBMITTED", "Submitted"), ("UNDER_REVIEW", "Under Review"), ("VERIFIED", "Verified"), ("REJECTED", "Rejected"), ("RETURNED", "Returned")], default="DRAFT", max_length=16)),
                ("version", models.BigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("engagement_id", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="contributions", to="hr_external.hrexternalengagement")),
            ],
            options={
                "verbose_name": "HR External Contribution",
                "verbose_name_plural": "HR External Contributions",
            },
        ),
        migrations.CreateModel(
            name="HrExternalWorkspace",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.BigIntegerField(db_index=True)),
                ("name", models.CharField(max_length=200)),
                ("workspace_type", models.CharField(choices=[("SKILL_MASTER_WORKSHOP", "Skill Master Workshop"), ("INDUSTRY_TEACHING_WORKSHOP", "Industry Teaching Workshop"), ("PRACTICE_BASE", "Practice Base"), ("INDUSTRY_ACADEMIC_PLATFORM", "Industry-academic Platform"), ("OTHER", "Other")], default="SKILL_MASTER_WORKSHOP", max_length=32)),
                ("organization_id", models.BigIntegerField(db_index=True)),
                ("start_at", models.DateField()),
                ("end_at", models.DateField(blank=True, null=True)),
                ("goals", models.JSONField(blank=True, default=list)),
                ("member_refs", models.JSONField(blank=True, default=list)),
                ("projects", models.JSONField(blank=True, default=list)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("ACTIVE", "Active"), ("SUSPENDED", "Suspended"), ("ENDED", "Ended"), ("ARCHIVED", "Archived")], default="DRAFT", max_length=16)),
                ("version", models.BigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("leader_engagement_id", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="led_workspaces", to="hr_external.hrexternalengagement")),
            ],
            options={
                "verbose_name": "HR External Workspace",
                "verbose_name_plural": "HR External Workspaces",
            },
        ),
        migrations.AddConstraint(
            model_name="hrexternalindustryprofile",
            constraint=models.CheckConstraint(condition=models.Q(("version__gte", 1)), name="hr_external_industry_profile_version_gte_1"),
        ),
        migrations.AddConstraint(
            model_name="hrexternalcontribution",
            constraint=models.CheckConstraint(condition=models.Q(("version__gte", 1)), name="hr_external_contribution_version_gte_1"),
        ),
        migrations.AddIndex(
            model_name="hrexternalcontribution",
            index=models.Index(fields=["tenant_id", "engagement_id", "verification_status"], name="hr_external_contrib_eng_ver_idx"),
        ),
        migrations.AddIndex(
            model_name="hrexternalcontribution",
            index=models.Index(fields=["tenant_id", "contribution_type", "status"], name="hr_external_contrib_type_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="hrexternalworkspace",
            constraint=models.CheckConstraint(condition=models.Q(("end_at__isnull", True), models.Q(("start_at__lt", models.F("end_at"))), _connector="OR"), name="hr_external_workspace_dates_valid"),
        ),
        migrations.AddConstraint(
            model_name="hrexternalworkspace",
            constraint=models.CheckConstraint(condition=models.Q(("version__gte", 1)), name="hr_external_workspace_version_gte_1"),
        ),
        migrations.AddIndex(
            model_name="hrexternalworkspace",
            index=models.Index(fields=["tenant_id", "workspace_type", "status"], name="hr_external_workspace_type_status_idx"),
        ),
        migrations.AddIndex(
            model_name="hrexternalworkspace",
            index=models.Index(fields=["tenant_id", "organization_id", "status"], name="hr_external_workspace_org_status_idx"),
        ),
    ]
