# Generated by Django 5.2 on 2026-08-09 (HR08-S8 hand-written, model-aligned)

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_external", "0006_tasks"),
    ]

    operations = [
        migrations.CreateModel(
            name="HrExternalRenewalReview",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.BigIntegerField(db_index=True)),
                ("review_due_at", models.DateField()),
                ("task_completion_summary", models.TextField(blank=True, default="")),
                ("quality_summary", models.TextField(blank=True, default="")),
                ("agreement_status", models.CharField(blank=True, default="", max_length=32)),
                ("access_summary", models.TextField(blank=True, default="")),
                ("requester_org_opinion", models.TextField(blank=True, default="")),
                ("person_willingness", models.TextField(blank=True, default="")),
                ("decision", models.CharField(blank=True, choices=[("RENEW", "Renew"), ("RENEW_WITH_CHANGES", "Renew With Changes"), ("CHANGE_CATEGORY", "Change Category"), ("CHANGE_HOST_ORG", "Change Host Org"), ("CONVERT_TO_REGULAR_HR_PROCESS", "Convert To Regular HR Process"), ("DO_NOT_RENEW", "Do Not Renew"), ("NEEDS_REVIEW", "Needs Review")], default="", max_length=32)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("IN_REVIEW", "In Review"), ("DECIDED", "Decided"), ("CANCELLED", "Cancelled")], default="DRAFT", max_length=16)),
                ("decided_by", models.BigIntegerField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.BigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("engagement_id", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="renewal_reviews", to="hr_external.hrexternalengagement")),
                ("next_engagement_id", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="renewed_from", to="hr_external.hrexternalengagement")),
            ],
            options={
                "verbose_name": "HR External Renewal Review",
                "verbose_name_plural": "HR External Renewal Reviews",
            },
        ),
        migrations.CreateModel(
            name="HrExternalExitCase",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.BigIntegerField(db_index=True)),
                ("exit_reason", models.CharField(choices=[("TERM_COMPLETED", "Term Completed"), ("NO_RENEWAL", "No Renewal"), ("PERSON_WITHDRAWAL", "Person Withdrawal"), ("SCHOOL_TERMINATION", "School Termination"), ("TASK_COMPLETED", "Task Completed"), ("ROLE_CONVERTED", "Role Converted"), ("REGULAR_HIRE", "Regular Hire"), ("COMPLIANCE_REASON", "Compliance Reason"), ("OTHER", "Other")], default="TERM_COMPLETED", max_length=32)),
                ("planned_end_at", models.DateField(blank=True, null=True)),
                ("actual_end_at", models.DateField(blank=True, null=True)),
                ("status", models.CharField(choices=[("PLANNED", "Planned"), ("UNDER_REVIEW", "Under Review"), ("READY_TO_EXIT", "Ready To Exit"), ("EXITING", "Exiting"), ("ENDED", "Ended"), ("CLEARANCE_PENDING", "Clearance Pending"), ("CLOSED", "Closed")], db_index=True, default="PLANNED", max_length=24)),
                ("required_clearance_policy", models.CharField(blank=True, default="", max_length=64)),
                ("agreement_termination_ref", models.CharField(blank=True, default="", max_length=64)),
                ("clearance_items", models.JSONField(blank=True, default=list)),
                ("version", models.BigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("engagement_id", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="exit_cases", to="hr_external.hrexternalengagement")),
            ],
            options={
                "verbose_name": "HR External Exit Case",
                "verbose_name_plural": "HR External Exit Cases",
            },
        ),
        migrations.AddConstraint(
            model_name="hrexternalrenewalreview",
            constraint=models.UniqueConstraint(fields=("engagement_id", "review_due_at"), name="uniq_hr_external_renewal_per_cycle"),
        ),
        migrations.AddConstraint(
            model_name="hrexternalrenewalreview",
            constraint=models.CheckConstraint(condition=models.Q(("version__gte", 1)), name="hr_external_renewal_version_gte_1"),
        ),
        migrations.AddIndex(
            model_name="hrexternalrenewalreview",
            index=models.Index(fields=["tenant_id", "status", "review_due_at"], name="hr_external_renewal_status_due_idx"),
        ),
        migrations.AddIndex(
            model_name="hrexternalrenewalreview",
            index=models.Index(fields=["tenant_id", "engagement_id"], name="hr_external_renewal_eng_idx"),
        ),
        migrations.AddConstraint(
            model_name="hrexternalexitcase",
            constraint=models.UniqueConstraint(condition=models.Q(("status__in", ["PLANNED", "UNDER_REVIEW", "READY_TO_EXIT", "EXITING", "CLEARANCE_PENDING"])), fields=("tenant_id", "engagement_id"), name="uniq_hr_external_active_exit_per_eng"),
        ),
        migrations.AddConstraint(
            model_name="hrexternalexitcase",
            constraint=models.CheckConstraint(condition=models.Q(("version__gte", 1)), name="hr_external_exit_version_gte_1"),
        ),
        migrations.AddIndex(
            model_name="hrexternalexitcase",
            index=models.Index(fields=["tenant_id", "status"], name="hr_external_exit_status_idx"),
        ),
        migrations.AddIndex(
            model_name="hrexternalexitcase",
            index=models.Index(fields=["tenant_id", "engagement_id"], name="hr_external_exit_eng_idx"),
        ),
    ]
