# Generated by Django 5.2 on 2026-08-09 (HR08-S12 hand-written, model-aligned)

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_external", "0008_projection"),
    ]

    operations = [
        migrations.CreateModel(
            name="HrExternalAuthorityConfig",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.BigIntegerField(db_index=True, unique=True)),
                ("authority_mode", models.CharField(choices=[("LEGACY_EMPLOYEE_TAG_ONLY", "Legacy Employee Tag Only"), ("DUAL_READ_COMPARE", "Dual Read Compare"), ("HR08_AUTHORITY", "HR08 Authority")], default="LEGACY_EMPLOYEE_TAG_ONLY", max_length=32)),
                ("cutover_at", models.DateTimeField(blank=True, null=True)),
                ("cutover_by", models.BigIntegerField(blank=True, null=True)),
                ("legacy_write_disabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "HR External Authority Config",
                "verbose_name_plural": "HR External Authority Configs",
            },
        ),
    ]
