# Generated by Django 5.2 on 2026-08-09 (HR08-B5 hand-written, model-aligned)

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_external", "0009_authority_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="HrExternalMaterial",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.BigIntegerField(db_index=True)),
                ("category", models.CharField(choices=[("IDENTITY", "Identity"), ("EDUCATION", "Education"), ("DEGREE", "Degree"), ("PROFESSIONAL_TITLE", "Professional Title"), ("SKILL_CERTIFICATE", "Skill Certificate"), ("ENTERPRISE_EXPERIENCE", "Enterprise Experience"), ("AGREEMENT", "Agreement"), ("CONTRIBUTION_EVIDENCE", "Contribution Evidence"), ("OTHER", "Other")], default="OTHER", max_length=32)),
                ("title", models.CharField(max_length=250)),
                ("sensitivity_level", models.CharField(choices=[("PUBLIC_HR", "Public HR"), ("RESTRICTED_HR", "Restricted HR"), ("SENSITIVE", "Sensitive"), ("HIGH_SENSITIVE", "High Sensitive")], default="SENSITIVE", max_length=24)),
                ("storage_ref", models.CharField(blank=True, default="", max_length=255)),
                ("original_filename", models.CharField(blank=True, default="", max_length=255)),
                ("mime_type", models.CharField(blank=True, default="", max_length=128)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, default="", max_length=64)),
                ("version_no", models.PositiveIntegerField(default=1)),
                ("status", models.CharField(choices=[("UPLOADED", "Uploaded"), ("VERIFIED", "Verified"), ("REJECTED", "Rejected"), ("SUPERSEDED", "Superseded")], default="UPLOADED", max_length=16)),
                ("uploaded_by", models.BigIntegerField(blank=True, null=True)),
                ("verified_by", models.BigIntegerField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_profile_id", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="materials", to="hr_external.hrexternalteacherprofile")),
            ],
            options={
                "verbose_name": "HR External Material",
                "verbose_name_plural": "HR External Materials",
            },
        ),
        migrations.CreateModel(
            name="HrExternalFileTicket",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.BigIntegerField(db_index=True)),
                ("actor_user_id", models.BigIntegerField(blank=True, null=True)),
                ("purpose", models.CharField(blank=True, default="", max_length=512)),
                ("token_hash", models.CharField(db_index=True, max_length=64)),
                ("expires_at", models.DateTimeField()),
                ("max_uses", models.PositiveIntegerField(default=1)),
                ("used_count", models.PositiveIntegerField(default=0)),
                ("revoked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("material_id", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="download_tickets", to="hr_external.hrexternalmaterial")),
            ],
            options={
                "verbose_name": "HR External File Ticket",
                "verbose_name_plural": "HR External File Tickets",
            },
        ),
        migrations.AddIndex(
            model_name="hrexternalmaterial",
            index=models.Index(fields=["tenant_id", "external_profile_id", "category"], name="hr_external_material_profile_cat_idx"),
        ),
        migrations.AddIndex(
            model_name="hrexternalmaterial",
            index=models.Index(fields=["tenant_id", "status"], name="hr_external_material_status_idx"),
        ),
        migrations.AddIndex(
            model_name="hrexternalfileticket",
            index=models.Index(fields=["tenant_id", "token_hash"], name="hr_external_file_ticket_token_idx"),
        ),
    ]
