# Generated by Django 5.2 on 2026-08-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_external", "0016_external_hiring_agreement_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="HrExternalPermissionMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("hr.external.profile.view", "查看本校外聘人员业务档案"),
                    ("hr.external.profile.create", "创建本校外聘人员业务档案"),
                    ("hr.external.profile.sensitive_view", "查看外聘人员受限敏感字段"),
                    ("hr.external.profile.export", "导出外聘人员受控数据"),
                    ("hr.external.industry.view", "查看产业导师与企业实践事实"),
                    ("hr.external.industry.manage", "维护产业导师与企业实践事实"),
                    ("hr.external.hiring.create", "发起外聘聘用申请"),
                    ("hr.external.hiring.review", "复核外聘聘用申请"),
                    ("hr.external.hiring.approve", "审批外聘聘用申请"),
                    ("hr.external.hiring.activate", "激活已满足协议要求的外聘聘任"),
                    ("hr.external.task.view", "查看外聘任务与派任"),
                    ("hr.external.task.manage", "维护外聘任务与派任"),
                    ("hr.external.task.verify", "核验外聘任务完成事实"),
                    ("hr.external.workload.verify", "核验外聘工作量事实"),
                    ("hr.external.renewal.review", "查看外聘续聘评审"),
                    ("hr.external.renewal.decide", "作出外聘续聘决定"),
                    ("hr.external.exit.manage", "执行外聘到期与终止流程"),
                    ("hr.external.access.view", "查看外聘系统权限与回执"),
                    ("hr.external.access.manage", "下发或回收外聘系统权限"),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
