# Generated by Django 5.2 on 2026-08-09 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_recruitment', '0004_alter_hrproposedhire_reservation_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hrrecruitmentpermissionmeta',
            options={'managed': False, 'permissions': (('hr04.plan.view', 'Hr04 Plan View'), ('hr04.plan.create', 'Hr04 Plan Create'), ('hr04.plan.approve', 'Hr04 Plan Approve'), ('hr04.campaign.view', 'Hr04 Campaign View'), ('hr04.campaign.manage', 'Hr04 Campaign Manage'), ('hr04.campaign.publish', 'Hr04 Campaign Publish'), ('hr04.application.view', 'Hr04 Application View'), ('hr04.application.manage', 'Hr04 Application Manage'), ('hr04.application.sensitive_view', 'Hr04 Application Sensitive_View'), ('hr04.application.export', 'Hr04 Application Export'), ('hr04.qualification.review', 'Hr04 Qualification Review'), ('hr04.qualification.finalize', 'Hr04 Qualification Finalize'), ('hr04.assessment.manage', 'Hr04 Assessment Manage'), ('hr04.assessment.score', 'Hr04 Assessment Score'), ('hr04.assessment.unlock_score', 'Hr04 Assessment Unlock_Score'), ('hr04.proposed_hire.manage', 'Hr04 Proposed_Hire Manage'), ('hr04.public_notice.publish', 'Hr04 Public_Notice Publish'), ('hr04.offer.manage', 'Hr04 Offer Manage'), ('hr04.handoff_hr05', 'Hr04 Handoff_Hr05'))},
        ),
    ]
