# Generated by Django 5.2 on 2026-08-09 00:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_recruitment', '0006_hrrecruitmentposition_uniq_hr_position_slug_per_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrApplicationSubmissionKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Application Submission Key',
                'verbose_name_plural': 'Application Submission Keys',
            },
        ),
        migrations.AddConstraint(
            model_name='hrjobapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('application_no__gt', '')), fields=('tenant_id', 'application_no'), name='uniq_hr_application_no_tenant'),
        ),
        migrations.AddField(
            model_name='hrapplicationsubmissionkey',
            name='application_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_keys', to='hr_recruitment.hrjobapplication', verbose_name='Application'),
        ),
        migrations.AddIndex(
            model_name='hrapplicationsubmissionkey',
            index=models.Index(fields=['tenant_id', 'idempotency_key'], name='hr_recruitm_tenant__818e33_idx'),
        ),
        migrations.AddConstraint(
            model_name='hrapplicationsubmissionkey',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'idempotency_key'), name='uniq_hr_application_submission_key'),
        ),
    ]
