# Generated by Django 5.2 on 2026-08-09 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_recruitment', '0007_hrapplicationsubmissionkey_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hrselectionresultsnapshot',
            name='uniq_hr_selection_rank_per_position',
        ),
        migrations.RemoveIndex(
            model_name='hrselectionresultsnapshot',
            name='hr_recruitm_tenant__ecf500_idx',
        ),
        migrations.AddField(
            model_name='hrselectionresultsnapshot',
            name='snapshot_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='hrselectionresultsnapshot',
            index=models.Index(fields=['tenant_id', 'recruitment_position_id', 'snapshot_version', 'rank'], name='hr_recruitm_tenant__14ae35_idx'),
        ),
        migrations.AddConstraint(
            model_name='hrselectionresultsnapshot',
            constraint=models.UniqueConstraint(fields=('recruitment_position_id', 'snapshot_version', 'rank'), name='uniq_hr_selection_rank_per_version'),
        ),
    ]
