# Generated by Django 5.2 on 2026-08-09 01:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HrChangeAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('code', models.CharField(choices=[('ORG_TRANSFER', 'Org Transfer'), ('POSITION_TRANSFER', 'Position Transfer'), ('ORG_POSITION_TRANSFER', 'Org and Position Transfer'), ('POST_CATEGORY_CHANGE', 'Post Category Change'), ('EMPLOYEE_CATEGORY_CHANGE', 'Employee Category Change'), ('EMPLOYMENT_TYPE_CHANGE', 'Employment Type Change'), ('MANAGER_CHANGE', 'Manager Change'), ('LOCATION_CHANGE', 'Location Change'), ('ADD_SECONDARY_ASSIGNMENT', 'Add Secondary Assignment'), ('END_SECONDARY_ASSIGNMENT', 'End Secondary Assignment'), ('PRIMARY_ASSIGNMENT_SWITCH', 'Primary Assignment Switch'), ('TEMPORARY_SECONDMENT', 'Temporary Secondment'), ('TEMPORARY_ATTACHMENT', 'Temporary Attachment'), ('RETURN_FROM_TEMPORARY', 'Return From Temporary'), ('BULK_ORG_RESTRUCTURE_MOVE', 'Bulk Org Restructure Move'), ('DATA_CORRECTION', 'Data Correction')], max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('enabled', models.BooleanField(default=True)),
                ('is_temporary', models.BooleanField(default=False)),
                ('reporting_manager_policy', models.CharField(choices=[('KEEP', 'Keep'), ('DERIVE_FROM_TARGET_ORG', 'Derive From Target Org'), ('SELECT_EXPLICIT', 'Select Explicit')], default='KEEP', max_length=32)),
                ('effective_date_rule_json', models.JSONField(blank=True, default=dict)),
                ('followup_policy_json', models.JSONField(blank=True, default=dict)),
                ('allowed_initiators_json', models.JSONField(blank=True, default=list)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HR Change Action',
                'verbose_name_plural': 'HR Change Actions',
                'indexes': [models.Index(fields=['tenant_id', 'enabled'], name='hr_changes__tenant__2aed41_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'code'), name='uniq_hr_change_action_tenant_code')],
            },
        ),
        migrations.CreateModel(
            name='HrChangeFieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('domain', models.CharField(db_index=True, max_length=32)),
                ('field_code', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=120)),
                ('legacy_field', models.CharField(blank=True, default='', max_length=64)),
                ('authority_source', models.CharField(blank=True, default='', max_length=64)),
                ('edit_mode', models.CharField(choices=[('CHANGE_CASE_ONLY', 'Change Case Only'), ('READONLY_PROJECTION', 'Readonly Projection'), ('LEGACY_ALLOWED', 'Legacy Allowed')], default='CHANGE_CASE_ONLY', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'HR Change Field Definition',
                'verbose_name_plural': 'HR Change Field Definitions',
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'domain', 'field_code'), name='uniq_hr_change_field_tenant_domain_code')],
            },
        ),
        migrations.CreateModel(
            name='HrChangeReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('action_code', models.CharField(db_index=True, max_length=40)),
                ('description', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('requires_document', models.BooleanField(default=False)),
                ('requires_approval', models.BooleanField(default=True)),
                ('default_workflow_key', models.CharField(blank=True, default='', max_length=64)),
                ('followup_policy_json', models.JSONField(blank=True, default=dict)),
                ('effective_date_rule_json', models.JSONField(blank=True, default=dict)),
                ('allowed_source_scope_json', models.JSONField(blank=True, default=list)),
                ('allowed_target_scope_json', models.JSONField(blank=True, default=list)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HR Change Reason',
                'verbose_name_plural': 'HR Change Reasons',
                'indexes': [models.Index(fields=['tenant_id', 'action_code', 'active'], name='hr_changes__tenant__2c95c0_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'action_code', 'code'), name='uniq_hr_change_reason_tenant_action_code')],
            },
        ),
    ]
