# Generated by Django 5.2 on 2026-08-09 03:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_changes', '0002_hrbulkchangebatch_hrpersonnelchangecase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrTemporaryAssignmentExtension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('old_return_at', models.DateField()),
                ('new_return_at', models.DateField()),
                ('reason', models.TextField(blank=True, default='')),
                ('requested_by', models.BigIntegerField(blank=True, null=True)),
                ('approved_by', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('APPLIED', 'Applied')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('link_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='hr_changes.hrtemporaryassignmentlink')),
            ],
            options={
                'verbose_name': 'HR Temporary Assignment Extension',
                'verbose_name_plural': 'HR Temporary Assignment Extensions',
                'indexes': [models.Index(fields=['tenant_id', 'status', 'created_at'], name='hr_changes__tenant__b2a0df_idx')],
            },
        ),
    ]
