# Generated by Django 5.2 on 2026-08-30 10:46

import hashlib
import json

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def _hash(payload):
    encoded = json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(",", ":"), default=str).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def backfill_execution_seals(apps, schema_editor):
    Snapshot = apps.get_model("hr_changes", "HrChangeEffectiveSnapshot")
    batch = []
    for row in Snapshot.objects.select_related("change_case_id").all().iterator(chunk_size=500):
        case = row.change_case_id
        row.tenant_id = case.tenant_id
        row.authority_domain = "HR03"
        row.authority_contract_version = 1
        row.sealed_at = row.applied_at or row.created_at
        row.content_hash = _hash({
            "tenantId": int(row.tenant_id), "changeCaseId": str(case.id),
            "staffId": str(case.staff_master_id_id), "appliedAt": row.applied_at.isoformat(),
            "effectiveAt": row.effective_at.isoformat(), "before": row.before_json or {},
            "after": row.after_json or {}, "sourceFactIds": row.source_fact_ids_json or [],
            "targetFactIds": row.target_fact_ids_json or [], "positionChanges": row.position_changes_json or {},
            "downstreamPlanVersion": int(row.downstream_plan_version), "legacyChecksum": row.checksum or "",
            "authorityDomain": "HR03", "authorityContractVersion": 1,
        })
        batch.append(row)
        if len(batch) >= 500:
            Snapshot.objects.bulk_update(batch, ["tenant_id", "authority_domain", "authority_contract_version", "sealed_at", "content_hash"])
            batch = []
    if batch:
        Snapshot.objects.bulk_update(batch, ["tenant_id", "authority_domain", "authority_contract_version", "sealed_at", "content_hash"])


def install_mysql_execution_seals(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    for table, code in (
        ("hr_changes_hrchangeeffectivesnapshot", "HR06_EXECUTION_EVIDENCE_IMMUTABLE"),
        ("hr06_change_authority_receipt", "HR06_AUTHORITY_RECEIPT_IMMUTABLE"),
    ):
        for suffix in ("seal_insert", "no_update", "no_delete"):
            schema_editor.execute(f"DROP TRIGGER IF EXISTS {table}_{suffix}")
        schema_editor.execute(f"CREATE TRIGGER {table}_no_update BEFORE UPDATE ON {table} FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '{code}'")
        schema_editor.execute(f"CREATE TRIGGER {table}_no_delete BEFORE DELETE ON {table} FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '{code}'")
    schema_editor.execute(
        """
        CREATE TRIGGER hr_changes_hrchangeeffectivesnapshot_seal_insert
        BEFORE INSERT ON hr_changes_hrchangeeffectivesnapshot
        FOR EACH ROW
        BEGIN
            IF NEW.sealed_at IS NULL OR NEW.content_hash NOT REGEXP '^[0-9a-f]{64}$'
               OR NEW.authority_domain <> 'HR03' OR NEW.authority_contract_version <> 1 THEN
                SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'HR06_EXECUTION_SEAL_INVALID';
            END IF;
            IF (SELECT COUNT(*) FROM hr_changes_hrpersonnelchangecase c
                JOIN hr_staff_hrstaffmaster s ON s.id = c.staff_master_id_id
                WHERE c.id = NEW.change_case_id_id AND c.tenant_id = NEW.tenant_id
                  AND s.tenant_id = NEW.tenant_id) <> 1 THEN
                SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'HR06_EXECUTION_PARENT_LINEAGE_INVALID';
            END IF;
        END
        """
    )
    schema_editor.execute(
        """
        CREATE TRIGGER hr06_change_authority_receipt_seal_insert
        BEFORE INSERT ON hr06_change_authority_receipt
        FOR EACH ROW
        BEGIN
            IF NEW.sealed_at IS NULL OR NEW.content_hash NOT REGEXP '^[0-9a-f]{64}$' THEN
                SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'HR06_RECEIPT_SEAL_INVALID';
            END IF;
            IF (SELECT COUNT(*) FROM hr_changes_hrpersonnelchangecase c
                JOIN hr_staff_hrstaffmaster s ON s.id = c.staff_master_id_id
                WHERE c.id = NEW.change_case_id AND c.tenant_id = NEW.tenant_id
                  AND s.tenant_id = NEW.tenant_id) <> 1 THEN
                SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'HR06_RECEIPT_PARENT_LINEAGE_INVALID';
            END IF;
            IF NEW.effective_snapshot_id IS NOT NULL AND
               (SELECT COUNT(*) FROM hr_changes_hrchangeeffectivesnapshot x
                WHERE x.id = NEW.effective_snapshot_id AND x.change_case_id_id = NEW.change_case_id
                  AND x.tenant_id = NEW.tenant_id) <> 1 THEN
                SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'HR06_RECEIPT_SNAPSHOT_LINEAGE_INVALID';
            END IF;
            IF NEW.sequence_no <> (SELECT COALESCE(MAX(r.sequence_no), 0) + 1
                FROM hr06_change_authority_receipt r WHERE r.change_case_id = NEW.change_case_id) THEN
                SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'HR06_RECEIPT_SEQUENCE_CONFLICT';
            END IF;
            IF EXISTS (SELECT 1 FROM hr06_change_authority_receipt r
                WHERE r.change_case_id = NEW.change_case_id AND r.kind = 'ORCHESTRATION_RESCIND') THEN
                SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'HR06_RECEIPT_CHAIN_ALREADY_RESCINDED';
            END IF;
            IF NEW.kind = 'CORRECTION' THEN
                IF NEW.authority_effect <> 1 OR NEW.provider_code <> 'HR03_FORMAL_CORRECTION'
                   OR NEW.provider_case_id IS NULL OR NEW.provider_case_version IS NULL
                   OR NEW.provider_snapshot_hash NOT REGEXP '^[0-9a-f]{64}$' THEN
                    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'HR06_CORRECTION_RECEIPT_INVALID';
                END IF;
                IF (SELECT COUNT(*) FROM hr_changes_hrchangecorrection hc
                    JOIN hr_staff_hrcorrectioncase pc ON pc.id = hc.provider_case_id
                    JOIN hr_changes_hrpersonnelchangecase c ON c.id = hc.change_case_id_id
                    WHERE hc.id = NEW.source_record_id AND hc.change_case_id_id = NEW.change_case_id
                      AND hc.tenant_id = NEW.tenant_id AND hc.status = 'APPLIED'
                      AND pc.tenant_id = NEW.tenant_id AND pc.status = 'APPLIED'
                      AND pc.version = NEW.provider_case_version
                      AND pc.staff_id_id = c.staff_master_id_id) <> 1 THEN
                    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'HR06_HR03_PROVIDER_RECEIPT_INVALID';
                END IF;
            ELSEIF NEW.kind = 'ORCHESTRATION_RESCIND' THEN
                IF NEW.authority_effect <> 0 OR NEW.provider_code <> 'HR06_ORCHESTRATION_ONLY'
                   OR NEW.provider_case_id IS NOT NULL OR NEW.provider_case_version IS NOT NULL THEN
                    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'HR06_RESCIND_CANNOT_CLAIM_HR03_EFFECT';
                END IF;
                IF (SELECT COUNT(*) FROM hr_changes_hrchangerescind rr
                    WHERE rr.id = NEW.source_record_id AND rr.change_case_id_id = NEW.change_case_id
                      AND rr.tenant_id = NEW.tenant_id AND rr.status = 'RESCINDED') <> 1 THEN
                    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'HR06_RESCIND_SOURCE_INVALID';
                END IF;
            ELSE
                SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'HR06_RECEIPT_KIND_INVALID';
            END IF;
        END
        """
    )


def remove_mysql_execution_seals(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    for table in ("hr_changes_hrchangeeffectivesnapshot", "hr06_change_authority_receipt"):
        for suffix in ("seal_insert", "no_update", "no_delete"):
            schema_editor.execute(f"DROP TRIGGER IF EXISTS {table}_{suffix}")


class Migration(migrations.Migration):
    # Forward and reverse trigger DDL must run outside Django's transaction.
    atomic = False

    dependencies = [
        ('hr_changes', '0006_correction_authority_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrChangeAuthorityReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('sequence_no', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('CORRECTION', 'HR03 correction'), ('ORCHESTRATION_RESCIND', 'HR06 orchestration rescind')], max_length=32)),
                ('authority_effect', models.BooleanField(default=False)),
                ('provider_code', models.CharField(max_length=40)),
                ('provider_case_id', models.UUIDField(blank=True, null=True)),
                ('provider_case_version', models.BigIntegerField(blank=True, null=True)),
                ('provider_snapshot_hash', models.CharField(blank=True, default='', max_length=64)),
                ('source_record_id', models.UUIDField()),
                ('idempotency_key', models.CharField(max_length=80)),
                ('payload_json', models.JSONField(default=dict)),
                ('effective_at', models.DateTimeField()),
                ('content_hash', models.CharField(default='', editable=False, max_length=64)),
                ('sealed_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hr06_change_authority_receipt',
            },
        ),
        migrations.AddField(
            model_name='hrchangeeffectivesnapshot',
            name='authority_contract_version',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='hrchangeeffectivesnapshot',
            name='authority_domain',
            field=models.CharField(default='HR03', editable=False, max_length=16),
        ),
        migrations.AddField(
            model_name='hrchangeeffectivesnapshot',
            name='content_hash',
            field=models.CharField(default='', editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='hrchangeeffectivesnapshot',
            name='sealed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='hrchangeeffectivesnapshot',
            name='tenant_id',
            field=models.BigIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='hrchangeeffectivesnapshot',
            name='change_case_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='effective_snapshot', to='hr_changes.hrpersonnelchangecase'),
        ),
        migrations.AddIndex(
            model_name='hrchangeeffectivesnapshot',
            index=models.Index(fields=['tenant_id', 'effective_at'], name='idx_hr06_effective_tenant'),
        ),
        migrations.AddField(
            model_name='hrchangeauthorityreceipt',
            name='change_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authority_receipts', to='hr_changes.hrpersonnelchangecase'),
        ),
        migrations.AddField(
            model_name='hrchangeauthorityreceipt',
            name='effective_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authority_receipts', to='hr_changes.hrchangeeffectivesnapshot'),
        ),
        migrations.AddIndex(
            model_name='hrchangeauthorityreceipt',
            index=models.Index(fields=['tenant_id', 'change_case', 'sequence_no'], name='idx_hr06_receipt_chain'),
        ),
        migrations.AddConstraint(
            model_name='hrchangeauthorityreceipt',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'idempotency_key'), name='uq_hr06_receipt_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='hrchangeauthorityreceipt',
            constraint=models.UniqueConstraint(fields=('change_case', 'sequence_no'), name='uq_hr06_receipt_sequence'),
        ),
        migrations.AddConstraint(
            model_name='hrchangeauthorityreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('sequence_no__gte', 1)), name='ck_hr06_receipt_sequence'),
        ),
        migrations.RunPython(backfill_execution_seals, migrations.RunPython.noop),
        migrations.RunPython(install_mysql_execution_seals, remove_mysql_execution_seals),
    ]
