"""
hr_recruitment/api/urls.py

HR04 API 路由（统一前缀 /api/hr/v1/recruitment/）。
S1 阶段：健康探针 + envelope 契约自检；S3-S8 逐模块挂载。
"""

from django.urls import path

from hr_recruitment.api import application as application_api
from hr_recruitment.api import assessment as assessment_api
from hr_recruitment.api import campaign as campaign_api
from hr_recruitment.api import candidate as candidate_api
from hr_recruitment.api import medical_background as medical_background_api
from hr_recruitment.api import plan as plan_api
from hr_recruitment.api import proposed_hire as proposed_hire_api
from hr_recruitment.api import qualification as qualification_api
from hr_recruitment.api import views as api_views

urlpatterns = [
    path(
        "api/hr/v1/recruitment/health",
        api_views.hr04_api_health,
        name="hr04-api-health",
    ),
    path(
        "api/hr/v1/recruitment/contract",
        api_views.hr04_api_contract,
        name="hr04-api-contract",
    ),
    # HR04-06 录用与人才引进（总册 13）
    path(
        "api/hr/v1/recruitment/proposed-hires",
        proposed_hire_api.proposed_hire_list,
        name="hr04-api-proposed-hire-list",
    ),
    path(
        "api/hr/v1/recruitment/proposed-hires",
        proposed_hire_api.create_proposed_hire,
        name="hr04-api-proposed-hire-create",
    ),
    path(
        "api/hr/v1/recruitment/proposed-hires/<uuid:proposed_hire_id>/decide",
        proposed_hire_api.decide_proposed_hire,
        name="hr04-api-proposed-hire-decide",
    ),
    path(
        "api/hr/v1/recruitment/proposed-hires/<uuid:proposed_hire_id>/handoff-to-hr05",
        proposed_hire_api.handoff_to_hr05,
        name="hr04-api-handoff-to-hr05",
    ),
    path(
        "api/hr/v1/recruitment/notices",
        proposed_hire_api.publish_notice,
        name="hr04-api-notice-publish",
    ),
    path(
        "api/hr/v1/recruitment/notices/<uuid:notice_id>/close",
        proposed_hire_api.close_notice,
        name="hr04-api-notice-close",
    ),
    path(
        "api/hr/v1/recruitment/notices/<uuid:notice_id>/objections",
        proposed_hire_api.receive_objection,
        name="hr04-api-notice-objection",
    ),
    path(
        "api/hr/v1/recruitment/offers",
        proposed_hire_api.create_offer,
        name="hr04-api-offer-create",
    ),
    path(
        "api/hr/v1/recruitment/offers/<uuid:offer_id>/accept",
        proposed_hire_api.accept_offer,
        name="hr04-api-offer-accept",
    ),
    # HR04-05 考试面试与考察（总册 12）
    path(
        "api/hr/v1/recruitment/assessment/schemes",
        assessment_api.create_scheme,
        name="hr04-api-assessment-scheme-create",
    ),
    path(
        "api/hr/v1/recruitment/assessment/schemes/<uuid:scheme_id>/components",
        assessment_api.add_component,
        name="hr04-api-assessment-component-add",
    ),
    path(
        "api/hr/v1/recruitment/assessment/schemes/<uuid:scheme_id>/lock",
        assessment_api.lock_scheme,
        name="hr04-api-assessment-scheme-lock",
    ),
    path(
        "api/hr/v1/recruitment/assessment/events",
        assessment_api.create_event,
        name="hr04-api-assessment-event-create",
    ),
    path(
        "api/hr/v1/recruitment/assessment/events/<uuid:event_id>/evaluators",
        assessment_api.assign_evaluator,
        name="hr04-api-assessment-evaluator-assign",
    ),
    path(
        "api/hr/v1/recruitment/assessment/events/<uuid:event_id>/participants",
        assessment_api.assign_participant,
        name="hr04-api-assessment-participant-assign",
    ),
    path(
        "api/hr/v1/recruitment/assessment/assignments/<uuid:assignment_id>/conflict",
        assessment_api.declare_conflict,
        name="hr04-api-assessment-conflict",
    ),
    path(
        "api/hr/v1/recruitment/assessment/score-sheets",
        assessment_api.create_score_sheet,
        name="hr04-api-assessment-score-sheet-create",
    ),
    path(
        "api/hr/v1/recruitment/assessment/score-sheets/<uuid:score_sheet_id>",
        assessment_api.score_sheet_detail,
        name="hr04-api-assessment-score-sheet-detail",
    ),
    path(
        "api/hr/v1/recruitment/assessment/score-sheets/<uuid:score_sheet_id>/scores",
        assessment_api.save_scores,
        name="hr04-api-assessment-score-save",
    ),
    path(
        "api/hr/v1/recruitment/assessment/score-sheets/<uuid:score_sheet_id>/lock",
        assessment_api.lock_score_sheet,
        name="hr04-api-assessment-score-lock",
    ),
    path(
        "api/hr/v1/recruitment/assessment/score-sheets/<uuid:score_sheet_id>/reopen",
        assessment_api.reopen_score_sheet,
        name="hr04-api-assessment-score-reopen",
    ),
    path(
        "api/hr/v1/recruitment/assessment/positions/<uuid:position_id>/freeze-result",
        assessment_api.freeze_result,
        name="hr04-api-assessment-freeze-result",
    ),
    # 体检/考察（§12.8 敏感隔离）
    path(
        "api/hr/v1/recruitment/applications/<uuid:application_id>/medical",
        medical_background_api.record_medical,
        name="hr04-api-medical-record",
    ),
    path(
        "api/hr/v1/recruitment/applications/<uuid:application_id>/medical",
        medical_background_api.medical_summary,
        name="hr04-api-medical-summary",
    ),
    path(
        "api/hr/v1/recruitment/applications/<uuid:application_id>/background",
        medical_background_api.record_background,
        name="hr04-api-background-record",
    ),
    path(
        "api/hr/v1/recruitment/applications/<uuid:application_id>/background",
        medical_background_api.background_summary,
        name="hr04-api-background-summary",
    ),
    # HR04-04 资格审查（总册 11）
    path(
        "api/hr/v1/recruitment/qualification/workbench",
        qualification_api.workbench,
        name="hr04-api-qualification-workbench",
    ),
    path(
        "api/hr/v1/recruitment/qualification/applications/<uuid:application_id>/precheck",
        qualification_api.precheck,
        name="hr04-api-qualification-precheck",
    ),
    path(
        "api/hr/v1/recruitment/qualification/applications/<uuid:application_id>/start-review",
        qualification_api.start_review,
        name="hr04-api-qualification-start-review",
    ),
    path(
        "api/hr/v1/recruitment/qualification/applications/<uuid:application_id>/decision",
        qualification_api.decision,
        name="hr04-api-qualification-decision",
    ),
    path(
        "api/hr/v1/recruitment/qualification/rule-sets",
        qualification_api.create_rule_set,
        name="hr04-api-qualification-rule-set-create",
    ),
    path(
        "api/hr/v1/recruitment/qualification/rule-sets/<uuid:rule_set_id>/rules",
        qualification_api.add_rule,
        name="hr04-api-qualification-rule-add",
    ),
    path(
        "api/hr/v1/recruitment/qualification/rule-sets/<uuid:rule_set_id>/lock",
        qualification_api.lock_rule_set,
        name="hr04-api-qualification-rule-set-lock",
    ),
    # HR04-03 人才库与应聘者（总册 10/23）
    path(
        "api/hr/v1/recruitment/candidates",
        candidate_api.list_candidates,
        name="hr04-api-candidate-list",
    ),
    path(
        "api/hr/v1/recruitment/candidates",
        candidate_api.create_candidate,
        name="hr04-api-candidate-create",
    ),
    path(
        "api/hr/v1/recruitment/candidates/identity-match",
        candidate_api.identity_match,
        name="hr04-api-candidate-identity-match",
    ),
    path(
        "api/hr/v1/recruitment/candidates/identity-match-exact",
        candidate_api.identity_match_exact,
        name="hr04-api-candidate-identity-match-exact",
    ),
    path(
        "api/hr/v1/recruitment/candidates/<uuid:candidate_id>",
        candidate_api.candidate_detail,
        name="hr04-api-candidate-detail",
    ),
    path(
        "api/hr/v1/recruitment/applications/drafts",
        application_api.save_draft,
        name="hr04-api-application-draft",
    ),
    path(
        "api/hr/v1/recruitment/applications/<uuid:application_id>",
        application_api.application_detail,
        name="hr04-api-application-detail",
    ),
    path(
        "api/hr/v1/recruitment/applications/<uuid:application_id>/submit",
        application_api.submit_application,
        name="hr04-api-application-submit",
    ),
    path(
        "api/hr/v1/recruitment/applications/<uuid:application_id>/withdraw",
        application_api.withdraw_application,
        name="hr04-api-application-withdraw",
    ),
    path(
        "api/hr/v1/recruitment/applications/<uuid:application_id>/materials",
        application_api.add_material,
        name="hr04-api-application-material",
    ),
    # HR04-02 招聘控制台/项目/岗位（总册 9）
    path(
        "api/hr/v1/recruitment/console",
        campaign_api.console,
        name="hr04-api-console",
    ),
    path(
        "api/hr/v1/recruitment/pipeline",
        campaign_api.pipeline,
        name="hr04-api-pipeline",
    ),
    path(
        "api/hr/v1/recruitment/campaigns",
        campaign_api.list_campaigns,
        name="hr04-api-campaign-list",
    ),
    path(
        "api/hr/v1/recruitment/campaigns",
        campaign_api.create_campaign,
        name="hr04-api-campaign-create",
    ),
    path(
        "api/hr/v1/recruitment/campaigns/from-plan",
        campaign_api.create_campaign_from_plan,
        name="hr04-api-campaign-create-from-plan",
    ),
    path(
        "api/hr/v1/recruitment/campaigns/<uuid:campaign_id>",
        campaign_api.campaign_detail,
        name="hr04-api-campaign-detail",
    ),
    path(
        "api/hr/v1/recruitment/campaigns/<uuid:campaign_id>/publish",
        campaign_api.publish_campaign,
        name="hr04-api-campaign-publish",
    ),
    path(
        "api/hr/v1/recruitment/campaigns/<uuid:campaign_id>/status",
        campaign_api.campaign_status,
        name="hr04-api-campaign-status",
    ),
    path(
        "api/hr/v1/recruitment/campaigns/<uuid:campaign_id>/announcements",
        campaign_api.create_announcement,
        name="hr04-api-campaign-announcement-create",
    ),
    path(
        "api/hr/v1/recruitment/positions",
        campaign_api.create_position,
        name="hr04-api-position-create",
    ),
    path(
        "api/hr/v1/recruitment/positions/<uuid:position_id>/ready",
        campaign_api.position_ready,
        name="hr04-api-position-ready",
    ),
    path(
        "api/hr/v1/recruitment/positions/<uuid:position_id>/open",
        campaign_api.position_open,
        name="hr04-api-position-open",
    ),
    path(
        "api/hr/v1/recruitment/positions/<uuid:position_id>/cancel",
        campaign_api.position_cancel,
        name="hr04-api-position-cancel",
    ),
    # HR04-01 年度用人计划（总册 8.5）
    path(
        "api/hr/v1/recruitment/plans",
        plan_api.list_plans,
        name="hr04-api-plan-list",
    ),
    path(
        "api/hr/v1/recruitment/plans",
        plan_api.create_plan,
        name="hr04-api-plan-create",
    ),
    path(
        "api/hr/v1/recruitment/plans/<uuid:cycle_id>",
        plan_api.plan_detail,
        name="hr04-api-plan-detail",
    ),
    path(
        "api/hr/v1/recruitment/plans/<uuid:cycle_id>/submit",
        plan_api.plan_submit,
        name="hr04-api-plan-submit",
    ),
    path(
        "api/hr/v1/recruitment/plans/<uuid:cycle_id>/approve",
        plan_api.plan_approve,
        name="hr04-api-plan-approve",
    ),
    path(
        "api/hr/v1/recruitment/plan-requests",
        plan_api.create_plan_request,
        name="hr04-api-plan-request-create",
    ),
    path(
        "api/hr/v1/recruitment/plan-requests/<uuid:request_id>/submit",
        plan_api.plan_request_submit,
        name="hr04-api-plan-request-submit",
    ),
    path(
        "api/hr/v1/recruitment/plan-requests/<uuid:request_id>/return",
        plan_api.plan_request_return,
        name="hr04-api-plan-request-return",
    ),
    path(
        "api/hr/v1/recruitment/plan-requests/<uuid:request_id>/approve",
        plan_api.plan_request_approve,
        name="hr04-api-plan-request-approve",
    ),
]
