import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [('hr_assessment', '0001_initial')]
    operations = [
        migrations.AlterField(model_name='hracknowledgement', name='acknowledgement_status', field=models.CharField(default='NOT_DELIVERED', max_length=30, verbose_name='确认状态')),
        migrations.AlterField(model_name='hracknowledgement', name='confirmed_at', field=models.DateTimeField(null=True, verbose_name='确认时间')),
        migrations.AlterField(model_name='hracknowledgement', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hracknowledgement', name='employee_opinion', field=models.TextField(default='', verbose_name='本人意见')),
        migrations.AlterField(model_name='hracknowledgement', name='received_at', field=models.DateTimeField(null=True, verbose_name='收到时间')),
        migrations.AlterField(model_name='hracknowledgement', name='result', field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acknowledgements', to='hr_assessment.hrfinalassessmentresult', verbose_name='所属结果')),
        migrations.AlterField(model_name='hracknowledgement', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hracknowledgement', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrannualassessmentcase', name='academic_year', field=models.CharField(blank=True, max_length=20, null=True, verbose_name='学年')),
        migrations.AlterField(model_name='hrannualassessmentcase', name='annual_goal_plan_id', field=models.UUIDField(null=True, verbose_name='目标计划 ID')),
        migrations.AlterField(model_name='hrannualassessmentcase', name='business_year', field=models.PositiveSmallIntegerField(null=True, verbose_name='业务年度')),
        migrations.AlterField(model_name='hrannualassessmentcase', name='routine_snapshot_id', field=models.UUIDField(null=True, verbose_name='平时考核快照 ID')),
        migrations.AlterField(model_name='hrannualassessmentcase', name='special_refs_json', field=models.JSONField(default=list, verbose_name='专项引用')),
        migrations.AlterField(model_name='hrassessmentarchivepackage', name='archive_package_id', field=models.CharField(max_length=100, unique=True, verbose_name='归档包 ID')),
        migrations.AlterField(model_name='hrassessmentarchivepackage', name='archive_provider_ref', field=models.CharField(default='', max_length=200, verbose_name='归档 Provider 引用')),
        migrations.AlterField(model_name='hrassessmentarchivepackage', name='archive_status', field=models.CharField(default='PENDING', max_length=30, verbose_name='归档状态')),
        migrations.AlterField(model_name='hrassessmentarchivepackage', name='archived_at', field=models.DateTimeField(null=True, verbose_name='归档时间')),
        migrations.AlterField(model_name='hrassessmentarchivepackage', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrassessmentarchivepackage', name='document_refs_json', field=models.JSONField(default=list, verbose_name='文件引用')),
        migrations.AlterField(model_name='hrassessmentarchivepackage', name='result', field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archives', to='hr_assessment.hrfinalassessmentresult', verbose_name='所属结果')),
        migrations.AlterField(model_name='hrassessmentarchivepackage', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrassessmentarchivepackage', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrassessmentcase', name='assessment_type', field=models.CharField(db_index=True, max_length=30, verbose_name='考核类型')),
        migrations.AlterField(model_name='hrassessmentcase', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrassessmentcase', name='cycle', field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='hr_assessment.hrassessmentcycle', verbose_name='所属周期')),
        migrations.AlterField(model_name='hrassessmentcase', name='policy_version_id', field=models.UUIDField(null=True, verbose_name='适用政策版本 ID')),
        migrations.AlterField(model_name='hrassessmentcase', name='provider_snapshot_set_id', field=models.UUIDField(null=True, verbose_name='Provider 快照集 ID')),
        migrations.AlterField(model_name='hrassessmentcase', name='staff_id', field=models.UUIDField(verbose_name='人员 ID')),
        migrations.AlterField(model_name='hrassessmentcase', name='status', field=models.CharField(db_index=True, default='DRAFT', max_length=30, verbose_name='Case 状态')),
        migrations.AlterField(model_name='hrassessmentcase', name='subject_snapshot', field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='hr_assessment.hrsubjectsnapshot', verbose_name='对象快照')),
        migrations.AlterField(model_name='hrassessmentcase', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrassessmentcase', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrassessmentclassificationprofileversion', name='content_hash', field=models.CharField(blank=True, default='', max_length=64, verbose_name='内容哈希 (SHA-256)')),
        migrations.AlterField(model_name='hrassessmentclassificationprofileversion', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrassessmentclassificationprofileversion', name='status', field=models.CharField(db_index=True, default='DRAFT', max_length=30, verbose_name='状态')),
        migrations.AlterField(model_name='hrassessmentclassificationprofileversion', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrassessmentclassificationprofileversion', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrassessmentclassificationprofileversion', name='version_no', field=models.PositiveIntegerField(default=1, verbose_name='版本号')),
        migrations.AlterField(model_name='hrassessmentcycle', name='academic_year', field=models.CharField(blank=True, max_length=20, null=True, verbose_name='学年')),
        migrations.AlterField(model_name='hrassessmentcycle', name='assessment_type', field=models.CharField(max_length=30, verbose_name='考核类型')),
        migrations.AlterField(model_name='hrassessmentcycle', name='business_year', field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='业务年度')),
        migrations.AlterField(model_name='hrassessmentcycle', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrassessmentcycle', name='cycle_no', field=models.CharField(max_length=50, verbose_name='周期编号')),
        migrations.AlterField(model_name='hrassessmentcycle', name='end_at', field=models.DateTimeField(verbose_name='结束时间')),
        migrations.AlterField(model_name='hrassessmentcycle', name='lifecycle_status', field=models.CharField(db_index=True, default='DRAFT', max_length=30, verbose_name='生命周期状态')),
        migrations.AlterField(model_name='hrassessmentcycle', name='name', field=models.CharField(max_length=200, verbose_name='周期名称')),
        migrations.AlterField(model_name='hrassessmentcycle', name='owner_org_id', field=models.UUIDField(blank=True, null=True, verbose_name='归属组织 ID')),
        migrations.AlterField(model_name='hrassessmentcycle', name='policy_version_id', field=models.UUIDField(verbose_name='绑定的政策版本 ID')),
        migrations.AlterField(model_name='hrassessmentcycle', name='start_at', field=models.DateTimeField(verbose_name='开始时间')),
        migrations.AlterField(model_name='hrassessmentcycle', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrassessmentcycle', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrassessmentdecisionsession', name='agenda_json', field=models.JSONField(default=dict, verbose_name='议程')),
        migrations.AlterField(model_name='hrassessmentdecisionsession', name='body_org_id', field=models.UUIDField(null=True, verbose_name='决策机构组织 ID')),
        migrations.AlterField(model_name='hrassessmentdecisionsession', name='case_refs_json', field=models.JSONField(default=list, verbose_name='Case 引用')),
        migrations.AlterField(model_name='hrassessmentdecisionsession', name='confidentiality', field=models.CharField(default='INTERNAL', max_length=30, verbose_name='保密级别')),
        migrations.AlterField(model_name='hrassessmentdecisionsession', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrassessmentdecisionsession', name='cycle_id', field=models.UUIDField(verbose_name='所属周期 ID')),
        migrations.AlterField(model_name='hrassessmentdecisionsession', name='meeting_at', field=models.DateTimeField(null=True, verbose_name='会议时间')),
        migrations.AlterField(model_name='hrassessmentdecisionsession', name='minutes_document_ref', field=models.UUIDField(null=True, verbose_name='纪要文件引用')),
        migrations.AlterField(model_name='hrassessmentdecisionsession', name='participants_json', field=models.JSONField(default=list, verbose_name='参与者')),
        migrations.AlterField(model_name='hrassessmentdecisionsession', name='quorum_policy_json', field=models.JSONField(default=dict, verbose_name='法定人数')),
        migrations.AlterField(model_name='hrassessmentdecisionsession', name='status', field=models.CharField(default='DRAFT', max_length=30, verbose_name='状态')),
        migrations.AlterField(model_name='hrassessmentdecisionsession', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrassessmentdecisionsession', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrassessmentevidenceref', name='case_id', field=models.UUIDField(db_index=True, verbose_name='考核 Case ID')),
        migrations.AlterField(model_name='hrassessmentevidenceref', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrassessmentevidenceref', name='indicator_id', field=models.UUIDField(null=True, verbose_name='指标 ID')),
        migrations.AlterField(model_name='hrassessmentevidenceref', name='provider_type', field=models.CharField(max_length=50, verbose_name='证据提供者类型')),
        migrations.AlterField(model_name='hrassessmentevidenceref', name='snapshot_hash', field=models.CharField(default='', max_length=64, verbose_name='证据哈希')),
        migrations.AlterField(model_name='hrassessmentevidenceref', name='source_as_of', field=models.DateTimeField(null=True, verbose_name='数据 as-of 时间')),
        migrations.AlterField(model_name='hrassessmentevidenceref', name='source_object_id', field=models.CharField(max_length=100, verbose_name='源对象 ID')),
        migrations.AlterField(model_name='hrassessmentevidenceref', name='source_object_type', field=models.CharField(max_length=100, verbose_name='源对象类型')),
        migrations.AlterField(model_name='hrassessmentevidenceref', name='source_version', field=models.CharField(default='', max_length=30, verbose_name='源版本')),
        migrations.AlterField(model_name='hrassessmentevidenceref', name='status', field=models.CharField(default='PENDING', max_length=30, verbose_name='核实状态')),
        migrations.AlterField(model_name='hrassessmentevidenceref', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrassessmentevidenceref', name='trust_level', field=models.CharField(default='SELF_REPORTED', max_length=30, verbose_name='可信度')),
        migrations.AlterField(model_name='hrassessmentevidenceref', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrassessmentevidenceref', name='verification_method', field=models.CharField(default='', max_length=50, verbose_name='核实方式')),
        migrations.AlterField(model_name='hrassessmentevidenceref', name='verification_note', field=models.TextField(default='', verbose_name='核实说明')),
        migrations.AlterField(model_name='hrassessmentevidenceref', name='verified_at', field=models.DateTimeField(null=True, verbose_name='核实时间')),
        migrations.AlterField(model_name='hrassessmentevidenceref', name='verified_by', field=models.UUIDField(null=True, verbose_name='核实人')),
        migrations.AlterField(model_name='hrassessmentgoal', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrassessmentgoal', name='current_version_id', field=models.UUIDField(blank=True, null=True, verbose_name='当前版本 ID')),
        migrations.AlterField(model_name='hrassessmentgoal', name='goal_code', field=models.CharField(max_length=50, verbose_name='目标编码')),
        migrations.AlterField(model_name='hrassessmentgoal', name='goal_plan', field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='hr_assessment.hrassessmentgoalplan', verbose_name='所属计划')),
        migrations.AlterField(model_name='hrassessmentgoal', name='owner_ref', field=models.UUIDField(blank=True, null=True, verbose_name='Owner 引用')),
        migrations.AlterField(model_name='hrassessmentgoal', name='owner_type', field=models.CharField(default='INDIVIDUAL', max_length=30, verbose_name='Owner 类型')),
        migrations.AlterField(model_name='hrassessmentgoal', name='source_ref', field=models.UUIDField(blank=True, null=True, verbose_name='来源引用')),
        migrations.AlterField(model_name='hrassessmentgoal', name='source_type', field=models.CharField(default='POSITION_DUTY', max_length=50, verbose_name='来源类型')),
        migrations.AlterField(model_name='hrassessmentgoal', name='status', field=models.CharField(db_index=True, default='DRAFT', max_length=30, verbose_name='状态')),
        migrations.AlterField(model_name='hrassessmentgoal', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrassessmentgoal', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrassessmentgoalplan', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrassessmentgoalplan', name='cycle_id', field=models.UUIDField(blank=True, null=True, verbose_name='所属周期 ID')),
        migrations.AlterField(model_name='hrassessmentgoalplan', name='goal_type', field=models.CharField(default='ANNUAL', max_length=30, verbose_name='目标类型')),
        migrations.AlterField(model_name='hrassessmentgoalplan', name='name', field=models.CharField(max_length=200, verbose_name='计划名称')),
        migrations.AlterField(model_name='hrassessmentgoalplan', name='status', field=models.CharField(default='DRAFT', max_length=30, verbose_name='计划状态')),
        migrations.AlterField(model_name='hrassessmentgoalplan', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrassessmentgoalplan', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrassessmentobjection', name='conclusion', field=models.TextField(default='', verbose_name='复核结论')),
        migrations.AlterField(model_name='hrassessmentobjection', name='conflict_check_json', field=models.JSONField(default=dict, verbose_name='冲突检查')),
        migrations.AlterField(model_name='hrassessmentobjection', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrassessmentobjection', name='evidence_json', field=models.JSONField(default=list, verbose_name='证据')),
        migrations.AlterField(model_name='hrassessmentobjection', name='reason', field=models.TextField(verbose_name='申诉理由')),
        migrations.AlterField(model_name='hrassessmentobjection', name='resolved_at', field=models.DateTimeField(null=True, verbose_name='解决时间')),
        migrations.AlterField(model_name='hrassessmentobjection', name='result', field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objections', to='hr_assessment.hrfinalassessmentresult', verbose_name='所属结果')),
        migrations.AlterField(model_name='hrassessmentobjection', name='reviewer_staff_id', field=models.UUIDField(null=True, verbose_name='复核人')),
        migrations.AlterField(model_name='hrassessmentobjection', name='status', field=models.CharField(db_index=True, default='SUBMITTED', max_length=30, verbose_name='处理状态')),
        migrations.AlterField(model_name='hrassessmentobjection', name='submitted_at', field=models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
        migrations.AlterField(model_name='hrassessmentobjection', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrassessmentobjection', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrassessmentpolicypack', name='assessment_domain', field=models.CharField(max_length=50, verbose_name='考核域')),
    ]
