import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [('hr_assessment', '0003_state_convergence_02')]
    operations = [
        migrations.AlterField(model_name='hrfinalassessmentresult', name='result_version_no', field=models.PositiveSmallIntegerField(default=1, verbose_name='结果版本号')),
        migrations.AlterField(model_name='hrfinalassessmentresult', name='status', field=models.CharField(db_index=True, default='FINALIZED', max_length=30, verbose_name='结果状态')),
        migrations.AlterField(model_name='hrfinalassessmentresult', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrfinalassessmentresult', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrgaterule', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrgaterule', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrgaterule', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrgateruleversion', name='content_hash', field=models.CharField(blank=True, default='', max_length=64, verbose_name='内容哈希 (SHA-256)')),
        migrations.AlterField(model_name='hrgateruleversion', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrgateruleversion', name='status', field=models.CharField(db_index=True, default='DRAFT', max_length=30, verbose_name='状态')),
        migrations.AlterField(model_name='hrgateruleversion', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrgateruleversion', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrgateruleversion', name='version_no', field=models.PositiveIntegerField(default=1, verbose_name='版本号')),
        migrations.AlterField(model_name='hrgoalassignment', name='assignment_type', field=models.CharField(default='INDIVIDUAL', max_length=30, verbose_name='分配类型')),
        migrations.AlterField(model_name='hrgoalassignment', name='contribution_role', field=models.CharField(blank=True, default='', max_length=50, verbose_name='贡献角色')),
        migrations.AlterField(model_name='hrgoalassignment', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrgoalassignment', name='effective_period_json', field=models.JSONField(default=dict, verbose_name='有效期间')),
        migrations.AlterField(model_name='hrgoalassignment', name='goal', field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='hr_assessment.hrassessmentgoal', verbose_name='所属目标')),
        migrations.AlterField(model_name='hrgoalassignment', name='staff_id', field=models.UUIDField(verbose_name='人员 ID')),
        migrations.AlterField(model_name='hrgoalassignment', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrgoalassignment', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrgoalcheckin', name='author_staff_id', field=models.UUIDField(verbose_name='作者 ID')),
        migrations.AlterField(model_name='hrgoalcheckin', name='blockers', field=models.TextField(blank=True, default='', verbose_name='阻碍')),
        migrations.AlterField(model_name='hrgoalcheckin', name='check_in_at', field=models.DateTimeField(verbose_name='Check-in 时间')),
        migrations.AlterField(model_name='hrgoalcheckin', name='comment', field=models.TextField(blank=True, default='', verbose_name='评语')),
        migrations.AlterField(model_name='hrgoalcheckin', name='goal_assignment', field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='hr_assessment.hrgoalassignment', verbose_name='所属分配')),
        migrations.AlterField(model_name='hrgoalcheckin', name='progress_claim', field=models.TextField(blank=True, default='', verbose_name='进展声明')),
        migrations.AlterField(model_name='hrgoalcheckin', name='support_needed', field=models.TextField(blank=True, default='', verbose_name='需要支持')),
        migrations.AlterField(model_name='hrgoalcheckin', name='verified_progress', field=models.TextField(blank=True, default='', verbose_name='核实进展')),
        migrations.AlterField(model_name='hrgoalcheckin', name='visibility', field=models.CharField(default='MANAGER_AND_SELF', max_length=30, verbose_name='可见性')),
        migrations.AlterField(model_name='hrgoalmeasure', name='baseline', field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='基线值')),
        migrations.AlterField(model_name='hrgoalmeasure', name='goal_version', field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measures', to='hr_assessment.hrgoalversion', verbose_name='所属目标版本')),
        migrations.AlterField(model_name='hrgoalmeasure', name='measure_code', field=models.CharField(max_length=50, verbose_name='度量编码')),
        migrations.AlterField(model_name='hrgoalmeasure', name='measure_type', field=models.CharField(default='NUMBER', max_length=30, verbose_name='度量类型')),
        migrations.AlterField(model_name='hrgoalmeasure', name='source_provider', field=models.CharField(default='SELF_REPORT', max_length=50, verbose_name='数据来源')),
        migrations.AlterField(model_name='hrgoalmeasure', name='target', field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='目标值')),
        migrations.AlterField(model_name='hrgoalmeasure', name='unit', field=models.CharField(default='', max_length=30, verbose_name='单位')),
        migrations.AlterField(model_name='hrgoalprogressevent', name='author_staff_id', field=models.UUIDField(null=True, verbose_name='作者 ID')),
        migrations.AlterField(model_name='hrgoalprogressevent', name='comment', field=models.TextField(blank=True, default='', verbose_name='备注')),
        migrations.AlterField(model_name='hrgoalprogressevent', name='goal_assignment', field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_events', to='hr_assessment.hrgoalassignment', verbose_name='所属分配')),
        migrations.AlterField(model_name='hrgoalprogressevent', name='measure_id', field=models.UUIDField(blank=True, null=True, verbose_name='度量 ID')),
        migrations.AlterField(model_name='hrgoalprogressevent', name='recorded_at', field=models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
        migrations.AlterField(model_name='hrgoalprogressevent', name='self_claimed_progress', field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='自报进度')),
        migrations.AlterField(model_name='hrgoalprogressevent', name='status_claim', field=models.CharField(default='', max_length=30, verbose_name='状态声明')),
        migrations.AlterField(model_name='hrgoalprogressevent', name='verified_progress', field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='核实进度')),
        migrations.AlterField(model_name='hrgoalversion', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrgoalversion', name='description', field=models.TextField(blank=True, default='', verbose_name='目标描述')),
        migrations.AlterField(model_name='hrgoalversion', name='goal', field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='hr_assessment.hrassessmentgoal', verbose_name='所属目标')),
        migrations.AlterField(model_name='hrgoalversion', name='measures_json', field=models.JSONField(default=list, verbose_name='度量指标')),
        migrations.AlterField(model_name='hrgoalversion', name='period_config_json', field=models.JSONField(default=dict, verbose_name='周期配置')),
        migrations.AlterField(model_name='hrgoalversion', name='status', field=models.CharField(default='DRAFT', max_length=30, verbose_name='版本状态')),
        migrations.AlterField(model_name='hrgoalversion', name='title', field=models.CharField(max_length=200, verbose_name='目标标题')),
        migrations.AlterField(model_name='hrgoalversion', name='version_no', field=models.PositiveIntegerField(default=1, verbose_name='版本号')),
        migrations.AlterField(model_name='hrindicatordefinition', name='code', field=models.CharField(max_length=50, verbose_name='指标编码')),
        migrations.AlterField(model_name='hrindicatordefinition', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrindicatordefinition', name='name', field=models.CharField(max_length=200, verbose_name='指标名称')),
        migrations.AlterField(model_name='hrindicatordefinition', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrindicatordefinition', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrindicatorsetversion', name='content_hash', field=models.CharField(blank=True, default='', max_length=64, verbose_name='内容哈希 (SHA-256)')),
        migrations.AlterField(model_name='hrindicatorsetversion', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrindicatorsetversion', name='status', field=models.CharField(db_index=True, default='DRAFT', max_length=30, verbose_name='状态')),
        migrations.AlterField(model_name='hrindicatorsetversion', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrindicatorsetversion', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrindicatorsetversion', name='version_no', field=models.PositiveIntegerField(default=1, verbose_name='版本号')),
        migrations.AlterField(model_name='hrindicatorversion', name='content_hash', field=models.CharField(blank=True, default='', max_length=64, verbose_name='内容哈希 (SHA-256)')),
        migrations.AlterField(model_name='hrindicatorversion', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrindicatorversion', name='status', field=models.CharField(db_index=True, default='DRAFT', max_length=30, verbose_name='状态')),
        migrations.AlterField(model_name='hrindicatorversion', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrindicatorversion', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrindicatorversion', name='version_no', field=models.PositiveIntegerField(default=1, verbose_name='版本号')),
        migrations.AlterField(model_name='hrmetricsnapshot', name='case_id', field=models.UUIDField(db_index=True, verbose_name='考核 Case ID')),
        migrations.AlterField(model_name='hrmetricsnapshot', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrmetricsnapshot', name='metric_code', field=models.CharField(max_length=50, verbose_name='指标代码')),
        migrations.AlterField(model_name='hrmetricsnapshot', name='period_json', field=models.JSONField(default=dict, verbose_name='周期')),
        migrations.AlterField(model_name='hrmetricsnapshot', name='provider', field=models.CharField(max_length=50, verbose_name='数据提供者')),
        migrations.AlterField(model_name='hrmetricsnapshot', name='snapshot_at', field=models.DateTimeField(auto_now_add=True, verbose_name='快照时间')),
        migrations.AlterField(model_name='hrmetricsnapshot', name='source_updated_at', field=models.DateTimeField(null=True, verbose_name='源更新时间')),
        migrations.AlterField(model_name='hrmetricsnapshot', name='source_version', field=models.CharField(default='', max_length=30, verbose_name='源版本')),
        migrations.AlterField(model_name='hrmetricsnapshot', name='status', field=models.CharField(default='VERIFIED', max_length=30, verbose_name='状态')),
        migrations.AlterField(model_name='hrmetricsnapshot', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrmetricsnapshot', name='unit', field=models.CharField(default='', max_length=30, verbose_name='单位')),
        migrations.AlterField(model_name='hrmetricsnapshot', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrmetricsnapshot', name='value', field=models.DecimalField(decimal_places=4, max_digits=15, null=True, verbose_name='数值')),
        migrations.AlterField(model_name='hrmultiraterfeedback', name='answers_json', field=models.JSONField(default=list, verbose_name='回答')),
        migrations.AlterField(model_name='hrmultiraterfeedback', name='reviewer_staff_id', field=models.UUIDField(verbose_name='评价人 ID')),
        migrations.AlterField(model_name='hrmultiraterfeedback', name='session', field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='hr_assessment.hrmultiratersession', verbose_name='所属会话')),
        migrations.AlterField(model_name='hrmultiraterfeedback', name='submitted_at', field=models.DateTimeField(null=True, verbose_name='提交时间')),
        migrations.AlterField(model_name='hrmultiratersession', name='anonymity_strategy', field=models.CharField(default='IDENTIFIED', max_length=30, verbose_name='匿名策略')),
        migrations.AlterField(model_name='hrmultiratersession', name='case_id', field=models.UUIDField(db_index=True, verbose_name='考核 Case ID')),
        migrations.AlterField(model_name='hrmultiratersession', name='closed_at', field=models.DateTimeField(null=True, verbose_name='关闭时间')),
        migrations.AlterField(model_name='hrmultiratersession', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrmultiratersession', name='min_responses_json', field=models.JSONField(default=dict, verbose_name='最小响应数')),
        migrations.AlterField(model_name='hrmultiratersession', name='questionnaire_version', field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hr_assessment.hrquestionnaireversion', verbose_name='问卷版本')),
        migrations.AlterField(model_name='hrmultiratersession', name='session_name', field=models.CharField(max_length=200, verbose_name='会话名称')),
        migrations.AlterField(model_name='hrmultiratersession', name='session_status', field=models.CharField(default='ACTIVE', max_length=30, verbose_name='会话状态')),
        migrations.AlterField(model_name='hrmultiratersession', name='started_at', field=models.DateTimeField(null=True, verbose_name='开始时间')),
        migrations.AlterField(model_name='hrmultiratersession', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrmultiratersession', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrquestionnaireversion', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrquestionnaireversion', name='name', field=models.CharField(max_length=200, verbose_name='问卷名称')),
        migrations.AlterField(model_name='hrquestionnaireversion', name='status', field=models.CharField(default='DRAFT', max_length=30, verbose_name='状态')),
        migrations.AlterField(model_name='hrquestionnaireversion', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrquestionnaireversion', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrquestionnaireversion', name='version_no', field=models.PositiveIntegerField(default=1, verbose_name='版本号')),
        migrations.AlterField(model_name='hrquestionversion', name='dimension', field=models.CharField(default='', max_length=50, verbose_name='维度')),
        migrations.AlterField(model_name='hrquestionversion', name='display_order', field=models.PositiveSmallIntegerField(default=0, verbose_name='显示顺序')),
        migrations.AlterField(model_name='hrquestionversion', name='options_json', field=models.JSONField(default=list, verbose_name='选项')),
        migrations.AlterField(model_name='hrquestionversion', name='purpose', field=models.CharField(default='', max_length=100, verbose_name='用途')),
        migrations.AlterField(model_name='hrquestionversion', name='question_text', field=models.TextField(verbose_name='问题文本')),
        migrations.AlterField(model_name='hrquestionversion', name='question_type', field=models.CharField(max_length=30, verbose_name='问题类型')),
        migrations.AlterField(model_name='hrquestionversion', name='questionnaire', field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='hr_assessment.hrquestionnaireversion', verbose_name='所属问卷')),
        migrations.AlterField(model_name='hrquestionversion', name='required', field=models.BooleanField(default=True, verbose_name='必答')),
        migrations.AlterField(model_name='hrquestionversion', name='scoring_rule_json', field=models.JSONField(default=dict, verbose_name='评分规则')),
        migrations.AlterField(model_name='hrquestionversion', name='sensitivity', field=models.CharField(default='INTERNAL_METRIC', max_length=30, verbose_name='敏感性')),
    ]
