import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [('hr_assessment', '0004_state_convergence_03')]
    operations = [
        migrations.AlterField(model_name='hrratingscaleversion', name='content_hash', field=models.CharField(blank=True, default='', max_length=64, verbose_name='内容哈希 (SHA-256)')),
        migrations.AlterField(model_name='hrratingscaleversion', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrratingscaleversion', name='status', field=models.CharField(db_index=True, default='DRAFT', max_length=30, verbose_name='状态')),
        migrations.AlterField(model_name='hrratingscaleversion', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrratingscaleversion', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrratingscaleversion', name='version_no', field=models.PositiveIntegerField(default=1, verbose_name='版本号')),
        migrations.AlterField(model_name='hrresultapplicationledger', name='consumed_at', field=models.DateTimeField(auto_now_add=True, verbose_name='消费时间')),
        migrations.AlterField(model_name='hrresultapplicationledger', name='consumer_domain', field=models.CharField(max_length=50, verbose_name='消费域')),
        migrations.AlterField(model_name='hrresultapplicationledger', name='consumer_object_id', field=models.UUIDField(null=True, verbose_name='消费对象 ID')),
        migrations.AlterField(model_name='hrresultapplicationledger', name='consumer_status', field=models.CharField(default='CONSUMED', max_length=30, verbose_name='消费状态')),
        migrations.AlterField(model_name='hrresultapplicationledger', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrresultapplicationledger', name='purpose', field=models.CharField(max_length=100, verbose_name='用途')),
        migrations.AlterField(model_name='hrresultapplicationledger', name='result', field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='hr_assessment.hrfinalassessmentresult', verbose_name='所属结果')),
        migrations.AlterField(model_name='hrresultapplicationledger', name='result_version', field=models.PositiveSmallIntegerField(verbose_name='消费的版本号')),
        migrations.AlterField(model_name='hrresultapplicationledger', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrresultapplicationledger', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrresultnotice', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrresultnotice', name='delivered_at', field=models.DateTimeField(null=True, verbose_name='送达时间')),
        migrations.AlterField(model_name='hrresultnotice', name='delivery_channel', field=models.CharField(default='SYSTEM', max_length=30, verbose_name='送达渠道')),
        migrations.AlterField(model_name='hrresultnotice', name='delivery_status', field=models.CharField(default='PENDING', max_length=30, verbose_name='送达状态')),
        migrations.AlterField(model_name='hrresultnotice', name='generated_document_id', field=models.UUIDField(null=True, verbose_name='生成的文件 ID')),
        migrations.AlterField(model_name='hrresultnotice', name='notice_no', field=models.CharField(max_length=50, verbose_name='告知编号')),
        migrations.AlterField(model_name='hrresultnotice', name='result', field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notices', to='hr_assessment.hrfinalassessmentresult', verbose_name='所属结果')),
        migrations.AlterField(model_name='hrresultnotice', name='result_version', field=models.PositiveSmallIntegerField(default=1, verbose_name='结果版本')),
        migrations.AlterField(model_name='hrresultnotice', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrresultnotice', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrresultrevision', name='after_snapshot_json', field=models.JSONField(default=dict, verbose_name='修订后快照')),
        migrations.AlterField(model_name='hrresultrevision', name='authority_staff_id', field=models.UUIDField(null=True, verbose_name='修订授权人')),
        migrations.AlterField(model_name='hrresultrevision', name='before_snapshot_json', field=models.JSONField(default=dict, verbose_name='修订前快照')),
        migrations.AlterField(model_name='hrresultrevision', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrresultrevision', name='effective_at', field=models.DateTimeField(null=True, verbose_name='生效时间')),
        migrations.AlterField(model_name='hrresultrevision', name='new_version', field=models.PositiveSmallIntegerField(verbose_name='新版本号')),
        migrations.AlterField(model_name='hrresultrevision', name='previous_version', field=models.PositiveSmallIntegerField(verbose_name='前一版本号')),
        migrations.AlterField(model_name='hrresultrevision', name='reason', field=models.TextField(verbose_name='修订原因')),
        migrations.AlterField(model_name='hrresultrevision', name='result', field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='hr_assessment.hrfinalassessmentresult', verbose_name='所属结果')),
        migrations.AlterField(model_name='hrresultrevision', name='revision_type', field=models.CharField(max_length=30, verbose_name='修订类型')),
        migrations.AlterField(model_name='hrresultrevision', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrresultrevision', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrresultruleversion', name='content_hash', field=models.CharField(blank=True, default='', max_length=64, verbose_name='内容哈希 (SHA-256)')),
        migrations.AlterField(model_name='hrresultruleversion', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrresultruleversion', name='status', field=models.CharField(db_index=True, default='DRAFT', max_length=30, verbose_name='状态')),
        migrations.AlterField(model_name='hrresultruleversion', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrresultruleversion', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrresultruleversion', name='version_no', field=models.PositiveIntegerField(default=1, verbose_name='版本号')),
        migrations.AlterField(model_name='hrreviewerassignment', name='assigned_at', field=models.DateTimeField(auto_now_add=True, verbose_name='分配时间')),
        migrations.AlterField(model_name='hrreviewerassignment', name='case_id', field=models.UUIDField(db_index=True, verbose_name='考核 Case ID')),
        migrations.AlterField(model_name='hrreviewerassignment', name='conflict_status', field=models.CharField(default='CLEAR', max_length=30, verbose_name='冲突状态')),
        migrations.AlterField(model_name='hrreviewerassignment', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrreviewerassignment', name='delegation_json', field=models.JSONField(default=dict, verbose_name='委托信息')),
        migrations.AlterField(model_name='hrreviewerassignment', name='due_at', field=models.DateTimeField(null=True, verbose_name='截止时间')),
        migrations.AlterField(model_name='hrreviewerassignment', name='reviewer_role', field=models.CharField(max_length=30, verbose_name='评议人角色')),
        migrations.AlterField(model_name='hrreviewerassignment', name='reviewer_staff_id', field=models.UUIDField(verbose_name='评议人 ID')),
        migrations.AlterField(model_name='hrreviewerassignment', name='scope', field=models.CharField(default='ASSIGNED_CASES', max_length=50, verbose_name='范围')),
        migrations.AlterField(model_name='hrreviewerassignment', name='status', field=models.CharField(default='PENDING', max_length=30, verbose_name='状态')),
        migrations.AlterField(model_name='hrreviewerassignment', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrreviewerassignment', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrreviewerevaluation', name='assignment', field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='hr_assessment.hrreviewerassignment', verbose_name='所属分配')),
        migrations.AlterField(model_name='hrreviewerevaluation', name='comment', field=models.TextField(default='', verbose_name='评语')),
        migrations.AlterField(model_name='hrreviewerevaluation', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrreviewerevaluation', name='indicator_evaluations_json', field=models.JSONField(default=list, verbose_name='指标评价')),
        migrations.AlterField(model_name='hrreviewerevaluation', name='rating_json', field=models.JSONField(default=dict, verbose_name='评分')),
        migrations.AlterField(model_name='hrreviewerevaluation', name='recommendation', field=models.CharField(default='', max_length=30, verbose_name='建议档次')),
        migrations.AlterField(model_name='hrreviewerevaluation', name='revision_no', field=models.PositiveSmallIntegerField(default=1, verbose_name='修订号')),
        migrations.AlterField(model_name='hrreviewerevaluation', name='submitted_at', field=models.DateTimeField(null=True, verbose_name='提交时间')),
        migrations.AlterField(model_name='hrreviewerevaluation', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrreviewerevaluation', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrroutineassessmententry', name='author_staff_id', field=models.UUIDField(null=True, verbose_name='记录人 ID')),
        migrations.AlterField(model_name='hrroutineassessmententry', name='category', field=models.CharField(default='', max_length=50, verbose_name='记录类别')),
        migrations.AlterField(model_name='hrroutineassessmententry', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrroutineassessmententry', name='goal_ref', field=models.UUIDField(blank=True, null=True, verbose_name='目标引用')),
        migrations.AlterField(model_name='hrroutineassessmententry', name='observation', field=models.TextField(blank=True, default='', verbose_name='观察记录')),
        migrations.AlterField(model_name='hrroutineassessmententry', name='period_end', field=models.DateField(null=True, verbose_name='期间结束')),
        migrations.AlterField(model_name='hrroutineassessmententry', name='period_start', field=models.DateField(null=True, verbose_name='期间开始')),
        migrations.AlterField(model_name='hrroutineassessmententry', name='rating', field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='评分(可选)')),
        migrations.AlterField(model_name='hrroutineassessmententry', name='revision', field=models.PositiveSmallIntegerField(default=1, verbose_name='修订号')),
        migrations.AlterField(model_name='hrroutineassessmententry', name='staff_id', field=models.UUIDField(verbose_name='人员 ID')),
        migrations.AlterField(model_name='hrroutineassessmententry', name='status', field=models.CharField(default='ACTIVE', max_length=30, verbose_name='状态')),
        migrations.AlterField(model_name='hrroutineassessmententry', name='task_ref', field=models.UUIDField(blank=True, null=True, verbose_name='任务引用')),
        migrations.AlterField(model_name='hrroutineassessmententry', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrroutineassessmententry', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrroutineassessmententry', name='visibility', field=models.CharField(default='MANAGER_AND_SELF', max_length=30, verbose_name='可见性')),
        migrations.AlterField(model_name='hrselfassessment', name='case_id', field=models.UUIDField(unique=True, verbose_name='考核 Case ID')),
        migrations.AlterField(model_name='hrselfassessment', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrselfassessment', name='goal_reflections_json', field=models.JSONField(default=list, verbose_name='目标反思')),
        migrations.AlterField(model_name='hrselfassessment', name='revision', field=models.PositiveSmallIntegerField(default=1, verbose_name='修订号')),
        migrations.AlterField(model_name='hrselfassessment', name='self_rating_json', field=models.JSONField(default=dict, verbose_name='自评分数(可选)')),
        migrations.AlterField(model_name='hrselfassessment', name='special_circumstances', field=models.TextField(default='', verbose_name='特殊情况')),
        migrations.AlterField(model_name='hrselfassessment', name='submitted_at', field=models.DateTimeField(null=True, verbose_name='提交时间')),
        migrations.AlterField(model_name='hrselfassessment', name='summary', field=models.TextField(default='', verbose_name='总结')),
        migrations.AlterField(model_name='hrselfassessment', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrselfassessment', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrspecialassessmentcase', name='result_schema_json', field=models.JSONField(default=dict, verbose_name='结果模式')),
        migrations.AlterField(model_name='hrspecialassessmentcase', name='scope_json', field=models.JSONField(default=dict, verbose_name='范围')),
        migrations.AlterField(model_name='hrspecialassessmentcase', name='special_type', field=models.CharField(max_length=50, verbose_name='专项类型')),
        migrations.AlterField(model_name='hrspecialassessmentcase', name='target_snapshot_json', field=models.JSONField(default=dict, verbose_name='目标快照')),
        migrations.AlterField(model_name='hrspecialassessmentcase', name='title', field=models.CharField(max_length=200, verbose_name='专项标题')),
        migrations.AlterField(model_name='hrspecialassessmentcase', name='trigger_event', field=models.CharField(default='', max_length=100, verbose_name='触发事件')),
        migrations.AlterField(model_name='hrsubjectsnapshot', name='case_id', field=models.UUIDField(unique=True, verbose_name='考核 Case ID')),
        migrations.AlterField(model_name='hrsubjectsnapshot', name='created_at', field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrsubjectsnapshot', name='discipline', field=models.CharField(default='', max_length=100, verbose_name='学科专业')),
        migrations.AlterField(model_name='hrsubjectsnapshot', name='display_name', field=models.CharField(max_length=200, verbose_name='姓名展示')),
        migrations.AlterField(model_name='hrsubjectsnapshot', name='employment_relationship_id', field=models.UUIDField(null=True, verbose_name='聘用关系 ID')),
        migrations.AlterField(model_name='hrsubjectsnapshot', name='job_category', field=models.CharField(default='', max_length=50, verbose_name='岗位类别')),
        migrations.AlterField(model_name='hrsubjectsnapshot', name='org_id', field=models.UUIDField(null=True, verbose_name='组织 ID')),
        migrations.AlterField(model_name='hrsubjectsnapshot', name='org_name', field=models.CharField(default='', max_length=200, verbose_name='组织名称')),
        migrations.AlterField(model_name='hrsubjectsnapshot', name='position_id', field=models.UUIDField(null=True, verbose_name='主岗 ID')),
        migrations.AlterField(model_name='hrsubjectsnapshot', name='position_name', field=models.CharField(default='', max_length=200, verbose_name='主岗名称')),
        migrations.AlterField(model_name='hrsubjectsnapshot', name='reviewer_line_json', field=models.JSONField(default=dict, verbose_name='评审线')),
        migrations.AlterField(model_name='hrsubjectsnapshot', name='snapshot_at', field=models.DateTimeField(verbose_name='快照时间')),
        migrations.AlterField(model_name='hrsubjectsnapshot', name='staff_code', field=models.CharField(default='', max_length=50, verbose_name='工号')),
        migrations.AlterField(model_name='hrsubjectsnapshot', name='staff_id', field=models.UUIDField(verbose_name='人员 ID')),
        migrations.AlterField(model_name='hrsubjectsnapshot', name='teacher_type', field=models.CharField(default='', max_length=50, verbose_name='教师类型')),
        migrations.AlterField(model_name='hrsubjectsnapshot', name='tenant_id', field=models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
        migrations.AlterField(model_name='hrsubjectsnapshot', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrsubjectsnapshot', name='worker_category', field=models.CharField(default='', max_length=50, verbose_name='人员类别')),
        migrations.AlterField(model_name='hrtermassessmentcase', name='agreement_id', field=models.UUIDField(verbose_name='HR07 Agreement ID')),
    ]
