# Generated by Django 5.2 on 2026-09-01 19:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_assessment', '0019_provider_snapshot_membership_seal'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrAssessmentCutoverEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('phase', models.CharField(max_length=40)),
                ('previous_phase', models.CharField(blank=True, default='', max_length=40)),
                ('authority_mode', models.CharField(max_length=32)),
                ('operator', models.CharField(max_length=128)),
                ('reason', models.CharField(max_length=255)),
                ('verification_report_id', models.CharField(blank=True, default='', max_length=64)),
                ('source_snapshot_hash', models.CharField(blank=True, default='', max_length=64)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'hr_assessment_cutover_event',
                'ordering': ('occurred_at', 'id'),
                'indexes': [models.Index(fields=['tenant_id', 'occurred_at'], name='hr_assessme_tenant__56eb2b_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'phase'), name='uq_hr12_cutover_tenant_phase')],
            },
        ),
    ]
