# Generated by Django 5.2 on 2026-09-01 20:15

from django.db import migrations, models


def reject_unmapped_uuid_organization_refs(apps, schema_editor):
    """Do not guess a UUID-to-HR02 integer mapping during authority alignment."""

    fields = (
        ("HrAssessmentCycle", "owner_org_id"),
        ("HrAssessmentDecisionSession", "body_org_id"),
        ("HrAssessmentPolicyPack", "owner_org_id"),
        ("HrAssessmentPopulationSnapshot", "org_id"),
        ("HrAssessmentPopulationSnapshot", "position_id"),
        ("HrSubjectSnapshot", "org_id"),
        ("HrSubjectSnapshot", "position_id"),
    )
    populated = []
    for model_name, field_name in fields:
        model = apps.get_model("hr_assessment", model_name)
        if model.objects.exclude(**{f"{field_name}__isnull": True}).exists():
            populated.append(f"{model_name}.{field_name}")
    if populated:
        raise RuntimeError(
            "HR12_ORG_REFERENCE_RECONCILIATION_REQUIRED: legacy UUID references "
            "cannot be converted to HR02 integer IDs automatically: "
            + ", ".join(populated)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('hr_assessment', '0021_hracknowledgement_result_version_and_more'),
    ]

    operations = [
        migrations.RunPython(
            reject_unmapped_uuid_organization_refs,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='hrassessmentcycle',
            name='owner_org_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='HR02 归属组织 ID'),
        ),
        migrations.AlterField(
            model_name='hrassessmentdecisionsession',
            name='body_org_id',
            field=models.BigIntegerField(null=True, verbose_name='HR02 决策机构组织 ID'),
        ),
        migrations.AlterField(
            model_name='hrassessmentpolicypack',
            name='owner_org_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='HR02 归属组织 ID'),
        ),
        migrations.AlterField(
            model_name='hrassessmentpopulationsnapshot',
            name='org_id',
            field=models.BigIntegerField(null=True, verbose_name='当时 HR02 组织 ID'),
        ),
        migrations.AlterField(
            model_name='hrassessmentpopulationsnapshot',
            name='position_id',
            field=models.BigIntegerField(null=True, verbose_name='当时 HR02 岗位 ID'),
        ),
        migrations.AlterField(
            model_name='hrsubjectsnapshot',
            name='org_id',
            field=models.BigIntegerField(null=True, verbose_name='HR02 组织 ID'),
        ),
        migrations.AlterField(
            model_name='hrsubjectsnapshot',
            name='position_id',
            field=models.BigIntegerField(null=True, verbose_name='HR02 岗位 ID'),
        ),
    ]
