# Generated by Django 5.2 on 2026-09-01 20:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_assessment', '0023_hrreviewerevaluation_hr12_evaluation_assignment_revision_uq'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrAssessmentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('document_type', models.CharField(max_length=40, verbose_name='文件类型')),
                ('related_object_type', models.CharField(max_length=40, verbose_name='关联对象类型')),
                ('related_object_id', models.UUIDField(db_index=True, verbose_name='关联对象 ID')),
                ('storage_key', models.CharField(max_length=512, verbose_name='受控存储键')),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('content_type', models.CharField(default='', max_length=127, verbose_name='内容类型')),
                ('size_bytes', models.PositiveBigIntegerField(verbose_name='文件字节数')),
                ('sha256', models.CharField(max_length=64, verbose_name='SHA-256')),
                ('uploaded_by', models.BigIntegerField(null=True, verbose_name='上传账号')),
                ('sealed_at', models.DateTimeField(verbose_name='封存时间')),
                ('status', models.CharField(default='SEALED', max_length=20, verbose_name='状态')),
            ],
            options={
                'verbose_name': '考核受控文件',
                'db_table': 'hr_assessment_document',
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'document_type', 'related_object_type', 'related_object_id'), name='hr12_document_business_object_uq')],
            },
        ),
    ]
