# Generated by Django 5.2 on 2026-09-01 20:41

from django.db import migrations, models


def verify_unique_result_versions(apps, schema_editor):
    Objection = apps.get_model("hr_assessment", "HrAssessmentObjection")
    from django.db.models import Count

    duplicate = (
        Objection.objects.values("tenant_id", "result_id", "result_version")
        .annotate(row_count=Count("id"))
        .filter(row_count__gt=1)
        .order_by("tenant_id", "result_id", "result_version")
        .first()
    )
    if duplicate:
        raise RuntimeError(
            "HR12_OBJECTION_RECONCILIATION_REQUIRED: duplicate legacy objections "
            "exist for one tenant/result/version; reconcile them before migration 0025"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('hr_assessment', '0024_hrassessmentdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrassessmentobjection',
            name='decision_code',
            field=models.CharField(default='', max_length=30, verbose_name='复核决定'),
        ),
        migrations.AddField(
            model_name='hrassessmentobjection',
            name='resolution_revision_id',
            field=models.UUIDField(null=True, verbose_name='结果更正版本 ID'),
        ),
        migrations.AddField(
            model_name='hrassessmentobjection',
            name='result_version',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='异议对应结果版本'),
        ),
        migrations.AddField(
            model_name='hrassessmentobjection',
            name='submitted_by_staff_id',
            field=models.UUIDField(null=True, verbose_name='异议提交人'),
        ),
        migrations.RunPython(
            verify_unique_result_versions,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='hrassessmentobjection',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'result', 'result_version'), name='hr12_objection_result_version_uq'),
        ),
    ]
