# Generated by Django 5.2.17 on 2026-09-19 09:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


TRIGGERS = {
    "hr12_archive_no_update_v14": ("UPDATE", "hr_assessment_archive_package", "IF OLD.archive_status = 'ARCHIVED' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'HR12_ARCHIVE_IMMUTABLE'; END IF;"),
    "hr12_archive_no_delete_v14": ("DELETE", "hr_assessment_archive_package", "IF OLD.archive_status = 'ARCHIVED' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'HR12_ARCHIVE_IMMUTABLE'; END IF;"),
    "hr12_archive_audit_no_update": ("UPDATE", "hr12_archive_access_audit", "SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'HR12_ARCHIVE_ACCESS_AUDIT_IMMUTABLE';"),
    "hr12_archive_audit_no_delete": ("DELETE", "hr12_archive_access_audit", "SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'HR12_ARCHIVE_ACCESS_AUDIT_IMMUTABLE';"),
}


def install_seals(apps, schema_editor):
    if schema_editor.connection.vendor != 'mysql':
        return  # SQLite ORM tests do not prove these MySQL triggers.
    for name, (event, table, body) in TRIGGERS.items():
        schema_editor.execute(f"DROP TRIGGER IF EXISTS {name}")
        schema_editor.execute(f"CREATE TRIGGER {name} BEFORE {event} ON {table} FOR EACH ROW BEGIN {body} END")


def remove_seals(apps, schema_editor):
    if schema_editor.connection.vendor != 'mysql':
        return
    for name in TRIGGERS:
        schema_editor.execute(f"DROP TRIGGER IF EXISTS {name}")


def protect_evidence_on_reverse(apps, schema_editor):
    database = schema_editor.connection.alias
    Audit = apps.get_model('hr_assessment', 'HrAssessmentArchiveAccessAudit')
    Archive = apps.get_model('hr_assessment', 'HrAssessmentArchivePackage')
    if Audit.objects.using(database).exists() or Archive.objects.using(database).filter(manifest_json__schemaVersion='hr12-archive-v2').exists():
        raise RuntimeError('HR12_ARCHIVE_EVIDENCE_EXISTS: use a forward fix; do not delete evidence to roll back code')


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('hr_assessment', '0027_document_access_audit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hrassessmentpermissionmeta',
            options={'default_permissions': (), 'managed': False, 'permissions': (('hr.assessment.policy.admin', '考核政策管理'), ('hr.assessment.cycle.admin', '考核周期管理'), ('hr.assessment.hr_reviewer', '校级人事评审'), ('hr.assessment.college_reviewer', '学院评审'), ('hr.assessment.manager_reviewer', '主管评审'), ('hr.assessment.panel_member', '评审委员会成员'), ('hr.assessment.calibration_manager', '校准管理'), ('hr.assessment.final_decider', '审定决策'), ('hr.assessment.result.correct', '追加更正或撤销已封板考核结果'), ('hr.assessment.ethics_reviewer', '师德评审'), ('hr.assessment.special_reviewer', '专项评审'), ('hr.assessment.archive_manager', '档案管理'), ('hr.assessment.archive.export', '导出考核归档证据'), ('hr.assessment.auditor', '审计'), ('hr.assessment.employee_self', '本人自助'), ('hr.assessment.analytics_view', '统计分析'))},
        ),
        migrations.CreateModel(
            name='HrAssessmentArchiveAccessAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True, help_text='学校租户标识 — fail-closed；不可为 NULL', verbose_name='租户 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('actor_user_id', models.PositiveBigIntegerField()),
                ('action', models.CharField(choices=[('VIEW', '查阅'), ('EXPORT', '导出'), ('COMPARE', '样本核对')], max_length=20)),
                ('purpose', models.CharField(max_length=500)),
                ('content_hash', models.CharField(max_length=64)),
                ('details_json', models.JSONField(default=dict)),
                ('request_id', models.CharField(blank=True, default='', max_length=128)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_audits', to='hr_assessment.hrassessmentarchivepackage')),
            ],
            options={
                'db_table': 'hr12_archive_access_audit',
                'indexes': [models.Index(fields=['tenant_id', 'archive', 'created_at'], name='idx_hr12_archive_access')],
                'constraints': [models.CheckConstraint(condition=models.Q(('purpose__gt', '')), name='ck_hr12_archive_reason')],
            },
        ),
        migrations.RunPython(install_seals, remove_seals, atomic=False),
        migrations.RunPython(migrations.RunPython.noop, protect_evidence_on_reverse),
    ]
