"""Canonical HR14 permission codes used by HTTP authority boundaries."""

READ_PERMISSION = "hr.appointment.view"
APPLICATION_PERMISSION = "hr.appointment.application"
MANAGE_PERMISSION = "hr.appointment.manage"
REVIEW_PERMISSION = "hr.appointment.review"
PUBLICITY_PERMISSION = "hr.appointment.publicity"
EFFECT_PERMISSION = "hr.appointment.effect"
FACT_PUBLISH_PERMISSION = "hr.appointment.fact.publish"
FACT_CORRECT_PERMISSION = "hr.appointment.fact.correct"
FACT_REVOKE_PERMISSION = "hr.appointment.fact.revoke"
