# S8: development fact + metric ledger + compliance + risk
from django.db import migrations, models; import django.utils.timezone as tz

class Migration(migrations.Migration):
    dependencies=[("horilla_auth","__first__"),("hr10_development","0007_practice_process")]
    operations=[
        migrations.CreateModel("HrDevelopmentFact",[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False)),
            ("tenant_id",models.BigIntegerField(db_index=True)),("created_at",models.DateTimeField(default=tz.now,editable=False)),("updated_at",models.DateTimeField(auto_now=True)),
            ("staff_master_id",models.BigIntegerField(db_index=True)),("fact_type",models.CharField(db_index=True,max_length=32)),("source_case_type",models.CharField(max_length=64)),("source_case_id",models.BigIntegerField()),("source_revision_no",models.IntegerField(default=0)),("activity_type",models.CharField(blank=True,default="",max_length=64)),("provider_org_id",models.BigIntegerField(blank=True,null=True)),("start_date",models.DateField(blank=True,null=True)),("end_date",models.DateField(blank=True,null=True)),("verified_hours",models.DecimalField(blank=True,decimal_places=1,max_digits=8,null=True)),("verified_days",models.IntegerField(blank=True,null=True)),("verified_credits",models.DecimalField(blank=True,decimal_places=1,max_digits=6,null=True)),("level_or_result",models.CharField(blank=True,default="",max_length=64)),("verification_status",models.CharField(db_index=True,max_length=48)),("evidence_package_hash",models.CharField(blank=True,default="",max_length=128)),("generated_at",models.DateTimeField()),("valid_from",models.DateField(blank=True,null=True)),("valid_to",models.DateField(blank=True,null=True)),("supersedes_fact_id",models.BigIntegerField(blank=True,null=True)),("immutable_hash",models.CharField(blank=True,default="",max_length=128))
        ],options={"db_table":"hr_development_fact","verbose_name":"发展事实","verbose_name_plural":"发展事实"}),
        migrations.CreateModel("HrDevelopmentMetricLedger",[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False)),
            ("tenant_id",models.BigIntegerField(db_index=True)),("created_at",models.DateTimeField(default=tz.now,editable=False)),("updated_at",models.DateTimeField(auto_now=True)),
            ("staff_master_id",models.BigIntegerField(db_index=True)),("fact_id",models.BigIntegerField(db_index=True)),("metric_code",models.CharField(max_length=64)),("raw_value",models.DecimalField(decimal_places=2,max_digits=10)),("raw_unit",models.CharField(max_length=16)),("normalized_value",models.DecimalField(blank=True,decimal_places=2,max_digits=10,null=True)),("normalized_unit",models.CharField(blank=True,default="",max_length=16)),("conversion_rule_version",models.CharField(blank=True,default="",max_length=64)),("eligibility_rule_version",models.CharField(blank=True,default="",max_length=64)),("window_key",models.CharField(blank=True,default="",max_length=64)),("calculated_at",models.DateTimeField())
        ],options={"db_table":"hr_development_metric_ledger","verbose_name":"发展度量台账","verbose_name_plural":"发展度量台账"}),
        migrations.CreateModel("HrDevelopmentComplianceRule",[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False)),
            ("tenant_id",models.BigIntegerField(db_index=True)),("created_at",models.DateTimeField(default=tz.now,editable=False)),("updated_at",models.DateTimeField(auto_now=True)),
            ("rule_pack_id",models.CharField(max_length=128)),("version",models.IntegerField(default=1)),("population_rule_json",models.JSONField(default=dict)),("metric_code",models.CharField(max_length=64)),("time_window_type",models.CharField(max_length=32)),("minimum_value",models.DecimalField(decimal_places=2,max_digits=10)),("unit",models.CharField(max_length=16)),("eligible_activity_types",models.JSONField(default=list)),("minimum_trust_level",models.IntegerField(default=3)),("exception_policy_json",models.JSONField(blank=True,default=dict)),("effective_from",models.DateField()),("effective_to",models.DateField(blank=True,null=True)),("status",models.CharField(default="PUBLISHED",max_length=16))
        ],options={"db_table":"hr_development_compliance_rule","verbose_name":"合规规则","verbose_name_plural":"合规规则","unique_together":[("tenant_id","rule_pack_id","version")]}),
        migrations.CreateModel("HrDevelopmentRiskCase",[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False)),
            ("tenant_id",models.BigIntegerField(db_index=True)),("created_at",models.DateTimeField(default=tz.now,editable=False)),("updated_at",models.DateTimeField(auto_now=True)),
            ("risk_type",models.CharField(db_index=True,max_length=48)),("staff_master_id",models.BigIntegerField(blank=True,db_index=True,null=True)),("source_case_type",models.CharField(blank=True,default="",max_length=64)),("source_case_id",models.BigIntegerField(blank=True,null=True)),("severity",models.CharField(default="MEDIUM",max_length=16)),("status",models.CharField(db_index=True,default="OPEN",max_length=32)),("detected_rule_version",models.CharField(blank=True,default="",max_length=64)),("detected_at",models.DateTimeField()),("owner_id",models.BigIntegerField(blank=True,null=True)),("due_at",models.DateTimeField(blank=True,null=True)),("resolution_reason",models.TextField(blank=True,default="")),("resolution_evidence_refs",models.JSONField(blank=True,default=list)),("version",models.IntegerField(default=1))
        ],options={"db_table":"hr_development_risk_case","verbose_name":"发展风险案例","verbose_name_plural":"发展风险案例"}),
    ]
