import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [('hr10_development', '0015_state_convergence_01')]
    operations = [
        migrations.AddField(model_name='hrlearningparticipation', name='updated_by', field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
        migrations.AddField(model_name='hrlearningprogram', name='created_by', field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
        migrations.AddField(model_name='hrlearningprogram', name='updated_by', field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
        migrations.AddField(model_name='hrlearningprogramversion', name='created_by', field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
        migrations.AddField(model_name='hrlearningprogramversion', name='updated_by', field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
        migrations.AddField(model_name='hrlearningsession', name='created_by', field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
        migrations.AddField(model_name='hrlearningsession', name='updated_by', field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
        migrations.AddField(model_name='hrpracticepositionscene', name='created_by', field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
        migrations.AddField(model_name='hrpracticepositionscene', name='updated_by', field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
        migrations.AddField(model_name='hrpracticeschoolevaluation', name='created_by', field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
        migrations.AddField(model_name='hrpracticeschoolevaluation', name='updated_by', field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
        migrations.AddField(model_name='hrtrainingrequest', name='created_by', field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
        migrations.AddField(model_name='hrtrainingrequest', name='updated_by', field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
        migrations.AddField(model_name='programinstructorref', name='created_by', field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
        migrations.AddField(model_name='programinstructorref', name='updated_by', field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
        migrations.AlterField(model_name='hrdevelopmentapprovalsnapshot', name='approver_id', field=models.BigIntegerField(verbose_name='审批人 ID')),
        migrations.AlterField(model_name='hrdevelopmentapprovalsnapshot', name='case_id', field=models.BigIntegerField(db_index=True, verbose_name='case ID')),
        migrations.AlterField(model_name='hrdevelopmentapprovalsnapshot', name='case_type', field=models.CharField(db_index=True, max_length=64, verbose_name='case 类型')),
        migrations.AlterField(model_name='hrdevelopmentapprovalsnapshot', name='comment', field=models.TextField(blank=True, default='', verbose_name='备注')),
        migrations.AlterField(model_name='hrdevelopmentapprovalsnapshot', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrdevelopmentapprovalsnapshot', name='decided_at', field=models.DateTimeField(verbose_name='决定时间')),
        migrations.AlterField(model_name='hrdevelopmentapprovalsnapshot', name='decision', field=models.CharField(max_length=32, verbose_name='决定')),
        migrations.AlterField(model_name='hrdevelopmentapprovalsnapshot', name='id', field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        migrations.AlterField(model_name='hrdevelopmentapprovalsnapshot', name='object_version', field=models.IntegerField(verbose_name='对象版本')),
        migrations.AlterField(model_name='hrdevelopmentapprovalsnapshot', name='organization_scope', field=models.BigIntegerField(blank=True, null=True, verbose_name='组织范围')),
        migrations.AlterField(model_name='hrdevelopmentapprovalsnapshot', name='reason_code', field=models.CharField(blank=True, default='', max_length=64, verbose_name='原因码')),
        migrations.AlterField(model_name='hrdevelopmentapprovalsnapshot', name='role', field=models.CharField(max_length=64, verbose_name='审批角色')),
        migrations.AlterField(model_name='hrdevelopmentapprovalsnapshot', name='snapshot_hash', field=models.CharField(max_length=128, verbose_name='快照哈希')),
        migrations.AlterField(model_name='hrdevelopmentapprovalsnapshot', name='step_no', field=models.IntegerField(verbose_name='步骤号')),
        migrations.AlterField(model_name='hrdevelopmentapprovalsnapshot', name='tenant_id', field=models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
        migrations.AlterField(model_name='hrdevelopmentapprovalsnapshot', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrdevelopmentapprovalsnapshot', name='workflow_policy_version_id', field=models.CharField(max_length=128, verbose_name='工作流政策版本 ID')),
        migrations.AlterField(model_name='hrdevelopmentcompliancerule', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrdevelopmentcompliancerule', name='id', field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        migrations.AlterField(model_name='hrdevelopmentcompliancerule', name='rule_pack_id', field=models.CharField(max_length=128, verbose_name='规则包 ID')),
        migrations.AlterField(model_name='hrdevelopmentcompliancerule', name='status', field=models.CharField(default='PUBLISHED', max_length=16, verbose_name='状态')),
        migrations.AlterField(model_name='hrdevelopmentcompliancerule', name='tenant_id', field=models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
        migrations.AlterField(model_name='hrdevelopmentcompliancerule', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrdevelopmentfact', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrdevelopmentfact', name='fact_type', field=models.CharField(choices=[('TRAINING_COMPLETION', '培训完成'), ('FURTHER_STUDY', '进修'), ('ENTERPRISE_PRACTICE', '企业实践'), ('DEVELOPMENT_OUTPUT', '发展成果')], db_index=True, max_length=32, verbose_name='事实类型')),
        migrations.AlterField(model_name='hrdevelopmentfact', name='id', field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        migrations.AlterField(model_name='hrdevelopmentfact', name='source_case_type', field=models.CharField(max_length=64, verbose_name='来源 case 类型')),
        migrations.AlterField(model_name='hrdevelopmentfact', name='tenant_id', field=models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
        migrations.AlterField(model_name='hrdevelopmentfact', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrdevelopmentimportjob', name='completed_at', field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
        migrations.AlterField(model_name='hrdevelopmentimportjob', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrdevelopmentimportjob', name='error_rows', field=models.IntegerField(default=0, verbose_name='错误行数')),
        migrations.AlterField(model_name='hrdevelopmentimportjob', name='error_workbook_path', field=models.CharField(blank=True, default='', max_length=512, verbose_name='错误工作簿路径')),
        migrations.AlterField(model_name='hrdevelopmentimportjob', name='file_hash', field=models.CharField(blank=True, default='', max_length=128, verbose_name='文件哈希')),
        migrations.AlterField(model_name='hrdevelopmentimportjob', name='file_name', field=models.CharField(blank=True, default='', max_length=256, verbose_name='文件名')),
        migrations.AlterField(model_name='hrdevelopmentimportjob', name='id', field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        migrations.AlterField(model_name='hrdevelopmentimportjob', name='job_type', field=models.CharField(help_text='LEGACY_EMPLOYEE_QUALIFICATION / LEGACY_EMPLOYEE_NOTE / LEGACY_DOCUMENT / EXCEL_PLAN / EXCEL_PROGRAM / EXCEL_PRACTICE', max_length=64, verbose_name='任务类型')),
        migrations.AlterField(model_name='hrdevelopmentimportjob', name='processed_rows', field=models.IntegerField(default=0, verbose_name='已处理')),
        migrations.AlterField(model_name='hrdevelopmentimportjob', name='result_summary_json', field=models.JSONField(blank=True, default=dict, verbose_name='结果摘要')),
        migrations.AlterField(model_name='hrdevelopmentimportjob', name='retry_count', field=models.IntegerField(default=0, verbose_name='重试次数')),
        migrations.AlterField(model_name='hrdevelopmentimportjob', name='started_at', field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
        migrations.AlterField(model_name='hrdevelopmentimportjob', name='status', field=models.CharField(db_index=True, default='PENDING', max_length=16, verbose_name='状态')),
        migrations.AlterField(model_name='hrdevelopmentimportjob', name='template_version', field=models.CharField(blank=True, default='', max_length=32, verbose_name='模板版本')),
        migrations.AlterField(model_name='hrdevelopmentimportjob', name='tenant_id', field=models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
        migrations.AlterField(model_name='hrdevelopmentimportjob', name='total_rows', field=models.IntegerField(default=0, verbose_name='总行数')),
        migrations.AlterField(model_name='hrdevelopmentimportjob', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrdevelopmentimportjob', name='warning_rows', field=models.IntegerField(default=0, verbose_name='警告行数')),
        migrations.AlterField(model_name='hrdevelopmentmetricledger', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrdevelopmentmetricledger', name='id', field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        migrations.AlterField(model_name='hrdevelopmentmetricledger', name='metric_code', field=models.CharField(max_length=64, verbose_name='度量码')),
        migrations.AlterField(model_name='hrdevelopmentmetricledger', name='tenant_id', field=models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
        migrations.AlterField(model_name='hrdevelopmentmetricledger', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrdevelopmentoutput', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrdevelopmentoutput', name='external_authority_ref', field=models.CharField(blank=True, default='', max_length=256, verbose_name='外部权威引用')),
        migrations.AlterField(model_name='hrdevelopmentoutput', name='id', field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        migrations.AlterField(model_name='hrdevelopmentoutput', name='output_type', field=models.CharField(max_length=48, verbose_name='成果类型')),
        migrations.AlterField(model_name='hrdevelopmentoutput', name='tenant_id', field=models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
        migrations.AlterField(model_name='hrdevelopmentoutput', name='title', field=models.CharField(max_length=256, verbose_name='成果标题')),
        migrations.AlterField(model_name='hrdevelopmentoutput', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrdevelopmentriskcase', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrdevelopmentriskcase', name='id', field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        migrations.AlterField(model_name='hrdevelopmentriskcase', name='risk_type', field=models.CharField(choices=[('MANDATORY_TRAINING_OVERDUE', '必修培训逾期'), ('PRACTICE_COMPLIANCE_DUE', '实践合规在即'), ('PRACTICE_COMPLIANCE_OVERDUE', '实践合规逾期'), ('MISSING_COMPLETION_EVIDENCE', '缺失完成证据'), ('PROVIDER_RISK', 'Provider 风险'), ('OPEN_SAFETY_INCIDENT', '未关闭安全事件'), ('BUDGET_OVERCOMMIT', '预算超承诺'), ('SCHEDULE_CONFLICT', '时间冲突'), ('UNVERIFIED_EXTERNAL_LEARNING', '外部学习未核验'), ('STALE_MIGRATED_FACT', '迁移事实陈旧'), ('DUPLICATE_EVIDENCE', '重复证据'), ('SOURCE_UNAVAILABLE', '数据源不可用')], db_index=True, max_length=48, verbose_name='风险类型')),
        migrations.AlterField(model_name='hrdevelopmentriskcase', name='severity', field=models.CharField(choices=[('CRITICAL', '严重'), ('HIGH', '高'), ('MEDIUM', '中'), ('LOW', '低')], default='MEDIUM', max_length=16)),
        migrations.AlterField(model_name='hrdevelopmentriskcase', name='status', field=models.CharField(choices=[('OPEN', '打开'), ('ACKNOWLEDGED', '已确认'), ('IN_PROGRESS', '处理中'), ('RESOLVED', '已解决'), ('WAIVED', '已豁免')], db_index=True, default='OPEN', max_length=32)),
        migrations.AlterField(model_name='hrdevelopmentriskcase', name='tenant_id', field=models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
        migrations.AlterField(model_name='hrdevelopmentriskcase', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrdevelopmentstagingrow', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrdevelopmentstagingrow', name='error_message', field=models.TextField(blank=True, default='', verbose_name='错误信息')),
        migrations.AlterField(model_name='hrdevelopmentstagingrow', name='id', field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        migrations.AlterField(model_name='hrdevelopmentstagingrow', name='import_job_id', field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='导入 job ID')),
        migrations.AlterField(model_name='hrdevelopmentstagingrow', name='migration_trust_level', field=models.CharField(default='UNKNOWN', max_length=32, verbose_name='迁移可信度')),
        migrations.AlterField(model_name='hrdevelopmentstagingrow', name='parsed_data', field=models.JSONField(blank=True, default=dict, verbose_name='解析后数据')),
        migrations.AlterField(model_name='hrdevelopmentstagingrow', name='raw_text', field=models.TextField(blank=True, default='', verbose_name='原始文本')),
        migrations.AlterField(model_name='hrdevelopmentstagingrow', name='source_field', field=models.CharField(blank=True, default='', max_length=64, verbose_name='来源字段')),
        migrations.AlterField(model_name='hrdevelopmentstagingrow', name='source_object_id', field=models.CharField(max_length=64, verbose_name='来源对象 ID')),
        migrations.AlterField(model_name='hrdevelopmentstagingrow', name='source_system', field=models.CharField(default='LEGACY_EMPLOYEE', max_length=64, verbose_name='来源系统')),
        migrations.AlterField(model_name='hrdevelopmentstagingrow', name='source_table', field=models.CharField(max_length=64, verbose_name='来源表')),
        migrations.AlterField(model_name='hrdevelopmentstagingrow', name='target_id', field=models.BigIntegerField(blank=True, null=True, verbose_name='目标 ID')),
        migrations.AlterField(model_name='hrdevelopmentstagingrow', name='target_model', field=models.CharField(blank=True, default='', max_length=64, verbose_name='目标模型')),
        migrations.AlterField(model_name='hrdevelopmentstagingrow', name='tenant_id', field=models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
        migrations.AlterField(model_name='hrdevelopmentstagingrow', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrdevelopmentstagingrow', name='verification_status', field=models.CharField(default='PENDING', max_length=16, verbose_name='核验状态')),
    ]
