import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [('hr10_development', '0017_state_convergence_03')]
    operations = [
        migrations.AlterField(model_name='hrfurtherstudycase', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrfurtherstudycase', name='field_or_major', field=models.CharField(blank=True, default='', max_length=256, verbose_name='专业/领域')),
        migrations.AlterField(model_name='hrfurtherstudycase', name='full_time_or_part_time', field=models.CharField(default='FULL_TIME', max_length=16, verbose_name='全/兼职')),
        migrations.AlterField(model_name='hrfurtherstudycase', name='funding_source', field=models.CharField(blank=True, default='', max_length=256, verbose_name='经费来源')),
        migrations.AlterField(model_name='hrfurtherstudycase', name='host_organization_id', field=models.BigIntegerField(blank=True, null=True, verbose_name='接受机构 ID')),
        migrations.AlterField(model_name='hrfurtherstudycase', name='id', field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        migrations.AlterField(model_name='hrfurtherstudycase', name='leave_ref', field=models.CharField(blank=True, default='', max_length=256, verbose_name='请假引用')),
        migrations.AlterField(model_name='hrfurtherstudycase', name='lifecycle_status', field=models.CharField(db_index=True, default='IN_PROGRESS', max_length=32, verbose_name='状态')),
        migrations.AlterField(model_name='hrfurtherstudycase', name='planned_end_date', field=models.DateField(verbose_name='计划结束日期')),
        migrations.AlterField(model_name='hrfurtherstudycase', name='staff_master_id', field=models.BigIntegerField(db_index=True, verbose_name='教职工 ID')),
        migrations.AlterField(model_name='hrfurtherstudycase', name='start_date', field=models.DateField(verbose_name='开始日期')),
        migrations.AlterField(model_name='hrfurtherstudycase', name='study_type', field=models.CharField(choices=[('VISITING', '访学'), ('NON_DEGREE', '非学历进修'), ('DEGREE', '学历提升'), ('CERTIFICATE_PROGRAM', '证书项目'), ('RESEARCH_VISIT', '科研访学')], max_length=32, verbose_name='进修类型')),
        migrations.AlterField(model_name='hrfurtherstudycase', name='tenant_id', field=models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
        migrations.AlterField(model_name='hrfurtherstudycase', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrfurtherstudymilestone', name='actual_date', field=models.DateField(blank=True, null=True, verbose_name='实际日期')),
        migrations.AlterField(model_name='hrfurtherstudymilestone', name='case_id', field=models.BigIntegerField(db_index=True, verbose_name='进修案例 ID')),
        migrations.AlterField(model_name='hrfurtherstudymilestone', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrfurtherstudymilestone', name='evidence_refs', field=models.JSONField(blank=True, default=dict, verbose_name='证据引用')),
        migrations.AlterField(model_name='hrfurtherstudymilestone', name='id', field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        migrations.AlterField(model_name='hrfurtherstudymilestone', name='milestone_type', field=models.CharField(choices=[('ADMITTED', '已录取'), ('REGISTERED', '已注册'), ('MID_REVIEW', '中期考核'), ('COURSE_COMPLETED', '课程完成'), ('THESIS', '论文答辩'), ('GRADUATED', '已毕业'), ('CERTIFICATE_RECEIVED', '证书获取'), ('RETURNED_TO_POST', '回岗报到')], max_length=32, verbose_name='里程碑类型')),
        migrations.AlterField(model_name='hrfurtherstudymilestone', name='planned_date', field=models.DateField(verbose_name='计划日期')),
        migrations.AlterField(model_name='hrfurtherstudymilestone', name='status', field=models.CharField(default='PENDING', max_length=16, verbose_name='状态')),
        migrations.AlterField(model_name='hrfurtherstudymilestone', name='tenant_id', field=models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
        migrations.AlterField(model_name='hrfurtherstudymilestone', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrfurtherstudymilestone', name='verification_status', field=models.CharField(default='SELF_REPORTED', max_length=48, verbose_name='核验状态')),
        migrations.AlterField(model_name='hrlearningcompletion', name='completion_status', field=models.CharField(choices=[('PASS', '通过'), ('FAIL', '未通过'), ('INCOMPLETE', '未完成'), ('WITHDRAWN', '已退出'), ('NO_SHOW', '未出席')], max_length=16, verbose_name='完成状态')),
        migrations.AlterField(model_name='hrlearningcompletion', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrlearningcompletion', name='enrollment_id', field=models.BigIntegerField(db_index=True, verbose_name='报名 ID')),
        migrations.AlterField(model_name='hrlearningcompletion', name='evidence_package_id', field=models.CharField(blank=True, default='', max_length=256, verbose_name='证据包 ID')),
        migrations.AlterField(model_name='hrlearningcompletion', name='id', field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        migrations.AlterField(model_name='hrlearningcompletion', name='immutable_hash', field=models.CharField(blank=True, default='', max_length=128, verbose_name='不可变哈希')),
        migrations.AlterField(model_name='hrlearningcompletion', name='program_version_id', field=models.BigIntegerField(verbose_name='项目版本 ID')),
        migrations.AlterField(model_name='hrlearningcompletion', name='revision_no', field=models.IntegerField(default=0, verbose_name='修订号')),
        migrations.AlterField(model_name='hrlearningcompletion', name='supersedes_id', field=models.BigIntegerField(blank=True, null=True, verbose_name='替代的旧版 ID')),
        migrations.AlterField(model_name='hrlearningcompletion', name='tenant_id', field=models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
        migrations.AlterField(model_name='hrlearningcompletion', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrlearningcompletion', name='verification_status', field=models.CharField(db_index=True, default='SELF_REPORTED', max_length=48, verbose_name='核验状态')),
        migrations.AlterField(model_name='hrlearningcompletion', name='verified_credits', field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='已核验学分')),
        migrations.AlterField(model_name='hrlearningcompletion', name='verified_hours', field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='已核验学时')),
        migrations.AlterField(model_name='hrlearningenrollment', name='assigned_at', field=models.DateTimeField(blank=True, null=True, verbose_name='分配时间')),
        migrations.AlterField(model_name='hrlearningenrollment', name='completed_at', field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
        migrations.AlterField(model_name='hrlearningenrollment', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrlearningenrollment', name='due_at', field=models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
        migrations.AlterField(model_name='hrlearningenrollment', name='enrollment_source', field=models.CharField(default='MANUAL', max_length=32, verbose_name='报名来源')),
        migrations.AlterField(model_name='hrlearningenrollment', name='enrollment_status', field=models.CharField(choices=[('PENDING', '待确认'), ('CONFIRMED', '已确认'), ('WAITLISTED', '候补中'), ('CANCELLED', '已取消'), ('NO_SHOW', '未出席'), ('COMPLETED', '已完成')], db_index=True, default='PENDING', max_length=32, verbose_name='报名状态')),
        migrations.AlterField(model_name='hrlearningenrollment', name='id', field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        migrations.AlterField(model_name='hrlearningenrollment', name='offering_id', field=models.BigIntegerField(db_index=True, verbose_name='班次 ID')),
        migrations.AlterField(model_name='hrlearningenrollment', name='request_id', field=models.BigIntegerField(blank=True, null=True, verbose_name='申请 ID')),
        migrations.AlterField(model_name='hrlearningenrollment', name='seat_status', field=models.CharField(blank=True, choices=[('CONFIRMED', '已确认'), ('WAITLISTED', '候补中')], default='', max_length=16, verbose_name='名额状态')),
        migrations.AlterField(model_name='hrlearningenrollment', name='staff_master_id', field=models.BigIntegerField(db_index=True, verbose_name='教职工 ID')),
        migrations.AlterField(model_name='hrlearningenrollment', name='started_at', field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
        migrations.AlterField(model_name='hrlearningenrollment', name='tenant_id', field=models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
        migrations.AlterField(model_name='hrlearningenrollment', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrlearningenrollment', name='version', field=models.IntegerField(default=1, verbose_name='乐观锁版本')),
        migrations.AlterField(model_name='hrlearningoffering', name='capacity', field=models.IntegerField(default=0, verbose_name='名额')),
        migrations.AlterField(model_name='hrlearningoffering', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrlearningoffering', name='delivery_mode', field=models.CharField(choices=[('ONSITE', '线下'), ('ONLINE_LIVE', '线上直播'), ('ONLINE_ASYNC', '线上异步'), ('BLENDED', '混合式'), ('SHADOWING', '跟岗'), ('VISITING', '访学'), ('FIELD_PRACTICE', '现场实践'), ('ENTERPRISE_PRACTICE', '企业实践'), ('SELF_DIRECTED_WITH_VERIFICATION', '自主+核验')], max_length=48, verbose_name='交付方式')),
        migrations.AlterField(model_name='hrlearningoffering', name='end_at', field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
        migrations.AlterField(model_name='hrlearningoffering', name='enrollment_close_at', field=models.DateTimeField(blank=True, null=True, verbose_name='报名截止')),
        migrations.AlterField(model_name='hrlearningoffering', name='enrollment_open_at', field=models.DateTimeField(blank=True, null=True, verbose_name='报名开始')),
        migrations.AlterField(model_name='hrlearningoffering', name='estimated_cost_per_person', field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='人均预估费用')),
        migrations.AlterField(model_name='hrlearningoffering', name='id', field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        migrations.AlterField(model_name='hrlearningoffering', name='instructor_refs', field=models.JSONField(blank=True, default=list, verbose_name='讲师引用')),
        migrations.AlterField(model_name='hrlearningoffering', name='lifecycle_status', field=models.CharField(choices=[('DRAFT', '草稿'), ('OPEN', '报名开放'), ('FULL', '已满'), ('WAITLIST_OPEN', '候补开放'), ('CLOSED', '已关闭'), ('CANCELLED', '已取消')], db_index=True, default='DRAFT', max_length=16, verbose_name='生命周期状态')),
        migrations.AlterField(model_name='hrlearningoffering', name='offering_no', field=models.CharField(max_length=64, verbose_name='班次编号')),
        migrations.AlterField(model_name='hrlearningoffering', name='online_provider_ref', field=models.CharField(blank=True, default='', max_length=256, verbose_name='线上平台引用')),
        migrations.AlterField(model_name='hrlearningoffering', name='program_version_id', field=models.BigIntegerField(db_index=True, verbose_name='项目版本 ID')),
        migrations.AlterField(model_name='hrlearningoffering', name='provider_contact_ref', field=models.CharField(blank=True, default='', max_length=256, verbose_name='提供商联系人引用')),
        migrations.AlterField(model_name='hrlearningoffering', name='start_at', field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
        migrations.AlterField(model_name='hrlearningoffering', name='tenant_id', field=models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
        migrations.AlterField(model_name='hrlearningoffering', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrlearningoffering', name='venue', field=models.CharField(blank=True, default='', max_length=256, verbose_name='地点/线上平台')),
        migrations.AlterField(model_name='hrlearningoffering', name='version', field=models.IntegerField(default=1, verbose_name='乐观锁版本')),
        migrations.AlterField(model_name='hrlearningoffering', name='waitlist_capacity', field=models.IntegerField(default=0, verbose_name='候补名额')),
        migrations.AlterField(model_name='hrlearningparticipation', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrlearningparticipation', name='duration_minutes', field=models.IntegerField(blank=True, null=True, verbose_name='时长(分钟)')),
        migrations.AlterField(model_name='hrlearningparticipation', name='enrollment_id', field=models.BigIntegerField(db_index=True, verbose_name='报名 ID')),
        migrations.AlterField(model_name='hrlearningparticipation', name='evidence_ref', field=models.CharField(blank=True, default='', max_length=256, verbose_name='证据引用')),
        migrations.AlterField(model_name='hrlearningparticipation', name='id', field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        migrations.AlterField(model_name='hrlearningparticipation', name='participation_type', field=models.CharField(choices=[('ATTENDED', '已出席'), ('LATE', '迟到'), ('LEFT_EARLY', '早退'), ('ABSENT', '缺席'), ('EXCUSED', '已请假'), ('UNKNOWN', '未知')], max_length=16, verbose_name='参与类型')),
        migrations.AlterField(model_name='hrlearningparticipation', name='session_id', field=models.BigIntegerField(blank=True, null=True, verbose_name='课程节 ID')),
        migrations.AlterField(model_name='hrlearningparticipation', name='source', field=models.CharField(choices=[('ONLINE_PROVIDER', '线上平台'), ('OFFLINE_SIGNIN', '线下签到'), ('MANUAL', '人工记录'), ('IMPORT', '导入')], max_length=32, verbose_name='来源')),
        migrations.AlterField(model_name='hrlearningparticipation', name='status', field=models.CharField(default='RECORDED', max_length=16, verbose_name='状态')),
        migrations.AlterField(model_name='hrlearningparticipation', name='tenant_id', field=models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
        migrations.AlterField(model_name='hrlearningparticipation', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrlearningprogram', name='activity_type', field=models.CharField(db_index=True, max_length=64, verbose_name='活动类型')),
        migrations.AlterField(model_name='hrlearningprogram', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrlearningprogram', name='current_version_id', field=models.BigIntegerField(blank=True, null=True, verbose_name='当前版本 ID')),
        migrations.AlterField(model_name='hrlearningprogram', name='id', field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        migrations.AlterField(model_name='hrlearningprogram', name='lifecycle_status', field=models.CharField(choices=[('DRAFT', '草稿'), ('UNDER_REVIEW', '审核中'), ('PUBLISHED', '已发布'), ('ACTIVE', '进行中'), ('CLOSING', '关闭中'), ('CLOSED', '已关闭'), ('ARCHIVED', '已归档'), ('CANCELLED', '已取消')], db_index=True, default='DRAFT', max_length=32, verbose_name='生命周期状态')),
        migrations.AlterField(model_name='hrlearningprogram', name='owner_org_id', field=models.BigIntegerField(blank=True, null=True, verbose_name='主办组织 ID')),
        migrations.AlterField(model_name='hrlearningprogram', name='program_code', field=models.CharField(max_length=64, verbose_name='项目编码')),
        migrations.AlterField(model_name='hrlearningprogram', name='provider_org_id', field=models.BigIntegerField(blank=True, null=True, verbose_name='提供机构 ID')),
        migrations.AlterField(model_name='hrlearningprogram', name='source', field=models.CharField(default='INTERNAL', max_length=32, verbose_name='来源')),
        migrations.AlterField(model_name='hrlearningprogram', name='target_population_rule_id', field=models.CharField(blank=True, default='', max_length=128, verbose_name='对象规则 ID')),
        migrations.AlterField(model_name='hrlearningprogram', name='tenant_id', field=models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
        migrations.AlterField(model_name='hrlearningprogram', name='title', field=models.CharField(max_length=256, verbose_name='项目标题')),
        migrations.AlterField(model_name='hrlearningprogram', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrlearningprogram', name='version', field=models.IntegerField(default=1, verbose_name='乐观锁版本')),
        migrations.AlterField(model_name='hrlearningprogramversion', name='completion_rule_json', field=models.JSONField(default=dict, verbose_name='完成规则')),
        migrations.AlterField(model_name='hrlearningprogramversion', name='content_hash', field=models.CharField(blank=True, default='', max_length=128, verbose_name='内容哈希')),
        migrations.AlterField(model_name='hrlearningprogramversion', name='cost_rule_json', field=models.JSONField(default=dict, verbose_name='费用规则')),
        migrations.AlterField(model_name='hrlearningprogramversion', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrlearningprogramversion', name='credit_rule_json', field=models.JSONField(default=dict, verbose_name='学分规则')),
    ]
