import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [('hr10_development', '0018_state_convergence_04')]
    operations = [
        migrations.AlterField(model_name='hrlearningprogramversion', name='curriculum_json', field=models.JSONField(default=dict, verbose_name='课程大纲')),
        migrations.AlterField(model_name='hrlearningprogramversion', name='document_requirement_json', field=models.JSONField(default=dict, verbose_name='材料要求')),
        migrations.AlterField(model_name='hrlearningprogramversion', name='effective_from', field=models.DateField(blank=True, null=True, verbose_name='生效日期')),
        migrations.AlterField(model_name='hrlearningprogramversion', name='effective_to', field=models.DateField(blank=True, null=True, verbose_name='失效日期')),
        migrations.AlterField(model_name='hrlearningprogramversion', name='eligibility_rule_json', field=models.JSONField(default=dict, verbose_name='资格规则')),
        migrations.AlterField(model_name='hrlearningprogramversion', name='evaluation_rule_json', field=models.JSONField(default=dict, verbose_name='评价规则')),
        migrations.AlterField(model_name='hrlearningprogramversion', name='id', field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        migrations.AlterField(model_name='hrlearningprogramversion', name='objectives_json', field=models.JSONField(default=dict, verbose_name='目标')),
        migrations.AlterField(model_name='hrlearningprogramversion', name='program_id', field=models.BigIntegerField(db_index=True, verbose_name='项目 ID')),
        migrations.AlterField(model_name='hrlearningprogramversion', name='published_at', field=models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
        migrations.AlterField(model_name='hrlearningprogramversion', name='status', field=models.CharField(choices=[('DRAFT', '草稿'), ('PUBLISHED', '已发布'), ('SUPERSEDED', '已被替代')], default='DRAFT', max_length=16, verbose_name='版本状态')),
        migrations.AlterField(model_name='hrlearningprogramversion', name='tenant_id', field=models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
        migrations.AlterField(model_name='hrlearningprogramversion', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrlearningprogramversion', name='version_no', field=models.IntegerField(default=1, verbose_name='版本号')),
        migrations.AlterField(model_name='hrlearningsession', name='attendance_required', field=models.BooleanField(default=True, verbose_name='需要签到')),
        migrations.AlterField(model_name='hrlearningsession', name='content_ref', field=models.CharField(blank=True, default='', max_length=256, verbose_name='内容引用')),
        migrations.AlterField(model_name='hrlearningsession', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrlearningsession', name='delivery_mode', field=models.CharField(choices=[('ONSITE', '线下'), ('ONLINE_LIVE', '线上直播'), ('ONLINE_ASYNC', '线上异步'), ('BLENDED', '混合式'), ('SHADOWING', '跟岗'), ('VISITING', '访学'), ('FIELD_PRACTICE', '现场实践'), ('ENTERPRISE_PRACTICE', '企业实践'), ('SELF_DIRECTED_WITH_VERIFICATION', '自主+核验')], max_length=48, verbose_name='交付方式')),
        migrations.AlterField(model_name='hrlearningsession', name='end_at', field=models.DateTimeField(verbose_name='结束时间')),
        migrations.AlterField(model_name='hrlearningsession', name='id', field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        migrations.AlterField(model_name='hrlearningsession', name='instructor_refs', field=models.JSONField(blank=True, default=list, verbose_name='讲师引用')),
        migrations.AlterField(model_name='hrlearningsession', name='offering_id', field=models.BigIntegerField(db_index=True, verbose_name='班次 ID')),
        migrations.AlterField(model_name='hrlearningsession', name='sequence', field=models.IntegerField(default=1, verbose_name='序号')),
        migrations.AlterField(model_name='hrlearningsession', name='start_at', field=models.DateTimeField(verbose_name='开始时间')),
        migrations.AlterField(model_name='hrlearningsession', name='tenant_id', field=models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
        migrations.AlterField(model_name='hrlearningsession', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrlearningsession', name='venue', field=models.CharField(blank=True, default='', max_length=256, verbose_name='地点')),
        migrations.AlterField(model_name='hrpracticepositionscene', name='confidentiality_level', field=models.CharField(default='INTERNAL', max_length=16, verbose_name='保密等级')),
        migrations.AlterField(model_name='hrpracticepositionscene', name='core_tasks', field=models.JSONField(blank=True, default=list, verbose_name='核心任务')),
        migrations.AlterField(model_name='hrpracticepositionscene', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrpracticepositionscene', name='enterprise_department', field=models.CharField(blank=True, default='', max_length=256, verbose_name='企业部门')),
        migrations.AlterField(model_name='hrpracticepositionscene', name='id', field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        migrations.AlterField(model_name='hrpracticepositionscene', name='max_participants', field=models.IntegerField(default=1, verbose_name='最大参与人数')),
        migrations.AlterField(model_name='hrpracticepositionscene', name='mentor_requirement', field=models.TextField(blank=True, default='', verbose_name='导师要求')),
        migrations.AlterField(model_name='hrpracticepositionscene', name='production_or_service_scene', field=models.TextField(blank=True, default='', verbose_name='生产/服务场景描述')),
        migrations.AlterField(model_name='hrpracticepositionscene', name='project_version_id', field=models.BigIntegerField(db_index=True, verbose_name='项目版本 ID')),
        migrations.AlterField(model_name='hrpracticepositionscene', name='real_position_name', field=models.CharField(max_length=256, verbose_name='真实岗位名称')),
        migrations.AlterField(model_name='hrpracticepositionscene', name='required_skills', field=models.JSONField(blank=True, default=list, verbose_name='要求技能')),
        migrations.AlterField(model_name='hrpracticepositionscene', name='safety_level', field=models.CharField(default='STANDARD', max_length=16, verbose_name='安全等级')),
        migrations.AlterField(model_name='hrpracticepositionscene', name='scene_code', field=models.CharField(max_length=64, verbose_name='场景编码')),
        migrations.AlterField(model_name='hrpracticepositionscene', name='specialty_mapping', field=models.CharField(blank=True, default='', max_length=256, verbose_name='专业映射')),
        migrations.AlterField(model_name='hrpracticepositionscene', name='tenant_id', field=models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
        migrations.AlterField(model_name='hrpracticepositionscene', name='title', field=models.CharField(max_length=256, verbose_name='场景标题')),
        migrations.AlterField(model_name='hrpracticepositionscene', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrpracticeschoolevaluation', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrpracticeschoolevaluation', name='id', field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        migrations.AlterField(model_name='hrpracticeschoolevaluation', name='tenant_id', field=models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
        migrations.AlterField(model_name='hrpracticeschoolevaluation', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrtrainingrequest', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrtrainingrequest', name='current_approval_step', field=models.IntegerField(default=0, verbose_name='当前审批步骤')),
        migrations.AlterField(model_name='hrtrainingrequest', name='development_need_id', field=models.BigIntegerField(blank=True, null=True, verbose_name='关联需求 ID')),
        migrations.AlterField(model_name='hrtrainingrequest', name='estimated_cost', field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='预估费用')),
        migrations.AlterField(model_name='hrtrainingrequest', name='external_program_snapshot_json', field=models.JSONField(blank=True, default=dict, verbose_name='外部项目快照')),
        migrations.AlterField(model_name='hrtrainingrequest', name='funding_source_id', field=models.CharField(blank=True, default='', max_length=64, verbose_name='经费来源 ID')),
        migrations.AlterField(model_name='hrtrainingrequest', name='id', field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        migrations.AlterField(model_name='hrtrainingrequest', name='leave_required', field=models.BooleanField(default=False, verbose_name='需要请假')),
        migrations.AlterField(model_name='hrtrainingrequest', name='lifecycle_status', field=models.CharField(choices=[('DRAFT', '草稿'), ('SUBMITTED', '已提交'), ('UNDER_MANAGER_REVIEW', '主管审核中'), ('UNDER_COLLEGE_REVIEW', '学院审核中'), ('UNDER_HR_REVIEW', '人事审核中'), ('UNDER_BUDGET_REVIEW', '预算审核中'), ('APPROVED', '已批准'), ('ENROLLMENT_PENDING', '待报名'), ('ENROLLED', '已报名'), ('IN_PROGRESS', '进行中'), ('COMPLETION_REVIEW', '完成核验中'), ('COMPLETED', '已完成'), ('ARCHIVED', '已归档'), ('RETURNED', '退回修改'), ('REJECTED', '已否决'), ('WITHDRAWN', '已撤回'), ('CANCELLED', '已取消'), ('WAITLISTED', '候补中'), ('NO_SHOW', '未出席'), ('FAILED', '未通过')], db_index=True, default='DRAFT', max_length=32, verbose_name='生命周期状态')),
        migrations.AlterField(model_name='hrtrainingrequest', name='offering_id', field=models.BigIntegerField(blank=True, null=True, verbose_name='班次 ID')),
        migrations.AlterField(model_name='hrtrainingrequest', name='plan_target_id', field=models.BigIntegerField(blank=True, null=True, verbose_name='关联目标 ID')),
        migrations.AlterField(model_name='hrtrainingrequest', name='program_id', field=models.BigIntegerField(blank=True, null=True, verbose_name='项目 ID')),
        migrations.AlterField(model_name='hrtrainingrequest', name='reason', field=models.TextField(blank=True, default='', verbose_name='申请理由')),
        migrations.AlterField(model_name='hrtrainingrequest', name='request_no', field=models.CharField(max_length=64, verbose_name='申请编号')),
        migrations.AlterField(model_name='hrtrainingrequest', name='request_type', field=models.CharField(choices=[('INTERNAL_PROGRAM', '校内项目'), ('EXTERNAL_PROGRAM', '校外项目'), ('FURTHER_STUDY', '进修'), ('TEAM_REQUEST', '团队申请')], db_index=True, max_length=32, verbose_name='申请类型')),
        migrations.AlterField(model_name='hrtrainingrequest', name='staff_master_id', field=models.BigIntegerField(db_index=True, verbose_name='教职工 ID')),
        migrations.AlterField(model_name='hrtrainingrequest', name='submitted_at', field=models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
        migrations.AlterField(model_name='hrtrainingrequest', name='tenant_id', field=models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
        migrations.AlterField(model_name='hrtrainingrequest', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrtrainingrequest', name='version', field=models.IntegerField(default=1, verbose_name='乐观锁版本')),
        migrations.AlterField(model_name='programinstructorref', name='bio', field=models.TextField(blank=True, default='', verbose_name='简介')),
        migrations.AlterField(model_name='programinstructorref', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
        migrations.AlterField(model_name='programinstructorref', name='display_name', field=models.CharField(max_length=128, verbose_name='显示名')),
        migrations.AlterField(model_name='programinstructorref', name='id', field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        migrations.AlterField(model_name='programinstructorref', name='organization', field=models.CharField(blank=True, default='', max_length=256, verbose_name='所属组织')),
        migrations.AlterField(model_name='programinstructorref', name='program_version_id', field=models.BigIntegerField(db_index=True, verbose_name='项目版本 ID')),
        migrations.AlterField(model_name='programinstructorref', name='ref_id', field=models.CharField(max_length=64, verbose_name='引用 ID')),
        migrations.AlterField(model_name='programinstructorref', name='ref_type', field=models.CharField(choices=[('INTERNAL_STAFF', '校内教师'), ('EXTERNAL_ENGAGEMENT', '外聘教师(HR08)'), ('PROVIDER_EXTERNAL', '培训Provider讲师')], max_length=32, verbose_name='引用类型')),
        migrations.AlterField(model_name='programinstructorref', name='tenant_id', field=models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
        migrations.AlterField(model_name='programinstructorref', name='title', field=models.CharField(blank=True, default='', max_length=128, verbose_name='职称/头衔')),
        migrations.AlterField(model_name='programinstructorref', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AddIndex(model_name='hrdevelopmentapprovalsnapshot', index=models.Index(fields=['approver_id', 'created_at'], name='hr_developm_approve_aed18e_idx')),
        migrations.AddIndex(model_name='hrdevelopmentauditevent', index=models.Index(fields=['tenant_id', 'actor_id', 'created_at'], name='hr_developm_tenant__005e0d_idx')),
        migrations.AddIndex(model_name='hrdevelopmentfact', index=models.Index(fields=['staff_master_id', 'fact_type', 'valid_from'], name='hr_developm_staff_m_d366cd_idx')),
        migrations.AddIndex(model_name='hrdevelopmentimportjob', index=models.Index(fields=['tenant_id', 'status'], name='hr_developm_tenant__89a04a_idx')),
        migrations.AddIndex(model_name='hrdevelopmentmetricledger', index=models.Index(fields=['staff_master_id', 'metric_code', 'window_key'], name='hr_developm_staff_m_3c7f3b_idx')),
        migrations.AddIndex(model_name='hrdevelopmentoutput', index=models.Index(fields=['staff_master_id', 'output_type'], name='hr_developm_staff_m_6e4fbd_idx')),
        migrations.AddIndex(model_name='hrdevelopmentoutput', index=models.Index(fields=['duplicate_group_id'], name='hr_developm_duplica_2a2d1c_idx')),
        migrations.AddIndex(model_name='hrdevelopmentriskcase', index=models.Index(fields=['tenant_id', 'risk_type', 'status', 'due_at'], name='hr_developm_tenant__43109e_idx')),
        migrations.AddIndex(model_name='hrdevelopmentstagingrow', index=models.Index(fields=['tenant_id', 'verification_status'], name='hr_developm_tenant__acbb91_idx')),
        migrations.AddIndex(model_name='hrdevelopmentstagingrow', index=models.Index(fields=['import_job_id'], name='hr_developm_import__acfc3c_idx')),
        migrations.AddIndex(model_name='hrdurationledger', index=models.Index(fields=['assignment_id'], name='hr_duration_assignm_7a96a1_idx')),
        migrations.AddIndex(model_name='hrdurationledger', index=models.Index(fields=['source_type'], name='hr_duration_source__7832c6_idx')),
        migrations.AddIndex(model_name='hrenterprisepracticeactivity', index=models.Index(fields=['assignment_id', 'activity_date'], name='hr_practice_assignm_e8295f_idx')),
        migrations.AddIndex(model_name='hrenterprisepracticeassignment', index=models.Index(fields=['staff_master_id', 'assignment_status'], name='hr_enterpri_staff_m_24b482_idx')),
        migrations.AddIndex(model_name='hrenterprisepracticeattendancefact', index=models.Index(fields=['assignment_id', 'date'], name='hr_practice_assignm_aca368_idx')),
        migrations.AddIndex(model_name='hrenterprisepracticeattendancefact', index=models.Index(fields=['trust_level'], name='hr_practice_trust_l_da15ec_idx')),
        migrations.AddIndex(model_name='hrenterprisepracticeattendancefact', index=models.Index(fields=['verification_status'], name='hr_practice_verific_8c4da3_idx')),
        migrations.AddIndex(model_name='hrenterprisepracticeproject', index=models.Index(fields=['tenant_id', 'lifecycle_status'], name='hr_enterpri_tenant__35cc1a_idx')),
        migrations.AddIndex(model_name='hrfurtherstudycase', index=models.Index(fields=['staff_master_id', 'lifecycle_status'], name='hr_further__staff_m_e62b45_idx')),
        migrations.AddIndex(model_name='hrfurtherstudymilestone', index=models.Index(fields=['case_id', 'milestone_type'], name='hr_further__case_id_6975de_idx')),
        migrations.AddIndex(model_name='hrlearningcompletion', index=models.Index(fields=['enrollment_id'], name='hr_learning_enrollm_89abf2_idx')),
        migrations.AddIndex(model_name='hrlearningcompletion', index=models.Index(fields=['verification_status'], name='hr_learning_verific_471086_idx')),
        migrations.AddIndex(model_name='hrlearningenrollment', index=models.Index(fields=['offering_id', 'enrollment_status'], name='hr_learning_offerin_d058b1_idx')),
        migrations.AddIndex(model_name='hrlearningenrollment', index=models.Index(fields=['staff_master_id', 'enrollment_status'], name='hr_learning_staff_m_6d5bca_idx')),
        migrations.AddIndex(model_name='hrlearningoffering', index=models.Index(fields=['program_version_id', 'lifecycle_status'], name='hr_learning_program_bc3e4d_idx')),
        migrations.AddIndex(model_name='hrlearningparticipation', index=models.Index(fields=['enrollment_id'], name='hr_learning_enrollm_cb26e3_idx')),
        migrations.AddIndex(model_name='hrlearningprogram', index=models.Index(fields=['tenant_id', 'lifecycle_status'], name='hr_learning_tenant__1959a9_idx')),
        migrations.AddIndex(model_name='hrlearningprogram', index=models.Index(fields=['tenant_id', 'activity_type'], name='hr_learning_tenant__ac8b07_idx')),
    ]
