# Generated by Django 5.2 on 2026-09-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "hr10_development",
            "0024_hrfurtherstudymilestone_writeback_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="hrlearningprogramversion",
            name="completion_rule_json",
            field=models.JSONField(blank=True, default=dict, verbose_name="完成规则"),
        ),
        migrations.AlterField(
            model_name="hrlearningprogramversion",
            name="evaluation_rule_json",
            field=models.JSONField(blank=True, default=dict, verbose_name="评价规则"),
        ),
        migrations.AlterField(
            model_name="hrlearningprogramversion",
            name="credit_rule_json",
            field=models.JSONField(blank=True, default=dict, verbose_name="学分规则"),
        ),
        migrations.AlterField(
            model_name="hrlearningprogramversion",
            name="cost_rule_json",
            field=models.JSONField(blank=True, default=dict, verbose_name="费用规则"),
        ),
        migrations.AlterField(
            model_name="hrlearningprogramversion",
            name="eligibility_rule_json",
            field=models.JSONField(blank=True, default=dict, verbose_name="资格规则"),
        ),
        migrations.AlterField(
            model_name="hrlearningprogramversion",
            name="document_requirement_json",
            field=models.JSONField(blank=True, default=dict, verbose_name="材料要求"),
        ),
    ]
