# HR10-S3: 培训项目
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [("horilla_auth", "__first__"), ("hr10_development", "0002_plan")]
    operations = [
        migrations.CreateModel(name="HrLearningProgram", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)), ("tenant_id", models.BigIntegerField(db_index=True)), ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)), ("updated_at", models.DateTimeField(auto_now=True)), ("program_code", models.CharField(max_length=64)), ("title", models.CharField(max_length=256)), ("activity_type", models.CharField(db_index=True, max_length=64)), ("owner_org_id", models.BigIntegerField(blank=True, null=True)), ("provider_org_id", models.BigIntegerField(blank=True, null=True)), ("target_population_rule_id", models.CharField(blank=True, default="", max_length=128)), ("current_version_id", models.BigIntegerField(blank=True, null=True)), ("lifecycle_status", models.CharField(db_index=True, default="DRAFT", max_length=32)), ("source", models.CharField(default="INTERNAL", max_length=32)), ("version", models.IntegerField(default=1))], options={"verbose_name": "培训项目", "verbose_name_plural": "培训项目", "db_table": "hr_learning_program", "unique_together": {("tenant_id", "program_code")}}),
        migrations.CreateModel(name="HrLearningProgramVersion", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)), ("tenant_id", models.BigIntegerField(db_index=True)), ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)), ("updated_at", models.DateTimeField(auto_now=True)), ("program_id", models.BigIntegerField(db_index=True)), ("version_no", models.IntegerField(default=1)), ("status", models.CharField(default="DRAFT", max_length=16)), ("objectives_json", models.JSONField(default=dict)), ("curriculum_json", models.JSONField(default=dict)), ("completion_rule_json", models.JSONField(default=dict)), ("evaluation_rule_json", models.JSONField(default=dict)), ("credit_rule_json", models.JSONField(default=dict)), ("cost_rule_json", models.JSONField(default=dict)), ("eligibility_rule_json", models.JSONField(default=dict)), ("document_requirement_json", models.JSONField(default=dict)), ("content_hash", models.CharField(blank=True, default="", max_length=128)), ("published_at", models.DateTimeField(blank=True, null=True)), ("effective_from", models.DateField(blank=True, null=True)), ("effective_to", models.DateField(blank=True, null=True))], options={"verbose_name": "培训项目版本", "verbose_name_plural": "培训项目版本", "db_table": "hr_learning_program_version", "unique_together": {("program_id", "version_no")}}),
        migrations.CreateModel(name="HrLearningOffering", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)), ("tenant_id", models.BigIntegerField(db_index=True)), ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)), ("updated_at", models.DateTimeField(auto_now=True)), ("program_version_id", models.BigIntegerField(db_index=True)), ("offering_no", models.CharField(max_length=64)), ("delivery_mode", models.CharField(max_length=48)), ("venue", models.CharField(blank=True, default="", max_length=256)), ("online_provider_ref", models.CharField(blank=True, default="", max_length=256)), ("start_at", models.DateTimeField(blank=True, null=True)), ("end_at", models.DateTimeField(blank=True, null=True)), ("enrollment_open_at", models.DateTimeField(blank=True, null=True)), ("enrollment_close_at", models.DateTimeField(blank=True, null=True)), ("capacity", models.IntegerField(default=0)), ("waitlist_capacity", models.IntegerField(default=0)), ("instructor_refs", models.JSONField(blank=True, default=list)), ("provider_contact_ref", models.CharField(blank=True, default="", max_length=256)), ("estimated_cost_per_person", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)), ("lifecycle_status", models.CharField(db_index=True, default="DRAFT", max_length=16)), ("version", models.IntegerField(default=1))], options={"verbose_name": "培训班次", "verbose_name_plural": "培训班次", "db_table": "hr_learning_offering", "unique_together": {("tenant_id", "offering_no")}}),
        migrations.CreateModel(name="HrLearningSession", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)), ("tenant_id", models.BigIntegerField(db_index=True)), ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)), ("updated_at", models.DateTimeField(auto_now=True)), ("offering_id", models.BigIntegerField(db_index=True)), ("sequence", models.IntegerField(default=1)), ("start_at", models.DateTimeField()), ("end_at", models.DateTimeField()), ("venue", models.CharField(blank=True, default="", max_length=256)), ("delivery_mode", models.CharField(max_length=48)), ("attendance_required", models.BooleanField(default=True)), ("instructor_refs", models.JSONField(blank=True, default=list)), ("content_ref", models.CharField(blank=True, default="", max_length=256))], options={"verbose_name": "培训课程节", "verbose_name_plural": "培训课程节", "db_table": "hr_learning_session"}),
        migrations.CreateModel(name="ProgramInstructorRef", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)), ("tenant_id", models.BigIntegerField(db_index=True)), ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)), ("updated_at", models.DateTimeField(auto_now=True)), ("program_version_id", models.BigIntegerField(db_index=True)), ("ref_type", models.CharField(max_length=32)), ("ref_id", models.CharField(max_length=64)), ("display_name", models.CharField(max_length=128)), ("title", models.CharField(blank=True, default="", max_length=128)), ("organization", models.CharField(blank=True, default="", max_length=256)), ("bio", models.TextField(blank=True, default=""))], options={"verbose_name": "培训讲师", "verbose_name_plural": "培训讲师", "db_table": "hr_learning_program_instructor", "unique_together": {("program_version_id", "ref_type", "ref_id")}}),
    ]
