# HR10-S4: 报名与审批
from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):
    dependencies = [("horilla_auth", "__first__"), ("hr10_development", "0003_program")]
    operations = [
        migrations.CreateModel(name="HrTrainingRequest", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)), ("tenant_id", models.BigIntegerField(db_index=True)), ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)), ("updated_at", models.DateTimeField(auto_now=True)), ("request_no", models.CharField(max_length=64)), ("staff_master_id", models.BigIntegerField(db_index=True)), ("request_type", models.CharField(db_index=True, max_length=32)), ("program_id", models.BigIntegerField(blank=True, null=True)), ("offering_id", models.BigIntegerField(blank=True, null=True)), ("external_program_snapshot_json", models.JSONField(blank=True, default=dict)), ("development_need_id", models.BigIntegerField(blank=True, null=True)), ("plan_target_id", models.BigIntegerField(blank=True, null=True)), ("estimated_cost", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)), ("funding_source_id", models.CharField(blank=True, default="", max_length=64)), ("leave_required", models.BooleanField(default=False)), ("reason", models.TextField(blank=True, default="")), ("lifecycle_status", models.CharField(db_index=True, default="DRAFT", max_length=32)), ("current_approval_step", models.IntegerField(default=0)), ("version", models.IntegerField(default=1)), ("submitted_at", models.DateTimeField(blank=True, null=True))], options={"verbose_name": "培训申请", "verbose_name_plural": "培训申请", "db_table": "hr_training_request"}),
        migrations.CreateModel(name="HrLearningEnrollment", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)), ("tenant_id", models.BigIntegerField(db_index=True)), ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)), ("updated_at", models.DateTimeField(auto_now=True)), ("offering_id", models.BigIntegerField(db_index=True)), ("staff_master_id", models.BigIntegerField(db_index=True)), ("request_id", models.BigIntegerField(blank=True, null=True)), ("enrollment_source", models.CharField(default="MANUAL", max_length=32)), ("enrollment_status", models.CharField(db_index=True, default="PENDING", max_length=32)), ("seat_status", models.CharField(blank=True, default="", max_length=16)), ("assigned_at", models.DateTimeField(blank=True, null=True)), ("due_at", models.DateTimeField(blank=True, null=True)), ("started_at", models.DateTimeField(blank=True, null=True)), ("completed_at", models.DateTimeField(blank=True, null=True)), ("version", models.IntegerField(default=1))], options={"verbose_name": "培训报名", "verbose_name_plural": "培训报名", "db_table": "hr_learning_enrollment", "unique_together": {("offering_id", "staff_master_id")}}),
        migrations.CreateModel(name="HrDevelopmentApprovalSnapshot", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)), ("tenant_id", models.BigIntegerField(db_index=True)), ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)), ("updated_at", models.DateTimeField(auto_now=True)), ("case_type", models.CharField(db_index=True, max_length=64)), ("case_id", models.BigIntegerField(db_index=True)), ("workflow_policy_version_id", models.CharField(max_length=128)), ("step_no", models.IntegerField()), ("role", models.CharField(max_length=64)), ("approver_id", models.BigIntegerField()), ("organization_scope", models.BigIntegerField(blank=True, null=True)), ("decision", models.CharField(max_length=32)), ("reason_code", models.CharField(blank=True, default="", max_length=64)), ("comment", models.TextField(blank=True, default="")), ("object_version", models.IntegerField()), ("snapshot_hash", models.CharField(max_length=128)), ("decided_at", models.DateTimeField())], options={"verbose_name": "审批快照", "verbose_name_plural": "审批快照", "db_table": "hr_development_approval_snapshot", "unique_together": {("case_type", "case_id", "step_no")}}),
    ]
