# S6: practice projects + scenes + placements + assignments + mentors + plans
from django.db import migrations, models; import django.utils.timezone as tz

class Migration(migrations.Migration):
    dependencies=[("horilla_auth","__first__"),("hr10_development","0005_completion")]
    operations=[
        migrations.CreateModel("HrEnterprisePracticeProject",[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False)),
            ("tenant_id",models.BigIntegerField(db_index=True)),("created_at",models.DateTimeField(default=tz.now,editable=False)),("updated_at",models.DateTimeField(auto_now=True)),
            ("project_no",models.CharField(max_length=64)),("title",models.CharField(max_length=256)),("specialty_category",models.CharField(blank=True,default="",max_length=128)),("provider_org_id",models.BigIntegerField()),("practice_base_ref",models.CharField(blank=True,default="",max_length=256)),("owner_org_id",models.BigIntegerField(blank=True,null=True)),("target_population_rule_id",models.CharField(blank=True,default="",max_length=128)),("current_version_id",models.BigIntegerField(blank=True,null=True)),("lifecycle_status",models.CharField(db_index=True,default="DRAFT",max_length=32)),("planned_start_date",models.DateField(blank=True,null=True)),("planned_end_date",models.DateField(blank=True,null=True)),("capacity",models.IntegerField(default=0)),("funding_source_id",models.CharField(blank=True,default="",max_length=64)),("version",models.IntegerField(default=1))
        ],options={"db_table":"hr_enterprise_practice_project","verbose_name":"企业实践项目","verbose_name_plural":"企业实践项目","unique_together":[("tenant_id","project_no")]}),
        migrations.CreateModel("HrEnterprisePracticeProjectVersion",[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False)),
            ("tenant_id",models.BigIntegerField(db_index=True)),("created_at",models.DateTimeField(default=tz.now,editable=False)),("updated_at",models.DateTimeField(auto_now=True)),
            ("project_id",models.BigIntegerField(db_index=True)),("version_no",models.IntegerField(default=1)),("objectives_json",models.JSONField(default=dict)),("position_scene_requirements_json",models.JSONField(default=dict)),("module_task_json",models.JSONField(default=dict)),("mentor_requirements_json",models.JSONField(default=dict)),("evaluation_rubric_json",models.JSONField(default=dict)),("output_requirements_json",models.JSONField(default=dict)),("safety_requirements_json",models.JSONField(default=dict)),("confidentiality_ip_requirements_json",models.JSONField(default=dict)),("completion_rule_json",models.JSONField(default=dict)),("policy_snapshot_json",models.JSONField(default=dict)),("content_hash",models.CharField(blank=True,default="",max_length=128)),("published_at",models.DateTimeField(blank=True,null=True))
        ],options={"db_table":"hr_enterprise_practice_project_version","verbose_name":"企业实践项目版本","verbose_name_plural":"企业实践项目版本","unique_together":[("project_id","version_no")]}),
        migrations.CreateModel("HrPracticePositionScene",[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False)),
            ("tenant_id",models.BigIntegerField(db_index=True)),("created_at",models.DateTimeField(default=tz.now,editable=False)),("updated_at",models.DateTimeField(auto_now=True)),
            ("project_version_id",models.BigIntegerField(db_index=True)),("scene_code",models.CharField(max_length=64)),("title",models.CharField(max_length=256)),("enterprise_department",models.CharField(blank=True,default="",max_length=256)),("real_position_name",models.CharField(max_length=256)),("production_or_service_scene",models.TextField(blank=True,default="")),("specialty_mapping",models.CharField(blank=True,default="",max_length=256)),("core_tasks",models.JSONField(blank=True,default=list)),("required_skills",models.JSONField(blank=True,default=list)),("safety_level",models.CharField(default="STANDARD",max_length=16)),("confidentiality_level",models.CharField(default="INTERNAL",max_length=16)),("max_participants",models.IntegerField(default=1)),("mentor_requirement",models.TextField(blank=True,default=""))
        ],options={"db_table":"hr_practice_position_scene","verbose_name":"实践岗位场景","verbose_name_plural":"实践岗位场景","unique_together":[("project_version_id","scene_code")]}),
        migrations.CreateModel("HrEnterprisePracticePlacement",[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False)),
            ("tenant_id",models.BigIntegerField(db_index=True)),("created_at",models.DateTimeField(default=tz.now,editable=False)),("updated_at",models.DateTimeField(auto_now=True)),
            ("project_id",models.BigIntegerField(db_index=True)),("project_version_id",models.BigIntegerField()),("scene_id",models.BigIntegerField()),("batch_no",models.CharField(max_length=64)),("start_date",models.DateField()),("end_date",models.DateField()),("capacity",models.IntegerField(default=0)),("enterprise_mentor_refs",models.JSONField(blank=True,default=list)),("school_contact_ref",models.CharField(blank=True,default="",max_length=256)),("venue",models.CharField(blank=True,default="",max_length=256)),("status",models.CharField(db_index=True,default="DRAFT",max_length=32)),("version",models.IntegerField(default=1))
        ],options={"db_table":"hr_enterprise_practice_placement","verbose_name":"实践批次","verbose_name_plural":"实践批次"}),
        migrations.CreateModel("HrEnterprisePracticeAssignment",[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False)),
            ("tenant_id",models.BigIntegerField(db_index=True)),("created_at",models.DateTimeField(default=tz.now,editable=False)),("updated_at",models.DateTimeField(auto_now=True)),
            ("placement_id",models.BigIntegerField(db_index=True)),("staff_master_id",models.BigIntegerField(db_index=True)),("request_id",models.BigIntegerField(blank=True,null=True)),("development_need_id",models.BigIntegerField(blank=True,null=True)),("assignment_status",models.CharField(db_index=True,default="DRAFT",max_length=32)),("assigned_scene_id",models.BigIntegerField()),("enterprise_mentor_id",models.BigIntegerField()),("school_mentor_id",models.BigIntegerField(blank=True,null=True)),("planned_hours",models.IntegerField(default=0)),("planned_days",models.IntegerField(default=0)),("actual_verified_hours",models.IntegerField(default=0)),("actual_verified_days",models.IntegerField(default=0)),("started_at",models.DateTimeField(blank=True,null=True)),("completed_at",models.DateTimeField(blank=True,null=True)),("version",models.IntegerField(default=1))
        ],options={"db_table":"hr_enterprise_practice_assignment","verbose_name":"实践派出","verbose_name_plural":"实践派出"}),
        migrations.CreateModel("HrEnterprisePracticeMentor",[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False)),
            ("tenant_id",models.BigIntegerField(db_index=True)),("created_at",models.DateTimeField(default=tz.now,editable=False)),("updated_at",models.DateTimeField(auto_now=True)),
            ("provider_org_id",models.BigIntegerField()),("person_display_name",models.CharField(max_length=128)),("position_title",models.CharField(blank=True,default="",max_length=128)),("professional_domain",models.CharField(blank=True,default="",max_length=128)),("credential_summary",models.TextField(blank=True,default="")),("contact_ref",models.CharField(blank=True,default="",max_length=256)),("active_from",models.DateField(blank=True,null=True)),("active_to",models.DateField(blank=True,null=True)),("verification_status",models.CharField(default="PENDING",max_length=32)),("access_identity_ref",models.CharField(blank=True,default="",max_length=256))
        ],options={"db_table":"hr_enterprise_practice_mentor","verbose_name":"企业实践导师","verbose_name_plural":"企业实践导师"}),
        migrations.CreateModel("HrEnterprisePracticePlan",[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False)),
            ("tenant_id",models.BigIntegerField(db_index=True)),("created_at",models.DateTimeField(default=tz.now,editable=False)),("updated_at",models.DateTimeField(auto_now=True)),
            ("assignment_id",models.BigIntegerField(db_index=True,unique=True)),("objective_snapshot_json",models.JSONField(default=dict)),("task_snapshot_json",models.JSONField(default=dict)),("schedule_json",models.JSONField(default=dict)),("expected_outputs_json",models.JSONField(default=dict)),("evidence_requirements_json",models.JSONField(default=dict)),("safety_ack_ref",models.CharField(blank=True,default="",max_length=256)),("confidentiality_ack_ref",models.CharField(blank=True,default="",max_length=256)),("approved_by_enterprise",models.BooleanField(default=False)),("approved_by_school",models.BooleanField(default=False)),("frozen_at",models.DateTimeField(blank=True,null=True)),("content_hash",models.CharField(blank=True,default="",max_length=128))
        ],options={"db_table":"hr_enterprise_practice_plan","verbose_name":"实践计划","verbose_name_plural":"实践计划"}),
    ]
