# S7: practice process (activity/evidence/evaluation/output)
from django.db import migrations, models; import django.utils.timezone as tz

class Migration(migrations.Migration):
    dependencies=[("horilla_auth","__first__"),("hr10_development","0006_practice_project")]
    operations=[
        migrations.CreateModel("HrEnterprisePracticeActivity",[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False)),
            ("tenant_id",models.BigIntegerField(db_index=True)),("created_at",models.DateTimeField(default=tz.now,editable=False)),("updated_at",models.DateTimeField(auto_now=True)),
            ("assignment_id",models.BigIntegerField(db_index=True)),("activity_date",models.DateField()),("activity_type",models.CharField(max_length=48)),("scene_id",models.BigIntegerField(blank=True,null=True)),("task_code",models.CharField(blank=True,default="",max_length=64)),("start_at",models.DateTimeField(blank=True,null=True)),("end_at",models.DateTimeField(blank=True,null=True)),("duration_minutes",models.IntegerField(blank=True,null=True)),("title",models.CharField(blank=True,default="",max_length=256)),("summary",models.TextField(blank=True,default="")),("source",models.CharField(default="SELF",max_length=32)),("status",models.CharField(db_index=True,default="DRAFT",max_length=16)),("evidence_refs",models.JSONField(blank=True,default=list)),("verifier_ref",models.CharField(blank=True,default="",max_length=256)),("verified_at",models.DateTimeField(blank=True,null=True)),("version",models.IntegerField(default=1))
        ],options={"db_table":"hr_practice_activity","verbose_name":"实践活动","verbose_name_plural":"实践活动"}),
        migrations.CreateModel("HrEnterprisePracticeEvidence",[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False)),
            ("tenant_id",models.BigIntegerField(db_index=True)),("created_at",models.DateTimeField(default=tz.now,editable=False)),("updated_at",models.DateTimeField(auto_now=True)),
            ("assignment_id",models.BigIntegerField(db_index=True)),("activity_id",models.BigIntegerField(blank=True,null=True)),("evidence_type",models.CharField(max_length=64)),("document_id",models.CharField(blank=True,default="",max_length=256)),("external_ref",models.CharField(blank=True,default="",max_length=256)),("captured_at",models.DateTimeField(blank=True,null=True)),("source",models.CharField(default="SELF",max_length=32)),("submitted_by",models.BigIntegerField(blank=True,null=True)),("verification_status",models.CharField(db_index=True,default="SELF_REPORTED",max_length=48)),("verified_by",models.BigIntegerField(blank=True,null=True)),("verified_at",models.DateTimeField(blank=True,null=True)),("content_hash",models.CharField(blank=True,default="",max_length=128)),("sensitivity",models.CharField(default="INTERNAL",max_length=32))
        ],options={"db_table":"hr_practice_evidence","verbose_name":"实践证据","verbose_name_plural":"实践证据"}),
        migrations.CreateModel("HrEnterpriseMentorFeedback",[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False)),
            ("tenant_id",models.BigIntegerField(db_index=True)),("created_at",models.DateTimeField(default=tz.now,editable=False)),("updated_at",models.DateTimeField(auto_now=True)),
            ("assignment_id",models.BigIntegerField(db_index=True)),("mentor_id",models.BigIntegerField()),("period_start",models.DateField(blank=True,null=True)),("period_end",models.DateField(blank=True,null=True)),("rubric_version_id",models.CharField(blank=True,default="",max_length=128)),("ratings_json",models.JSONField(default=dict)),("strengths",models.TextField(blank=True,default="")),("gaps",models.TextField(blank=True,default="")),("incident_flags",models.TextField(blank=True,default="")),("recommendation",models.TextField(blank=True,default="")),("submitted_at",models.DateTimeField(blank=True,null=True)),("signature_or_verification_ref",models.CharField(blank=True,default="",max_length=256)),("revision_no",models.IntegerField(default=0))
        ],options={"db_table":"hr_practice_mentor_feedback","verbose_name":"企业导师评价","verbose_name_plural":"企业导师评价"}),
        migrations.CreateModel("HrPracticeSchoolEvaluation",[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False)),
            ("tenant_id",models.BigIntegerField(db_index=True)),("created_at",models.DateTimeField(default=tz.now,editable=False)),("updated_at",models.DateTimeField(auto_now=True)),
            ("assignment_id",models.BigIntegerField(db_index=True)),("evaluator_id",models.BigIntegerField()),("rubric_version_id",models.CharField(blank=True,default="",max_length=128)),("evidence_package_id",models.CharField(blank=True,default="",max_length=256)),("ratings_json",models.JSONField(default=dict)),("completion_recommendation",models.CharField(default="PENDING",max_length=16)),("concerns",models.TextField(blank=True,default="")),("submitted_at",models.DateTimeField(blank=True,null=True)),("revision_no",models.IntegerField(default=0))
        ],options={"db_table":"hr_practice_school_evaluation","verbose_name":"学校评价","verbose_name_plural":"学校评价"}),
        migrations.CreateModel("HrEnterprisePracticeEvaluation",[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False)),
            ("tenant_id",models.BigIntegerField(db_index=True)),("created_at",models.DateTimeField(default=tz.now,editable=False)),("updated_at",models.DateTimeField(auto_now=True)),
            ("assignment_id",models.BigIntegerField(db_index=True,unique=True)),("project_version_id",models.BigIntegerField()),("enterprise_evaluation_ref",models.CharField(blank=True,default="",max_length=256)),("school_evaluation_ref",models.CharField(blank=True,default="",max_length=256)),("completion_status",models.CharField(max_length=24)),("verified_hours",models.IntegerField(default=0)),("verified_days",models.IntegerField(default=0)),("rubric_result_json",models.JSONField(default=dict)),("final_comment",models.TextField(blank=True,default="")),("decided_by",models.BigIntegerField(blank=True,null=True)),("decided_at",models.DateTimeField(blank=True,null=True)),("evidence_package_hash",models.CharField(blank=True,default="",max_length=128)),("revision_no",models.IntegerField(default=0)),("immutable_hash",models.CharField(blank=True,default="",max_length=128))
        ],options={"db_table":"hr_practice_evaluation","verbose_name":"企业实践最终评价","verbose_name_plural":"企业实践最终评价"}),
        migrations.CreateModel("HrDevelopmentOutput",[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False)),
            ("tenant_id",models.BigIntegerField(db_index=True)),("created_at",models.DateTimeField(default=tz.now,editable=False)),("updated_at",models.DateTimeField(auto_now=True)),
            ("staff_master_id",models.BigIntegerField(db_index=True)),("source_activity_type",models.CharField(max_length=64)),("source_case_id",models.BigIntegerField()),("output_type",models.CharField(max_length=48)),("title",models.CharField(max_length=256)),("description",models.TextField(blank=True,default="")),("period",models.CharField(blank=True,default="",max_length=64)),("evidence_refs",models.JSONField(blank=True,default=list)),("external_authority_ref",models.CharField(blank=True,default="",max_length=256)),("verification_status",models.CharField(db_index=True,default="SELF_REPORTED",max_length=48)),("verified_by",models.BigIntegerField(blank=True,null=True)),("verified_at",models.DateTimeField(blank=True,null=True)),("duplicate_group_id",models.CharField(blank=True,default="",max_length=64)),("version",models.IntegerField(default=1))
        ],options={"db_table":"hr_development_output","verbose_name":"发展成果","verbose_name_plural":"发展成果"}),
    ]
