import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [('hr10_development', '0016_state_convergence_02')]
    operations = [
        migrations.AlterField(model_name='hrdurationledger', name='assignment_id', field=models.BigIntegerField(db_index=True, verbose_name='派出 ID')),
        migrations.AlterField(model_name='hrdurationledger', name='calculated_at', field=models.DateTimeField(verbose_name='计算时间')),
        migrations.AlterField(model_name='hrdurationledger', name='conversion_rule_version', field=models.CharField(blank=True, default='', max_length=64, verbose_name='换算规则版本')),
        migrations.AlterField(model_name='hrdurationledger', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrdurationledger', name='eligible_days', field=models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='有效天数')),
        migrations.AlterField(model_name='hrdurationledger', name='eligible_hours', field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='有效小时数')),
        migrations.AlterField(model_name='hrdurationledger', name='excluded_reason', field=models.CharField(blank=True, default='', max_length=64, verbose_name='排除原因')),
        migrations.AlterField(model_name='hrdurationledger', name='id', field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        migrations.AlterField(model_name='hrdurationledger', name='raw_days', field=models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='原始天数')),
        migrations.AlterField(model_name='hrdurationledger', name='raw_hours', field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='原始小时数')),
        migrations.AlterField(model_name='hrdurationledger', name='source_id', field=models.BigIntegerField(verbose_name='来源记录 ID')),
        migrations.AlterField(model_name='hrdurationledger', name='source_type', field=models.CharField(choices=[('ACTIVITY', '活动'), ('ATTENDANCE', '出勤'), ('MENTOR_CONFIRMED', '导师确认'), ('MANUAL_ADJUST', '人工调整')], max_length=32, verbose_name='来源类型')),
        migrations.AlterField(model_name='hrdurationledger', name='tenant_id', field=models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
        migrations.AlterField(model_name='hrdurationledger', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrenterprisementorfeedback', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrenterprisementorfeedback', name='id', field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        migrations.AlterField(model_name='hrenterprisementorfeedback', name='tenant_id', field=models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
        migrations.AlterField(model_name='hrenterprisementorfeedback', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrenterprisepracticeactivity', name='activity_date', field=models.DateField(verbose_name='活动日期')),
        migrations.AlterField(model_name='hrenterprisepracticeactivity', name='activity_type', field=models.CharField(choices=[('OBSERVATION', '考察观摩'), ('POSITION_WORK', '岗位操作'), ('TECHNICAL_TRAINING', '技能培训'), ('PRODUCTION_TASK', '生产任务'), ('SERVICE_TASK', '服务任务'), ('R_AND_D', '研发'), ('TECHNICAL_IMPROVEMENT', '技术改进'), ('QUALITY_ACTIVITY', '质量活动'), ('PROJECT_MEETING', '项目会议'), ('EMPLOYEE_TRAINING_DELIVERY', '员工培训授课'), ('STUDENT_PRACTICE_GUIDANCE', '学生实践指导'), ('TEACHING_TRANSFORMATION', '教学转化'), ('OTHER', '其他')], max_length=48, verbose_name='活动类型')),
        migrations.AlterField(model_name='hrenterprisepracticeactivity', name='assignment_id', field=models.BigIntegerField(db_index=True, verbose_name='派出 ID')),
        migrations.AlterField(model_name='hrenterprisepracticeactivity', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrenterprisepracticeactivity', name='duration_minutes', field=models.IntegerField(blank=True, null=True, verbose_name='时长(分钟)')),
        migrations.AlterField(model_name='hrenterprisepracticeactivity', name='evidence_refs', field=models.JSONField(blank=True, default=list, verbose_name='证据引用')),
        migrations.AlterField(model_name='hrenterprisepracticeactivity', name='id', field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        migrations.AlterField(model_name='hrenterprisepracticeactivity', name='source', field=models.CharField(default='SELF', max_length=32, verbose_name='来源')),
        migrations.AlterField(model_name='hrenterprisepracticeactivity', name='status', field=models.CharField(db_index=True, default='DRAFT', max_length=16, verbose_name='状态')),
        migrations.AlterField(model_name='hrenterprisepracticeactivity', name='summary', field=models.TextField(blank=True, default='', verbose_name='摘要')),
        migrations.AlterField(model_name='hrenterprisepracticeactivity', name='task_code', field=models.CharField(blank=True, default='', max_length=64, verbose_name='任务编码')),
        migrations.AlterField(model_name='hrenterprisepracticeactivity', name='tenant_id', field=models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
        migrations.AlterField(model_name='hrenterprisepracticeactivity', name='title', field=models.CharField(blank=True, default='', max_length=256, verbose_name='活动标题')),
        migrations.AlterField(model_name='hrenterprisepracticeactivity', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrenterprisepracticeassignment', name='assignment_status', field=models.CharField(choices=[('DRAFT', '草稿'), ('SUBMITTED', '已提交'), ('APPROVED', '已批准'), ('REJECTED', '已否决'), ('IN_PROGRESS', '进行中'), ('SUSPENDED', '已暂停'), ('COMPLETION_REVIEW', '完成核验中'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消'), ('TERMINATED_EARLY', '提前终止')], db_index=True, default='DRAFT', max_length=32)),
        migrations.AlterField(model_name='hrenterprisepracticeassignment', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrenterprisepracticeassignment', name='id', field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        migrations.AlterField(model_name='hrenterprisepracticeassignment', name='tenant_id', field=models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
        migrations.AlterField(model_name='hrenterprisepracticeassignment', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrenterprisepracticeattendancefact', name='anomaly_flags_json', field=models.JSONField(blank=True, default=dict, verbose_name='异常标记')),
        migrations.AlterField(model_name='hrenterprisepracticeattendancefact', name='assignment_id', field=models.BigIntegerField(db_index=True, verbose_name='派出 ID')),
        migrations.AlterField(model_name='hrenterprisepracticeattendancefact', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrenterprisepracticeattendancefact', name='date', field=models.DateField(verbose_name='日期')),
        migrations.AlterField(model_name='hrenterprisepracticeattendancefact', name='duration_minutes', field=models.IntegerField(blank=True, null=True, verbose_name='时长(分钟)')),
        migrations.AlterField(model_name='hrenterprisepracticeattendancefact', name='end_at', field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
        migrations.AlterField(model_name='hrenterprisepracticeattendancefact', name='id', field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        migrations.AlterField(model_name='hrenterprisepracticeattendancefact', name='source', field=models.CharField(choices=[('ENTERPRISE_SYSTEM', '企业系统'), ('MENTOR', '企业导师'), ('SCHOOL_CHECK', '学校检查'), ('SELF_WITH_EVIDENCE', '教师自报+证据'), ('IMPORT', '导入')], max_length=32, verbose_name='来源')),
        migrations.AlterField(model_name='hrenterprisepracticeattendancefact', name='source_ref', field=models.CharField(blank=True, default='', max_length=256, verbose_name='来源引用')),
        migrations.AlterField(model_name='hrenterprisepracticeattendancefact', name='start_at', field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
        migrations.AlterField(model_name='hrenterprisepracticeattendancefact', name='tenant_id', field=models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
        migrations.AlterField(model_name='hrenterprisepracticeattendancefact', name='trust_level', field=models.IntegerField(default=1, help_text='5=Authority核验, 4=Provider核验, 3=文档核验, 2=人工核验, 1=教师自报', verbose_name='信任等级 1-5')),
        migrations.AlterField(model_name='hrenterprisepracticeattendancefact', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrenterprisepracticeattendancefact', name='verification_status', field=models.CharField(db_index=True, default='SELF_REPORTED', max_length=48, verbose_name='核验状态')),
        migrations.AlterField(model_name='hrenterprisepracticeattendancefact', name='verified_at', field=models.DateTimeField(blank=True, null=True, verbose_name='核验时间')),
        migrations.AlterField(model_name='hrenterprisepracticeattendancefact', name='verified_by', field=models.BigIntegerField(blank=True, null=True, verbose_name='核验人')),
        migrations.AlterField(model_name='hrenterprisepracticeevaluation', name='completion_status', field=models.CharField(choices=[('PASS', '通过'), ('FAIL', '未通过'), ('INCOMPLETE', '未完成'), ('EARLY_TERMINATED', '提前终止')], max_length=24, verbose_name='最终结果')),
        migrations.AlterField(model_name='hrenterprisepracticeevaluation', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrenterprisepracticeevaluation', name='id', field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        migrations.AlterField(model_name='hrenterprisepracticeevaluation', name='tenant_id', field=models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
        migrations.AlterField(model_name='hrenterprisepracticeevaluation', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrenterprisepracticeevidence', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrenterprisepracticeevidence', name='document_id', field=models.CharField(blank=True, default='', max_length=256, verbose_name='文件 ID')),
        migrations.AlterField(model_name='hrenterprisepracticeevidence', name='evidence_type', field=models.CharField(max_length=64, verbose_name='证据类型')),
        migrations.AlterField(model_name='hrenterprisepracticeevidence', name='id', field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        migrations.AlterField(model_name='hrenterprisepracticeevidence', name='tenant_id', field=models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
        migrations.AlterField(model_name='hrenterprisepracticeevidence', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrenterprisepracticementor', name='contact_ref', field=models.CharField(blank=True, default='', max_length=256, verbose_name='联系方式引用')),
        migrations.AlterField(model_name='hrenterprisepracticementor', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrenterprisepracticementor', name='credential_summary', field=models.TextField(blank=True, default='', verbose_name='资质')),
        migrations.AlterField(model_name='hrenterprisepracticementor', name='id', field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        migrations.AlterField(model_name='hrenterprisepracticementor', name='person_display_name', field=models.CharField(max_length=128, verbose_name='导师姓名')),
        migrations.AlterField(model_name='hrenterprisepracticementor', name='position_title', field=models.CharField(blank=True, default='', max_length=128, verbose_name='职位')),
        migrations.AlterField(model_name='hrenterprisepracticementor', name='professional_domain', field=models.CharField(blank=True, default='', max_length=128, verbose_name='专业领域')),
        migrations.AlterField(model_name='hrenterprisepracticementor', name='tenant_id', field=models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
        migrations.AlterField(model_name='hrenterprisepracticementor', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrenterprisepracticeplacement', name='batch_no', field=models.CharField(max_length=64, verbose_name='批次号')),
        migrations.AlterField(model_name='hrenterprisepracticeplacement', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrenterprisepracticeplacement', name='id', field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        migrations.AlterField(model_name='hrenterprisepracticeplacement', name='tenant_id', field=models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
        migrations.AlterField(model_name='hrenterprisepracticeplacement', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrenterprisepracticeplan', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrenterprisepracticeplan', name='id', field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        migrations.AlterField(model_name='hrenterprisepracticeplan', name='tenant_id', field=models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
        migrations.AlterField(model_name='hrenterprisepracticeplan', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrenterprisepracticeproject', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrenterprisepracticeproject', name='id', field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        migrations.AlterField(model_name='hrenterprisepracticeproject', name='lifecycle_status', field=models.CharField(choices=[('DRAFT', '草稿'), ('DESIGNING', '设计中'), ('READY_FOR_REVIEW', '待审核'), ('APPROVED', '已批准'), ('PUBLISHED', '已发布'), ('MATCHING', '匹配中'), ('READY_TO_START', '准备启动'), ('ACTIVE', '进行中'), ('COMPLETION_REVIEW', '完成核验中'), ('COMPLETED', '已完成'), ('CLOSED', '已关闭'), ('ARCHIVED', '已归档'), ('RETURNED', '退回修改'), ('REJECTED', '已否决'), ('SUSPENDED', '已暂停'), ('CANCELLED', '已取消'), ('TERMINATED_EARLY', '提前终止')], db_index=True, default='DRAFT', max_length=32)),
        migrations.AlterField(model_name='hrenterprisepracticeproject', name='owner_org_id', field=models.BigIntegerField(blank=True, null=True, verbose_name='校内主办组织')),
        migrations.AlterField(model_name='hrenterprisepracticeproject', name='practice_base_ref', field=models.CharField(blank=True, default='', max_length=256, verbose_name='基地引用')),
        migrations.AlterField(model_name='hrenterprisepracticeproject', name='project_no', field=models.CharField(max_length=64, verbose_name='项目编号')),
        migrations.AlterField(model_name='hrenterprisepracticeproject', name='provider_org_id', field=models.BigIntegerField(verbose_name='企业/基地 ID')),
        migrations.AlterField(model_name='hrenterprisepracticeproject', name='specialty_category', field=models.CharField(blank=True, default='', max_length=128, verbose_name='专业大类')),
        migrations.AlterField(model_name='hrenterprisepracticeproject', name='tenant_id', field=models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
        migrations.AlterField(model_name='hrenterprisepracticeproject', name='title', field=models.CharField(max_length=256, verbose_name='项目标题')),
        migrations.AlterField(model_name='hrenterprisepracticeproject', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrenterprisepracticeprojectversion', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
        migrations.AlterField(model_name='hrenterprisepracticeprojectversion', name='id', field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        migrations.AlterField(model_name='hrenterprisepracticeprojectversion', name='project_id', field=models.BigIntegerField(db_index=True, verbose_name='项目 ID')),
        migrations.AlterField(model_name='hrenterprisepracticeprojectversion', name='tenant_id', field=models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
        migrations.AlterField(model_name='hrenterprisepracticeprojectversion', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        migrations.AlterField(model_name='hrfurtherstudycase', name='agreement_ref', field=models.CharField(blank=True, default='', max_length=256, verbose_name='协议引用')),
    ]
