# Generated by Django 5.2 on 2026-08-30. Includes legacy sealing and MySQL guards.

import hashlib
import json
import hr10_development.models.development_fact
from django.conf import settings
from django.db import migrations, models


HASH_FIELDS = (
    "tenant_id", "staff_master_id", "fact_type", "source_case_type",
    "source_case_id", "source_revision_no", "activity_type", "provider_org_id",
    "start_date", "end_date", "verified_hours", "verified_days",
    "verified_credits", "level_or_result", "verification_status",
    "evidence_package_hash", "generated_at", "valid_from", "valid_to",
    "supersedes_fact_id", "record_kind", "correction_reason",
    "correction_evidence_ref", "idempotency_key", "sealed_at", "sealed_by",
)


def _canonical(value):
    return value.isoformat() if hasattr(value, "isoformat") else value


def seal_legacy_facts(apps, schema_editor):
    Fact = apps.get_model("hr10_development", "HrDevelopmentFact")
    batch = []
    for row in Fact.objects.all().iterator(chunk_size=500):
        row.record_kind = "ORIGINAL"
        row.supersedes_fact_id = None
        row.correction_reason = ""
        row.correction_evidence_ref = ""
        row.idempotency_key = f"legacy:{row.tenant_id}:{row.id}"
        row.sealed_at = row.generated_at or row.created_at
        row.sealed_by = None
        payload = {field: _canonical(getattr(row, field)) for field in HASH_FIELDS}
        encoded = json.dumps(
            payload, ensure_ascii=False, sort_keys=True, separators=(",", ":"),
            default=str,
        ).encode("utf-8")
        row.content_hash = hashlib.sha256(encoded).hexdigest()
        row.immutable_hash = row.content_hash
        batch.append(row)
        if len(batch) >= 500:
            Fact.objects.bulk_update(
                batch,
                ["record_kind", "supersedes_fact_id", "correction_reason",
                 "correction_evidence_ref", "idempotency_key", "sealed_at",
                 "sealed_by", "content_hash", "immutable_hash"],
            )
            batch = []
    if batch:
        Fact.objects.bulk_update(
            batch,
            ["record_kind", "supersedes_fact_id", "correction_reason",
             "correction_evidence_ref", "idempotency_key", "sealed_at",
             "sealed_by", "content_hash", "immutable_hash"],
        )


def install_mysql_fact_seal(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    for name in (
        "hr10_development_fact_no_update", "hr10_development_fact_no_delete",
        "hr10_development_fact_tenant_parent",
    ):
        schema_editor.execute(f"DROP TRIGGER IF EXISTS {name}")
    schema_editor.execute(
        """
        CREATE TRIGGER hr10_development_fact_no_update
        BEFORE UPDATE ON hr_development_fact
        FOR EACH ROW
        BEGIN
            IF OLD.sealed_at IS NOT NULL THEN
                SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'HR10_DEVELOPMENT_FACT_IMMUTABLE: append a successor';
            END IF;
        END
        """
    )
    schema_editor.execute(
        """
        CREATE TRIGGER hr10_development_fact_no_delete
        BEFORE DELETE ON hr_development_fact
        FOR EACH ROW
        BEGIN
            IF OLD.sealed_at IS NOT NULL THEN
                SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'HR10_DEVELOPMENT_FACT_IMMUTABLE: delete forbidden';
            END IF;
        END
        """
    )
    schema_editor.execute(
        """
        CREATE TRIGGER hr10_development_fact_tenant_parent
        BEFORE INSERT ON hr_development_fact
        FOR EACH ROW
        BEGIN
            IF NEW.supersedes_fact_id IS NOT NULL AND NOT EXISTS (
                SELECT 1 FROM hr_development_fact parent
                WHERE parent.id = NEW.supersedes_fact_id
                  AND parent.tenant_id = NEW.tenant_id
                  AND parent.staff_master_id = NEW.staff_master_id
            ) THEN
                SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'HR10_DEVELOPMENT_FACT_PARENT_NOT_IN_TENANT';
            END IF;
        END
        """
    )


def remove_mysql_fact_seal(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    for name in (
        "hr10_development_fact_no_update", "hr10_development_fact_no_delete",
        "hr10_development_fact_tenant_parent",
    ):
        schema_editor.execute(f"DROP TRIGGER IF EXISTS {name}")


class Migration(migrations.Migration):

    dependencies = [
        ('hr10_development', '0022_alter_hr10developmentpermissionmeta_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hr10developmentpermissionmeta',
            options={'managed': False, 'permissions': (('hr.development.plan.view', 'Hr Development Plan View'), ('hr.development.plan.create', 'Hr Development Plan Create'), ('hr.development.plan.approve', 'Hr Development Plan Approve'), ('hr.development.plan.publish', 'Hr Development Plan Publish'), ('hr.development.program.view', 'Hr Development Program View'), ('hr.development.program.manage', 'Hr Development Program Manage'), ('hr.development.program.publish', 'Hr Development Program Publish'), ('hr.development.request.view', 'Hr Development Request View'), ('hr.development.request.create', 'Hr Development Request Create'), ('hr.development.request.approve', 'Hr Development Request Approve'), ('hr.development.request.review_budget', 'Hr Development Request Review_Budget'), ('hr.development.practice.view', 'Hr Development Practice View'), ('hr.development.practice.manage', 'Hr Development Practice Manage'), ('hr.development.practice.publish', 'Hr Development Practice Publish'), ('hr.development.process.record', 'Hr Development Process Record'), ('hr.development.completion.verify', 'Hr Development Completion Verify'), ('hr.development.evaluation.manage', 'Hr Development Evaluation Manage'), ('hr.development.output.verify', 'Hr Development Output Verify'), ('hr.development.record.view', 'Hr Development Record View'), ('hr.development.fact.correct', 'Hr Development Fact Correct'), ('hr.development.fact.revoke', 'Hr Development Fact Revoke'), ('hr.development.analytics.read', 'Hr Development Analytics Read'), ('hr.development.audit', 'Hr Development Audit'), ('hr.development.import.manage', 'Hr Development Import Manage'))},
        ),
        migrations.AlterModelOptions(
            name='hrdevelopmentfact',
            options={'base_manager_name': 'objects', 'verbose_name': '发展事实', 'verbose_name_plural': '发展事实'},
        ),
        migrations.AddField(
            model_name='hrdevelopmentfact',
            name='content_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='hrdevelopmentfact',
            name='correction_evidence_ref',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='hrdevelopmentfact',
            name='correction_reason',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='hrdevelopmentfact',
            name='idempotency_key',
            field=models.CharField(default=hr10_development.models.development_fact._development_fact_idempotency_key, max_length=128),
        ),
        migrations.AddField(
            model_name='hrdevelopmentfact',
            name='record_kind',
            field=models.CharField(choices=[('ORIGINAL', '原始正式事实'), ('CORRECTION', '追加更正'), ('REVOCATION', '追加撤销')], db_index=True, default='ORIGINAL', max_length=16),
        ),
        migrations.AddField(
            model_name='hrdevelopmentfact',
            name='sealed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='hrdevelopmentfact',
            name='sealed_by',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(seal_legacy_facts, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='hrdevelopmentfact',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'supersedes_fact_id'), name='uq_hr10_fact_one_successor'),
        ),
        migrations.AddConstraint(
            model_name='hrdevelopmentfact',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'idempotency_key'), name='uq_hr10_fact_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='hrdevelopmentfact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('record_kind', 'ORIGINAL'), ('supersedes_fact_id__isnull', True)), models.Q(('record_kind__in', ('CORRECTION', 'REVOCATION')), ('supersedes_fact_id__isnull', False), models.Q(('correction_reason', ''), _negated=True), models.Q(('correction_evidence_ref', ''), _negated=True)), _connector='OR'), name='ck_hr10_fact_lineage'),
        ),
        migrations.AddConstraint(
            model_name='hrdevelopmentfact',
            constraint=models.CheckConstraint(condition=models.Q(('sealed_at__isnull', False), models.Q(('content_hash', ''), _negated=True), models.Q(('immutable_hash', ''), _negated=True)), name='ck_hr10_fact_sealed'),
        ),
        migrations.RunPython(install_mysql_fact_seal, remove_mysql_fact_seal),
    ]
