# Generated by Django 5.2 on 2026-08-30 10:45

from django.db import migrations, models


def mark_legacy_false_successes(apps, schema_editor):
    Milestone = apps.get_model("hr10_development", "HrFurtherStudyMilestone")
    Milestone.objects.using(schema_editor.connection.alias).filter(
        milestone_type__in=["GRADUATED", "CERTIFICATE_RECEIVED"],
        status="VERIFIED",
    ).update(
        status="WRITEBACK_FAILED",
        writeback_status="FAILED",
        writeback_error=(
            "LEGACY_FALSE_SUCCESS: no durable HR03 education/degree/credential receipt; "
            "verification must be retried"
        ),
    )


def restore_legacy_statuses(apps, schema_editor):
    Milestone = apps.get_model("hr10_development", "HrFurtherStudyMilestone")
    Milestone.objects.using(schema_editor.connection.alias).filter(
        milestone_type__in=["GRADUATED", "CERTIFICATE_RECEIVED"],
        status="WRITEBACK_FAILED",
        writeback_error__startswith="LEGACY_FALSE_SUCCESS:",
    ).update(status="VERIFIED")


class Migration(migrations.Migration):

    dependencies = [
        ('hr10_development', '0023_formal_development_fact_seal'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrfurtherstudymilestone',
            name='writeback_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='写回时间'),
        ),
        migrations.AddField(
            model_name='hrfurtherstudymilestone',
            name='writeback_error',
            field=models.TextField(blank=True, default='', verbose_name='写回错误'),
        ),
        migrations.AddField(
            model_name='hrfurtherstudymilestone',
            name='writeback_refs',
            field=models.JSONField(blank=True, default=dict, verbose_name='HR03 写回引用'),
        ),
        migrations.AddField(
            model_name='hrfurtherstudymilestone',
            name='writeback_request_hash',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='写回请求哈希'),
        ),
        migrations.AddField(
            model_name='hrfurtherstudymilestone',
            name='writeback_status',
            field=models.CharField(db_index=True, default='NOT_REQUIRED', max_length=16, verbose_name='HR03 写回状态'),
        ),
        migrations.RunPython(mark_legacy_false_successes, restore_legacy_statuses),
    ]
