# Generated by Django 5.2 on 2026-08-30 08:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


def create_exchange_permission(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    content_type, _created = ContentType.objects.get_or_create(
        app_label="hr_data", model="metricdefinitionversion"
    )
    Permission.objects.get_or_create(
        content_type=content_type,
        codename="hr.data.exchange",
        defaults={"name": "管理 HR18 异步数据交换与对账"},
    )


def remove_exchange_permission(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    Permission.objects.filter(
        content_type__app_label="hr_data",
        content_type__model="metricdefinitionversion",
        codename="hr.data.exchange",
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('hr_data', '0010_submission_separation_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeDatasetVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(db_index=True, default='DRAFT', max_length=32)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('dataset_code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('schema_json', models.JSONField(default=dict)),
                ('source_snapshot_json', models.JSONField(default=dict)),
                ('payload_ref', models.CharField(max_length=255)),
                ('payload_hash', models.CharField(max_length=64)),
                ('record_count', models.PositiveBigIntegerField(default=0)),
                ('frozen_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'hr18_exchange_dataset_version',
                'indexes': [models.Index(fields=['tenant_id', 'dataset_code', 'status'], name='idx_hr18_ex_dataset_status')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'dataset_code', 'version_no'), name='uq_hr18_exchange_dataset_ver')],
            },
        ),
        migrations.CreateModel(
            name='ExchangeJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('job_no', models.CharField(max_length=64)),
                ('snapshot_hash', models.CharField(max_length=64)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('LEASED', 'Leased by worker'), ('RETRY_WAIT', 'Waiting to retry'), ('TRANSMITTED', 'Transmitted'), ('ACKNOWLEDGED', 'Receipt received'), ('RECONCILED', 'Reconciled'), ('DEAD_LETTER', 'Dead letter')], db_index=True, default='QUEUED', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('dispatch_ref', models.CharField(blank=True, default='', max_length=255)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('transmitted_at', models.DateTimeField(blank=True, null=True)),
                ('dataset_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_jobs', to='hr_data.exchangedatasetversion')),
            ],
            options={
                'db_table': 'hr18_exchange_job',
            },
        ),
        migrations.CreateModel(
            name='ExchangeReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('receipt_ref', models.CharField(max_length=255)),
                ('accepted', models.BooleanField()),
                ('received_payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('received_record_count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('receipt_hash', models.CharField(max_length=64)),
                ('received_at', models.DateTimeField()),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_receipt', to='hr_data.exchangejob')),
            ],
            options={
                'db_table': 'hr18_exchange_receipt',
            },
        ),
        migrations.CreateModel(
            name='ExchangeReconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('expected_payload_hash', models.CharField(max_length=64)),
                ('received_payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('expected_record_count', models.PositiveBigIntegerField()),
                ('received_record_count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('MATCHED', 'Matched'), ('MISMATCH', 'Mismatch'), ('REJECTED', 'Rejected by target')], max_length=16)),
                ('differences_json', models.JSONField(blank=True, default=dict)),
                ('reconciled_at', models.DateTimeField()),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation', to='hr_data.exchangejob')),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation', to='hr_data.exchangereceipt')),
            ],
            options={
                'db_table': 'hr18_exchange_reconciliation',
            },
        ),
        migrations.CreateModel(
            name='ExchangeTargetMappingVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(db_index=True, default='DRAFT', max_length=32)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('target_code', models.CharField(max_length=64)),
                ('dataset_code', models.CharField(max_length=64)),
                ('dataset_version', models.PositiveIntegerField()),
                ('transport_kind', models.CharField(max_length=32)),
                ('provider_key', models.CharField(max_length=64)),
                ('mapping_json', models.JSONField(default=dict)),
                ('expected_receipt', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'hr18_exchange_target_mapping_version',
                'indexes': [models.Index(fields=['tenant_id', 'dataset_code', 'dataset_version'], name='idx_hr18_ex_target_dataset')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'target_code', 'version_no'), name='uq_hr18_exchange_target_ver')],
            },
        ),
        migrations.AddField(
            model_name='exchangejob',
            name='target_mapping_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_jobs', to='hr_data.exchangetargetmappingversion'),
        ),
        migrations.CreateModel(
            name='ExchangeDeadLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('reason_code', models.CharField(max_length=64)),
                ('final_attempt_no', models.PositiveIntegerField()),
                ('snapshot_hash', models.CharField(max_length=64)),
                ('failed_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dead_letter', to='hr_data.exchangejob')),
            ],
            options={
                'db_table': 'hr18_exchange_dead_letter',
                'indexes': [models.Index(fields=['tenant_id', 'resolved_at', 'failed_at'], name='idx_hr18_exchange_dead_queue')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'job_id'), name='uq_hr18_exchange_dead_letter_job')],
            },
        ),
        migrations.CreateModel(
            name='ExchangeAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('attempt_no', models.PositiveIntegerField()),
                ('idempotency_key', models.CharField(max_length=160)),
                ('provider_version', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('TRANSMITTED', 'Transmitted'), ('RETRYABLE_FAILURE', 'Retryable failure'), ('TERMINAL_FAILURE', 'Terminal failure')], max_length=24)),
                ('dispatch_ref', models.CharField(blank=True, default='', max_length=255)),
                ('response_hash', models.CharField(blank=True, default='', max_length=64)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='hr_data.exchangejob')),
            ],
            options={
                'db_table': 'hr18_exchange_attempt',
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'job_id', 'attempt_no'), name='uq_hr18_exchange_attempt_no'), models.UniqueConstraint(fields=('tenant_id', 'idempotency_key'), name='uq_hr18_exchange_attempt_key')],
            },
        ),
        migrations.AddConstraint(
            model_name='exchangereceipt',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'receipt_ref'), name='uq_hr18_exchange_receipt_ref'),
        ),
        migrations.AddConstraint(
            model_name='exchangereceipt',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'job_id'), name='uq_hr18_exchange_receipt_job'),
        ),
        migrations.AddConstraint(
            model_name='exchangereconciliation',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'job_id'), name='uq_hr18_exchange_reconcile_job'),
        ),
        migrations.AddIndex(
            model_name='exchangejob',
            index=models.Index(fields=['tenant_id', 'status', 'next_attempt_at'], name='idx_hr18_exchange_job_queue'),
        ),
        migrations.AddConstraint(
            model_name='exchangejob',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'job_no'), name='uq_hr18_exchange_job_no'),
        ),
        migrations.AddConstraint(
            model_name='exchangejob',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'idempotency_key'), name='uq_hr18_exchange_job_idempotency'),
        ),
        migrations.RunPython(create_exchange_permission, remove_exchange_permission),
    ]
