# Generated by Django 5.2 on 2026-08-30 08:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_data', '0011_exchange_runtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricEvaluationSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('evaluation_no', models.CharField(max_length=64)),
                ('metric_code', models.CharField(max_length=64)),
                ('metric_version', models.PositiveIntegerField()),
                ('population_code', models.CharField(max_length=64)),
                ('population_version', models.PositiveIntegerField()),
                ('dimension_versions_json', models.JSONField(blank=True, default=list)),
                ('as_of_date', models.DateField()),
                ('as_of_evidence_id', models.UUIDField()),
                ('evidence_hash', models.CharField(max_length=64)),
                ('source_receipts_json', models.JSONField(default=dict)),
                ('result_json', models.JSONField(default=dict)),
                ('input_row_count', models.PositiveIntegerField(default=0)),
                ('provider_version', models.CharField(max_length=64)),
                ('evaluator_version', models.CharField(max_length=64)),
                ('calculation_hash', models.CharField(max_length=64)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hr18_metric_evaluation_snapshot',
                'permissions': [('hr.data.metric.evaluate', '执行 HR18 通用指标表达式求值')],
                'indexes': [models.Index(fields=['tenant_id', 'metric_code', 'metric_version', 'as_of_date'], name='idx_hr18_metric_eval_def')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'evaluation_no'), name='uq_hr18_metric_eval_no')],
            },
        ),
    ]
