# Generated by Django 5.2 on 2026-08-30 09:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


def create_takeover_permission(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    content_type, _created = ContentType.objects.get_or_create(
        app_label="hr_data", model="metricdefinitionversion"
    )
    Permission.objects.get_or_create(
        content_type=content_type,
        codename="hr.data.legacy.takeover",
        defaults={"name": "执行 HR18 旧报表证据接管与写封锁"},
    )


def remove_takeover_permission(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    Permission.objects.filter(
        content_type__app_label="hr_data",
        content_type__model="metricdefinitionversion",
        codename="hr.data.legacy.takeover",
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('hr_data', '0012_metric_expression_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyReportAssetVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(db_index=True, default='DRAFT', max_length=32)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('legacy_source', models.CharField(default='report.ReportTemplate', max_length=64)),
                ('legacy_object_id', models.PositiveBigIntegerField()),
                ('report_slug', models.CharField(max_length=100)),
                ('legacy_name', models.CharField(max_length=100)),
                ('legacy_config_hash', models.CharField(max_length=64)),
                ('disposition', models.CharField(choices=[('MIGRATE', 'Migrate to canonical report asset'), ('ARCHIVE', 'Archive legacy preference'), ('UNAVAILABLE', 'Evidence unavailable')], max_length=16)),
                ('canonical_asset_ref', models.CharField(blank=True, default='', max_length=255)),
                ('provider_key', models.CharField(blank=True, default='', max_length=64)),
                ('mapping_json', models.JSONField(blank=True, default=dict)),
                ('mapping_idempotency_key', models.CharField(blank=True, max_length=128, null=True)),
                ('source_evidence_hash', models.CharField(max_length=64)),
                ('inventoried_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'hr18_legacy_report_asset_version',
                'indexes': [models.Index(fields=['tenant_id', 'legacy_source', 'legacy_object_id', 'status'], name='idx_hr18_legacy_asset_current')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'legacy_source', 'legacy_object_id', 'version_no'), name='uq_hr18_legacy_asset_ver'), models.UniqueConstraint(fields=('tenant_id', 'mapping_idempotency_key'), name='uq_hr18_legacy_mapping_idem')],
            },
        ),
        migrations.CreateModel(
            name='LegacyReportCutoverStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('cutover_code', models.CharField(max_length=64)),
                ('step_no', models.PositiveIntegerField()),
                ('phase', models.CharField(choices=[('INVENTORIED', 'Assets inventoried'), ('DUAL_READ_VERIFIED', 'Dual-read evidence verified'), ('CUTOVER', 'Canonical reads activated'), ('LEGACY_WRITE_BLOCKED', 'Legacy writes blocked'), ('UNAVAILABLE', 'Required evidence unavailable')], db_index=True, max_length=24)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('asset_count', models.PositiveIntegerField(default=0)),
                ('matched_count', models.PositiveIntegerField(default=0)),
                ('archived_count', models.PositiveIntegerField(default=0)),
                ('unavailable_count', models.PositiveIntegerField(default=0)),
                ('evidence_json', models.JSONField(blank=True, default=dict)),
                ('evidence_hash', models.CharField(max_length=64)),
                ('recorded_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'hr18_legacy_report_cutover_step',
                'indexes': [models.Index(fields=['tenant_id', 'cutover_code', 'phase', 'step_no'], name='idx_hr18_legacy_cutover_state')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'cutover_code', 'step_no'), name='uq_hr18_legacy_cutover_step'), models.UniqueConstraint(fields=('tenant_id', 'idempotency_key'), name='uq_hr18_legacy_cutover_idem')],
            },
        ),
        migrations.CreateModel(
            name='LegacyReportReconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('run_no', models.CharField(max_length=64)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('MATCHED', 'Legacy and canonical outputs match'), ('MISMATCH', 'Outputs differ'), ('UNAVAILABLE', 'One or both evidence sources unavailable')], db_index=True, max_length=16)),
                ('provider_version', models.CharField(blank=True, default='', max_length=64)),
                ('legacy_output_hash', models.CharField(blank=True, default='', max_length=64)),
                ('canonical_output_hash', models.CharField(blank=True, default='', max_length=64)),
                ('legacy_record_count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('canonical_record_count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('differences_json', models.JSONField(blank=True, default=dict)),
                ('evidence_json', models.JSONField(blank=True, default=dict)),
                ('evidence_hash', models.CharField(max_length=64)),
                ('reconciled_at', models.DateTimeField()),
                ('asset_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='hr_data.legacyreportassetversion')),
            ],
            options={
                'db_table': 'hr18_legacy_report_reconciliation',
                'indexes': [models.Index(fields=['tenant_id', 'asset_version', 'status', 'reconciled_at'], name='idx_hr18_leg_recon_asset')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'idempotency_key'), name='uq_hr18_legacy_reconcile_idem'), models.UniqueConstraint(fields=('tenant_id', 'run_no'), name='uq_hr18_legacy_reconcile_run')],
            },
        ),
        migrations.CreateModel(
            name='LegacyReportWriteBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('legacy_source', models.CharField(default='report.ReportTemplate', max_length=64)),
                ('evidence_hash', models.CharField(max_length=64)),
                ('activated_at', models.DateTimeField()),
                ('cutover_step', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='write_block', to='hr_data.legacyreportcutoverstep')),
            ],
            options={
                'db_table': 'hr18_legacy_report_write_block',
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'legacy_source'), name='uq_hr18_legacy_write_block')],
            },
        ),
        migrations.RunPython(
            create_takeover_permission,
            remove_takeover_permission,
        ),
    ]
