# Generated by Django 5.2 on 2026-08-30 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_data', '0015_submissiondispatchjob_submissiondispatchevent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metricdefinitionversion',
            options={'permissions': [('hr.data.view', '查看 HR18 人事数据中心'), ('hr.data.define', '维护 HR18 人口维度指标定义'), ('hr.data.asof', '执行 HR18 历史时点重建'), ('hr.data.quality', '执行 HR18 数据质量治理'), ('hr.data.submit', '创建并提交 HR18 正式数据报送'), ('hr.data.approve', '独立审批 HR18 正式数据报送'), ('hr.data.receipt', '登记 HR18 外部正式报送回执')]},
        ),
    ]
