from django.urls import path

from . import (
    api,
    application_api,
    batch_api,
    batch_configuration_api,
    capacity_api,
    decision_api,
    population_api,
    term_api,
    term_effect_api,
)

app_name = "hr_appointment_api"
urlpatterns = [
    path("dashboard/", api.dashboard, name="dashboard"),
    path("batches/", batch_api.create_batch, name="batch-create"),
    path(
        "batches/<uuid:batch_id>/",
        batch_configuration_api.update_batch,
        name="batch-update",
    ),
    path(
        "batches/<uuid:batch_id>/population/freeze/",
        population_api.freeze_population,
        name="batch-population-freeze",
    ),
    path(
        "batches/<uuid:batch_id>/publish/",
        batch_api.publish_batch,
        name="batch-publish",
    ),
    path(
        "batches/<uuid:batch_id>/applications/open/",
        batch_api.open_applications,
        name="batch-applications-open",
    ),
    path(
        "batches/<uuid:batch_id>/applications/close/",
        batch_api.close_applications,
        name="batch-applications-close",
    ),
    path(
        "batches/<uuid:batch_id>/eligibility/start/",
        batch_api.begin_eligibility_review,
        name="batch-eligibility-start",
    ),
    path(
        "batches/<uuid:batch_id>/review/start/",
        batch_api.begin_review,
        name="batch-review-start",
    ),
    path("applications/", application_api.create_application, name="application-create"),
    path(
        "applications/<uuid:case_id>/submit/",
        application_api.submit_application,
        name="application-submit",
    ),
    path(
        "applications/<uuid:case_id>/return/",
        application_api.return_application,
        name="application-return",
    ),
    path(
        "applications/<uuid:case_id>/eligibility/pass/",
        application_api.pass_eligibility,
        name="application-eligibility-pass",
    ),
    path(
        "applications/<uuid:case_id>/eligibility/reject/",
        application_api.reject_eligibility,
        name="application-eligibility-reject",
    ),
    path(
        "applications/<uuid:case_id>/withdraw/",
        application_api.withdraw_application,
        name="application-withdraw",
    ),
    path(
        "applications/<uuid:case_id>/review/start/",
        application_api.start_review,
        name="application-review-start",
    ),
    path(
        "applications/<uuid:case_id>/ranking-result/",
        api.ranking_result,
        name="ranking-result",
    ),
    path(
        "applications/<uuid:case_id>/publicity/",
        api.open_publicity,
        name="publicity-open",
    ),
    path(
        "applications/<uuid:case_id>/collective-decision/",
        decision_api.record_collective_decision,
        name="collective-decision-record",
    ),
    path(
        "applications/<uuid:case_id>/capacity-reservation/",
        capacity_api.prepare_capacity,
        name="appointment-capacity-prepare",
    ),
    path(
        "applications/<uuid:case_id>/apply-effect/",
        api.apply_effect,
        name="appointment-effect-apply",
    ),
    path(
        "publicities/<uuid:publicity_id>/objections/",
        api.submit_publicity_objection,
        name="publicity-objection-submit",
    ),
    path(
        "publicity-objections/<uuid:objection_id>/resolve/",
        api.resolve_publicity_objection,
        name="publicity-objection-resolve",
    ),
    path(
        "publicities/<uuid:publicity_id>/close/",
        api.close_publicity,
        name="publicity-close",
    ),
    path(
        "publicities/<uuid:publicity_id>/cancel/",
        api.cancel_publicity,
        name="publicity-cancel",
    ),
    path(
        "appointment-facts/<uuid:fact_id>/term/",
        term_api.register_term,
        name="term-register",
    ),
    path(
        "terms/<uuid:term_id>/expiring/",
        term_api.mark_expiring,
        name="term-mark-expiring",
    ),
    path(
        "terms/<uuid:term_id>/expired/",
        term_api.mark_expired,
        name="term-mark-expired",
    ),
    path(
        "terms/<uuid:term_id>/renewals/",
        term_api.open_renewal,
        name="renewal-open",
    ),
    path(
        "renewals/<uuid:renewal_id>/decision/",
        term_api.decide_renewal,
        name="renewal-decision",
    ),
    path(
        "renewals/<uuid:renewal_id>/apply-effect/",
        term_effect_api.apply_renewal_effect,
        name="renewal-effect-apply",
    ),
    path(
        "terms/<uuid:term_id>/changes/",
        term_api.open_change,
        name="term-change-open",
    ),
    path(
        "term-changes/<uuid:change_id>/decision/",
        term_api.decide_change,
        name="term-change-decision",
    ),
    path(
        "term-changes/<uuid:change_id>/apply-effect/",
        term_effect_api.apply_change_effect,
        name="term-change-effect-apply",
    ),
]
