# Generated by Django 5.2 on 2026-08-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HrTimePermissionMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('hr.time.admin', 'HR Time: Admin'), ('hr.time.policy.manage', 'HR Time: Policy Manager'), ('hr.time.schedule.manage', 'HR Time: Schedule Manager'), ('hr.time.attendance.manage', 'HR Time: Attendance Manager'), ('hr.time.attendance.verify', 'HR Time: Attendance Verifier'), ('hr.time.leave.admin', 'HR Time: Leave Admin'), ('hr.time.leave.approve', 'HR Time: Leave Approver'), ('hr.time.overtime.approve', 'HR Time: Overtime Approver'), ('hr.time.close', 'HR Time: Period Closer'), ('hr.time.audit', 'HR Time: Auditor'), ('hr.time.self', 'HR Time: Employee Self Service'), ('hr.time.team.view', 'HR Time: Manager Team'), ('hr.time.device.admin', 'HR Time: Device Admin'), ('hr.time.analytics.read', 'HR Time: Read Analytics')),
                'managed': False,
            },
        ),
    ]
