# Generated by Django 5.2 on 2026-08-08 23:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_time', '0006_hrattendancecorrectioncase_hrcomptimeaccount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HrLeavePolicyPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, verbose_name='Code')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('jurisdiction', models.CharField(blank=True, default='', max_length=64)),
                ('worker_scope', models.CharField(blank=True, default='', max_length=128)),
                ('current_version_id', models.BigIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Policy Pack',
                'verbose_name_plural': 'Leave Policy Packs',
            },
        ),
        migrations.CreateModel(
            name='HrLeavePolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_no', models.PositiveIntegerField(verbose_name='版本号')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PUBLISHED', '已发布'), ('RETIRED', '已退役')], default='DRAFT', max_length=16)),
                ('entitlement_mode', models.CharField(choices=[('GRANT', '直接授予'), ('ACCRUAL', '累积'), ('SERVICE_YEARS', '按服务年限'), ('LEGAL_TIER', '法定档位')], default='GRANT', max_length=32)),
                ('eligibility_rule', models.JSONField(blank=True, default=dict)),
                ('grant_accrual_rule', models.JSONField(blank=True, default=dict)),
                ('carry_forward_rule', models.JSONField(blank=True, default=dict)),
                ('expiry_rule', models.JSONField(blank=True, default=dict)),
                ('reservation_rule', models.JSONField(blank=True, default=dict)),
                ('evidence_rule', models.JSONField(blank=True, default=dict)),
                ('approval_rule', models.JSONField(blank=True, default=dict)),
                ('interaction_rules', models.JSONField(blank=True, default=dict)),
                ('effective_from', models.DateField(verbose_name='生效日')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='失效日')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('leave_policy_pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='hr_time.hrleavepolicypack')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Policy Version',
                'verbose_name_plural': 'Leave Policy Versions',
            },
        ),
        migrations.CreateModel(
            name='HrLeaveEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_master_id', models.BigIntegerField(verbose_name='HR03 人员 id')),
                ('employment_relationship_id', models.BigIntegerField(blank=True, null=True)),
                ('enrolled_from', models.DateField(verbose_name='入保开始')),
                ('enrolled_to', models.DateField(blank=True, null=True, verbose_name='入保结束')),
                ('eligibility_snapshot', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(default='MANUAL', max_length=32, verbose_name='来源')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('leave_policy_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='hr_time.hrleavepolicyversion')),
            ],
            options={
                'verbose_name': 'Leave Enrollment',
                'verbose_name_plural': 'Leave Enrollments',
            },
        ),
        migrations.CreateModel(
            name='HrLeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, verbose_name='Code')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('category', models.CharField(choices=[('ANNUAL', '年休假'), ('SICK', '病假'), ('PERSONAL', '事假'), ('MARRIAGE', '婚假'), ('BEREAVEMENT', '丧假'), ('MATERNITY', '产假'), ('PATERNITY_OR_CARE', '陪产/护理假'), ('PARENTAL', '育儿假'), ('FAMILY_VISIT', '探亲假'), ('WORK_INJURY', '工伤停工留薪'), ('COMP_TIME', '调休'), ('ACADEMIC_OR_SABBATICAL', '学术/学术休假'), ('OTHER', '其他')], default='OTHER', max_length=32)),
                ('unit', models.CharField(choices=[('DAYS', '天'), ('HOURS', '小时'), ('MINUTES', '分钟')], default='DAYS', max_length=16)),
                ('paid_classification', models.CharField(choices=[('PAID', '带薪'), ('UNPAID', '无薪'), ('POLICY_DEPENDENT', '依政策')], default='POLICY_DEPENDENT', max_length=16)),
                ('requires_plan', models.BooleanField(default=True, verbose_name='需要额度账户')),
                ('requires_evidence', models.BooleanField(default=False, verbose_name='需要证明')),
                ('sensitive_reason', models.BooleanField(default=False, verbose_name='敏感原因（病假等）')),
                ('active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Type',
                'verbose_name_plural': 'Leave Types',
            },
        ),
        migrations.AddField(
            model_name='hrleavepolicyversion',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_versions', to='hr_time.hrleavetype'),
        ),
        migrations.CreateModel(
            name='HrLeaveAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_master_id', models.BigIntegerField(verbose_name='HR03 人员 id')),
                ('account_year', models.PositiveIntegerField(verbose_name='账户年度')),
                ('status', models.CharField(choices=[('ACTIVE', '生效'), ('CLOSED', '已结清')], default='ACTIVE', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('policy_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hr_time.hrleavepolicyversion')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='hr_time.hrleavetype')),
            ],
            options={
                'verbose_name': 'Leave Account',
                'verbose_name_plural': 'Leave Accounts',
            },
        ),
        migrations.CreateModel(
            name='HrSchoolBreakFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_master_id', models.BigIntegerField(verbose_name='HR03 人员 id')),
                ('school_year', models.CharField(max_length=16, verbose_name='学年')),
                ('break_type', models.CharField(choices=[('WINTER', '寒假'), ('SUMMER', '暑假')], max_length=16)),
                ('scheduled_days', models.PositiveIntegerField(verbose_name='计划假期天数')),
                ('actually_released_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='实际放假天数')),
                ('worked_during_break_days', models.PositiveIntegerField(default=0, verbose_name='假期期间工作天数')),
                ('source', models.CharField(default='MANUAL', max_length=32, verbose_name='来源')),
                ('verified', models.BooleanField(default=False, verbose_name='已核验')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Break Fact',
                'verbose_name_plural': 'School Break Facts',
            },
        ),
        migrations.CreateModel(
            name='HrLeaveLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('GRANT', '授予'), ('ACCRUAL', '累积'), ('RESERVE', '预占'), ('RESERVATION_RELEASE', '预占释放'), ('USE', '使用'), ('RESTORE', '恢复'), ('ADJUST', '人工调整'), ('CARRY_FORWARD', '结转'), ('EXPIRE', '过期'), ('CONVERT', '折算'), ('MIGRATION', '迁移')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='数量')),
                ('unit', models.CharField(choices=[('DAYS', '天'), ('HOURS', '小时'), ('MINUTES', '分钟')], default='DAYS', max_length=16)),
                ('effective_date', models.DateField(verbose_name='生效日')),
                ('source_type', models.CharField(max_length=32, verbose_name='来源类型')),
                ('source_id', models.CharField(blank=True, default='', max_length=64)),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='过期日')),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='变动后余额')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='hr_time.hrleaveaccount')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hr_time.hrleaveledgerentry')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Ledger Entry',
                'verbose_name_plural': 'Leave Ledger Entries',
                'indexes': [models.Index(fields=['tenant_id', 'account', 'effective_date'], name='hr11_ledger_entry_date')],
            },
        ),
        migrations.AddConstraint(
            model_name='hrleavepolicypack',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'code'), name='uniq_hr11_lppack_code'),
        ),
        migrations.AddIndex(
            model_name='hrleaveenrollment',
            index=models.Index(fields=['tenant_id', 'staff_master_id', 'enrolled_from'], name='hr11_enroll_ten_staff_from'),
        ),
        migrations.AddConstraint(
            model_name='hrleavetype',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'code'), name='uniq_hr11_lt_code'),
        ),
        migrations.AddIndex(
            model_name='hrleavepolicyversion',
            index=models.Index(fields=['tenant_id', 'leave_policy_pack', 'status'], name='hr11_lpver_ten_pack_status'),
        ),
        migrations.AddConstraint(
            model_name='hrleavepolicyversion',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'leave_policy_pack', 'version_no'), name='uniq_hr11_lpver_no'),
        ),
        migrations.AddConstraint(
            model_name='hrleaveaccount',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'staff_master_id', 'leave_type', 'account_year'), name='uniq_hr11_leave_acct'),
        ),
        migrations.AddConstraint(
            model_name='hrschoolbreakfact',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'staff_master_id', 'school_year', 'break_type'), name='uniq_hr11_break_fact'),
        ),
    ]
