# Generated by Django 5.2 on 2026-08-09 00:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_time', '0008_hrleaverequest_hrleaveevidence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HrTimeClosePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_type', models.CharField(choices=[('MONTHLY', '月度'), ('CUSTOM', '自定义')], default='MONTHLY', max_length=16)),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('status', models.CharField(choices=[('OPEN', '开启'), ('PRE_CLOSE', '预关闭'), ('CLOSED', '已关闭'), ('REOPENED', '已重开')], default='OPEN', max_length=16)),
                ('close_rule_version', models.CharField(blank=True, default='', max_length=32)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot_id', models.BigIntegerField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Time Close Period',
                'verbose_name_plural': 'Time Close Periods',
            },
        ),
        migrations.CreateModel(
            name='HrTimeCloseSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_definition_version', models.CharField(default='1.0', max_length=32)),
                ('policy_versions', models.JSONField(blank=True, default=list)),
                ('calendar_versions', models.JSONField(blank=True, default=list)),
                ('staff_count', models.PositiveIntegerField(default=0)),
                ('attendance_fact_hash', models.CharField(blank=True, default='', max_length=64)),
                ('leave_ledger_hash', models.CharField(blank=True, default='', max_length=64)),
                ('overtime_fact_hash', models.CharField(blank=True, default='', max_length=64)),
                ('close_summary_json', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='hr_time.hrtimecloseperiod')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Time Close Snapshot',
                'verbose_name_plural': 'Time Close Snapshots',
            },
        ),
        migrations.CreateModel(
            name='HrPayrollTimeBasis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_master_id', models.BigIntegerField(verbose_name='HR03 人员 id')),
                ('regular_work_minutes', models.PositiveIntegerField(default=0)),
                ('payable_authorized_absence_minutes', models.PositiveIntegerField(default=0)),
                ('unpaid_absence_minutes', models.PositiveIntegerField(default=0)),
                ('verified_overtime_minutes', models.PositiveIntegerField(default=0)),
                ('comp_time_minutes', models.PositiveIntegerField(default=0)),
                ('unexcused_absence_minutes', models.PositiveIntegerField(default=0)),
                ('basis_version', models.CharField(default='1.0', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('close_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_bases', to='hr_time.hrtimeclosesnapshot')),
            ],
            options={
                'verbose_name': 'Payroll Time Basis',
                'verbose_name_plural': 'Payroll Time Bases',
            },
        ),
        migrations.CreateModel(
            name='HrTimeCorrectionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=255, verbose_name='原因')),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('impacted_staff_ids', models.JSONField(blank=True, default=list)),
                ('before_snapshot_id', models.BigIntegerField(blank=True, null=True)),
                ('change_cases', models.JSONField(blank=True, default=list)),
                ('after_snapshot_id', models.BigIntegerField(blank=True, null=True)),
                ('audit', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_batches', to='hr_time.hrtimecloseperiod')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Time Correction Batch',
                'verbose_name_plural': 'Time Correction Batches',
            },
        ),
        migrations.CreateModel(
            name='HrTimeRiskCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('risk_code', models.CharField(choices=[('UNEXCUSED_ABSENCE_THRESHOLD', '旷工阈值'), ('DEVICE_DATA_GAP', '设备数据缺口'), ('LEAVE_LEDGER_DRIFT', '假期账户漂移'), ('POLICY_AMBIGUITY', '规则歧义'), ('SCHEDULE_GAP', '排班缺口'), ('CLOSE_OVERDUE', '月结逾期'), ('OVERTIME_ANOMALY', '加班异常'), ('MASS_LATE_PATTERN', '集中迟到模式'), ('SOURCE_RECONCILIATION_FAILED', '数据源对账失败')], max_length=40)),
                ('staff_master_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', '待处理'), ('ACKNOWLEDGED', '已确认'), ('RESOLVED', '已解决')], default='OPEN', max_length=16)),
                ('severity', models.CharField(choices=[('LOW', '低'), ('MEDIUM', '中'), ('HIGH', '高'), ('CRITICAL', '严重')], default='MEDIUM', max_length=16)),
                ('owner_role', models.CharField(blank=True, default='', max_length=64)),
                ('summary', models.TextField(blank=True, default='')),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Time Risk Case',
                'verbose_name_plural': 'Time Risk Cases',
            },
        ),
        migrations.AddConstraint(
            model_name='hrtimecloseperiod',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'start_date', 'end_date'), name='uniq_hr11_close_period'),
        ),
        migrations.AddConstraint(
            model_name='hrpayrolltimebasis',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'close_snapshot', 'staff_master_id'), name='uniq_hr11_basis_snapshot_staff'),
        ),
        migrations.AddIndex(
            model_name='hrtimeriskcase',
            index=models.Index(fields=['tenant_id', 'status', 'severity'], name='hr11_risk_ten_status_sev'),
        ),
    ]
