# Generated by Django 5.2 on 2026-08-30 13:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_contracts', '0004_hrcontractspermissionmeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrcontractcase',
            name='case_type',
            field=models.CharField(choices=[('SIGN', 'Sign'), ('RENEW', 'Renew'), ('CHANGE', 'Change'), ('TERMINATE', 'Terminate'), ('REVIEW', 'Manual review')], max_length=16),
        ),
        migrations.CreateModel(
            name='HrContractExpiryPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('policy_version', models.CharField(max_length=64)),
                ('agreement_type', models.CharField(blank=True, default='', max_length=50)),
                ('warning_days', models.PositiveIntegerField()),
                ('critical_after_days', models.PositiveIntegerField(default=0)),
                ('action_type', models.CharField(choices=[('CREATE_RENEWAL_CASE', 'Create renewal case'), ('MANUAL_REVIEW', 'Create manual review case')], max_length=32)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('content_hash', models.CharField(editable=False, max_length=64)),
            ],
            options={
                'db_table': 'hr07_contract_expiry_policy',
                'indexes': [models.Index(fields=['tenant_id', 'agreement_type', 'active'], name='idx_hr07_exp_pol_match')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'policy_version', 'agreement_type'), name='uq_hr07_exp_pol_version')],
            },
        ),
        migrations.CreateModel(
            name='HrContractExpiryRiskFact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('risk_stage', models.CharField(choices=[('EXPIRING', 'Expiring'), ('OVERDUE', 'Overdue')], max_length=16)),
                ('severity', models.CharField(choices=[('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=16)),
                ('due_date', models.DateField()),
                ('observed_as_of', models.DateField()),
                ('days_to_expiry', models.IntegerField()),
                ('policy_version', models.CharField(max_length=64)),
                ('policy_hash', models.CharField(max_length=64)),
                ('evidence_json', models.JSONField(default=dict)),
                ('evidence_hash', models.CharField(max_length=64)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('action_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expiry_risk_facts', to='hr_contracts.hrcontractcase')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expiry_risk_facts', to='hr_contracts.hrcontractagreement')),
                ('contract_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expiry_risk_facts', to='hr_contracts.hrcontractversion')),
            ],
            options={
                'db_table': 'hr07_contract_expiry_risk',
                'indexes': [models.Index(fields=['tenant_id', 'agreement', 'risk_stage'], name='idx_hr07_exp_risk_agree'), models.Index(fields=['tenant_id', 'due_date', 'severity'], name='idx_hr07_exp_risk_due')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'idempotency_key'), name='uq_hr07_exp_risk_key')],
            },
        ),
    ]
