# Generated by Django 5.2 on 2026-09-01

import uuid

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):
    dependencies = [("hr_contracts", "0005_alter_hrcontractcase_case_type_and_more")]

    operations = [
        migrations.CreateModel(
            name="HrContractTemplateVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.PositiveBigIntegerField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.PositiveBigIntegerField(blank=True, null=True)),
                ("updated_by", models.PositiveBigIntegerField(blank=True, null=True)),
                ("template_code", models.CharField(max_length=64)),
                ("template_name", models.CharField(max_length=160)),
                ("agreement_type", models.CharField(max_length=50)),
                ("version_no", models.PositiveIntegerField()),
                ("body_template", models.TextField()),
                ("numbering_rule_json", models.JSONField(default=dict)),
                ("term_rule_json", models.JSONField(default=dict)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("PUBLISHED", "Published"), ("RETIRED", "Retired")],
                        db_index=True,
                        default="PUBLISHED",
                        max_length=16,
                    ),
                ),
                ("content_hash", models.CharField(editable=False, max_length=64)),
                ("published_at", models.DateTimeField(default=timezone.now)),
                ("published_by", models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "hr07_contract_template_version",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "template_code", "status"],
                        name="idx_hr07_tpl_current",
                    ),
                    models.Index(
                        fields=["tenant_id", "agreement_type", "effective_from"],
                        name="idx_hr07_tpl_type_date",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "template_code", "version_no"),
                        name="uq_hr07_tpl_code_version",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("effective_to__isnull", True), ("effective_to__gt", models.F("effective_from")), _connector="OR"),
                        name="ck_hr07_tpl_date_range",
                    ),
                ],
            },
        )
    ]
