# Generated by Django 5.2 on 2026-09-02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("hr_contracts", "0006_hrcontracttemplateversion")]

    operations = [
        migrations.AlterModelOptions(
            name="hrcontractspermissionmeta",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("hr.contracts.agreement.view", "查看学校合同主档及正式版本"),
                    ("hr.contracts.agreement.create", "创建合同主档"),
                    ("hr.contracts.agreement.sign", "冻结首个签署版本"),
                    ("hr.contracts.agreement.activate", "使已签署版本正式生效"),
                    ("hr.contracts.case.create", "发起合同续签、变更或解除业务单"),
                    ("hr.contracts.case.submit", "提交合同续签、变更或解除业务单"),
                    ("hr.contracts.case.approve", "审批合同续签、变更或解除业务单"),
                    ("hr.contracts.case.sign", "冻结续签或变更后的新合同版本"),
                    ("hr.contracts.case.activate", "使续签或变更后的新合同版本生效"),
                    ("hr.contracts.case.terminate", "执行已批准合同解除生效"),
                    ("hr.contracts.version.correct", "更正已签署合同并追加正式后继版本"),
                    ("hr.contracts.version.void", "作废错误、重复或法律上未成立的签署版本"),
                    ("hr.contracts.document.view", "查看合同文档元数据"),
                    ("hr.contracts.document.upload", "上传合同签署文件与附件"),
                    ("hr.contracts.document.download", "下载合同签署文件与附件"),
                ),
            },
        ),
        migrations.CreateModel(
            name="HrAgreementDocument",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.PositiveBigIntegerField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.PositiveBigIntegerField(blank=True, null=True)),
                ("updated_by", models.PositiveBigIntegerField(blank=True, null=True)),
                ("document_type", models.CharField(choices=[("SIGNED_CONTRACT", "Signed contract"), ("SIGNATURE_RECEIPT", "Signature receipt"), ("ATTACHMENT", "Attachment")], max_length=32)),
                ("signature_status", models.CharField(choices=[("NOT_APPLICABLE", "Not applicable"), ("PENDING", "Pending"), ("SIGNED", "Signed")], default="NOT_APPLICABLE", max_length=24)),
                ("file_path", models.CharField(max_length=500, unique=True)),
                ("file_name", models.CharField(max_length=255)),
                ("mime_type", models.CharField(default="application/pdf", max_length=100)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("agreement", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="documents", to="hr_contracts.hrcontractagreement")),
                ("version", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="documents", to="hr_contracts.hrcontractversion")),
            ],
            options={"db_table": "hr07_agreement_document"},
        ),
        migrations.CreateModel(
            name="HrContractAuditEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.PositiveBigIntegerField(db_index=True)),
                ("action", models.CharField(db_index=True, max_length=64)),
                ("object_type", models.CharField(max_length=64)),
                ("object_id", models.CharField(max_length=128)),
                ("actor_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("purpose", models.CharField(blank=True, default="", max_length=300)),
                ("before_json", models.JSONField(blank=True, default=dict)),
                ("after_json", models.JSONField(blank=True, default=dict)),
                ("request_id", models.CharField(blank=True, default="", max_length=128)),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "hr07_contract_audit_event",
                "indexes": [
                    models.Index(fields=["tenant_id", "object_type", "object_id"], name="idx_hr07_audit_object"),
                    models.Index(fields=["tenant_id", "occurred_at"], name="idx_hr07_audit_time"),
                ],
            },
        ),
        migrations.CreateModel(
            name="HrContractDownloadTicket",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.PositiveBigIntegerField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.PositiveBigIntegerField(blank=True, null=True)),
                ("updated_by", models.PositiveBigIntegerField(blank=True, null=True)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("purpose", models.CharField(max_length=300)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("document", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="download_tickets", to="hr_contracts.hragreementdocument")),
            ],
            options={"db_table": "hr07_contract_download_ticket"},
        ),
        migrations.AddIndex(
            model_name="hragreementdocument",
            index=models.Index(fields=["tenant_id", "agreement", "created_at"], name="idx_hr07_doc_agree"),
        ),
        migrations.AddIndex(
            model_name="hragreementdocument",
            index=models.Index(fields=["tenant_id", "version"], name="idx_hr07_doc_version"),
        ),
        migrations.AddIndex(
            model_name="hrcontractdownloadticket",
            index=models.Index(fields=["tenant_id", "document", "expires_at"], name="idx_hr07_ticket_doc"),
        ),
    ]
