# Generated by Django 5.2 on 2026-08-08 16:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_time', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HrTimePolicyPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, verbose_name='Code')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('policy_family', models.CharField(choices=[('ADMIN_FIXED', '行政固定班'), ('TEACHER_FLEX', '教师弹性'), ('LAB_SHIFT', '实验室轮班'), ('SECURITY_ROTATION', '安保轮转'), ('COUNSELOR_DUTY', '辅导员值班'), ('EXTERNAL_SERVICE', '外聘服务'), ('OTHER', '其他')], default='OTHER', max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', '生效'), ('INACTIVE', '停用')], default='ACTIVE', max_length=16)),
                ('current_version_id', models.BigIntegerField(blank=True, null=True, verbose_name='当前版本 id')),
                ('effective_scope', models.JSONField(blank=True, default=dict, verbose_name='生效范围')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Time Policy Pack',
                'verbose_name_plural': 'Time Policy Packs',
            },
        ),
        migrations.CreateModel(
            name='HrTimeRecordingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, verbose_name='Code')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('method', models.CharField(choices=[('FIXED_POSITIVE_TIME', '固定班次，完整打卡'), ('FLEXIBLE_POSITIVE_TIME', '弹性时段，记录实际工时'), ('NEGATIVE_TIME', '默认按计划工作，仅记录偏差'), ('ABSENCE_ONLY', '只管理请假/缺勤'), ('OVERTIME_ONLY', '只记录批准加班'), ('DUTY_BASED', '按职责/任务核验，非每日坐班'), ('HYBRID', '多种模式组合')], max_length=32, verbose_name='记录方式')),
                ('requires_punch', models.BooleanField(default=True, verbose_name='要求打卡')),
                ('requires_timesheet', models.BooleanField(default=False, verbose_name='要求工时申报')),
                ('requires_daily_presence', models.BooleanField(default=True, verbose_name='要求日考勤')),
                ('overtime_recording_mode', models.CharField(default='ON_REQUEST', max_length=32, verbose_name='加班记录方式')),
                ('absence_recording_mode', models.CharField(default='ON_EXCEPTION', max_length=32, verbose_name='缺勤记录方式')),
                ('effective_from', models.DateField(verbose_name='生效日')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='失效日')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Time Recording Profile',
                'verbose_name_plural': 'Time Recording Profiles',
            },
        ),
        migrations.CreateModel(
            name='HrTimePolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_no', models.PositiveIntegerField(verbose_name='版本号')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PUBLISHED', '已发布'), ('RETIRED', '已退役')], default='DRAFT', max_length=16)),
                ('work_calendar_policy', models.JSONField(blank=True, default=dict)),
                ('schedule_policy', models.JSONField(blank=True, default=dict)),
                ('grace_policy_json', models.JSONField(blank=True, default=dict, verbose_name='宽限政策（late/early grace minutes 等）')),
                ('rounding_policy_json', models.JSONField(blank=True, default=dict, verbose_name='取整政策（raw 事件永不取整）')),
                ('overtime_policy_ref', models.JSONField(blank=True, default=dict, verbose_name='加班政策引用')),
                ('leave_policy_ref', models.JSONField(blank=True, default=dict, verbose_name='请假政策引用')),
                ('missing_punch_policy', models.JSONField(blank=True, default=dict, verbose_name='缺卡政策')),
                ('absence_policy', models.JSONField(blank=True, default=dict, verbose_name='缺勤政策')),
                ('effective_from', models.DateField(verbose_name='生效日')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='失效日')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, editable=False, max_length=64, verbose_name='内容哈希')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('policy_pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='hr_time.hrtimepolicypack')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recording_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hr_time.hrtimerecordingprofile')),
            ],
            options={
                'verbose_name': 'Time Policy Version',
                'verbose_name_plural': 'Time Policy Versions',
            },
        ),
        migrations.AddConstraint(
            model_name='hrtimepolicypack',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'code'), name='uniq_hr11_ppack_code'),
        ),
        migrations.AddConstraint(
            model_name='hrtimerecordingprofile',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'code'), name='uniq_hr11_rec_profile_code'),
        ),
        migrations.AddIndex(
            model_name='hrtimepolicyversion',
            index=models.Index(fields=['tenant_id', 'policy_pack', 'status'], name='hr11_pver_tpack_status'),
        ),
        migrations.AddConstraint(
            model_name='hrtimepolicyversion',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'policy_pack', 'version_no'), name='uniq_hr11_pver_no'),
        ),
    ]
