# Generated by Django 5.2 on 2026-08-08 17:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_time', '0002_hrtimepolicypack_hrtimerecordingprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HrShiftDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, verbose_name='Code')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('shift_family', models.CharField(blank=True, default='', max_length=32, verbose_name='班次族')),
                ('current_version_id', models.BigIntegerField(blank=True, null=True, verbose_name='当前版本 id')),
                ('active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shift Definition',
                'verbose_name_plural': 'Shift Definitions',
            },
        ),
        migrations.CreateModel(
            name='HrShiftVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_no', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('cross_midnight', models.BooleanField(default=False, verbose_name='跨午夜')),
                ('break_policy_id', models.BigIntegerField(blank=True, null=True)),
                ('minimum_minutes', models.PositiveIntegerField(default=0, verbose_name='最小工时（分钟）')),
                ('standard_minutes', models.PositiveIntegerField(default=480, verbose_name='标准工时（分钟）')),
                ('grace_in_minutes', models.PositiveIntegerField(default=0, verbose_name='签到宽限（分钟）')),
                ('grace_out_minutes', models.PositiveIntegerField(default=0, verbose_name='签退宽限（分钟）')),
                ('earliest_punch_minutes', models.PositiveIntegerField(default=0, verbose_name='最早打卡（分钟，班前）')),
                ('latest_punch_minutes', models.PositiveIntegerField(default=0, verbose_name='最晚打卡（分钟，班后）')),
                ('effective_from', models.DateField(verbose_name='生效日')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='失效日')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='hr_time.hrshiftdefinition')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shift Version',
                'verbose_name_plural': 'Shift Versions',
            },
        ),
        migrations.CreateModel(
            name='HrWorkCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, verbose_name='Code')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('region_code', models.CharField(blank=True, default='', max_length=16, verbose_name='区域码')),
                ('calendar_type', models.CharField(choices=[('NATIONAL_BASE', '国家法定基线'), ('REGIONAL', '地方日历'), ('SCHOOL_ADMIN', '学校行政日历'), ('SCHOOL_TEACHER', '学校教师日历'), ('SHIFT_OPERATION', '轮班运营日历'), ('CUSTOM', '自定义')], default='SCHOOL_ADMIN', max_length=32)),
                ('current_version_id', models.BigIntegerField(blank=True, null=True, verbose_name='当前版本 id')),
                ('active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Calendar',
                'verbose_name_plural': 'Work Calendars',
            },
        ),
        migrations.CreateModel(
            name='HrWorkCalendarVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(verbose_name='年度')),
                ('version_no', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('source_type', models.CharField(blank=True, default='', max_length=32, verbose_name='来源类型（国务院/校历等）')),
                ('source_ref', models.CharField(blank=True, default='', max_length=128, verbose_name='来源引用')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PUBLISHED', '已发布'), ('SUPERSEDED', '已被取代')], default='DRAFT', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('supersedes_version_id', models.BigIntegerField(blank=True, null=True, verbose_name='取代的版本 id')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='hr_time.hrworkcalendar')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Calendar Version',
                'verbose_name_plural': 'Work Calendar Versions',
            },
        ),
        migrations.CreateModel(
            name='HrCalendarDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='日期')),
                ('day_type', models.CharField(choices=[('REGULAR_WORKDAY', '普通工作日'), ('REST_DAY', '休息日'), ('STATUTORY_HOLIDAY', '法定节假日'), ('MAKEUP_WORKDAY', '调休工作日'), ('SCHOOL_BREAK', '寒暑假'), ('SPECIAL_CLOSURE', '特殊关闭'), ('PARTIAL_HOLIDAY', '部分公民放假')], max_length=32, verbose_name='日类型')),
                ('statutory_holiday_code', models.CharField(blank=True, max_length=32, null=True, verbose_name='法定节假日编码')),
                ('is_working_day', models.BooleanField(default=True, verbose_name='是否工作日')),
                ('expected_work_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='期望工时（分钟）')),
                ('makeup_for_date', models.DateField(blank=True, null=True, verbose_name='调休对应日期')),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('calendar_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='hr_time.hrworkcalendarversion')),
            ],
            options={
                'verbose_name': 'Calendar Day',
                'verbose_name_plural': 'Calendar Days',
            },
        ),
        migrations.CreateModel(
            name='HrWorkPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, verbose_name='Code')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('cycle_length_days', models.PositiveIntegerField(default=7, verbose_name='周期天数')),
                ('pattern_json', models.JSONField(default=list, verbose_name='周期模板（每日班次 code 或 null=休息）')),
                ('current_version', models.PositiveIntegerField(default=1, verbose_name='当前版本')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Pattern',
                'verbose_name_plural': 'Work Patterns',
            },
        ),
        migrations.CreateModel(
            name='HrScheduleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_master_id', models.BigIntegerField(verbose_name='HR03 人员 id')),
                ('assignment_id', models.BigIntegerField(blank=True, null=True, verbose_name='HR03 任职 id')),
                ('time_policy_version_id', models.BigIntegerField(blank=True, null=True, verbose_name='时间政策版本 id')),
                ('effective_from', models.DateField(verbose_name='生效日')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='失效日')),
                ('source', models.CharField(default='MANUAL', max_length=32, verbose_name='来源')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shift_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hr_time.hrshiftversion')),
                ('calendar_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hr_time.hrworkcalendarversion')),
                ('work_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hr_time.hrworkpattern')),
            ],
            options={
                'verbose_name': 'Schedule Assignment',
                'verbose_name_plural': 'Schedule Assignments',
            },
        ),
        migrations.CreateModel(
            name='HrScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_from', models.DateField(verbose_name='开始日期')),
                ('date_to', models.DateField(verbose_name='结束日期')),
                ('exception_type', models.CharField(choices=[('TEMP_SHIFT_CHANGE', '临时换班'), ('AUTHORIZED_TRAINING', '授权培训'), ('ENTERPRISE_PRACTICE', '企业实践'), ('OFFICIAL_DUTY', '公务/外勤'), ('TRAVEL', '出差'), ('SPECIAL_CLOSURE', '特殊关闭'), ('MANUAL_CORRECTION', '人工更正')], max_length=32, verbose_name='例外类型')),
                ('original_schedule_snapshot', models.JSONField(blank=True, default=dict, verbose_name='原排班快照')),
                ('replacement_schedule_snapshot', models.JSONField(blank=True, default=dict, verbose_name='替换排班快照')),
                ('reason', models.CharField(max_length=255, verbose_name='原因')),
                ('source_case_id', models.CharField(blank=True, default='', max_length=64, verbose_name='来源 case id')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('schedule_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='hr_time.hrscheduleassignment')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Schedule Exception',
                'verbose_name_plural': 'Schedule Exceptions',
                'indexes': [models.Index(fields=['tenant_id', 'exception_type', 'date_from'], name='hr11_schexc_ten_type_from')],
            },
        ),
        migrations.AddConstraint(
            model_name='hrshiftdefinition',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'code'), name='uniq_hr11_shift_code'),
        ),
        migrations.AddIndex(
            model_name='hrshiftversion',
            index=models.Index(fields=['tenant_id', 'shift', 'effective_from'], name='hr11_shiftver_ten_sf'),
        ),
        migrations.AddConstraint(
            model_name='hrshiftversion',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'shift', 'version_no'), name='uniq_hr11_shiftver_no'),
        ),
        migrations.AddConstraint(
            model_name='hrworkcalendar',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'code'), name='uniq_hr11_cal_code'),
        ),
        migrations.AddIndex(
            model_name='hrworkcalendarversion',
            index=models.Index(fields=['tenant_id', 'calendar', 'year'], name='hr11_calver_ten_cal_year'),
        ),
        migrations.AddConstraint(
            model_name='hrworkcalendarversion',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'calendar', 'year', 'version_no'), name='uniq_hr11_calver_year'),
        ),
        migrations.AddIndex(
            model_name='hrcalendarday',
            index=models.Index(fields=['tenant_id', 'calendar_version', 'day_type'], name='hr11_calday_ten_ver_type'),
        ),
        migrations.AddConstraint(
            model_name='hrcalendarday',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'calendar_version', 'date'), name='uniq_hr11_calday_date'),
        ),
        migrations.AddConstraint(
            model_name='hrworkpattern',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'code'), name='uniq_hr11_pattern_code'),
        ),
        migrations.AddIndex(
            model_name='hrscheduleassignment',
            index=models.Index(fields=['tenant_id', 'staff_master_id', 'effective_from'], name='hr11_sched_ten_staff_from'),
        ),
        migrations.AddIndex(
            model_name='hrscheduleassignment',
            index=models.Index(fields=['tenant_id', 'assignment_id', 'effective_from'], name='hr11_sched_ten_asg_from'),
        ),
    ]
