# Generated by Django 5.2 on 2026-08-08 17:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_time', '0003_hrshiftdefinition_hrshiftversion_hrworkcalendar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HrAttendanceDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=64, verbose_name='提供方')),
                ('external_device_id', models.CharField(max_length=128, verbose_name='设备外部 id')),
                ('name', models.CharField(max_length=128, verbose_name='设备名')),
                ('location_id', models.BigIntegerField(blank=True, null=True)),
                ('timezone', models.CharField(default='Asia/Shanghai', max_length=64, verbose_name='设备时区')),
                ('status', models.CharField(choices=[('ACTIVE', '在线'), ('INACTIVE', '停用'), ('OFFLINE', '离线')], default='ACTIVE', max_length=16)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('secret_ref', models.CharField(blank=True, default='', max_length=128, verbose_name='密钥引用（Secret Manager）')),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Device',
                'verbose_name_plural': 'Attendance Devices',
            },
        ),
        migrations.CreateModel(
            name='HrRawTimeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_master_id', models.BigIntegerField(verbose_name='HR03 人员 id')),
                ('event_type', models.CharField(choices=[('IN', '签到'), ('OUT', '签退'), ('BREAK_IN', '休息开始'), ('BREAK_OUT', '休息结束')], max_length=16, verbose_name='事件类型')),
                ('event_at_utc', models.DateTimeField(verbose_name='事件时间（UTC）')),
                ('event_timezone', models.CharField(default='Asia/Shanghai', max_length=64, verbose_name='事件时区')),
                ('local_event_at', models.DateTimeField(verbose_name='事件时间（本地）')),
                ('source_event_id', models.CharField(blank=True, default='', max_length=128, verbose_name='来源事件 id')),
                ('dedupe_key', models.CharField(max_length=255, verbose_name='幂等键')),
                ('location_ref', models.CharField(blank=True, default='', max_length=128, verbose_name='位置引用')),
                ('raw_payload_hash', models.CharField(max_length=64, verbose_name='原始载荷哈希')),
                ('trust_level', models.PositiveSmallIntegerField(default=1, verbose_name='信任级别')),
                ('ingest_status', models.CharField(choices=[('RECEIVED', '已接收'), ('VALIDATED', '已验证'), ('PERSON_UNMAPPED', '人员未映射'), ('DUPLICATE', '重复'), ('REJECTED', '拒绝'), ('STAGED', '待人工处理')], default='RECEIVED', max_length=32)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='hr_time.hrattendancedevice')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Raw Time Event',
                'verbose_name_plural': 'Raw Time Events',
            },
        ),
        migrations.CreateModel(
            name='HrTimeEventPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pairing_status', models.CharField(choices=[('PAIRED', '已配对'), ('OPEN', '待配对'), ('AMBIGUOUS', '配对歧义'), ('INVALID_ORDER', '顺序异常'), ('CROSS_SHIFT', '跨班次'), ('MANUAL_REVIEW', '人工复核')], default='OPEN', max_length=32)),
                ('pairing_rule_version', models.CharField(blank=True, default='', max_length=32, verbose_name='配对规则版本')),
                ('shift_business_date', models.DateField(verbose_name='班次业务日期')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='时长（分钟）')),
                ('anomaly_codes', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('in_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hr_time.hrrawtimeevent')),
                ('out_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hr_time.hrrawtimeevent')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Time Event Pair',
                'verbose_name_plural': 'Time Event Pairs',
            },
        ),
        migrations.CreateModel(
            name='HrTimeEventSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('BIOMETRIC', '生物识别设备'), ('MOBILE', '移动端'), ('WEB', 'Web 端'), ('API', '系统 API'), ('IMPORT', '批量导入'), ('MANUAL', '人工补录')], max_length=32, verbose_name='来源类型')),
                ('provider', models.CharField(blank=True, default='', max_length=64, verbose_name='提供方')),
                ('device_ref', models.CharField(blank=True, default='', max_length=128, verbose_name='设备引用')),
                ('trust_level', models.PositiveSmallIntegerField(default=1, verbose_name='信任级别（1-5，5 最高）')),
                ('signature_required', models.BooleanField(default=False, verbose_name='要求签名')),
                ('geofence_required', models.BooleanField(default=False, verbose_name='要求地理围栏')),
                ('active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Time Event Source',
                'verbose_name_plural': 'Time Event Sources',
            },
        ),
        migrations.AddField(
            model_name='hrrawtimeevent',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='hr_time.hrtimeeventsource'),
        ),
        migrations.AddConstraint(
            model_name='hrattendancedevice',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'provider', 'external_device_id'), name='uniq_hr11_device_ext'),
        ),
        migrations.AddIndex(
            model_name='hrtimeeventpair',
            index=models.Index(fields=['tenant_id', 'pairing_status', 'shift_business_date'], name='hr11_pair_ten_status_date'),
        ),
        migrations.AddConstraint(
            model_name='hrtimeeventpair',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'in_event'), name='uniq_hr11_pair_inevent'),
        ),
        migrations.AddConstraint(
            model_name='hrtimeeventsource',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'source_type', 'provider', 'device_ref'), name='uniq_hr11_eventsrc'),
        ),
        migrations.AddIndex(
            model_name='hrrawtimeevent',
            index=models.Index(fields=['tenant_id', 'staff_master_id', 'event_at_utc'], name='hr11_event_ten_staff_at'),
        ),
        migrations.AddIndex(
            model_name='hrrawtimeevent',
            index=models.Index(fields=['tenant_id', 'source', 'event_at_utc'], name='hr11_event_ten_src_at'),
        ),
        migrations.AddConstraint(
            model_name='hrrawtimeevent',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'source', 'dedupe_key'), name='uniq_hr11_event_dedupe'),
        ),
    ]
