# Generated by Django 5.2 on 2026-08-08 23:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_time', '0004_hrattendancedevice_hrrawtimeevent_hrtimeeventpair_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HrTimeSheetPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_master_id', models.BigIntegerField(verbose_name='HR03 人员 id')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('SUBMITTED', '已提交'), ('APPROVED', '已批准'), ('RETURNED', '退回')], default='DRAFT', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Time Sheet Period',
                'verbose_name_plural': 'Time Sheet Periods',
            },
        ),
        migrations.CreateModel(
            name='HrTimeSheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='日期')),
                ('entry_type', models.CharField(choices=[('ATTENDANCE_TIME', '出勤时间'), ('DUTY_TIME', '值班时间'), ('TRAINING', '培训'), ('TRAVEL', '出差'), ('OVERTIME', '加班')], max_length=32)),
                ('minutes', models.PositiveIntegerField(verbose_name='时长（分钟）')),
                ('project_ref', models.CharField(blank=True, default='', max_length=64)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='hr_time.hrtimesheetperiod')),
            ],
            options={
                'verbose_name': 'Time Sheet Entry',
                'verbose_name_plural': 'Time Sheet Entries',
            },
        ),
        migrations.CreateModel(
            name='HrAttendanceDayFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_master_id', models.BigIntegerField(verbose_name='HR03 人员 id')),
                ('assignment_id', models.BigIntegerField(blank=True, null=True)),
                ('business_date', models.DateField(verbose_name='班次业务日期')),
                ('policy_version_id', models.BigIntegerField(blank=True, null=True)),
                ('calendar_version_id', models.BigIntegerField(blank=True, null=True)),
                ('schedule_snapshot_json', models.JSONField(blank=True, default=dict)),
                ('expected_minutes', models.PositiveIntegerField(default=0, verbose_name='期望工时（分钟）')),
                ('actual_minutes', models.PositiveIntegerField(default=0, verbose_name='实际工时（分钟）')),
                ('credited_minutes', models.PositiveIntegerField(default=0, verbose_name='记入工时（分钟）')),
                ('authorized_absence_minutes', models.PositiveIntegerField(default=0, verbose_name='授权缺勤（分钟）')),
                ('overtime_minutes_candidate', models.PositiveIntegerField(default=0, verbose_name='加班候选（分钟）')),
                ('status', models.CharField(choices=[('PRESENT', '出勤'), ('PARTIAL_PRESENT', '部分出勤'), ('AUTHORIZED_ABSENCE', '授权缺勤'), ('AUTHORIZED_DUTY', '授权公务/外勤'), ('REST_DAY', '休息日'), ('STATUTORY_HOLIDAY', '法定节假日'), ('MISSING_TIME', '缺卡待核查'), ('PENDING_REVIEW', '待复核'), ('UNEXCUSED_ABSENCE', '未授权缺勤候选'), ('SOURCE_UNAVAILABLE', '数据源不可用'), ('NOT_APPLICABLE', '不适用')], default='MISSING_TIME', max_length=32)),
                ('evaluation_version', models.PositiveIntegerField(default=1, verbose_name='评估版本')),
                ('source_pair_ids', models.JSONField(blank=True, default=list, verbose_name='来源配对 id 列表')),
                ('finalized', models.BooleanField(default=False, verbose_name='是否终态')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Day Fact',
                'verbose_name_plural': 'Attendance Day Facts',
                'indexes': [models.Index(fields=['tenant_id', 'staff_master_id', 'business_date'], name='hr11_dayfact_ten_staff_date'), models.Index(fields=['tenant_id', 'status', 'business_date'], name='hr11_dayfact_ten_status_date')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'staff_master_id', 'business_date'), name='uniq_hr11_dayfact_staff_date')],
            },
        ),
        migrations.CreateModel(
            name='HrTimeBalanceLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_master_id', models.BigIntegerField(verbose_name='HR03 人员 id')),
                ('account_type', models.CharField(choices=[('WORK_HOURS', '工时'), ('OVERTIME', '加班'), ('COMP_TIME', '调休'), ('PENDING', '待补')], max_length=32)),
                ('credit_minutes', models.PositiveIntegerField(default=0, verbose_name='贷方（分钟）')),
                ('debit_minutes', models.PositiveIntegerField(default=0, verbose_name='借方（分钟）')),
                ('source_type', models.CharField(choices=[('ATTENDANCE_DAY_FACT', '日考勤事实'), ('OVERTIME_FACT', '加班事实'), ('COMP_TIME', '调休'), ('ADJUST', '人工调整'), ('MIGRATION', '迁移'), ('REVERSAL', '冲正')], max_length=32)),
                ('source_id', models.CharField(blank=True, default='', max_length=64)),
                ('effective_date', models.DateField(verbose_name='生效日')),
                ('balance_after', models.IntegerField(default=0, verbose_name='变动后余额（分钟）')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hr_time.hrtimebalanceledger')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Time Balance Ledger',
                'verbose_name_plural': 'Time Balance Ledgers',
                'indexes': [models.Index(fields=['tenant_id', 'staff_master_id', 'account_type', 'effective_date'], name='hr11_ledger_ten_staff_type_date')],
            },
        ),
        migrations.AddConstraint(
            model_name='hrtimesheetperiod',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'staff_master_id', 'start_date', 'end_date'), name='uniq_hr11_tsp_period'),
        ),
        migrations.AddConstraint(
            model_name='hrtimesheetentry',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'period', 'date', 'entry_type'), name='uniq_hr11_tse_period_date_type'),
        ),
    ]
