# Generated by Django 5.2 on 2026-08-08 23:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_time', '0005_hrtimesheetperiod_hrtimesheetentry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HrAttendanceCorrectionCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_change_json', models.JSONField(blank=True, default=dict)),
                ('reason_code', models.CharField(choices=[('MISSING_PUNCH', '漏卡'), ('WRONG_PUNCH', '错卡'), ('DEVICE_OUTAGE', '设备故障'), ('OFFICIAL_DUTY', '公务/外勤'), ('MIGRATION', '历史迁移'), ('AUTHORIZED_CORRECTION', '授权更正')], max_length=32)),
                ('evidence_ids', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('SUBMITTED', '已提交'), ('UNDER_REVIEW', '复核中'), ('APPROVED', '已批准'), ('REJECTED', '已拒绝')], default='SUBMITTED', max_length=32)),
                ('approval_snapshot', models.JSONField(blank=True, default=dict)),
                ('resulting_fact_version_id', models.BigIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target_fact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='hr_time.hrattendancedayfact')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Correction Case',
                'verbose_name_plural': 'Attendance Correction Cases',
            },
        ),
        migrations.CreateModel(
            name='HrCompTimeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_master_id', models.BigIntegerField(verbose_name='HR03 人员 id')),
                ('account_year', models.PositiveIntegerField(verbose_name='年度')),
                ('status', models.CharField(choices=[('ACTIVE', '生效'), ('CLOSED', '已结清')], default='ACTIVE', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comp Time Account',
                'verbose_name_plural': 'Comp Time Accounts',
            },
        ),
        migrations.CreateModel(
            name='HrOvertimeFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_master_id', models.BigIntegerField(verbose_name='HR03 人员 id')),
                ('actual_start_at', models.DateTimeField(verbose_name='实际开始')),
                ('actual_end_at', models.DateTimeField(verbose_name='实际结束')),
                ('actual_minutes', models.PositiveIntegerField(verbose_name='实际时长（分钟）')),
                ('eligible_minutes', models.PositiveIntegerField(verbose_name='可结算时长（分钟）')),
                ('policy_version_id', models.BigIntegerField(blank=True, null=True)),
                ('evidence_source', models.CharField(blank=True, default='', max_length=64)),
                ('verification_status', models.CharField(choices=[('CANDIDATE', '候选'), ('VERIFIED', '已核验'), ('REJECTED', '已驳回')], default='CANDIDATE', max_length=16)),
                ('settlement_mode', models.CharField(choices=[('PAY_CANDIDATE', '支付候选'), ('COMP_TIME', '转调休'), ('NO_COMPENSATION', '不补偿'), ('POLICY_DEPENDENT', '依政策')], default='POLICY_DEPENDENT', max_length=32)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Overtime Fact',
                'verbose_name_plural': 'Overtime Facts',
            },
        ),
        migrations.CreateModel(
            name='HrCompTimeLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('CREDIT', '入账'), ('DEBIT', '使用'), ('REVERSAL', '冲正'), ('EXPIRE', '过期')], max_length=16)),
                ('minutes', models.PositiveIntegerField(verbose_name='分钟')),
                ('effective_date', models.DateField(verbose_name='生效日')),
                ('balance_after', models.IntegerField(default=0, verbose_name='变动后余额（分钟）')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='hr_time.hrcomptimeaccount')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hr_time.hrcomptimeledger')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_fact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hr_time.hrovertimefact')),
            ],
            options={
                'verbose_name': 'Comp Time Ledger',
                'verbose_name_plural': 'Comp Time Ledgers',
            },
        ),
        migrations.CreateModel(
            name='HrOvertimeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_master_id', models.BigIntegerField(verbose_name='HR03 人员 id')),
                ('assignment_id', models.BigIntegerField(blank=True, null=True)),
                ('requested_start_at', models.DateTimeField(verbose_name='申请开始')),
                ('requested_end_at', models.DateTimeField(verbose_name='申请结束')),
                ('reason', models.CharField(max_length=255, verbose_name='原因')),
                ('overtime_type', models.CharField(blank=True, default='', max_length=32, verbose_name='加班类型')),
                ('planned_minutes', models.PositiveIntegerField(verbose_name='计划时长（分钟）')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('SUBMITTED', '已提交'), ('APPROVED', '已批准'), ('REJECTED', '已拒绝'), ('CANCELLED', '已取消')], default='DRAFT', max_length=16)),
                ('approval_snapshot', models.JSONField(blank=True, default=dict)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Overtime Request',
                'verbose_name_plural': 'Overtime Requests',
            },
        ),
        migrations.AddField(
            model_name='hrovertimefact',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facts', to='hr_time.hrovertimerequest'),
        ),
        migrations.CreateModel(
            name='HrTimeSourceIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_ref', models.CharField(max_length=128, verbose_name='来源/设备引用')),
                ('start_at', models.DateTimeField(verbose_name='开始时间')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('affected_scope', models.JSONField(blank=True, default=dict)),
                ('severity', models.CharField(choices=[('LOW', '低'), ('MEDIUM', '中'), ('HIGH', '高'), ('CRITICAL', '严重')], default='MEDIUM', max_length=16)),
                ('reconciliation_status', models.CharField(choices=[('OPEN', '待对账'), ('RECONCILING', '对账中'), ('RECONCILED', '已对账')], default='OPEN', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Time Source Incident',
                'verbose_name_plural': 'Time Source Incidents',
            },
        ),
        migrations.CreateModel(
            name='HrAttendanceException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_master_id', models.BigIntegerField(verbose_name='HR03 人员 id')),
                ('business_date', models.DateField(verbose_name='班次业务日期')),
                ('exception_code', models.CharField(choices=[('MISSING_IN', '缺签到'), ('MISSING_OUT', '缺签退'), ('LATE', '迟到'), ('EARLY_OUT', '早退'), ('INSUFFICIENT_HOURS', '工时不足'), ('EXCESS_HOURS', '工时超标'), ('OVERLAP_LEAVE', '与请假重叠'), ('OVERLAP_SCHEDULE', '排班重叠'), ('DEVICE_CONFLICT', '设备冲突'), ('DUPLICATE_EVENT', '重复事件'), ('UNKNOWN_SOURCE', '未知来源'), ('UNAUTHORIZED_LOCATION', '未授权地点'), ('OUT_OF_WINDOW', '超出时段')], max_length=32, verbose_name='异常码')),
                ('evidence', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('OPEN', '待处理'), ('REVIEWING', '复核中'), ('RESOLVED', '已解决'), ('DISMISSED', '已排除')], default='OPEN', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_fact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='hr_time.hrattendancedayfact')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Exception',
                'verbose_name_plural': 'Attendance Exceptions',
                'indexes': [models.Index(fields=['tenant_id', 'status', 'business_date'], name='hr11_exc_ten_status_date')],
            },
        ),
        migrations.AddConstraint(
            model_name='hrcomptimeaccount',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'staff_master_id', 'account_year'), name='uniq_hr11_comptime_acct'),
        ),
        migrations.AddIndex(
            model_name='hrcomptimeledger',
            index=models.Index(fields=['tenant_id', 'account', 'effective_date'], name='hr11_comptime_ledger_date'),
        ),
        migrations.AddIndex(
            model_name='hrovertimerequest',
            index=models.Index(fields=['tenant_id', 'staff_master_id', 'status'], name='hr11_otreq_ten_staff_status'),
        ),
        migrations.AddIndex(
            model_name='hrovertimefact',
            index=models.Index(fields=['tenant_id', 'staff_master_id', 'verification_status'], name='hr11_otfact_ten_staff_ver'),
        ),
        migrations.AddIndex(
            model_name='hrtimesourceincident',
            index=models.Index(fields=['tenant_id', 'severity', 'start_at'], name='hr11_inc_ten_sev_start'),
        ),
    ]
