# Generated by Django 5.2 on 2026-08-08 23:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_time', '0007_hrleavepolicypack_hrleavepolicyversion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HrLeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_master_id', models.BigIntegerField(verbose_name='HR03 人员 id')),
                ('assignment_id', models.BigIntegerField(blank=True, null=True)),
                ('policy_version_id', models.BigIntegerField(blank=True, null=True)),
                ('start_at', models.DateField(verbose_name='开始日期')),
                ('end_at', models.DateField(verbose_name='结束日期')),
                ('start_breakdown', models.CharField(choices=[('FULL_DAY', '全天'), ('HALF_DAY_AM', '上午半天'), ('HALF_DAY_PM', '下午半天'), ('HOURS', '小时')], default='FULL_DAY', max_length=16)),
                ('end_breakdown', models.CharField(choices=[('FULL_DAY', '全天'), ('HALF_DAY_AM', '上午半天'), ('HALF_DAY_PM', '下午半天'), ('HOURS', '小时')], default='FULL_DAY', max_length=16)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='申请数量')),
                ('calculated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='计算数量')),
                ('unit', models.CharField(choices=[('DAYS', '天'), ('HOURS', '小时'), ('MINUTES', '分钟')], default='DAYS', max_length=16)),
                ('reason_category', models.CharField(blank=True, default='', max_length=32)),
                ('reason_text', models.CharField(blank=True, default='', max_length=255, verbose_name='原因（敏感字段按假别受限）')),
                ('reservation_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('SUBMITTED', '已提交'), ('UNDER_REVIEW', '审批中'), ('APPROVED', '已批准'), ('SCHEDULED', '已排程'), ('IN_PROGRESS', '进行中'), ('COMPLETED', '已完成'), ('RETURNED_FROM_LEAVE', '已销假'), ('CLOSED', '已关闭'), ('RETURNED', '退回'), ('REJECTED', '拒绝'), ('WITHDRAWN', '已撤回'), ('CANCELLED', '已取消'), ('CHANGE_IN_PROGRESS', '变更中'), ('VOID', '作废')], default='DRAFT', max_length=32)),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('return_reason', models.CharField(blank=True, default='', max_length=255)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='hr_time.hrleaveaccount')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='hr_time.hrleavetype')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Request',
                'verbose_name_plural': 'Leave Requests',
            },
        ),
        migrations.CreateModel(
            name='HrLeaveEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_id', models.CharField(max_length=64, verbose_name='文档 id')),
                ('evidence_type', models.CharField(blank=True, default='', max_length=32)),
                ('verification_status', models.CharField(choices=[('PENDING', '待核验'), ('VERIFIED', '已核验'), ('REJECTED', '已拒绝')], default='PENDING', max_length=16)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('sensitivity', models.CharField(choices=[('NORMAL', '普通'), ('MEDICAL', '医疗'), ('RESTRICTED', '受限')], default='NORMAL', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('verifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidences', to='hr_time.hrleaverequest')),
            ],
            options={
                'verbose_name': 'Leave Evidence',
                'verbose_name_plural': 'Leave Evidences',
            },
        ),
        migrations.CreateModel(
            name='HrLeaveApprovalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow_version', models.CharField(max_length=32, verbose_name='流程版本')),
                ('approver_chain', models.JSONField(default=list, verbose_name='审批链')),
                ('approval_rules_snapshot', models.JSONField(blank=True, default=dict)),
                ('submitted_data_hash', models.CharField(max_length=64, verbose_name='提交数据哈希')),
                ('decisions', models.JSONField(blank=True, default=list, verbose_name='决策链')),
                ('final_decision_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_snapshots', to='hr_time.hrleaverequest')),
            ],
            options={
                'verbose_name': 'Leave Approval Snapshot',
                'verbose_name_plural': 'Leave Approval Snapshots',
            },
        ),
        migrations.CreateModel(
            name='HrAbsenceFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_master_id', models.BigIntegerField(verbose_name='HR03 人员 id')),
                ('start_at', models.DateField(verbose_name='开始日期')),
                ('end_at', models.DateField(verbose_name='结束日期')),
                ('scheduled_minutes_impacted', models.PositiveIntegerField(default=0, verbose_name='影响排班时长（分钟）')),
                ('chargeable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='可扣数量')),
                ('paid_classification', models.CharField(choices=[('PAID', '带薪'), ('UNPAID', '无薪'), ('POLICY_DEPENDENT', '依政策')], default='POLICY_DEPENDENT', max_length=16)),
                ('policy_version_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', '生效'), ('SUPERSEDED', '被取代'), ('CANCELLED', '已取消')], default='ACTIVE', max_length=16)),
                ('effective_snapshot', models.JSONField(blank=True, default=dict)),
                ('fact_version', models.PositiveIntegerField(default=1, verbose_name='事实版本')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absence_facts', to='hr_time.hrleaverequest')),
            ],
            options={
                'verbose_name': 'Absence Fact',
                'verbose_name_plural': 'Absence Facts',
            },
        ),
        migrations.CreateModel(
            name='HrReturnFromLeaveCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actual_return_at', models.DateField(verbose_name='实际返岗日期')),
                ('expected_return_at', models.DateField(verbose_name='预期返岗日期')),
                ('early_return', models.BooleanField(default=False, verbose_name='提前返岗')),
                ('evidence', models.CharField(blank=True, default='', max_length=255)),
                ('resulting_usage_adjustment', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='用量调整')),
                ('schedule_restore_status', models.CharField(default='PENDING', max_length=16)),
                ('downstream_reconcile_status', models.CharField(default='PENDING', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_cases', to='hr_time.hrleaverequest')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Return From Leave Case',
                'verbose_name_plural': 'Return From Leave Cases',
            },
        ),
        migrations.AddIndex(
            model_name='hrleaverequest',
            index=models.Index(fields=['tenant_id', 'staff_master_id', 'status'], name='hr11_lreq_ten_staff_status'),
        ),
        migrations.AddIndex(
            model_name='hrabsencefact',
            index=models.Index(fields=['tenant_id', 'staff_master_id', 'start_at'], name='hr11_absfact_ten_staff_start'),
        ),
    ]
