# Generated by Django 5.2 on 2026-08-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_time', '0009_hrtimecloseperiod_hrtimeclosesnapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrtimeriskcase',
            name='tenant_id',
            field=models.BigIntegerField(db_index=True, verbose_name='Tenant ID'),
        ),
    ]
