# Generated by Django 5.2 on 2026-08-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_time', '0010_alter_hrtimeriskcase_tenant_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='hrtimebalanceledger',
            new_name='hex_time_ledger_type_date',
            old_name='hr11_ledger_ten_staff_type_date',
        ),
    ]
