# Generated by hand for HR05-S11（authority mode）
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_onboarding", "0003_hrprovisioningrequest_payload_json"),
    ]

    operations = [
        migrations.CreateModel(
            name="HrOnboardingAuthorityMode",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.BigIntegerField(db_index=True, unique=True)),
                ("mode", models.CharField(choices=[("LEGACY_ONBOARDING_ONLY", "Legacy Onboarding Only"), ("DUAL_READ_COMPARE", "Dual Read Compare"), ("HR05_AUTHORITY", "HR05 Authority")], default="LEGACY_ONBOARDING_ONLY", max_length=32)),
                ("switched_by", models.BigIntegerField(blank=True, null=True)),
                ("old_mode", models.CharField(blank=True, default="", max_length=32)),
                ("new_mode", models.CharField(blank=True, default="", max_length=32)),
                ("reason", models.TextField(blank=True, default="")),
                ("reconcile_report_id", models.CharField(blank=True, default="", max_length=64)),
                ("switched_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "HR Onboarding Authority Mode",
                "verbose_name_plural": "HR Onboarding Authority Modes",
            },
        ),
    ]
