# Generated by Django 5.2 on 2026-08-30 10:30

import django.db.models.deletion
import hashlib
import json
import uuid
from django.db import migrations, models
from django.utils import timezone


SNAPSHOT_TABLE = "hr_onboarding_hronboardingactivationsnapshot"
AMENDMENT_TABLE = "hr_onboarding_hronboardingactivationamendment"
CASE_TABLE = "hr_onboarding_hronboardingcase"


def _canonical_hash(payload):
    encoded = json.dumps(
        payload,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
        default=str,
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def backfill_activation_seals(apps, schema_editor):
    Snapshot = apps.get_model("hr_onboarding", "HrOnboardingActivationSnapshot")
    alias = schema_editor.connection.alias
    for snapshot in Snapshot.objects.using(alias).select_related("case").iterator():
        case = snapshot.case
        activated_at = snapshot.activated_at or snapshot.created_at or timezone.now()
        payload = {
            "tenantId": int(snapshot.tenant_id),
            "caseId": str(snapshot.case_id),
            "activatedAt": activated_at.isoformat(),
            "personId": str(snapshot.person_id) if snapshot.person_id else None,
            "staffMasterId": (
                str(snapshot.staff_master_id) if snapshot.staff_master_id else None
            ),
            "employmentId": str(snapshot.employment_id) if snapshot.employment_id else None,
            "assignmentId": str(snapshot.assignment_id) if snapshot.assignment_id else None,
            "staffNo": snapshot.staff_no or "",
            "organizationId": snapshot.organization_id,
            "positionId": snapshot.position_id,
            "sourceType": case.source_type or "",
            "sourceId": case.source_id or "",
            "hr04ProposedHireId": case.hr04_proposed_hire_id or "",
            "hr04ApplicationId": case.hr04_application_id or "",
            "sourceVersions": snapshot.source_versions_json or {},
        }
        Snapshot.objects.using(alias).filter(pk=snapshot.pk).update(
            activated_at=activated_at,
            source_type=case.source_type or "",
            source_id=case.source_id or "",
            hr04_proposed_hire_id=case.hr04_proposed_hire_id or "",
            hr04_application_id=case.hr04_application_id or "",
            sealed_at=activated_at,
            content_hash=_canonical_hash(payload),
        )


def create_mysql_activation_seals(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    statements = [
        "DROP TRIGGER IF EXISTS hr05_activation_snapshot_bi_seal",
        "DROP TRIGGER IF EXISTS hr05_activation_snapshot_bu_seal",
        "DROP TRIGGER IF EXISTS hr05_activation_snapshot_bd_seal",
        "DROP TRIGGER IF EXISTS hr05_activation_amendment_bi_seal",
        "DROP TRIGGER IF EXISTS hr05_activation_amendment_bu_seal",
        "DROP TRIGGER IF EXISTS hr05_activation_amendment_bd_seal",
        f"""
        CREATE TRIGGER hr05_activation_snapshot_bi_seal
        BEFORE INSERT ON {SNAPSHOT_TABLE}
        FOR EACH ROW
        BEGIN
            IF NEW.content_hash IS NULL OR CHAR_LENGTH(NEW.content_hash) <> 64
               OR NEW.sealed_at IS NULL THEN
                SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'HR05_ACTIVATION_SEAL_REQUIRED';
            END IF;
            IF NOT EXISTS (
                SELECT 1 FROM {CASE_TABLE} c
                WHERE c.id = NEW.case_id
                  AND c.tenant_id = NEW.tenant_id
                  AND c.source_type = NEW.source_type
                  AND c.source_id = NEW.source_id
                  AND COALESCE(c.hr04_proposed_hire_id, '') = COALESCE(NEW.hr04_proposed_hire_id, '')
                  AND COALESCE(c.hr04_application_id, '') = COALESCE(NEW.hr04_application_id, '')
            ) THEN
                SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'HR05_ACTIVATION_PARENT_CHAIN_INVALID';
            END IF;
        END
        """,
        f"""
        CREATE TRIGGER hr05_activation_snapshot_bu_seal
        BEFORE UPDATE ON {SNAPSHOT_TABLE}
        FOR EACH ROW
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'HR05_ACTIVATION_FACT_IMMUTABLE'
        """,
        f"""
        CREATE TRIGGER hr05_activation_snapshot_bd_seal
        BEFORE DELETE ON {SNAPSHOT_TABLE}
        FOR EACH ROW
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'HR05_ACTIVATION_FACT_IMMUTABLE'
        """,
        f"""
        CREATE TRIGGER hr05_activation_amendment_bi_seal
        BEFORE INSERT ON {AMENDMENT_TABLE}
        FOR EACH ROW
        BEGIN
            IF NEW.content_hash IS NULL OR CHAR_LENGTH(NEW.content_hash) <> 64
               OR NEW.request_hash IS NULL OR CHAR_LENGTH(NEW.request_hash) <> 64
               OR NEW.sealed_at IS NULL THEN
                SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'HR05_ACTIVATION_AMENDMENT_SEAL_REQUIRED';
            END IF;
            IF NOT EXISTS (
                SELECT 1 FROM {SNAPSHOT_TABLE} s
                WHERE s.id = NEW.snapshot_id AND s.tenant_id = NEW.tenant_id
            ) THEN
                SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'HR05_ACTIVATION_AMENDMENT_TENANT_INVALID';
            END IF;
            IF NEW.predecessor_id IS NULL AND NEW.sequence_no <> 1 THEN
                SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'HR05_ACTIVATION_AMENDMENT_SEQUENCE_INVALID';
            END IF;
            IF NEW.predecessor_id IS NOT NULL AND NOT EXISTS (
                SELECT 1 FROM {AMENDMENT_TABLE} p
                WHERE p.id = NEW.predecessor_id
                  AND p.snapshot_id = NEW.snapshot_id
                  AND p.tenant_id = NEW.tenant_id
                  AND p.sequence_no + 1 = NEW.sequence_no
                  AND p.action <> 'REVOCATION'
            ) THEN
                SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'HR05_ACTIVATION_AMENDMENT_PREDECESSOR_INVALID';
            END IF;
            IF EXISTS (
                SELECT 1 FROM {AMENDMENT_TABLE} r
                WHERE r.snapshot_id = NEW.snapshot_id AND r.action = 'REVOCATION'
            ) THEN
                SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'HR05_ACTIVATION_FACT_ALREADY_REVOKED';
            END IF;
        END
        """,
        f"""
        CREATE TRIGGER hr05_activation_amendment_bu_seal
        BEFORE UPDATE ON {AMENDMENT_TABLE}
        FOR EACH ROW
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'HR05_ACTIVATION_AMENDMENT_IMMUTABLE'
        """,
        f"""
        CREATE TRIGGER hr05_activation_amendment_bd_seal
        BEFORE DELETE ON {AMENDMENT_TABLE}
        FOR EACH ROW
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'HR05_ACTIVATION_AMENDMENT_IMMUTABLE'
        """,
    ]
    with schema_editor.connection.cursor() as cursor:
        for statement in statements:
            cursor.execute(statement)


def drop_mysql_activation_seals(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        for name in (
            "hr05_activation_snapshot_bi_seal",
            "hr05_activation_snapshot_bu_seal",
            "hr05_activation_snapshot_bd_seal",
            "hr05_activation_amendment_bi_seal",
            "hr05_activation_amendment_bu_seal",
            "hr05_activation_amendment_bd_seal",
        ):
            cursor.execute(f"DROP TRIGGER IF EXISTS {name}")


class Migration(migrations.Migration):
    # MySQL trigger DDL implicitly commits and is unsafe in an atomic migration.
    atomic = False

    dependencies = [
        ('hr_onboarding', '0012_rename_hr_ob_outbox_tenant_status_at_hr_onboardi_tenant__8d1b93_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hronboardingpermissionmeta',
            options={'managed': False, 'permissions': (('hr05.case.view', 'Hr05 Case View'), ('hr05.case.create', 'Hr05 Case Create'), ('hr05.case.cancel', 'Hr05 Case Cancel'), ('hr05.case.activate', 'Hr05 Case Activate'), ('hr05.activation_fact.correct', 'Hr05 Activation_Fact Correct'), ('hr05.activation_fact.revoke', 'Hr05 Activation_Fact Revoke'), ('hr05.report.checkin', 'Hr05 Report Checkin'), ('hr05.material.review', 'Hr05 Material Review'), ('hr05.material.sensitive_view', 'Hr05 Material Sensitive_View'), ('hr05.task.manage', 'Hr05 Task Manage'), ('hr05.task.complete', 'Hr05 Task Complete'), ('hr05.task.waive', 'Hr05 Task Waive'), ('hr05.identity.provision', 'Hr05 Identity Provision'), ('hr05.position.commit', 'Hr05 Position Commit'), ('hr05.probation.manage', 'Hr05 Probation Manage'), ('hr05.probation.finalize', 'Hr05 Probation Finalize'), ('hr05.export', 'Hr05 Export'), ('hr05.sensitive_export', 'Hr05 Sensitive_Export'))},
        ),
        migrations.AddField(
            model_name='hronboardingactivationsnapshot',
            name='content_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='hronboardingactivationsnapshot',
            name='hr04_application_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='hronboardingactivationsnapshot',
            name='hr04_proposed_hire_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='hronboardingactivationsnapshot',
            name='sealed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hronboardingactivationsnapshot',
            name='source_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='hronboardingactivationsnapshot',
            name='source_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='hronboardingactivationsnapshot',
            name='case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='activation_snapshot', to='hr_onboarding.hronboardingcase'),
        ),
        migrations.RunPython(backfill_activation_seals, migrations.RunPython.noop),
        migrations.CreateModel(
            name='HrOnboardingActivationAmendment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('sequence_no', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('CORRECTION', 'Correction'), ('REVOCATION', 'Revocation')], max_length=16)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('reason', models.TextField()),
                ('before_snapshot_json', models.JSONField(default=dict)),
                ('after_snapshot_json', models.JSONField(default=dict)),
                ('actor_user_id', models.BigIntegerField(blank=True, null=True)),
                ('effective_at', models.DateTimeField()),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('sealed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('predecessor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor', to='hr_onboarding.hronboardingactivationamendment')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amendments', to='hr_onboarding.hronboardingactivationsnapshot')),
            ],
            options={
                'verbose_name': 'HR Onboarding Activation Amendment',
                'verbose_name_plural': 'HR Onboarding Activation Amendments',
                'indexes': [models.Index(fields=['tenant_id', 'snapshot', 'sequence_no'], name='idx_hr05_act_amend_chain')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'idempotency_key'), name='uniq_hr05_act_amend_tenant_idem'), models.UniqueConstraint(fields=('snapshot', 'sequence_no'), name='uniq_hr05_act_amend_sequence'), models.CheckConstraint(condition=models.Q(('sequence_no__gt', 0)), name='ck_hr05_act_amend_sequence_pos')],
            },
        ),
        migrations.RunPython(create_mysql_activation_seals, drop_mysql_activation_seals),
    ]
